### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: couldn't find class: C:\Program Files\Java\jre1.8.0_181\lib\rt.jar (is your soot-class-path set properly?)

### ISSUE THREAD

**Issue by anantad** [Sable/soot#1007]
Hi Sir,

Would request for your help in resolving the issue i am facing. 
Here it is - 
I tried running soot in command line with below command(as explained in 'https://github.com/Sable/soot/wiki/Introduction:-Soot-as-a-command-line-tool' ):

"C:\Program Files (x86)\Java\jdk1.8.0_181\bin\java.exe" -cp soot-2.5.0.jar soot.Main -cp . "C:\Program Files\Java\jre1.8.0_181\lib\rt.jar" HelloWorld

AND 

"C:\Program Files (x86)\Java\jdk1.8.0_181\bin\java.exe" -cp sootclasses-trunk-jar-with-dependencies.jar soot.Main -cp . "C:\Program Files\Java\jre1.8.0_181\lib\rt.jar" HelloWorld

For both I am getting below exception 
Exception in thread "main" java.lang.RuntimeException: couldn't find class: C:\Program Files\Java\jre1.8.0_181\lib\rt.jar (is your soot-class-path set properly?)
        at soot.SootResolver.bringToHierarchy(SootResolver.java:205)
        at soot.SootResolver.bringToSignatures(SootResolver.java:239)
        at soot.SootResolver.processResolveWorklist(SootResolver.java:154)
        at soot.SootResolver.resolveClass(SootResolver.java:124)
        at soot.Scene.loadClass(Scene.java:448)
        at soot.Scene.loadClassAndSupport(Scene.java:433)
        at soot.Scene.loadNecessaryClass(Scene.java:1053)
        at soot.Scene.loadNecessaryClasses(Scene.java:1067)
        at soot.Main.run(Main.java:167)
        at soot.Main.main(Main.java:141)

Could you please tell what I am missing !

Regards,
Ananta Kumar
IIITB,Bangalore

**Comment by Symbolk** [comment]
Try this:

```sh
java -cp sootclasses-trunk-jar-with-dependencies.jar soot.Main --soot-classpath .;"%JAVA_HOME%"\jre\lib\rt.jar PackageName.ClassName
```
