### ISSUE TITLE
java.lang.RuntimeException: No method source set for method 

### ISSUE THREAD

**Issue by TheJokerrrr** [Sable/soot#1013]
Hi,  I am trying to run Pack twice, at the second run java.lang.RuntimeException: No method source set for method  exception occured, How can i fix this?

I am also trying add two packs first and invoke soot.Main.main, but now, two packs are running in parallel manner, but i want to run two packs one after one, how can i do this?

**Comment by mbenz89** [comment]
Can you explain your setup a bit more thoroughly? How does your call to `soot.Main.main` look like?

Packs are generally not run in parallel. Are you really adding a pack or rather a phase to an existing pack?

**Comment by anddann** [comment]
Due to no response, I close the issue...

**Comment by JeannedArk** [comment]
Hi,

I can reliably reproduce this issue with the following code:
```
import org.slf4j.LoggerFactory
import soot.*
import soot.options.Options
import java.io.IOException
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.Paths
import java.nio.file.StandardCopyOption

class BugDemoMultiInstrumentMain {
    companion object {

        @JvmStatic
        fun main(args: Array<String>) {
            require(args.size == 2) { "Require 1. arg to be apk path, 2. arg to be output dir" }
            val apkPath = Paths.get(args[0])
            val outputDir = Paths.get(args[1])
            // Works here
            BugDemoMultiInstrument.instrument(apkPath, outputDir)
            // Crashes here with:
            // java.lang.RuntimeException: No method source set for method <android.support.v4.view.accessibility.AccessibilityWindowInfoCompat: android.support.v4.view.accessibility.AccessibilityWindowInfoCompat obtain()>
            BugDemoMultiInstrument.instrument(apkPath, outputDir)
        }

    }
}

object BugDemoMultiInstrument {

    private val log = LoggerFactory.getLogger(this::class.java)

    init {
        val transformer = ITransformer()
        PackManager.v().getPack("jtp").add(transformer)
    }

    fun instrument(apkPath: Path, outputDir: Path): Path {
        outputDir.createDirIfNonExisting()
        val workDir = Files.createTempDirectory("instrumentation")
        val apkToolDir = workDir.resolve("apkTool")

        return sootInstrumentation(apkPath, outputDir, workDir, apkToolDir)
    }

    private fun sootInstrumentation(apkPath: Path, outputDir: Path, workDir: Path, apkToolDir: Path): Path {
        Files.createDirectories(apkToolDir)

        val tmpOutApk = workDir.resolve(apkPath.fileName)
        Files.copy(apkPath, tmpOutApk, StandardCopyOption.REPLACE_EXISTING)
        val sootDir = workDir.resolve("soot")
        configSoot(tmpOutApk, sootDir)

        val instrumentedApk = instrumentWithSoot(apkPath, sootDir)
        val outputApk = outputDir.resolve(
            instrumentedApk.fileName.toString().replace(".apk", "-instrumented.apk")
        )

        Files.move(instrumentedApk, outputApk, StandardCopyOption.REPLACE_EXISTING)

        return outputApk
    }

    @Throws(IOException::class)
    private fun configSoot(
        processingApk: Path,
        sootOutputDir: Path
    ) {
        Options.v().set_allow_phantom_refs(true)
        Options.v().set_src_prec(Options.src_prec_apk)
        Options.v().set_output_dir(sootOutputDir.toString())
        Options.v().set_debug(true)
        Options.v().set_validate(true)
        Options.v().set_output_format(Options.output_format_dex)

        val processDirs = ArrayList<String>()
        processDirs.add(processingApk.toString())

        Options.v().set_process_multiple_dex(true)
        Options.v().set_process_dir(processDirs)

        Options.v().set_android_jars("ANDROID_HOME".asEnvDir.resolve("platforms").toString())

        Scene.v().loadNecessaryClasses()
    }

    private fun instrumentWithSoot(apkPath: Path, sootDir: Path): Path {
        log.info("Start instrumenting...")

        PackManager.v().runPacks()
        PackManager.v().writeOutput()

        val instrumentedApk = sootDir.resolve(apkPath.fileName)
        log.info("Instrumentation finished: $instrumentedApk")

        if (!Files.exists(instrumentedApk))
            throw RuntimeException("Failed to instrument $this. Instrumented APK not found.")

        return instrumentedApk
    }

    class ITransformer : Transform("jtp.bug", object : BodyTransformer() {
        override fun internalTransform(b: Body, phaseName: String, options: MutableMap<String, String>) {
            b.validate()
        }
    })

}
```

Due too architectural circumstances we are forced to have a singleton instance of the instrumenter, but this leads to crashes as soon as the first instrumentation was evoked as the provided code shows.

For me the following exception is thrown:

> 15:49:31.812 [Thread-19] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: No method source set for method <android.support.v4.view.accessibility.AccessibilityWindowInfoCompat: android.support.v4.view.accessibility.AccessibilityWindowInfoCompat obtain()>
> java.lang.RuntimeException: No method source set for method <android.support.v4.view.accessibility.AccessibilityWindowInfoCompat: android.support.v4.view.accessibility.AccessibilityWindowInfoCompat obtain()>
> 	at soot.SootMethod.retrieveActiveBody(SootMethod.java:398)
> 	at soot.PackManager$1.run(PackManager.java:1279)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)

or

> Exception in thread "Thread-21" Exception in thread "Thread-20" Exception in thread "Thread-22" Exception in thread "Thread-23" Exception in thread "Thread-18" Exception in thread "main" Exception in thread "Thread-19" Exception in thread "Thread-24" java.lang.RuntimeException: No method source set for method <android.support.v7.widget.SnapHelper$2: void <init>(android.support.v7.widget.SnapHelper,android.content.Context)>
> 	at soot.SootMethod.retrieveActiveBody(SootMethod.java:398)
> 	at soot.PackManager$1.run(PackManager.java:1279)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Exception in thread "Thread-25" java.util.concurrent.RejectedExecutionException: Task soot.PackManager$1@61c1be2f rejected from heros.solver.CountingThreadPoolExecutor@423325e0[Shutting down, pool size = 7, active threads = 1, queued tasks = 0, completed tasks = 7]
> 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
> 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
> 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
> 	at heros.solver.CountingThreadPoolExecutor.execute(CountingThreadPoolExecutor.java:51)
> 	at soot.PackManager.retrieveAllBodies(PackManager.java:1275)
> 	at soot.PackManager.runPacksNormally(PackManager.java:497)
> 	at soot.PackManager.runPacks(PackManager.java:419)
> 	at com.testfabrik.BugDemoMultiInstrument.instrumentWithSoot(BugDemoMultiInstrument.kt:91)
> 	at com.testfabrik.BugDemoMultiInstrument.sootInstrumentation(BugDemoMultiInstrument.kt:55)
> 	at com.testfabrik.BugDemoMultiInstrument.instrument(BugDemoMultiInstrument.kt:44)
> 	at com.testfabrik.BugDemoMultiInstrumentMain$Companion.main(BugDemoMultiInstrument.kt:24)
> 	at com.testfabrik.BugDemoMultiInstrumentMain.main(BugDemoMultiInstrument.kt)
> java.lang.RuntimeException: No method source set for method <android.support.design.internal.BottomNavigationPresenter$SavedState$1: void <init>()>
> 	at soot.SootMethod.retrieveActiveBody(SootMethod.java:398)
> 	at soot.PackManager$1.run(PackManager.java:1279)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)

depending on the given app.

**Comment by mtileria** [comment]
I can reproduce the issue in a similar situation. And it is also the same as #1043 
In my case, I'm instrumenting apks and then calling PackManager.v().writeOutput(). After this, when I try to load the classes again I get the exception. 
```
Exception in thread "main" java.lang.RuntimeException: No method source set for method <com.rhul.simpledataitem.MainActivity: void <init>()>
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:398).
```
It is worth to mention the program generates the instrumented apk and write correctly. 
I'm using soot  3.2.0. This is my configuration. 

```
		Options.v().set_src_prec(Options.src_prec_apk);
		Options.v().set_output_format(Options.output_format_dex);
		Options.v().set_whole_program(true);
		Options.v().set_force_overwrite(true);
		Options.v().set_allow_phantom_refs(true);
		Options.v().set_prepend_classpath(true);
		Options.v().set_android_jars(androidPlatforms);
		Options.v().set_process_dir(Collections.singletonList(apkPath));
		Options.v().set_process_multiple_dex(true);
		Options.v().set_validate(true);
		Scene.v().loadNecessaryClasses();
```

This is one apk that I'm using  https://github.com/mtileria/Android-testcases/blob/master/apk/SimpleDataItem/mobile-debug.apk but the same problem occurs using DirectLeak1.apk from DroidBench and a dummy instrumentation like adding one AssignStmt, which I put below.


The dummy instrumentation is 
```

	public void internalTransform(String phaseName, Map<String, String> options) {
		SootClass sClass = Scene.v().getSootClass("xx.xx.MainActivity");
		Body body = sClass.getMethodByName("onCreate").getActiveBody();
		Local arg = Jimple.v().newLocal("l1", RefType.v("java.lang.String"));
		body.getLocals().add(arg);
		AssignStmt astm = Jimple.v().newAssignStmt(arg, StringConstant.v("crash!"));
		Unit first = body.getUnits().getFirst();
		body.getUnits().insertBefore(astm, first);
	}
```

And this is the Main. 

```
			PackManager.v().getPack("wjtp")
					.add(new Transform("wjtp.MyInstrumentation", new DummySceneTransformer(classesToInstrument)));
			PackManager.v().getPack("wjtp").apply(); 
			printClassByName("xx.x.MainActivity");  --> No Error
			PackManager.v().writeOutput();
			printClassByName("xx.x.MainActivity"); --> Error
```

Note that the first time that I call printClassByName("xx.x.MainActivity"), the program iterates over all the methods and output the class without any problem, but when I call the same function after call PackManager.v().writeOutput(), I get the No method source set for method [...] 	at soot.SootMethod.retrieveActiveBody(SootMethod.java:398).

I can see that the body "disappear" while Debugging after writing the output apk.

**Comment by JeannedArk** [comment]
I created a really dirty workaround that worked for me. After each instrumentation I call the following:
```kotlin
    /**
     * Set all fields to null from soot.Singletons
     */
    private fun resetSoot() {
        val G = soot.G.v()

        val fields = arrayListOf<String>(
            "instance_soot_PackManager",
            "instance_soot_options_Options",
            "instance_soot_PhaseOptions",
            "instance_soot_Scene",
            "instance_soot_PhaseOptions",
            "instance_soot_jimple_toolkits_callgraph_VirtualCalls",
            "instance_soot_jimple_spark_fieldrw_FieldTagger",
            "instance_soot_util_SharedBitSetCache",
            "instance_soot_options_Options",
            "instance_soot_jimple_toolkits_callgraph_CHATransformer",
            "instance_soot_toolkits_graph_SlowPseudoTopologicalOrderer",
            "instance_soot_jimple_toolkits_invoke_SynchronizerManager",
            "instance_soot_jimple_toolkits_typing_integer_ClassHierarchy",
            "instance_soot_Main",
            "instance_soot_tagkit_TagManager",
            "instance_soot_jimple_toolkits_pointer_representations_Environment",
            "instance_soot_jimple_toolkits_pointer_representations_TypeConstants",
            "instance_soot_coffi_Util",
            "instance_soot_SourceLocator",
            "instance_soot_coffi_CONSTANT_Utf8_collector",
            "instance_soot_dava_toolkits_base_finders_AbruptEdgeFinder",
            "instance_soot_jimple_toolkits_base_Aggregator",
            "instance_soot_jimple_toolkits_annotation_arraycheck_ArrayBoundsChecker",
            "instance_soot_jimple_spark_pag_ArrayElement",
            "instance_soot_jimple_toolkits_annotation_tags_ArrayNullTagAggregator",
            "instance_soot_dava_toolkits_base_AST_ASTWalker",
            "instance_soot_baf_Baf",
            "instance_soot_BooleanType",
            "instance_soot_jimple_toolkits_scalar_pre_BusyCodeMotion",
            "instance_soot_ByteType",
            "instance_soot_jimple_toolkits_pointer_CastCheckEliminatorDumper",
            "instance_soot_CharType",
            "instance_soot_jimple_toolkits_annotation_arraycheck_ClassFieldAnalysis",
            "instance_soot_jimple_toolkits_scalar_CommonSubexpressionEliminator",
            "instance_soot_jimple_toolkits_scalar_ConditionalBranchFolder",
            "instance_soot_jimple_toolkits_scalar_ConstantPropagatorAndFolder",
            "instance_soot_grimp_toolkits_base_ConstructorFolder",
            "instance_soot_jimple_toolkits_scalar_CopyPropagator",
            "instance_soot_jimple_toolkits_graph_CriticalEdgeRemover",
            "instance_soot_dava_toolkits_base_finders_CycleFinder",
            "instance_soot_dava_Dava",
            "instance_soot_dava_DavaPrinter",
            "instance_soot_xml_XMLPrinter",
            "instance_soot_Printer",
            "instance_soot_jimple_toolkits_scalar_DeadAssignmentEliminator",
            "instance_soot_jimple_toolkits_pointer_DependenceTagAggregator",
            "instance_soot_coffi_Double2ndHalfType",
            "instance_soot_DoubleType",
            "instance_soot_baf_DoubleWordType",
            "instance_soot_jimple_toolkits_pointer_DumbPointerAnalysis",
            "instance_soot_jimple_spark_sets_EmptyPointsToSet",
            "instance_soot_ErroneousType",
            "instance_soot_dava_toolkits_base_finders_ExceptionFinder",
            "instance_soot_jimple_toolkits_pointer_FieldRWTagger",
            "instance_soot_FloatType",
            "instance_soot_jimple_toolkits_pointer_FullObjectSet",
            "instance_soot_grimp_Grimp",
            "instance_soot_dava_toolkits_base_finders_IfFinder",
            "instance_soot_IntType",
            "instance_soot_jimple_Jimple",
            "instance_soot_dava_toolkits_base_finders_LabeledBlockFinder",
            "instance_soot_jimple_toolkits_scalar_pre_LazyCodeMotion",
            "instance_soot_tagkit_LineNumberTagAggregator",
            "instance_soot_tagkit_InnerClassTagAggregator",
            "instance_soot_jimple_toolkits_annotation_LineNumberAdder",
            "instance_soot_baf_toolkits_base_LoadStoreOptimizer",
            "instance_soot_baf_toolkits_base_StoreChainOptimizer",
            "instance_soot_jimple_toolkits_scalar_LocalNameStandardizer",
            "instance_soot_toolkits_scalar_LocalPacker",
            "instance_soot_toolkits_scalar_LocalSplitter",
            "instance_soot_coffi_Long2ndHalfType",
            "instance_soot_LongType",
            "instance_soot_dava_toolkits_base_misc_MonitorConverter",
            "instance_soot_jimple_toolkits_scalar_NopEliminator",
            "instance_soot_jimple_NullConstant",
            "instance_soot_jimple_toolkits_annotation_nullcheck_NullPointerChecker",
            "instance_soot_NullType",
            "instance_soot_dava_toolkits_base_misc_PackageNamer",
            "instance_soot_PackManager",
            "instance_soot_baf_toolkits_base_PeepholeOptimizer",
            "instance_soot_jimple_toolkits_annotation_profiling_ProfilingGenerator",
            "instance_soot_jimple_toolkits_annotation_arraycheck_RectangularArrayFinder",
            "instance_soot_RefType",
            "instance_soot_Scene",
            "instance_soot_dava_toolkits_base_finders_SequenceFinder",
            "instance_soot_shimple_Shimple",
            "instance_soot_shimple_ShimpleTransformer",
            "instance_soot_shimple_toolkits_scalar_SConstantPropagatorAndFolder",
            "instance_soot_ShortType",
            "instance_soot_jimple_toolkits_pointer_SideEffectTagger",
            "instance_soot_jimple_spark_SparkTransformer",
            "instance_soot_jimple_toolkits_invoke_StaticInliner",
            "instance_soot_jimple_toolkits_invoke_StaticMethodBinder",
            "instance_soot_StmtAddressType",
            "instance_soot_dava_toolkits_base_finders_SwitchFinder",
            "instance_soot_dava_toolkits_base_finders_SynchronizedBlockFinder",
            "instance_soot_dava_toolkits_base_misc_ThrowFinder",
            "instance_soot_dava_toolkits_base_misc_ThrowNullConverter",
            "instance_soot_Timers",
            "instance_soot_dava_toolkits_base_AST_TryContentsFinder",
            "instance_soot_jimple_toolkits_typing_TypeAssigner",
            "instance_soot_jimple_toolkits_scalar_UnconditionalBranchFolder",
            "instance_soot_jimple_toolkits_scalar_ConstantCastEliminator",
            "instance_soot_jimple_toolkits_scalar_IdentityCastEliminator",
            "instance_soot_jimple_toolkits_scalar_FieldStaticnessCorrector",
            "instance_soot_jimple_toolkits_scalar_MethodStaticnessCorrector",
            "instance_soot_jimple_toolkits_scalar_IdentityOperationEliminator",
            "instance_soot_UnknownType",
            "instance_soot_jimple_toolkits_scalar_UnreachableCodeEliminator",
            "instance_soot_toolkits_scalar_UnusedLocalEliminator",
            "instance_soot_coffi_UnusuableType",
            "instance_soot_dava_toolkits_base_AST_UselessTryRemover",
            "instance_soot_VoidType",
            "instance_soot_baf_WordType",
            "instance_soot_jimple_spark_fieldrw_FieldReadTagAggregator",
            "instance_soot_jimple_spark_fieldrw_FieldWriteTagAggregator",
            "instance_soot_jimple_spark_fieldrw_FieldTagAggregator",
            "instance_soot_EntryPoints",
            "instance_soot_jimple_toolkits_annotation_callgraph_CallGraphTagger",
            "instance_soot_jimple_toolkits_annotation_nullcheck_NullPointerColorer",
            "instance_soot_jimple_toolkits_annotation_parity_ParityTagger",
            "instance_soot_jimple_toolkits_annotation_methods_UnreachableMethodsTagger",
            "instance_soot_jimple_toolkits_annotation_fields_UnreachableFieldsTagger",
            "instance_soot_jimple_toolkits_annotation_qualifiers_TightestQualifiersTagger",
            "instance_soot_jimple_toolkits_pointer_ParameterAliasTagger",
            "instance_soot_jimple_toolkits_annotation_defs_ReachingDefsTagger",
            "instance_soot_jimple_toolkits_annotation_liveness_LiveVarsTagger",
            "instance_soot_toolkits_graph_interaction_InteractionHandler",
            "instance_soot_jimple_toolkits_annotation_logic_LoopInvariantFinder",
            "instance_soot_jimple_toolkits_annotation_AvailExprTagger",
            "instance_soot_util_PhaseDumper",
            "instance_soot_util_cfgcmd_AltClassLoader",
            "instance_soot_toolkits_exceptions_ThrowableSet_Manager",
            "instance_soot_toolkits_exceptions_UnitThrowAnalysis",
            "instance_soot_dexpler_DalvikThrowAnalysis",
            "instance_soot_dexpler_DexFileProvider",
            "instance_soot_toolkits_exceptions_PedanticThrowAnalysis",
            "instance_soot_toolkits_exceptions_TrapTightener",
            "instance_soot_toolkits_exceptions_DuplicateCatchAllTrapRemover",
            "instance_soot_jimple_toolkits_annotation_callgraph_CallGraphGrapher",
            "instance_soot_SootResolver",
            "instance_soot_javaToJimple_InitialResolver",
            "instance_soot_jimple_paddle_PaddleHook",
            "instance_soot_jimple_toolkits_annotation_DominatorsTagger",
            "instance_soot_jimple_toolkits_annotation_purity_PurityAnalysis",
            "instance_soot_javaToJimple_toolkits_CondTransformer",
            "instance_soot_dava_toolkits_base_AST_transformations_UselessLabelFinder",
            "instance_soot_dava_DavaStaticBlockCleaner",
            "instance_soot_dava_toolkits_base_AST_traversals_ClosestAbruptTargetFinder",
            "instance_soot_jimple_spark_sets_AllSharedListNodes",
            "instance_soot_jimple_spark_sets_AllSharedHybridNodes",
            "instance_soot_jimple_toolkits_thread_synchronization_LockAllocator",
            "instance_soot_jimple_toolkits_thread_mhp_MhpTransformer",
            "instance_soot_JastAddInitialResolver",
            "instance_soot_jimple_toolkits_annotation_j5anno_AnnotationGenerator",
            "instance_soot_sootify_TemplatePrinter",
            "instance_soot_dexpler_DexResolver",
            "instance_soot_jimple_toolkits_scalar_EmptySwitchEliminator",
            "instance_soot_toDex_SynchronizedMethodTransformer",
            "instance_soot_toDex_TrapSplitter",
            "instance_soot_toDex_FastDexTrapTightener",
            "instance_soot_jimple_toolkits_base_RenameDuplicatedClasses",
            "instance_soot_jimple_toolkits_typing_fast_Integer127Type",
            "instance_soot_jimple_toolkits_typing_fast_Integer1Type",
            "instance_soot_jimple_toolkits_typing_fast_Integer32767Type",
            "instance_soot_jimple_toolkits_typing_fast_BottomType",
            "instance_soot_dexpler_TrapMinimizer",
            "instance_soot_toolkits_scalar_SmartLocalDefsPool",
            "instance_soot_jimple_spark_internal_PublicAndProtectedAccessibility",
            "instance_soot_jimple_spark_internal_CompleteAccessibility",
            "instance_soot_jimple_toolkits_reflection_ConstantInvokeMethodBaseTransformer",
            "instance_soot_jbco_jimpleTransformations_ClassRenamer",
            "instance_soot_jbco_jimpleTransformations_MethodRenamer",
            "instance_soot_LambdaMetaFactory",
            "instance_soot_jbco_jimpleTransformations_FieldRenamer"
        )

        fields.forEach {
            val optionsField = G.javaClass.superclass.getDeclaredField(it)
            optionsField.isAccessible = true
            optionsField.set(G, null)
        }
    }
```

**Comment by mbenz89** [comment]
You have to reset Soot between two runs of the same. This is done by calling `G.v().reset()` which essentially does what your reflection hack does.

**Comment by mbenz89** [comment]
```
PackManager.v().getPack("wjtp").apply(); 
			printClassByName("xx.x.MainActivity");  --> No Error
			PackManager.v().writeOutput();
			printClassByName("xx.x.MainActivity"); --> Error
```

This kind of error is probably rather caused because Soot releases the bodies after the `writeOutput` call. You can prevent this by using the option: `Options.v().set_no_writeout_body_releasing(true)`
