### ISSUE TITLE
[Question] Generate CFG for Java 8 Stream Api and lambda expression.

### ISSUE THREAD

**Issue by luckyxkw** [Sable/soot#1018]
Hi I have encountered a NullPointerException when generating CFG for methods that contain usage of stream Api. I can convert my classes to jimple files though. I am using the release version 3.1.0.
This is the command I am using for generating CFG:
```
java -cp sootclasses-trunk-jar-with-dependencies.jar soot.tools.CFGViewer -process-dir test-example/target/hello-world-1.0-SNAPSHOT.jar -d example-output/hello-world
Soot started on Sat Sep 15 00:41:20 SGT 2018
[Thread-6] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: null
java.lang.NullPointerException
	at soot.tools.CFGViewer.print_cfg(CFGViewer.java:237)
	at soot.tools.CFGViewer.internalTransform(CFGViewer.java:87)
	at soot.BodyTransformer.transform(BodyTransformer.java:54)
	at soot.Transform.apply(Transform.java:108)
	at soot.BodyPack.internalApply(BodyPack.java:52)
	at soot.Pack.apply(Pack.java:125)
	at soot.PackManager.runBodyPacks(PackManager.java:1001)
	at soot.PackManager.access$000(PackManager.java:141)
	at soot.PackManager$1.run(PackManager.java:649)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-6" java.lang.NullPointerException
	at soot.tools.CFGViewer.print_cfg(CFGViewer.java:237)
	at soot.tools.CFGViewer.internalTransform(CFGViewer.java:87)
	at soot.BodyTransformer.transform(BodyTransformer.java:54)
	at soot.Transform.apply(Transform.java:108)
	at soot.BodyPack.internalApply(BodyPack.java:52)
	at soot.Pack.apply(Pack.java:125)
	at soot.PackManager.runBodyPacks(PackManager.java:1001)
	at soot.PackManager.access$000(PackManager.java:141)
	at soot.PackManager$1.run(PackManager.java:649)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
	at soot.tools.CFGViewer.print_cfg(CFGViewer.java:237)
	at soot.tools.CFGViewer.internalTransform(CFGViewer.java:87)
	at soot.BodyTransformer.transform(BodyTransformer.java:54)
	at soot.Transform.apply(Transform.java:108)
	at soot.BodyPack.internalApply(BodyPack.java:52)
	at soot.Pack.apply(Pack.java:125)
	at soot.PackManager.runBodyPacks(PackManager.java:1001)
	at soot.PackManager.access$000(PackManager.java:141)
	at soot.PackManager$1.run(PackManager.java:649)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

This is my source code(class Foo and Bar are packaged in the jar as well and should not be the cause of this exception):
```
package com.example;

import java.util.Arrays;
import java.util.List;

/**
 * Hello world!
 *
 */
public class App 
{
    private Bar bar;
    private Foo foo;

    public App() {
        bar = new Bar();
        foo = new Foo();
    }

    public void test(int x)
    {
        for (int i = 0; i < 5; i++) {
            System.out.println( "Hello World!" );
        }
        if (x > 0) {
            System.out.println( foo.fooMethod() );
        } else {
            System.out.println( bar.barMethod() );
        }
        List<Integer> arrList = Arrays.asList(1,2,3,4,5,6);
        arrList.stream().filter(i -> i%2 == 0).forEach(i -> System.out.println(i));
    }
}

```

**Comment by mbenz89** [comment]
Can you debug into the failing method `at soot.tools.CFGViewer.print_cfg`and track down the root cause of this error? I think `CFGViewer` was written quite before invokedynamic existed. It might be that it cannot handle invokedynamic calls at all. I guess the change to fix this would be rather small, though.

**Comment by rohit777anand** [comment]
@mbenz89 is this issue resolved?

**Comment by mbenz89** [comment]
@rohit777anand not as far as I know.
