### ISSUE TITLE
Trying to create interface expression for non-interface type

### ISSUE THREAD

**Issue by Jacoppy** [Sable/soot#1027]
Hi,
after I have exported some jimple files, trying to import them throw me the following error:
`[Thread-6] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: Trying to create interface invoke expression for non-interface type: com.revmob.RevMobAdsListener Use JVirtualInvokeExpr or JSpecialInvokeExpr instead!
java.lang.RuntimeException: Trying to create interface invoke expression for non-interface type: com.revmob.RevMobAdsListener Use JVirtualInvokeExpr or JSpecialInvokeExpr instead!
	at soot.jimple.internal.JInterfaceInvokeExpr.<init>(JInterfaceInvokeExpr.java:45)
	at soot.jimple.Jimple.newInterfaceInvokeExpr(Jimple.java:491)
	at soot.jimple.parser.Walker.outANonstaticInvokeExpr(Walker.java:1413)
	at soot.jimple.parser.analysis.DepthFirstAdapter.caseANonstaticInvokeExpr(DepthFirstAdapter.java:2680)
	at soot.jimple.parser.node.ANonstaticInvokeExpr.apply(ANonstaticInvokeExpr.java:65)
	at soot.jimple.parser.analysis.DepthFirstAdapter.caseAInvokeStatement(DepthFirstAdapter.java:2044)
	at soot.jimple.parser.node.AInvokeStatement.apply(AInvokeStatement.java:40)
	at soot.jimple.parser.analysis.DepthFirstAdapter.caseAFullMethodBody(DepthFirstAdapter.java:1392)
	at soot.jimple.parser.node.AFullMethodBody.apply(AFullMethodBody.java:56)
	at soot.jimple.parser.analysis.DepthFirstAdapter.caseAMethodMember(DepthFirstAdapter.java:663)
	at soot.jimple.parser.node.AMethodMember.apply(AMethodMember.java:71)
	at soot.jimple.parser.analysis.DepthFirstAdapter.caseAFileBody(DepthFirstAdapter.java:470)
	at soot.jimple.parser.node.AFileBody.apply(AFileBody.java:46)
	at soot.jimple.parser.BodyExtractorWalker.caseAFile(BodyExtractorWalker.java:94)
	at soot.jimple.parser.node.AFile.apply(AFile.java:61)
	at soot.jimple.parser.analysis.DepthFirstAdapter.caseStart(DepthFirstAdapter.java:34)
	at soot.jimple.parser.node.Start.apply(Start.java:37)
	at soot.jimple.parser.JimpleAST.stashBodiesForClass(JimpleAST.java:131)
	at soot.jimple.parser.JimpleAST.getBody(JimpleAST.java:97)
	at soot.jimple.JimpleMethodSource.getBody(JimpleMethodSource.java:44)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:399)
	at soot.PackManager$3.run(PackManager.java:1293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

I have identified that the error is thrown by interfaceinvoke. One of the jimple files that cause that exception is attached as file, same as for the referred interface .
I don't understand why soot says that com.revmob.RevMobAdsListener.jimple is not an interface is it is declared as it.
How can I fix this?

[com.revmob.RevMobAdsListener.txt](https://github.com/Sable/soot/files/2411923/com.revmob.RevMobAdsListener.txt)

[com.revmob.ads.fullscreen.FullscreenActivity.txt](https://github.com/Sable/soot/files/2411913/com.revmob.ads.fullscreen.FullscreenActivity.txt)

**Comment by mbenz89** [comment]
Can you provide me with all Jimple files and a piece of Code which I can use to reproduce the problem?
It's hard to tell why this is failing without debugging.

Only by looking at the Jimple, it catches my eye that every method in the interface is declared as abstract. Maybe the parsing process is flawed in the sense that it flags every interface method as `abstract` instead of `interface` and thus, the method type/modifiers does not correspond to the invoke statement when calling it.

@StevenArzt I am quite currious how "well-maintained" the Jimple frontend is. Are you aware of any major flaws here?

**Comment by Jacoppy** [comment]
Well, mainly it throws the exception when the program starts running. 
My configs are the following : 

` public void initSoot(String apkPath,File[] jimplePath){


        Options.v().set_src_prec(Options.src_prec_apk_c_j);

        Options.v().set_process_dir(Collections.singletonList(apkPath));

        Options.v().set_output_format(Options.output_format_dex);

        String androidJarPath = Scene.v().getAndroidJarPath(jarsPath, apkPath);

        List<String> pathList = new ArrayList<String>();

        pathList.add(apkPath);

        pathList.add(androidJarPath);

        for(File i : jimplePath) {

            pathList.add(i.getAbsolutePath());

        }
        Options.v().set_process_dir(pathList);

        Options.v().set_force_android_jar(apkPath);

        Options.v().set_keep_line_number(true);

        Options.v().set_process_multiple_dex(true);

        Options.v().set_allow_phantom_refs(true);

        Options.v().set_whole_program(true);

        Options.v().set_wrong_staticness(Options.wrong_staticness_ignore);

        Options.v().set_exclude(excludePackagesList);

        Options.v().set_no_bodies_for_excluded(true);

        Scene.v().addBasicClass("java.lang.Object", SootClass.SIGNATURES);

        Scene.v().loadNecessaryClasses();

        PackManager.v().runPacks();

    }`


it immediately throws exception.

**Comment by Jacoppy** [comment]
jimplePath are all the folders containing jimple files.

**Comment by Jacoppy** [comment]
Hi, sorry for the pressure but I'm working on it and I would need some advices or I can't get further.. thanks

**Comment by mbenz89** [comment]
Again, if you provide me with the input files, I can have a look.
However, as Steven already mentioned, you won't be able to get executable code when parsing from Jimple and writing out as dex. I suggest you use dex files as intermediate storage instead of Jimple files, i.e. read in the apk you want to analyze, do whatever you want to do with the classes (if I remember correctly, it was filtering out some of them) and write out the processed classes back into a dex file (output option `forceDex`). You can then read in this dex file additionally to another apk in another Soot run and write everything out to a new apk.
