### ISSUE TITLE
InvocationTargetException when using static Inliner in soot with  apache lucene jar?

### ISSUE THREAD

**Issue by achabdo** [Sable/soot#1028]
I got this error when executing my java program after using the static inliner with CHA for Call Graph construction .

DaCapo unknown luindex starting =====.
java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
	at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java)
	at java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java)
	at java.lang.reflect.Method.internalInvoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java)
	at org.dacapo.harness.Luindex.iterate(Luindex.java)
	at org.dacapo.harness.Benchmark.run(Benchmark.java)
	at org.dacapo.harness.TestHarness.main(TestHarness.java)
	at java.lang.reflect.Method.internalInvoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java)
	at Harness.main(Unknown Source)
Caused by: java.lang.NullPointerException
	at org.apache.lucene.store.FSDirectory.getLockID(FSDirectory.java)
	at org.apache.lucene.store.Directory.setLockFactory(Directory.java)
	at org.apache.lucene.store.FSDirectory.getDirectory(FSDirectory.java)
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java)
	at org.dacapo.luindex.Index.main(Index.java)
	... 8 more

**Comment by pavanupb** [comment]
Could you please provide your java program
