### ISSUE TITLE
Trying to export a slice of jimple

### ISSUE THREAD

**Issue by Jacoppy** [Sable/soot#1034]
Hi, 
I am trying to export a jimple slice to a binary file. The slice is composed by Units and Local and I have made my own class that implements Serializable to contain this content.
But when I try to write this to a file I get 

java.io.NotSerializableException: soot.SootClass

There is any other way to export this?

**Comment by mbenz89** [comment]
SootClass is not serializable.  What are you trying to accomplish here?

Usually, it does not make sense to serialize Soot's state since deserializing would take nearly as long as creating it from scratch by analyzing the target code. If you want to export classes for later use, I suggest doing that as class/Jimple files.

**Comment by Jacoppy** [comment]
I am actually trying to export a slice of code from a jimpleBody to another jimpleBody in different runs. So even using the jimple as output format doesn't work well because it's incomplete in some ways..

**Comment by mbenz89** [comment]
You could create a new Class with methods containing your slices and write it out as class file. In the next run, you can read in this class and call/inline the methods as needed.

**Comment by Jacoppy** [comment]
I have tried  but when I tried to read it back that class it was throwing errors regarding the absence of any reference to that class. I though it was regarding the lack of Local variables but it wasn't.

**Comment by Jacoppy** [comment]
In particular the error is the following one : 
`[Thread-4] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: couldn't find identityref! in <Ciccio: void tmp()>
java.lang.RuntimeException: couldn't find identityref! in <Ciccio: void tmp()>
	at soot.Body.getThisLocal(Body.java:300)
	at soot.jimple.toolkits.scalar.DeadAssignmentEliminator.internalTransform(DeadAssignmentEliminator.java:185)
	at soot.BodyTransformer.transform(BodyTransformer.java:51)
	at soot.Transform.apply(Transform.java:120)
	at soot.JimpleBodyPack.applyPhaseOptions(JimpleBodyPack.java:84)
	at soot.JimpleBodyPack.internalApply(JimpleBodyPack.java:105)
	at soot.Pack.apply(Pack.java:125)
	at soot.jimple.JimpleMethodSource.getBody(JimpleMethodSource.java:53)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:399)
	at soot.PackManager$3.run(PackManager.java:1293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by mbenz89** [comment]
Does your method has an identity statement which assigns the `this` reference to a local? Every method should have it.

**Comment by Jacoppy** [comment]
Probably it doesn't ,would you give me any reference to make it? Thank you very much :)

**Comment by mbenz89** [comment]
```
// add "this" local
Local thisLocal = Jimple.v().newLocal("this", sc.getType());
b.getLocals().add(thisLocal);
b.getUnits().add(Jimple.v().newIdentityStmt(thisLocal, Jimple.v().newThisRef(sc.getType())));
```

where `b` is the method's body and `sc` is the SootClass that contains the method.

**Comment by ericbodden** [comment]
It seems like you have an IndentityStmt with a ParameterRef that has an invalid index.

**Comment by mbenz89** [comment]
Maybe you should have a look at some of the Jimple created by Soot. You might notice, that for the this reference and each parameter, there is an identity statement that assigns it to a local for each method.

**Comment by Jacoppy** [comment]
But I have followed the code suggested :thinking: 


> ```
> // add "this" local
> Local thisLocal = Jimple.v().newLocal("this", sc.getType());
> b.getLocals().add(thisLocal);
> b.getUnits().add(Jimple.v().newIdentityStmt(thisLocal, Jimple.v().newThisRef(sc.getType())));
> ```
> 
> where `b` is the method's body and `sc` is the SootClass that contains the method.

**Comment by mbenz89** [comment]
The proposed code is only for assigning the `this` reference to a local. You have to do the same for all parameters of a method, i.e. for each parameter add an identity statement which assigns the parameter to a local.

Afterwards, the methods header should look similar to this:

```
public int stepPoly(int)
{
ExampleClass r0;
int i0;
    r0 := @this;
    i0 := @parameter0;
...
```

**Comment by Jacoppy** [comment]
Oh okay nice, sorry I didn't understand it :) I will try tomorrow, thank you for the patience and for the help!

**Comment by Jacoppy** [comment]
Ok I got it.. and there is way by soot to convert a Local to an ` Value identityRef `?

**Comment by Jacoppy** [comment]
Yup, I sorted it out sorry :) 
I am now trying to assign a Local to a Static invoke like following 

```
Local l 
b.getLocals().add(l);
vinvokeExpr = Jimple.v().newStaticInvokeExpr(get_context.makeRef()); 
 AssignStmt astmt = Jimple.v().newAssignStmt(l, vinvokeExpr);
 b.getUnits().add(astmt);
```
but I get this error:

Exception in thread "main" java.lang.RuntimeException: wrong static-ness

There is something wrong in the assignment?

**Comment by mbenz89** [comment]
I guess you are trying to call a non-static method with a static invoke expression.

There is another, unrelated issue: 
`
Local l 
b.getLocals().add(l)
`
You have to instantiate this local, it will be null otherwise. I suggest using the `LocalGenerator` for this.

**Comment by Jacoppy** [comment]
Ok you are right.. yes the local is created by the LocalGenerator :+1: 
I'm trying to call the getApplicationContext, which is from the doc an abstract method...Ho can I make it work ? I tried to create an AbstractInvokeExpr but without success.

**Comment by mbenz89** [comment]
Calling public/protected method in Java requires virtual dispatch since the actual receiver of that call has to be determined in the class' hierarchy.
Thus, you have to use a `virtualInvoke` statement using the object against which you want to dispatch as base object, e.g. the `this` reference of the current activity when your call is done in a member method of an activity.
