### ISSUE TITLE
Problem importing a method after export dex

### ISSUE THREAD

**Issue by Jacoppy** [Sable/soot#1043]
Hello again,
I am exporting as dex all the dependencies class found.
When I try to import them back and I try to get the active bodies from the SootMethods of these classes, Soot throws exception : 
```
Exception in thread "main" java.lang.RuntimeException: no active body present for method <rid.hth.XZU.z.a: rid.hth.XZU.z.b a(int)>
	at soot.SootMethod.getActiveBody(SootMethod.java:334)
	at Instrumenter.main(Instrumenter.java:46)  
```
The problem is that if I check if the same classes before the export has Active body, soot tells me true, and unpacking the .dex file in which all my classes are stored , I can clearly see that they have an active body.
How can I workaround this issue?

**Comment by Jacoppy** [comment]
Any answer would be appreciated....

**Comment by zhhailon** [comment]
Have you tried `SootMethod.retrieveActiveBody`?
