### ISSUE TITLE
Inquiry about "NoClassDefFoundError"

### ISSUE THREAD

**Issue by LightningStorm49** [Sable/soot#1051]
Hi,

I try to use the Flowdroid to paint the control flow diagram but when I download the released version and try to run it using command line, there is an exception occurs:

Exception in thread "main" java.lang.NoClassDefFoundError: javax/activation/UnsupportedDataTypeException
        at soot.jimple.infoflow.cmd.MainClass.run(MainClass.java:230)
        at soot.jimple.infoflow.cmd.MainClass.main(MainClass.java:196)
Caused by: java.lang.ClassNotFoundException: javax.activation.UnsupportedDataTypeException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 2 more

I tried to use eclipse to run it but a similar problem occurs: 

Exception in thread "main" java.lang.NoClassDefFoundError: javax/activation/UnsupportedDataTypeException
	at flowdroidcg.CGGenerator.main(CGGenerator.java:29)
Caused by: java.lang.ClassNotFoundException: javax.activation.UnsupportedDataTypeException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 1 more

The problem occurred when I tried to call the SetupApplication method:
SetupApplication app = new SetupApplication(androidPlatformPath, appPath);

Could you please help me with that?

Thank you in advance!

**Comment by StevenArzt** [comment]
The ```UnsupportedDataTypeException``` class should exist since Java 1.6 as part of the normal Java runtime (rt.jar). I'll replace it with a custom exception class for the next version of FlowDroid. For now, you can change the method ```runInfoflow()``` in the ```SetupApplication``` class to not throw this exception as a workaround.
