### ISSUE TITLE
java.lang.IndexOutOfBoundsException when Instrumenting 

### ISSUE THREAD

**Issue by yxycsz** [Sable/soot#1057]
Hi,

Thanks for providing this amazing framework. I am trying to develop an instrumenting tool of android apps. 
However, I got java.lang.IndexOutOfBoundsException when processing an apk.
Here are the steps to reproduce this error.

soot: soot-3.1.0-20181031.115041-85-jar-with-dependencies.jar

target: wechat-6-7-3.apk
please download form:
https://wechat.en.uptodown.com/android
or
https://www.dropbox.com/s/57tpj2grro5ksd8/wechat-6-7-3.apk?dl=0

Command line:
```
java -jar soot-3.1.0-20181031.115041-85-jar-with-dependencies.jar -src-prec apk --allow-phantom-refs -output-format dex -force-android-jar /…/Android/Sdk/platforms/android-28/android.jar --process-dir /…/wechat-6-7-3.apk -process-multiple-dex
```

Stack trace:
```
[Thread-17] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: Index: 2140, Size: 2140
java.lang.IndexOutOfBoundsException: Index: 2140, Size: 2140
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at soot.toDex.StmtVisitor.reduceInstructions(StmtVisitor.java:285)
	at soot.toDex.StmtVisitor.finalizeInstructions(StmtVisitor.java:228)
	at soot.toDex.DexPrinter.toInstructions(DexPrinter.java:1513)
	at soot.toDex.DexPrinter.toMethodImplementation(DexPrinter.java:1174)
	at soot.toDex.DexPrinter.toMethods(DexPrinter.java:1083)
	at soot.toDex.DexPrinter.addAsClassDefItem(DexPrinter.java:656)
	at soot.toDex.DexPrinter.add(DexPrinter.java:1646)
	at soot.PackManager.writeClass(PackManager.java:1110)
	at soot.PackManager$2.run(PackManager.java:710)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-17" java.lang.IndexOutOfBoundsException: Index: 2140, Size: 2140
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at soot.toDex.StmtVisitor.reduceInstructions(StmtVisitor.java:285)
	at soot.toDex.StmtVisitor.finalizeInstructions(StmtVisitor.java:228)
	at soot.toDex.DexPrinter.toInstructions(DexPrinter.java:1513)
	at soot.toDex.DexPrinter.toMethodImplementation(DexPrinter.java:1174)
	at soot.toDex.DexPrinter.toMethods(DexPrinter.java:1083)
	at soot.toDex.DexPrinter.addAsClassDefItem(DexPrinter.java:656)
	at soot.toDex.DexPrinter.add(DexPrinter.java:1646)
	at soot.PackManager.writeClass(PackManager.java:1110)
	at soot.PackManager$2.run(PackManager.java:710)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IndexOutOfBoundsException: Index: 2140, Size: 2140
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at soot.toDex.StmtVisitor.reduceInstructions(StmtVisitor.java:285)
	at soot.toDex.StmtVisitor.finalizeInstructions(StmtVisitor.java:228)
	at soot.toDex.DexPrinter.toInstructions(DexPrinter.java:1513)
	at soot.toDex.DexPrinter.toMethodImplementation(DexPrinter.java:1174)
	at soot.toDex.DexPrinter.toMethods(DexPrinter.java:1083)
	at soot.toDex.DexPrinter.addAsClassDefItem(DexPrinter.java:656)
	at soot.toDex.DexPrinter.add(DexPrinter.java:1646)
	at soot.PackManager.writeClass(PackManager.java:1110)
	at soot.PackManager$2.run(PackManager.java:710)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I even tried to use apktool to decompile and recompile, to “format” the apk. Then apply it on soot, but still got the same error. 
Please take a look.

**Comment by mbenz89** [comment]
Fixed by #1135
