### ISSUE TITLE
How to instrument IfStmt with condtion as boolean true/false

### ISSUE THREAD

**Issue by jyotigajrani** [Sable/soot#1084]
I have some  IF statement with condition and target.
I want to instrument it to make the condition TRUE always.
I tried this approach for the same:
`IfStmt is=(IfStmt) stm; //My current IF statement

Stmt afterEx = is.getTarget();

LocalGenerator generator = new LocalGenerator(methodBody);

Value intCounter = generator.generateLocal(IntType.v());

AssignStmt assignStmt = new JAssignStmt(intCounter, IntConstant.v(0));

methodBody.getUnits().insertBefore(assignStmt,stm);

IfStmt ifStmt = Jimple.v().newIfStmt(Jimple.v().newEqExpr(intCounter,IntConstant.v(0)), afterEx);

methodBody.getUnits().swapWith(is, ifStmt);`

I get Exception:
`java.lang.ArrayIndexOutOfBoundsException: 329
	at soot.toolkits.scalar.SimpleLocalDefs$FlowAssignment.omissible(SimpleLocalDefs.java:216)
	at soot.toolkits.scalar.SimpleLocalDefs$FlowAssignment.omissible(SimpleLocalDefs.java:89)
	at soot.toolkits.scalar.FlowAnalysis.initFlow(FlowAnalysis.java:474)
	at soot.toolkits.scalar.FlowAnalysis.doAnalysis(FlowAnalysis.java:541)
	at soot.toolkits.scalar.ForwardFlowAnalysis.doAnalysis(ForwardFlowAnalysis.java:46)
	at soot.toolkits.scalar.SimpleLocalDefs$FlowAssignment.<init>(SimpleLocalDefs.java:179)
	at soot.toolkits.scalar.SimpleLocalDefs.init(SimpleLocalDefs.java:425)
	at soot.toolkits.scalar.SimpleLocalDefs.<init>(SimpleLocalDefs.java:370)
	at soot.toolkits.scalar.SimpleLocalDefs.<init>(SimpleLocalDefs.java:330)
	at soot.toolkits.scalar.SimpleLocalDefs.<init>(SimpleLocalDefs.java:326)
	at soot.toolkits.scalar.LocalDefs$Factory.newLocalDefs(LocalDefs.java:94)
	at soot.toolkits.scalar.LocalDefs$Factory.newLocalDefs(LocalDefs.java:77)
	at soot.jimple.toolkits.scalar.CopyPropagator.internalTransform(CopyPropagator.java:139)
	at soot.BodyTransformer.transform(BodyTransformer.java:55)
	at soot.BodyTransformer.transform(BodyTransformer.java:59)
	at soot.PackManager.runBodyPacks(PackManager.java:1014)
	at soot.PackManager.access$000(PackManager.java:146)
	at soot.PackManager$1.run(PackManager.java:664)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

@StevenArzt May you please check and suggest how can I do that?
Is this way is correct or I have to use some other approach?

Thanks & Regards
Jyoti

**Comment by jyotigajrani** [comment]
Issue solved...

**Comment by mbenz89** [comment]
Could you please post the your working code here as a reference for others?
