### ISSUE TITLE
Failed to apply jb to <org.apache.commons.lang3.time.DateUtils: java.util.Date addMonths(java.util.Date,int)>

### ISSUE THREAD

**Issue by basti-shi031** [Sable/soot#1095]
I use `soot-3.1.0-20181128.132702-90-jar-with-dependencies.jar` to get invoked method list by `PackManager.v().runPacks();`.But I get this exception:

```
java.lang.RuntimeException: Failed to apply jb to <org.apache.commons.lang3.time.DateUtils: java.util.Date addMonths(java.util.Date,int)>
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:2067)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:402)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processNewMethod(OnFlyCallGraphBuilder.java:755)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processReachables(OnFlyCallGraphBuilder.java:269)
	at soot.jimple.spark.solver.OnFlyCallGraph.build(OnFlyCallGraph.java:83)
	at soot.jimple.spark.builder.ContextInsensitiveBuilder.build(ContextInsensitiveBuilder.java:100)
	at soot.jimple.spark.SparkTransformer.internalTransform(SparkTransformer.java:101)
	at soot.SceneTransformer.transform(SceneTransformer.java:36)
	at soot.Transform.apply(Transform.java:102)
	at soot.RadioScenePack.internalApply(RadioScenePack.java:68)
	at soot.jimple.toolkits.callgraph.CallGraphPack.internalApply(CallGraphPack.java:58)
	at soot.Pack.apply(Pack.java:117)
	at soot.PackManager.runWholeProgramPacks(PackManager.java:611)
	at soot.PackManager.runPacksNormally(PackManager.java:495)
	at soot.PackManager.runPacks(PackManager.java:419)
	at cn.edu.fudan.se.cfg.rq2.utils.SootUtils.getInvokeMethodList(SootUtils.java:104)
	at cn.edu.fudan.se.cfg.rq3.API2List.apiToList(API2List.java:65)
	at cn.edu.fudan.se.cfg.rq3.API2List.main(API2List.java:39)
Caused by: Unexpected type null
	at soot.jimple.toolkits.typing.integer.ClassHierarchy.typeNode(ClassHierarchy.java:152)
	at soot.jimple.toolkits.typing.integer.TypeResolver.typeVariable(TypeResolver.java:121)
	at soot.jimple.toolkits.typing.integer.ConstraintCollector.caseIdentityStmt(ConstraintCollector.java:520)
	at soot.jimple.internal.JIdentityStmt.apply(JIdentityStmt.java:75)
	at soot.jimple.toolkits.typing.integer.ConstraintCollector.collect(ConstraintCollector.java:104)
	at soot.jimple.toolkits.typing.integer.TypeResolver.collect_constraints_1(TypeResolver.java:209)
	at soot.jimple.toolkits.typing.integer.TypeResolver.resolve_step_1(TypeResolver.java:178)
	at soot.jimple.toolkits.typing.integer.TypeResolver.resolve(TypeResolver.java:147)
	at soot.jimple.toolkits.typing.fast.TypeResolver.inferTypes(TypeResolver.java:174)
	at soot.jimple.toolkits.typing.TypeAssigner.internalTransform(TypeAssigner.java:121)
	at soot.BodyTransformer.transform(BodyTransformer.java:51)
	at soot.Transform.apply(Transform.java:120)
	at soot.JimpleBodyPack.applyPhaseOptions(JimpleBodyPack.java:73)
	at soot.JimpleBodyPack.internalApply(JimpleBodyPack.java:105)
	at soot.Pack.apply(Pack.java:125)
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:2065)
	... 17 more
```

This is my option:

```java
argsList.addAll(Arrays.asList(new String[]{"-allow-phantom-refs", "-w",
                "-cp",
                "C:/cs/jdk1.8.0_181/jre/lib/jce.jar;C:/cs/jdk1.8.0_181/jre/lib/rt.jar;" + 					classesPath,
                "-process-dir",
                classesPath,
                "jb",
                "enabled:true"}));
Options.v().set_src_prec(Options.src_prec_java);
Options.v().set_whole_program(true);
Options.v().set_allow_phantom_refs(true);
Options.v().set_output_format(Options.output_format_none);
Options.v().setPhaseOption("cg.spark", "on");
Options.v().set_no_bodies_for_excluded(true);
```

Would you help me to find out what the excetion is and what should I do?
Thx!

**Comment by mbenz89** [comment]
For some reason Soot tries to resolve a non-integer type as integer...or there is an unhandled integer type.

Can you post the code you are analyzing for further investigation?

**Comment by rflores5** [comment]
@mbenz89 
I would like to investigate this issue. Can I be assigned it?
