### ISSUE TITLE
soot.SootResolver$SootClassNotFoundException when ...

### ISSUE THREAD

**Issue by abhijit819** [Sable/soot#1096]
Steps to reproduce:
1.) **Ran the example** can anybody help me out with this. Thanks. 

Files used to reproduce: 
https://raw.githubusercontent.com/wiki/Sable/soot/code/createclass/Main.java

Soot version: <pre>trunk</pre> 

Command line:
<pre>java -cp sootclasses-trunk-jar-with-dependencies.jar soot.Main -cp . -pp  Main</pre>

Max Memory:
<pre>866MB</pre>

Stack trace:
<pre>soot.SootResolver$SootClassNotFoundException: couldn&#39;t find class: soot.Body (is your soot-class-path set properly?)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:232)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:214)
	at soot.SootResolver.bringToSignatures(SootResolver.java:279)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:172)
	at soot.SootResolver.resolveClass(SootResolver.java:134)
	at soot.Scene.loadClass(Scene.java:942)
	at soot.Scene.loadClassAndSupport(Scene.java:929)
	at soot.Scene.loadNecessaryClass(Scene.java:1729)
	at soot.Scene.loadNecessaryClasses(Scene.java:1741)
	at soot.Main.run(Main.java:241)
	at soot.Main.main(Main.java:141)
</pre>

**Comment by mbenz89** [comment]
With this command-line, you are instructing Soot to analyze the provided `Main` class. This class uses Soot itself and thus it uses the `soot.Body` class. Soot now complains that it cannot find the source of the `soot.Body` class, which is correct since you did not add the Soot classes to Soot's classpath.

What you really want to do is run your `Main` class with Java directly, since it uses Soot as a library to create a class. You really do not want to analyze `Main` with Soot.

This is your command-line: `java -cp sootclasses-trunk-jar-with-dependencies.jar:. Main`

**Comment by abhijit819** [comment]
Thank you. This was very helpful.
