### ISSUE TITLE
java.lang.IllegalArgumentException when ...

### ISSUE THREAD

**Issue by icoolfox72** [Sable/soot#1100]
Steps to reproduce:
1.) runs soot on Mac OS Mojave

Files used to reproduce: 
Very simple basic java program
class HelloWorldApp {
    public static void main(String[] args) {
        System.out.println("Hello World!"); // Display the string.
    }
}

Soot version: <pre>trunk</pre>

Command line:
<pre>-cp .:../MyFirstJava/rt.jar HelloWorldApp -f jimple</pre>

Max Memory:
<pre>4096MB</pre>

Stack trace:
<pre>java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.&#60;init&#62;(ClassReader.java:185)
	at org.objectweb.asm.ClassReader.&#60;init&#62;(ClassReader.java:168)
	at org.objectweb.asm.ClassReader.&#60;init&#62;(ClassReader.java:439)
	at soot.asm.AsmClassSource.resolve(AsmClassSource.java:65)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:240)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:214)
	at soot.SootResolver.bringToSignatures(SootResolver.java:279)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:172)
	at soot.SootResolver.resolveClass(SootResolver.java:134)
	at soot.Scene.loadClass(Scene.java:942)
	at soot.Scene.loadClassAndSupport(Scene.java:927)
	at soot.Scene.loadNecessaryClass(Scene.java:1729)
	at soot.Scene.loadNecessaryClasses(Scene.java:1741)
	at soot.Main.run(Main.java:241)
	at soot.Main.main(Main.java:141)
</pre>

**Comment by ShuyangLiu** [comment]
Not sure if this is the actual issue, but did you include jasmin and polyglot?

**Comment by pavanupb** [comment]
You need to place your app name in -process-dir for soot to process all the classes found in the directory. Try running with below command:
-cp .:../MyFirstJava/rt.jar -process-dir <your-dir> -f jimple
