### ISSUE TITLE
can't resolve java classpath issue

### ISSUE THREAD

**Issue by abhijit819** [Sable/soot#1101]

**Comment by abhijit819** [comment]
Hi,

I am new to Soot and I tried the following code:
`
public class mytry
{
	public static void main(String[] args) {
		args = new String[] {"VeryBusyClass"};
		
		if (args.length == 0) {
			System.out.println("Usage: java RunVeryBusyAnalysis class_to_analyse");
			System.exit(0);
		}
	Options.v().set_soot_classpath("/home/abhijit/Desktop/soot/nightly_build/soot_10th_jan_2019/");	
   		Options.v().set_keep_line_number(true);
		SootClass sClass = Scene.v().loadClassAndSupport(args[0]);		
		sClass.setApplicationClass();
		
		Iterator methodIt = sClass.getMethods().iterator();
		while (methodIt.hasNext()) {
			SootMethod m = (SootMethod)methodIt.next();
			Body b = m.retrieveActiveBody();
			
			System.out.println("=======================================");			
			System.out.println(m.toString());
		}
	}
}

`
Running this command :
 java -cp sootclasses-trunk-jar-with-dependencies.jar:.:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar mytry


The error is:
Exception in thread "main" soot.SootResolver$SootClassNotFoundException: couldn't find class: java.lang.Object (is your soot-class-path set properly?) Try adding rt.jar to Soot's classpath, e.g.:
java -cp sootclasses.jar soot.Main -cp .:/path/to/jdk/jre/lib/rt.jar <other options>
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:232)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:214)
	at soot.SootResolver.bringToSignatures(SootResolver.java:279)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:172)
	at soot.SootResolver.resolveClass(SootResolver.java:134)
	at soot.Scene.loadClass(Scene.java:942)
	at soot.Scene.loadClassAndSupport(Scene.java:927)
	at mytry.main(mytry.java:37)

Can you please help me out with understanding what's going wrong here. How can I load the rt.jar?

Thanks and regards,
Abhijit
