### ISSUE TITLE
Compiling Jasmin assembly

### ISSUE THREAD

**Issue by BaerMitUmlaut** [Sable/soot#1102]
On your github.io page you mention

>What input formats does Soot provide?
>- Jasmin, a low-level intermediate representation.

However, I simply cannot figure out how to use a Jasmin file as an input format. I tried grabbing the Jasmin standalone binary from [here](https://soot-build.cs.uni-paderborn.de/public/origin/master/soot/jasmin-master/3.0.1/build/), but it does not compile the output Soot generated for the following class (due to the function reference/lambda magic):

```java
import java.util.function.Function;

public class test {
    public static void main(String... argv) {
        Function<Object, Object> dummyRef = test::dummy;
        dummyRef.apply(null);
    }

    public static Object dummy(Object object) {
        return null;
    }
}
```

<details>
<summary>Generated output:</summary>

```jasmin
.source test.java
.class public test
.super java/lang/Object

.inner_class_attr 
.inner_class_spec_attr "java/lang/invoke/MethodHandles$Lookup" "java/lang/invoke/MethodHandles" "Lookup" public static final .end .inner_class_spec_attr
.end .inner_class_attr

.method public <init>()V
    .limit stack 1
    .limit locals 1
    aload_0
    invokespecial java/lang/Object/<init>()V
    return
.end method

.method public static transient main([Ljava/lang/String;)V
    .limit stack 2
    .limit locals 1
    invokedynamic "apply" ()Ljava/util/function/Function; java/lang/invoke/LambdaMetafactory/metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite;((Ljava/lang/invoke/MethodType;)methodtype:\blankjava.lang.Object\blank__METHODTYPE__(java.lang.Object),(Ljava/lang/invoke/MethodHandle;)methodhandle:\blank"REF_INVOKE_STATIC"\blank<test:\blankjava.lang.Object\blankdummy(java.lang.Object)>,(Ljava/lang/invoke/MethodType;)methodtype:\blankjava.lang.Object\blank__METHODTYPE__(java.lang.Object))
    aconst_null
    invokeinterface java/util/function/Function/apply(Ljava/lang/Object;)Ljava/lang/Object; 2
    pop
    return
.end method

.method public static dummy(Ljava/lang/Object;)Ljava/lang/Object;
    .limit stack 1
    .limit locals 1
    aconst_null
    areturn
.end method
```
</details>
<br>

Is there any way to compile that output?

**Comment by ericbodden** [comment]
Hmm, this used to work. What error message are you seeing?

Also, why are you using Jasmin in the first place? Instead you can just ask Soot to directly generate .class files.

Cheers
Eric

**Comment by BaerMitUmlaut** [comment]
Jasmin 3.0.1 error:
```
$ java -jar jamsin-trunk.jar jsmn/test.jasmin
test.jasmin:20: Warning - Syntax error.
    invokedynamic "apply" ()Ljava/util/function/Function; java/lang/invoke/LambdaMetafactory/metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite;((Ljava/lang/invoke/MethodType;)methodtype:\
                                                                                                                                                                                                                                                                                                                                                                ^
instead expected token classes are [SEP]
jsmn/test.jasmin: Found 1 errors
```

Jasmin 2.5.0 error:
```
$ jasmin jsmn/test.jasmin 
test.jasmin:20: Warning - Syntax error.
    invokedynamic "apply" ()Ljava/util/function/Function; java/lang/invoke/LambdaMetafactory/metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite;((Ljava/lang/invoke/MethodType;)methodtype:\
                                                                                                                                                                                                                                                                                                                                                                ^
jsmn/test.jasmin: Found 1 errors
```

Soot error (though I'm not sure if I need more flags to run it):
```
$ java -jar sootclasses-trunk-jar-with-dependencies.jar -cp .:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/rt.jar jsmn/test
Soot started on Sat Jan 26 04:51:54 PST 2019
java.lang.RuntimeException: Attempt to create RefType containing a / --> jsmn/test
	at soot.RefType.<init>(RefType.java:59)
	at soot.RefType.v(RefType.java:77)
	at soot.SootClass.initializeRefType(SootClass.java:112)
	at soot.SootClass.<init>(SootClass.java:97)
	at soot.SootClass.<init>(SootClass.java:121)
	at soot.SootResolver.makeClassRef(SootResolver.java:118)
	at soot.SootResolver.resolveClass(SootResolver.java:132)
	at soot.Scene.loadClass(Scene.java:942)
	at soot.Scene.loadClassAndSupport(Scene.java:927)
	at soot.Scene.loadNecessaryClass(Scene.java:1729)
	at soot.Scene.loadNecessaryClasses(Scene.java:1741)
	at soot.Main.run(Main.java:241)
	at soot.Main.main(Main.java:141)
```

**Comment by BaerMitUmlaut** [comment]
Taking a closer look at it, seems like the `\blank` is the problem. Is it supposed to be a space? Found this in Soot's source.
```java
return bsmArgString.replace(",", "\\comma").replace(" ", "\\blank") [...]
```

**Comment by BaerMitUmlaut** [comment]
I'm currently digging a little deeper. Jasmin 2.4 (and below I believe) do not know the `.inner_class_attr` instruction. If those instructions at the top are removed, it also shows a syntax error in the invokedynamic instruction and notes that `\b` is not a valid escape sequence.

So I switched to debugging Jasmin and the error comes directly from the generated parser, I assume it treats the \ as a token seperator. The grammar is quite massive, I'm not quite sure where to look to change that, I'll try reverting to old versions of it and see if I can find one that works for now.

Oh and I also found this commit through git blame: https://github.com/Sable/jasmin/commit/96accfb59e1b32eddc8e55cfcef43fa7d9c7f567
That function is only called for the invokedynamic instruction, I assume the parser is supposed to return the whole thing as one token that is later unescaped - did I get this right?

**Comment by BaerMitUmlaut** [comment]
I found the culprit! It was actually not the `\blank`, it was the `:` which is a token separator:
https://github.com/Sable/jasmin/blob/develop/src/jasmin/Scanner.java#L52

For testing I simply removed it from the separators, as the example given above has no labels. This raises the following exception:
```
test.j:21: C:\Users\------\Documents\Private\compiler\test.j: exception - <java.lang.UnsupportedOperationException> static argument type not currently supported: Ljava/lang/invoke/MethodType;..
    a
     ^
java.lang.UnsupportedOperationException: static argument type not currently supported: Ljava/lang/invoke/MethodType;
```

Which makes a whole lot more sense. Seems like Jasmin never actually supported function references (or at least not in the way soot generates them)? I'm not sure where to go from here. Time to take a look into soot's source now I guess, since I'm not sure how difficult it would be to add support for that myself.

**Comment by BaerMitUmlaut** [comment]
Holy crap I managed to implement it in Jasmin. It's a hacky approach right now, with some things hardcoded, but I could make it nicer if you would like a PR, let me know.

Basically you only need one new class, MethodTypeCP, which writes `CONSTANT_METHOD_TYPE` (= 16) and the constant pool index of the method signature (`(Ljava/lang/Object;)Ljava/lang/Object;` in my case). Then the special handling of `invokedynamic` needs to be expanded to handle both `Ljava/lang/invoke/MethodType;` and `Ljava/lang/invoke/MethodHandle;` which involves some parsing of Soot's output above.

Ideally that should be cleaned up, too, especially since it contains a colon that breaks the parser. I assume the current String representation was meant mainly for debugging purposes.

**Comment by ericbodden** [comment]
Thanks a lot for getting this fixed! We’d be more than happy to accept a pull request. Please try to make it as simple and as easy to understand as possible.
