### ISSUE TITLE
System tests are failing non-deterministically 

### ISSUE THREAD

**Issue by mbenz89** [Sable/soot#1122]
As witnessed in #1120 the LambdaMetaFactory system tests are failing from time to time.
In the stated PR, `soot.lambdaMetaFactory.LambdaMetaFactoryCHATest` was failing with an exception that unfortunately got lost.
If I remember correctly, the exception was caused by using a virtualInvoke statement where an interfaceInvoke would have been required...

**Comment by jpstotz** [comment]
@mbenz89  Unfortunately I also don't have the stacktrace shown by the CI. However there is another error thrown by this test non-deterministically (usually by the `lambdaNoCaptures` from the `lambdaMetaFactory` tests):

```
[Thread-118] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: Failed to convert <java.util.function.Function: java.util.function.Function andThen(java.util.function.Function)>
java.lang.RuntimeException: Failed to convert <java.util.function.Function: java.util.function.Function andThen(java.util.function.Function)>
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:2040)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:402)
	at soot.PackManager$1.run(PackManager.java:1279)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Trying to create virtual invoke expression for interface type (java.util.function.Function in file null). Use JInterfaceInvokeExpr instead!
	at soot.jimple.internal.JVirtualInvokeExpr.<init>(JVirtualInvokeExpr.java:49)
	at soot.jimple.Jimple.newVirtualInvokeExpr(Jimple.java:469)
	at soot.LambdaMetaFactory$ThunkMethodSource._invokeImplMethod(LambdaMetaFactory.java:699)
	at soot.LambdaMetaFactory$ThunkMethodSource.invokeImplMethod(LambdaMetaFactory.java:646)
	at soot.LambdaMetaFactory$ThunkMethodSource.getInvokeBody(LambdaMetaFactory.java:483)
	at soot.LambdaMetaFactory$ThunkMethodSource.getBody(LambdaMetaFactory.java:334)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:402)
	at soot.LambdaMetaFactory.makeLambdaHelper(LambdaMetaFactory.java:239)
	at soot.asm.AsmMethodSource.convertInvokeDynamicInsn(AsmMethodSource.java:1420)
	at soot.asm.AsmMethodSource.convert(AsmMethodSource.java:1791)
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:2038)
	... 5 more
```
As the CountingThreadPoolExecutor  is involved I would guess that there is a threading issue causing this.

Note: In Intellij there is the nice option to start a set of unit tests and repeat them "Until Failure". This simplifies to reproduce such errors.

**Comment by mbenz89** [comment]
Thanks for reporting the exact stack trace! Also, thanks for pointing out that feature, I did not know it yet :). 

Since the PR, I've witnessed several issues with the `LambdaMetaFactory` that seem to be related. I will investigate this further when I find time for it. 

@anddann MIght also be interesting to you...

**Comment by anddann** [comment]
Side note: without `synchronized` at the `soot.LambdaMetaFactory.makeLambdaHelper` method, I can  reproduce the error reliable

**Comment by mbenz89** [comment]
@anddann The authors of the `LambdaMetaFactory` reported NPE's when not synchronizing the `soot.LambdaMetaFactory.makeLambdaHelper` method: #1078 and #1083
Are you witnessing the same?

**Comment by anddann** [comment]
@mbenz89 I get the same stacktrace as reported in #1078 `crash2.rtf`

**Comment by mbenz89** [comment]
fixed by https://github.com/Sable/soot/pull/1191
