### ISSUE TITLE
java.lang.RuntimeException when ...

### ISSUE THREAD

**Issue by TrangJun** [Sable/soot#1123]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: <pre>trunk</pre>

Command line:
<pre>-w -f n -allow-phantom-refs -x android.support. -x android.annotation. -process-dir /home/trangjun/Downloads/app.apk -android-jars android-jars -src-prec apk -no-bodies-for-excluded</pre>

Max Memory:
<pre>1820MB</pre>

Stack trace:
<pre>java.lang.RuntimeException: No method source set for method &#60;com.amazon.device.ads.legacy.ThreadUtils$MobileAdsAsyncTask: java.lang.Object doInBackground(java.lang.Object[])&#62;
	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:90)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:322)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processNewMethod(OnFlyCallGraphBuilder.java:531)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processReachables(OnFlyCallGraphBuilder.java:420)
	at soot.jimple.toolkits.callgraph.CallGraphBuilder.build(CallGraphBuilder.java:96)
	at soot.jimple.toolkits.callgraph.CHATransformer.internalTransform(CHATransformer.java:46)
	at soot.SceneTransformer.transform(SceneTransformer.java:39)
	at soot.SceneTransformer.transform(SceneTransformer.java:45)
	at soot.SceneTransformer.transform(SceneTransformer.java:50)
	at edu.buffalo.cse.blueseal.utils.DynamicEntryPointsManager.parseLayoutForDynamicEntryPoints(DynamicEntryPointsManager.java:52)
	at edu.buffalo.cse.blueseal.utils.DynamicEntryPointsManager.&#60;init&#62;(DynamicEntryPointsManager.java:40)
	at edu.buffalo.cse.blueseal.utils.EntryPointsManager.loadApkEntryPoints(EntryPointsManager.java:42)
	at edu.buffalo.cse.blueseal.BSCallgraph.BSCallGraphTransformer.internalTransform(BSCallGraphTransformer.java:40)
	at soot.SceneTransformer.transform(SceneTransformer.java:39)
	at soot.Transform.apply(Transform.java:90)
	at soot.ScenePack.internalApply(ScenePack.java:40)
	at soot.Pack.apply(Pack.java:118)
	at soot.PackManager.runWholeProgramPacks(PackManager.java:571)
	at soot.PackManager.runPacksNormally(PackManager.java:461)
	at soot.PackManager.runPacks(PackManager.java:396)
	at soot.Main.run(Main.java:271)
	at soot.Main.main(Main.java:147)
	at edu.buffalo.cse.blueseal.main.Main.main(Main.java:48)
</pre>

**Comment by mbenz89** [comment]
Could you provide the analyzed app?

**Comment by TrangJun** [comment]
this is the app https://github.com/ub-rms/blueseal

**Comment by TrangJun** [comment]
I didn't meet this error when I ran with older apk file. I think cause this problem is soot version don't support for new app which have amazon service
