### ISSUE TITLE
Unit test LambdaMetaFactoryAdaptTest: ConcurrentModificationException

### ISSUE THREAD

**Issue by jpstotz** [Sable/soot#1125]
From time to time I am getting an ConcurrentModificationException when executing `mvn test` for the current soot develop branch (012b72dc924dd17fa4ab49a88d69ff2c885a6ad1):

```
[INFO] Running soot.lambdaMetaFactory.LambdaMetaFactoryAdaptTest
[Thread-55] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: Failed to apply jb to <soot.lambdaMetaFactory.Adapt: void lambda$parameterWidening$7(java.lang.Number)>
java.lang.RuntimeException: Failed to apply jb to <soot.lambdaMetaFactory.Adapt: void lambda$parameterWidening$7(java.lang.Number)>
        at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:2068)
        at soot.SootMethod.retrieveActiveBody(SootMethod.java:402)
        at soot.PackManager$1.run(PackManager.java:1279)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.ConcurrentModificationException
        at soot.util.HashChain$LinkIterator.hasNext(HashChain.java:563)
        at java.util.AbstractCollection.toArray(AbstractCollection.java:139)
        at java.util.ArrayList.<init>(ArrayList.java:178)
        at soot.util.HashChain.snapshotIterator(HashChain.java:372)
        at soot.FastHierarchy.<init>(FastHierarchy.java:165)
        at soot.Scene.getOrMakeFastHierarchy(Scene.java:1273)
        at soot.jimple.toolkits.typing.fast.BytecodeHierarchy.ancestor_(BytecodeHierarchy.java:224)
        at soot.jimple.toolkits.typing.fast.BytecodeHierarchy.ancestor(BytecodeHierarchy.java:292)
        at soot.jimple.toolkits.typing.fast.TypeResolver$CastInsertionUseVisitor.visit(TypeResolver.java:204)
        at soot.jimple.toolkits.typing.fast.UseChecker.handleInvokeExpr(UseChecker.java:140)
        at soot.jimple.toolkits.typing.fast.UseChecker.caseInvokeStmt(UseChecker.java:182)
        at soot.jimple.internal.JInvokeStmt.apply(JInvokeStmt.java:91)
        at soot.jimple.toolkits.typing.fast.UseChecker.check(UseChecker.java:127)
        at soot.jimple.toolkits.typing.fast.TypeResolver.insertCasts(TypeResolver.java:411)
        at soot.jimple.toolkits.typing.fast.TypeResolver.minCasts(TypeResolver.java:435)
        at soot.jimple.toolkits.typing.fast.TypeResolver.inferTypes(TypeResolver.java:152)
        at soot.jimple.toolkits.typing.TypeAssigner.internalTransform(TypeAssigner.java:121)
        at soot.BodyTransformer.transform(BodyTransformer.java:51)
        at soot.Transform.apply(Transform.java:120)
        at soot.JimpleBodyPack.applyPhaseOptions(JimpleBodyPack.java:73)
        at soot.JimpleBodyPack.internalApply(JimpleBodyPack.java:105)
        at soot.Pack.apply(Pack.java:125)
        at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:2066)
        ... 5 more
```

**Comment by mbenz89** [comment]
Related to #1122

**Comment by mbenz89** [comment]
fixed by https://github.com/Sable/soot/pull/1191
