### ISSUE TITLE
soot.SootResolver$SootClassNotFoundException when ...

### ISSUE THREAD

**Issue by BushraAloraini** [Sable/soot#1128]
I am using soot as a library, but it seems that it does not find  DotGraph!

Soot version: <pre>trunk</pre>

Command line:
java -cp <path-to-jar>soot.Main -cp <.:path-to-rt.jar> -pp -process-dir .</pre>

Max Memory:
<pre>3641MB</pre>

Stack trace:
<pre>soot.SootResolver$SootClassNotFoundException: couldn&#39;t find class: soot.util.dot.DotGraph (is your soot-class-path set properly?)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:232)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:214)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:175)
	at soot.SootResolver.resolveClass(SootResolver.java:134)
	at soot.Scene.loadClass(Scene.java:942)
	at soot.Scene.loadClassAndSupport(Scene.java:927)
	at soot.Scene.loadNecessaryClasses(Scene.java:1753)
	at soot.Main.run(Main.java:241)
	at soot.Main.main(Main.java:141)
</pre>

**Comment by BushraAloraini** [comment]
This seems to be a bug. Looking at soot/src/main/java/soot/SootResolver.java: line 232

` throw new SootClassNotFoundException(
              "couldn't find class: " + className + " (is your soot-class-path set properly?)" + suffix);`


It just throws this exception after ensuring that rt.jar or jce.jar in the classpath. The problem does not appear when adding the option  "-allow-phantom-refs"   but this option may not render good results.

**Comment by BushraAloraini** [comment]
I think I found the solution: 
we just need to add soot.jar to soot.Main -cp , so it would be : java -cp <path-to-soot-jar> soot.Main -cp <.:path-to-rt.jar:path-to-soot-jar> -pp -process-dir .</pre>
