### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by roskad** [Sable/soot#1132]
Hello,

Soot produces a StackOverflowError with [this apk](https://github.com/Sable/soot/files/2975683/109B67907AAEB3B3477B3191836E2DD810252B2F9B8DA125ABE475D26796D75C.zip).

This is the start of the printstack :
`at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:512) ~[?:?]
	at java.lang.StringBuilder.append(StringBuilder.java:141) ~[?:?]
	at soot.SootField.getSubSignature(SootField.java:102) ~[soot-3.3.0.jar:?]
	at soot.SootField.getSignature(SootField.java:76) ~[soot-3.3.0.jar:?]
	at soot.AbstractSootFieldRef.getSignature(AbstractSootFieldRef.java:84) ~[soot-3.3.0.jar:?]
	at soot.jimple.internal.AbstractInstanceFieldRef.toString(AbstractInstanceFieldRef.java:60) ~[soot-3.3.0.jar:?]
	at soot.jimple.internal.JAssignStmt.toString(JAssignStmt.java:218) ~[soot-3.3.0.jar:?]
	at java.lang.String.valueOf(String.java:2788) ~[?:?]
	at java.lang.StringBuilder.append(StringBuilder.java:135) ~[?:?]
	at soot.jimple.internal.JLookupSwitchStmt.toString(JLookupSwitchStmt.java:97) ~[soot-3.3.0.jar:?]
	at java.lang.String.valueOf(String.java:2788) ~[?:?]
	at java.lang.StringBuilder.append(StringBuilder.java:135) ~[?:?]
	at soot.jimple.internal.JLookupSwitchStmt.toString(JLookupSwitchStmt.java:97) ~[soot-3.3.0.jar:?]
	at java.lang.String.valueOf(String.java:2788) ~[?:?]
	at java.lang.StringBuilder.append(StringBuilder.java:135) ~[?:?]
	at soot.jimple.internal.JLookupSwitchStmt.toString(JLookupSwitchStmt.java:102) ~[soot-3.3.0.jar:?]
	at java.lang.String.valueOf(String.java:2788) ~[?:?]
	at java.lang.StringBuilder.append(StringBuilder.java:135) ~[?:?]
	at soot.jimple.internal.JLookupSwitchStmt.toString(JLookupSwitchStmt.java:97) ~[soot-3.3.0.jar:?]
	at java.lang.String.valueOf(String.java:2788) ~[?:?]
	at java.lang.StringBuilder.append(StringBuilder.java:135) ~[?:?]
	at soot.jimple.internal.JLookupSwitchStmt.toString(JLookupSwitchStmt.java:102) ~[soot-3.3.0.jar:?]
	at java.lang.String.valueOf(String.java:2788) ~[?:?]
	at java.lang.StringBuilder.append(StringBuilder.java:135) ~[?:?]
	at soot.jimple.internal.JLookupSwitchStmt.toString(JLookupSwitchStmt.java:97) ~[soot-3.3.0.jar:?]
	at java.lang.String.valueOf(String.java:2788) ~[?:?]
	at java.lang.StringBuilder.append(StringBuilder.java:135) ~[?:?]
	at soot.jimple.internal.JLookupSwitchStmt.toString(JLookupSwitchStmt.java:102) ~[soot-3.3.0.jar:?]
	at java.lang.String.valueOf(String.java:2788) ~[?:?]`

Regards,
Remy

**Comment by jpstotz** [comment]
Can you please tell us what you did to produce this error (and for which class and field in the APK it occurred)? It seems like you called `getSubSignature()` on a specific field. However I just tried the APK using development branch and performed:

	for (SootClass sootClass : Scene.v().getApplicationClasses()) {
		for (SootField f : sootClass.getFields()) {
			System.out.println(f.getSubSignature());
		}
	}

However it did not trigger the error you encountered.

**Comment by roskad** [comment]
I make a minimalist java which produces the StackOverflow. Please find it [here](https://gitlab.centralesupelec.fr/nicol_rem/simplesoot) (or just [the java class](https://gitlab.centralesupelec.fr/nicol_rem/simplesoot/blob/master/src/main/java/Main.java)).

The output juste before the StackOverflow is : 
> Class : **com.immersion.hapticmediasdk.models.HttpUnsuccessfulException**
>    Method : **\<init\>**
>       $r0 := @this: com.immersion.hapticmediasdk.models.httpunsuccessfulexception
>       $i0 := @parameter0: int
>       $r1 := @parameter1: java.lang.string
>       specialinvoke $r0.<java.lang.exception: void <init>(java.lang.string)>($r1)
> 
> Exception in thread "main" java.lang.StackOverflowError

I found other apks which throw the same error today, if you wish.

**Comment by JeannedArk** [comment]
I ran into the same issue with the following [com.db.pwcc.dbmobile](https://storage.evozi.com/apk/dl/17/04/24/com.db.pwcc.dbmobile.apk?h=Lk26cGv8nCA1Wc6C4HuvuA&t=1562058724&vc=17972) (file was too big to upload, I hope the link is available for long enough). Here is a minimal example that evokes that bug:

```
import soot.*
import soot.options.Options
import java.io.IOException
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardCopyOption

class BugDemo : Instrumenter() {

    override fun instrument(apkPath: Path, outputDir: Path): Path {
        outputDir.createDirIfNonExisting()
        val workDir = Files.createTempDirectory("instrumentation")
        val apkToolDir = workDir.resolve("apkTool")

        val instrumentedApk = sootInstrumentation(apkPath, outputDir, workDir, apkToolDir)
        return instrumentedApk
    }

    private fun sootInstrumentation(apkPath: Path, outputDir: Path, workDir: Path, apkToolDir: Path): Path {
        Files.createDirectories(apkToolDir)

        val tmpOutApk = workDir.resolve(apkPath.fileName)
        Files.copy(apkPath, tmpOutApk, StandardCopyOption.REPLACE_EXISTING)
        val sootDir = workDir.resolve("soot")
        configSoot(tmpOutApk, sootDir)

        val instrumentedApk = instrumentWithSoot(apkPath, sootDir)
        val outputApk = outputDir.resolve(
            instrumentedApk.fileName.toString().replace(".apk", "-instrumented.apk")
        )

        Files.move(instrumentedApk, outputApk, StandardCopyOption.REPLACE_EXISTING)

        return outputApk
    }

    @Throws(IOException::class)
    private fun configSoot(
        processingApk: Path,
        sootOutputDir: Path
    ) {
        Options.v().set_allow_phantom_refs(true)
        Options.v().set_src_prec(Options.src_prec_apk)
        Options.v().set_output_dir(sootOutputDir.toString())
        Options.v().set_debug(true)
        Options.v().set_validate(true)
        Options.v().set_output_format(Options.output_format_dex)

        val processDirs = ArrayList<String>()
        processDirs.add(processingApk.toString())

        Options.v().set_process_multiple_dex(true)
        Options.v().set_process_dir(processDirs)

        Options.v().set_android_jars("ANDROID_HOME".asEnvDir.resolve("platforms").toString())

        Scene.v().loadNecessaryClasses()
    }

    private fun instrumentWithSoot(apkPath: Path, sootDir: Path): Path {
        log.info("Start instrumenting...")

        val transformer = ITransformer()

        PackManager.v().getPack("jtp").add(transformer)

        PackManager.v().runPacks()
        PackManager.v().writeOutput()

        val instrumentedApk = sootDir.resolve(apkPath.fileName)
        log.info("Instrumentation finished: $instrumentedApk")

        if (!Files.exists(instrumentedApk))
            throw RuntimeException("Failed to instrument $this. Instrumented APK not found.")

        return instrumentedApk
    }

    inner class ITransformer :
        Transform("jtp.bug", object : BodyTransformer() {

            override fun internalTransform(b: Body, phaseName: String, options: MutableMap<String, String>) {
                b.validate()
            }
        })

}
```
I am using ca.mcgill.sable:soot:3.3.0-SNAPSHOT.

Extract from the evoked bug:

> 10:05:38.146 [Thread-12] DEBUG soot.PackManager - Transforming com.db.pwcc.dbmobile.postbox.messages.DownloadContentService$shhssh...
> 10:05:38.149 [Thread-12] DEBUG soot.PackManager - Transforming net.gini.android.vision.DocumentImportEnabledFileTypes...
> 10:05:38.153 [Thread-12] DEBUG soot.PackManager - Transforming android.arch.lifecycle.MutableLiveData...
> 10:05:38.154 [Thread-12] DEBUG soot.PackManager - Transforming uuuuuu.hrhrrh...
> 10:05:41.191 [Thread-15] DEBUG soot.PackManager - Transforming android.arch.persistence.db.SupportSQLiteProgram...
> 10:05:38.164 [Thread-16] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: null
> java.lang.StackOverflowError: null
> 	at soot.SootField.getSubSignature(SootField.java:102)
> 	at soot.SootField.getSignature(SootField.java:76)
> 	at soot.AbstractSootFieldRef.getSignature(AbstractSootFieldRef.java:84)
> 	at soot.jimple.StaticFieldRef.toString(StaticFieldRef.java:54)
> 	at soot.jimple.internal.JAssignStmt.toString(JAssignStmt.java:218)
> 	at java.lang.String.valueOf(String.java:2994)
> 	at java.lang.StringBuilder.append(StringBuilder.java:131)
> 	at soot.jimple.internal.JLookupSwitchStmt.toString(JLookupSwitchStmt.java:97)
> 	at java.lang.String.valueOf(String.java:2994)
> 	at java.lang.StringBuilder.append(StringBuilder.java:131)
> 	at soot.jimple.internal.JLookupSwitchStmt.toString(JLookupSwitchStmt.java:102)
