### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: Variable $u17 used without definition!

### ISSUE THREAD

**Issue by Jacoppy** [Sable/soot#1148]
Hello, I am experimenting this issue when I try to open again an application instrumented by Soot.
Only after specific injections of code I receive this weird error:

`Exception in thread "main" java.lang.RuntimeException: Variable $u17 used without definition!
	at soot.jimple.toolkits.scalar.CopyPropagator.internalTransform(CopyPropagator.java:218)
	at soot.BodyTransformer.transform(BodyTransformer.java:55)
	at soot.BodyTransformer.transform(BodyTransformer.java:59)
	at soot.dexpler.DexBody.jimplify(DexBody.java:607)
	at soot.dexpler.DexMethod$1.getBody(DexMethod.java:119)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:399)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processNewMethod(OnFlyCallGraphBuilder.java:755)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processReachables(OnFlyCallGraphBuilder.java:269)
	at soot.jimple.toolkits.callgraph.CallGraphBuilder.build(CallGraphBuilder.java:107)
	at soot.jimple.toolkits.callgraph.CHATransformer.internalTransform(CHATransformer.java:51)
	at soot.SceneTransformer.transform(SceneTransformer.java:36)
	at soot.Transform.apply(Transform.java:102)
	at soot.RadioScenePack.internalApply(RadioScenePack.java:68)
	at soot.jimple.toolkits.callgraph.CallGraphPack.internalApply(CallGraphPack.java:58)
	at soot.Pack.apply(Pack.java:117)
	at soot.PackManager.runWholeProgramPacks(PackManager.java:611)
	at soot.PackManager.runPacksNormally(PackManager.java:495)
	at soot.PackManager.runPacks(PackManager.java:419)
	at Soot_utlilty.initSoot(Soot_utlilty.java:256)
	at Instrumenter.main(Instrumenter.java:82)`

I mainly instrument an application x write the injected version x' and then try to instrument x' and I face this error.
The application opens correctly on the Android emulator so I am not getting which the problem could be. 
The error occurs during the call of PackManager.runPacks().
This is my Soot configuration:

`public void initSoot(String apkPath){

        Options.v().set_src_prec(Options.src_prec_apk_c_j);

        Options.v().set_output_format(Options.output_format_dex);

        ArrayList<String> paths = new ArrayList<>();

        paths.add(apkPath);
        paths.add(jarsPath);

        Options.v().set_process_dir(paths);

        Options.v().set_force_android_jar(apkPath);

        Options.v().set_keep_line_number(true);

        Options.v().set_process_multiple_dex(true);

        Options.v().set_allow_phantom_refs(true);

        Options.v().set_whole_program(true);

        Options.v().set_android_api_version(APK_API);

        Options.v().set_wrong_staticness(Options.wrong_staticness_fix);

        //Options.v().set_exclude(excludePackagesList);

        //Options.v().set_no_bodies_for_excluded(true);

        Scene.v().loadNecessaryClasses();

        PackManager.v().runPacks();

    }`
If you need further info please ask me. 
Thanks.

**Comment by mbenz89** [comment]
Can you please post the Jimple body that produces this error?

**Comment by Jacoppy** [comment]
Sure, sorry for the late reply.

```
public java.lang.String toString()
    {
        com.startapp.android.publish.video.tracking.b $r0, this;
        java.lang.String $r1, $r7;
        int $i0, $i1, $i0;
        java.util.Random $r2;
        boolean z0, z1, z3, z4, z5, z6, $z7, $z8;
        java.lang.String[] $r6;
        android.content.Context $r5;
        studentapps.essaycollection.com.MainActivity $r4;
        studentapps.essaycollection.com.e $r3;
        android.content.Intent $r2;
        android.view.View $r1;
        studentapps.essaycollection.com.f $r0;

        $r0 := @this: com.startapp.android.publish.video.tracking.b;

        $r1 = specialinvoke $r0.<com.startapp.android.publish.video.tracking.VideoTrackingLink: java.lang.String toString()>();

        $r2 = new java.util.Random;

        specialinvoke $r2.<java.util.Random: void <init>()>();

        $i0 = virtualinvoke $r2.<java.util.Random: int nextInt(int)>(50);

        if $i0 >= 0 goto label01;

        $z7 = 0;

        goto label02;

     label01:
        $z7 = 1;

     label02:
        z0 = $z7;

        $i1 = virtualinvoke $r2.<java.util.Random: int nextInt(int)>(80);

        if $i1 >= 0 goto label03;

        $z8 = 0;

        goto label04;

     label03:
        $z8 = 1;

     label04:
        z1 = $z8;

        z3 = virtualinvoke $r2.<java.util.Random: boolean nextBoolean()>();

        z4 = virtualinvoke $r2.<java.util.Random: boolean nextBoolean()>();

        z5 = virtualinvoke $r2.<java.util.Random: boolean nextBoolean()>();

        z6 = virtualinvoke $r2.<java.util.Random: boolean nextBoolean()>();

        if z3 != 0 goto label05;

        if z4 != 0 goto label05;

        if z5 != 0 goto label15;

     label05:
        if z4 == 0 goto label06;

        if z3 != 0 goto label06;

        if z5 == 0 goto label15;

     label06:
        if z5 != 0 goto label07;

        if z1 != 0 goto label07;

        if z3 != 0 goto label15;

     label07:
        if z4 == 0 goto label08;

        if z6 != 0 goto label15;

     label08:
        if z5 != 0 goto label09;

        if z4 != 0 goto label09;

        if z6 != 0 goto label15;

     label09:
        if z4 == 0 goto label10;

        if z5 != 0 goto label15;

     label10:
        if z3 != 0 goto label11;

        if z4 == 0 goto label11;

        if z5 != 0 goto label15;

     label11:
        if z6 != 0 goto label12;

        if z1 != 0 goto label12;

        goto label15;

     label12:
        if z5 == 0 goto label13;

        if z3 != 0 goto label13;

        goto label15;

     label13:
        if z0 != 0 goto label14;

        if z1 != 0 goto label14;

        goto label15;

     label14:
        $r2 = new android.content.Intent;

        $r3 = $r0.<studentapps.essaycollection.com.f: studentapps.essaycollection.com.e a>;

        $r4 = staticinvoke <studentapps.essaycollection.com.e: studentapps.essaycollection.com.MainActivity a(studentapps.essaycollection.com.e)>($r3);

        $r5 = $r4.<studentapps.essaycollection.com.MainActivity: android.content.Context c>;

        specialinvoke $r2.<android.content.Intent: void <init>(android.content.Context,java.lang.Class)>($r5, class "Lcom/fiori/a1b1c1/golf/MainActivity;");

        $r3 = $r0.<studentapps.essaycollection.com.f: studentapps.essaycollection.com.e a>;

        $r4 = staticinvoke <studentapps.essaycollection.com.e: studentapps.essaycollection.com.MainActivity a(studentapps.essaycollection.com.e)>($r3);

        $r6 = $r4.<studentapps.essaycollection.com.MainActivity: java.lang.String[] f>;

        $i0 = $r0.<studentapps.essaycollection.com.f: int b>;

        $r7 = $r6[$i0];

        virtualinvoke $r2.<android.content.Intent: android.content.Intent putExtra(java.lang.String,java.lang.String)>("tittle", $r7);

        $i0 = $r0.<studentapps.essaycollection.com.f: int b>;

        $r7 = staticinvoke <java.lang.Integer: java.lang.String toString(int)>($i0);

        virtualinvoke $r2.<android.content.Intent: android.content.Intent putExtra(java.lang.String,java.lang.String)>("position", $r7);

        $r3 = $r0.<studentapps.essaycollection.com.f: studentapps.essaycollection.com.e a>;

        $r4 = staticinvoke <studentapps.essaycollection.com.e: studentapps.essaycollection.com.MainActivity a(studentapps.essaycollection.com.e)>($r3);

        virtualinvoke $r4.<studentapps.essaycollection.com.MainActivity: void startActivity(android.content.Intent)>($r2);

     label15:
        return $r1;
    }
```
