### ISSUE TITLE
soot.SootResolver$SootClassNotFoundException when ...

### ISSUE THREAD

**Issue by zaoqi** [Sable/soot#1158]
It seems that rt.jar requires javax.crypto.BadPaddingException ...

Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: <pre>trunk</pre>

Command line:
<pre>-W -cp /usr/lib/jvm/default/jre/lib/rt.jar:. -process-path .</pre>

Max Memory:
<pre>409MB</pre>

Stack trace:
<pre>soot.SootResolver$SootClassNotFoundException: couldn&#39;t find class: javax.crypto.BadPaddingException (is your soot-class-path set properly?)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:232)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:214)
	at soot.SootResolver.bringToSignatures(SootResolver.java:279)
	at soot.SootResolver.bringToBodies(SootResolver.java:319)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:164)
	at soot.SootResolver.resolveClass(SootResolver.java:134)
	at soot.Scene.tryLoadClass(Scene.java:912)
	at soot.Scene.loadBasicClasses(Scene.java:1652)
	at soot.Scene.loadNecessaryClasses(Scene.java:1738)
	at soot.Main.run(Main.java:241)
	at soot.Main.main(Main.java:141)
</pre>

**Comment by pavanupb** [comment]
@zaoqi Could you please provide the application you are trying to analyze
