### ISSUE TITLE
java.lang.RuntimeException when ...

### ISSUE THREAD

**Issue by YuuuuuuuuY** [Sable/soot#1161]
Steps to reproduce:
1.) put `Test.java` and `J.java` in the same dir.
2.) compile: `javac Test.java`
3.) run soot using the command below

Files used to reproduce: 
```java
//Test.java
public class Test {
	public void run () {
		J.run();
	}
}
```
```java
//J.java
public class J {
	public static void run() {
		int i = 0;
		int j = i+1;
		return;
	}
}
```

Soot version: <pre>trunk</pre>

Command line:
<pre>-f J -cp .:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/rt.jar -app Test</pre>

Max Memory:
<pre>1820MB</pre>

Stack trace:
<pre>java.lang.RuntimeException: Failed to convert &#60;Test: void run()&#62;
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:2040)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:402)
	at soot.PackManager$1.run(PackManager.java:1279)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: 
Aborting: can&#39;t find classfile J
	at soot.Scene.getSootClass(Scene.java:1137)
	at soot.asm.AsmMethodSource.convertMethodInsn(AsmMethodSource.java:1281)
	at soot.asm.AsmMethodSource.convert(AsmMethodSource.java:1789)
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:2038)
	... 5 more
</pre>

**Comment by pavanupb** [comment]
Try using the -process-dir option and give the directory which contains class files
-f J -cp .:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/rt.jar -process-dir <your directory>

**Comment by YuuuuuuuuY** [comment]
@pavanupb What if there are classes in the same dir but not referenced by Main directly or indirectly, which don't wanted to be processed?

**Comment by pavanupb** [comment]
If you want to run a single file then you need to activate phantom references

**Comment by YuuuuuuuuY** [comment]
I believe this is a bug because soot is not aware that J is a dependency of Test. When visiting the statement "J.run();", it fails to tell that the owner class is J, instead it considers it as soot.LongType.

**Comment by YuuuuuuuuY** [comment]
In soot.asm.MethodBuilder.visitMethodInsn(), the call to `AsmUtil.toBaseType("J", ...)` returns `LongType` instead of a reference type representing class `J`. 
Should it be `AsmUtil.toJimpleRefType(...)`?

**Comment by mbenz89** [comment]
Hm. You might be right here. The owner of a method has to be a class.

There is no way to distinghuis if J is a class name or indicates the long type in `AsmUtil.toBaseType`, right?

Would you like to open a pr with a proper fix?

**Comment by YuuuuuuuuY** [comment]
@mbenz89 Yeah I agree. Just opened a pr. #1371

**Comment by mbenz89** [comment]
It is still strange that J cannot be detected as class. The type should have a leading `L` in bytecode: `LJ`.

Could you post the output of `javap -c Test` so we can have a look at the bytcode of Test.java?

The initial stacktrace also looks like the `J.class` file could not be found.

Could you also try another command line: `-f J -cp .:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/rt.jar -process-dir path-containing-your-classes -w`.

**Comment by YuuuuuuuuY** [comment]
Here's the output of `javap -c Test`:
```Compiled from "Test.java"
public class Test {
  public Test();
    Code:
       0: aload_0
       1: invokespecial #1                  // Method java/lang/Object."<init>":()V
       4: return

  public void run();
    Code:
       0: invokestatic  #2                  // Method J.run:()V
       3: return
}
```

Soot works fine with `-process-dir`.
With the fix, it also works fine with `-app`.

I debugged and saw the value of `owner` is always like `java/lang/Object` for a class. For an array it's `[Ljava/lang/Object;`.
