### ISSUE TITLE
java.lang.RuntimeException: Invalid value type for primitibe operation

### ISSUE THREAD

**Issue by chizizhixin** [Sable/soot#1168]
I want to instrument Google News apk using soot 3.2, but I meet this problem, I do not know how to solve it.

java.lang.RuntimeException: Invalid value type for primitibe operation
	at soot.toDex.ExprVisitor.buildCalculatingBinaryInsn(ExprVisitor.java:327)
	at soot.toDex.ExprVisitor.caseAndExpr(ExprVisitor.java:426)
	at soot.jimple.internal.JAndExpr.apply(JAndExpr.java:43)
	at soot.toDex.StmtVisitor.caseAssignStmt(StmtVisitor.java:494)
	at soot.jimple.internal.JAssignStmt.apply(JAssignStmt.java:242)
	at soot.toDex.DexPrinter.toInstructions(DexPrinter.java:1511)
	at soot.toDex.DexPrinter.toMethodImplementation(DexPrinter.java:1174)
	at soot.toDex.DexPrinter.toMethods(DexPrinter.java:1083)
	at soot.toDex.DexPrinter.addAsClassDefItem(DexPrinter.java:656)
	at soot.toDex.DexPrinter.add(DexPrinter.java:1646)
	at soot.PackManager.writeClass(PackManager.java:1110)
	at soot.PackManager$2.run(PackManager.java:710)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

my code is :

`
	   
	   
	public static void doInstrument(){
	     G.reset();
            Options.v().set_allow_phantom_refs(true);
	    Options.v().set_src_prec(Options.src_prec_apk); 
	    Options.v().set_android_jars(Constants.androidPlatformLocation);
	    Options.v().set_process_dir(Collections.singletonList(Constants.apkFileLocation()));
            Options.v().set_prepend_classpath(true);
	    Options.v().set_whole_program(true);
	    Options.v().set_process_multiple_dex(true);
	    Options.v().set_force_overwrite(true);
	    Options.v().set_android_api_version(22);
	    
	    Options.v().set_keep_line_number(true);
	    Options.v().set_no_writeout_body_releasing(true);
	    Options.v().set_no_bodies_for_excluded(true);
	    Options.v().set_include_all(true);
	    //Options.v().set_validate(true);  
	    //output as APK, too//-f J  
	    Options.v().set_output_format(Options.output_format_dex);
	    Options.v().set_output_dir(Constants.apkForTestCase());
	    
	    Scene.v().addBasicClass("android.app.Activity", SootClass.SIGNATURES);
	    Scene.v().addBasicClass("android.util.Log", SootClass.SIGNATURES);
	    Scene.v().loadBasicClasses();
	    Scene.v().loadNecessaryClasses();
		
		PackManager.v().getPack("jtp").add(new Transform("jtp.myInstrumenter", new BodyTransformer() {

			@Override
			protected void internalTransform(Body b, String arg1, Map<String, String> arg2) {
				final PatchingChain<Unit> units = b.getUnits();
                                ohter code...
                   }
		}));
		PackManager.v().runPacks();
	    PackManager.v().writeOutput();
	}

**Comment by chizizhixin** [comment]
I found that many apps have this problem, I am very confused, I look forward to having a reply.

**Comment by joaoluizn** [comment]
Had the same problem looking for some viable solution, any update?

**Comment by iuribtt** [comment]
Same here...

**Comment by RichardHoOoOo** [comment]
I have the same problem on many apks downloaded from Google Play. But it never occurs on apks downloaded from F-Droid.

**Comment by RichardHoOoOo** [comment]
This bug has been fixed by v4.2.1. It is ok to close now.
