### ISSUE TITLE
Error loading java.lang.reflect.AnnotatedElement

### ISSUE THREAD

**Issue by askary94** [Sable/soot#1169]
hello.
I use Soot 2.5 and get follow error. please help me:

  ```[java] Exception in thread "main" java.lang.Error: Error loading java.lang.reflect.AnnotatedElement
     [java] 	at soot.JastAddJ.PathPart.getCompilationUnit(PathPart.java:124)
     [java] 	at soot.JastAddJ.Program.getCompilationUnit(Program.java:927)
     [java] 	at soot.JastAddJ.Program.lookupType_compute(Program.java:1273)
     [java] 	at soot.JastAddJ.Program.lookupType(Program.java:1255)
     [java] 	at soot.JastAddJ.Program.Define_TypeDecl_lookupType(Program.java:2049)
     [java] 	at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1323)
     [java] 	at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1323)
     [java] 	at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1323)
     [java] 	at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1323)
     [java] 	at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1323)
     [java] 	at soot.JastAddJ.Expr.lookupType(Expr.java:795)
     [java] 	at soot.JastAddJ.TypeAccess.decls_compute(TypeAccess.java:304)
     [java] 	at soot.JastAddJ.TypeAccess.decls(TypeAccess.java:294)
     [java] 	at soot.JastAddJ.TypeAccess.refined_LookupType_decl(TypeAccess.java:279)
     [java] 	at soot.JastAddJ.TypeAccess.decl_compute(TypeAccess.java:326)
     [java] 	at soot.JastAddJ.TypeAccess.decl(TypeAccess.java:319)
     [java] 	at soot.JastAddJ.TypeAccess.type_compute(TypeAccess.java:417)
     [java] 	at soot.JastAddJ.TypeAccess.type(TypeAccess.java:411)
     [java] 	at soot.JastAddJ.InterfaceDecl.isCircular_compute(InterfaceDecl.java:832)
     [java] 	at soot.JastAddJ.InterfaceDecl.isCircular(InterfaceDecl.java:819)
     [java] 	at soot.JastAddJ.ClassDecl.isCircular_compute(ClassDecl.java:1203)
     [java] 	at soot.JastAddJ.ClassDecl.isCircular(ClassDecl.java:1155)
     [java] 	at soot.JastAddJ.ClassDecl$2.computeNextCurrent(ClassDecl.java:213)
     [java] 	at soot.JastAddJ.ClassDecl$2.hasNext(ClassDecl.java:200)
     [java] 	at soot.JastAddJ.ClassDecl.memberTypes_compute(ClassDecl.java:887)
     [java] 	at soot.JastAddJ.ClassDecl.memberTypes(ClassDecl.java:878)
     [java] 	at soot.JastAddJ.GenericClassDecl.Define_SimpleSet_lookupType(GenericClassDecl.java:874)
     [java] 	at soot.JastAddJ.ASTNode.Define_SimpleSet_lookupType(ASTNode.java:1443)
     [java] 	at soot.JastAddJ.ASTNode.Define_SimpleSet_lookupType(ASTNode.java:1443)
     [java] 	at soot.JastAddJ.ASTNode.Define_SimpleSet_lookupType(ASTNode.java:1443)
     [java] 	at soot.JastAddJ.ASTNode.Define_SimpleSet_lookupType(ASTNode.java:1443)
     [java] 	at soot.JastAddJ.Expr.lookupType(Expr.java:801)
     [java] 	at soot.JastAddJ.ParTypeAccess.Define_SimpleSet_lookupType(ParTypeAccess.java:261)
     [java] 	at soot.JastAddJ.ASTNode.Define_SimpleSet_lookupType(ASTNode.java:1443)
     [java] 	at soot.JastAddJ.Expr.lookupType(Expr.java:801)
     [java] 	at soot.JastAddJ.ParTypeAccess.Define_SimpleSet_lookupType(ParTypeAccess.java:261)
     [java] 	at soot.JastAddJ.ASTNode.Define_SimpleSet_lookupType(ASTNode.java:1443)
     [java] 	at soot.JastAddJ.Expr.lookupType(Expr.java:801)
     [java] 	at soot.JastAddJ.TypeAccess.decls_compute(TypeAccess.java:302)
     [java] 	at soot.JastAddJ.TypeAccess.decls(TypeAccess.java:294)
     [java] 	at soot.JastAddJ.TypeAccess.refined_LookupType_decl(TypeAccess.java:279)
     [java] 	at soot.JastAddJ.TypeAccess.decl_compute(TypeAccess.java:326)
     [java] 	at soot.JastAddJ.TypeAccess.decl(TypeAccess.java:319)
     [java] 	at soot.JastAddJ.TypeAccess.type_compute(TypeAccess.java:417)
     [java] 	at soot.JastAddJ.TypeAccess.type(TypeAccess.java:411)
     [java] 	at soot.JastAddJ.ParTypeAccess.type_compute(ParTypeAccess.java:235)
     [java] 	at soot.JastAddJ.ParTypeAccess.type(ParTypeAccess.java:221)
     [java] 	at soot.JastAddJ.ParTypeAccess.type_compute(ParTypeAccess.java:235)
     [java] 	at soot.JastAddJ.ParTypeAccess.type(ParTypeAccess.java:221)
     [java] 	at soot.JastAddJ.ParameterDeclaration.type_compute(ParameterDeclaration.java:297)
     [java] 	at soot.JastAddJ.ParameterDeclaration.type(ParameterDeclaration.java:291)
     [java] 	at soot.JastAddJ.MethodDecl.signature_compute(MethodDecl.java:981)
     [java] 	at soot.JastAddJ.MethodDecl.signature(MethodDecl.java:970)
     [java] 	at soot.JastAddJ.TypeDecl.localMethodsSignatureMap_compute(TypeDecl.java:1981)
     [java] 	at soot.JastAddJ.TypeDecl.localMethodsSignatureMap(TypeDecl.java:1970)
     [java] 	at soot.JastAddJ.TypeDecl$1.<init>(TypeDecl.java:358)
     [java] 	at soot.JastAddJ.TypeDecl.localMethodsIterator(TypeDecl.java:357)
     [java] 	at soot.JastAddJ.ParClassDecl.localMethodsSignatureMap_compute(ParClassDecl.java:1228)
     [java] 	at soot.JastAddJ.ParClassDecl.localMethodsSignatureMap(ParClassDecl.java:1220)
     [java] 	at soot.JastAddJ.ClassDecl.methodsSignatureMap_compute(ClassDecl.java:793)
     [java] 	at soot.JastAddJ.ClassDecl.methodsSignatureMap(ClassDecl.java:786)
     [java] 	at soot.JastAddJ.TypeDecl$2.<init>(TypeDecl.java:379)
     [java] 	at soot.JastAddJ.TypeDecl.methodsIterator(TypeDecl.java:378)
     [java] 	at soot.JastAddJ.TypeDecl.methodsNameMap_compute(TypeDecl.java:1938)
     [java] 	at soot.JastAddJ.TypeDecl.methodsNameMap(TypeDecl.java:1930)
     [java] 	at soot.JastAddJ.TypeDecl.memberMethods_compute(TypeDecl.java:1917)
     [java] 	at soot.JastAddJ.TypeDecl.memberMethods(TypeDecl.java:1912)
     [java] 	at soot.JastAddJ.AbstractDot.Define_Collection_lookupMethod(AbstractDot.java:463)
     [java] 	at soot.JastAddJ.Expr.lookupMethod(Expr.java:711)
     [java] 	at soot.JastAddJ.MethodAccess.decls_compute(MethodAccess.java:791)
     [java] 	at soot.JastAddJ.MethodAccess.decls(MethodAccess.java:782)
     [java] 	at soot.JastAddJ.MethodAccess.decl_compute(MethodAccess.java:847)
     [java] 	at soot.JastAddJ.MethodAccess.decl(MethodAccess.java:840)
     [java] 	at soot.JastAddJ.MethodAccess.transformation(MethodAccess.java:538)
     [java] 	at soot.JastAddJ.ASTNode.transformation(ASTNode.java:451)
     [java] 	at soot.JastAddJ.ASTNode.transformation(ASTNode.java:451)
     [java] 	at soot.JastAddJ.ASTNode.transformation(ASTNode.java:451)
     [java] 	at soot.JastAddJ.ASTNode.transformation(ASTNode.java:451)
     [java] 	at soot.JastAddJ.ASTNode.transformation(ASTNode.java:451)
     [java] 	at soot.JastAddJ.TypeDecl.createAssertionsDisabled(TypeDecl.java:795)
     [java] 	at soot.JastAddJ.AssertStmt.transformation(AssertStmt.java:71)
     [java] 	at soot.JastAddJ.ASTNode.transformation(ASTNode.java:451)
     [java] 	at soot.JastAddJ.ASTNode.transformation(ASTNode.java:451)
     [java] 	at soot.JastAddJ.ASTNode.transformation(ASTNode.java:451)
     [java] 	at soot.JastAddJ.ASTNode.transformation(ASTNode.java:451)
     [java] 	at soot.JastAddJ.MethodDecl.transformation(MethodDecl.java:458)
     [java] 	at soot.JastAddJ.ASTNode.transformation(ASTNode.java:451)
     [java] 	at soot.JastAddJ.ASTNode.transformation(ASTNode.java:451)
     [java] 	at soot.JastAddJ.TypeDecl.transformation(TypeDecl.java:923)
     [java] 	at soot.JastAddJ.CompilationUnit.transformation(CompilationUnit.java:153)
     [java] 	at soot.JastAddInitialResolver.formAst(JastAddInitialResolver.java:66)
     [java] 	at soot.JavaClassSource.resolve(JavaClassSource.java:52)
     [java] 	at soot.SootResolver.bringToHierarchy(SootResolver.java:184)
     [java] 	at soot.SootResolver.bringToSignatures(SootResolver.java:209)
     [java] 	at soot.SootResolver.bringToBodies(SootResolver.java:250)
     [java] 	at soot.SootResolver.processResolveWorklist(SootResolver.java:135)
     [java] 	at soot.SootResolver.resolveClass(SootResolver.java:124)
     [java] 	at soot.Scene.loadClass(Scene.java:390)
     [java] 	at soot.Scene.loadClassAndSupport(Scene.java:375)
     [java] 	at edu.ksu.cis.envgen.Configuration.loadUnit(Configuration.java:206)
     [java] 	at edu.ksu.cis.envgen.Configuration.initialize(Configuration.java:106)
     [java] 	at edu.ksu.cis.envgen.Configuration.<init>(Configuration.java:49)
     [java] 	at edu.ksu.cis.envgen.EnvGenerator.main(EnvGenerator.java:49)
     [java] Caused by: java.lang.ArrayIndexOutOfBoundsException: 1612
     [java] 	at soot.JastAddJ.BytecodeParser.parseThisClass(BytecodeParser.java:436)
     [java] 	at soot.JastAddJ.BytecodeParser.parseTypeDecl(BytecodeParser.java:402)
     [java] 	at soot.JastAddJ.BytecodeParser.parse(BytecodeParser.java:339)
     [java] 	at soot.JastAddJ.BytecodeParser.read(BytecodeParser.java:9)
     [java] 	at soot.JastAddJ.PathPart.getCompilationUnit(PathPart.java:111)
     [java] 	... 102 more
     [java] Java Result: 1```

**Comment by anddann** [comment]
Can you please test a new soot version 3.3.1?
