### ISSUE TITLE
"java.lang.IllegalArgumentException" thrown when processing project with a META-INF or module-info class.

### ISSUE THREAD

**Issue by BobbyRBruce** [Sable/soot#1179]
I have received the following error when attempting to load classes in Soot , via `Scene.v().loadNecessaryClasses()`.
```
Exception in thread "main" java.lang.IllegalArgumentException           
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:185)   
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:168)   
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:439)   
        at soot.asm.AsmClassSource.resolve(AsmClassSource.java:65)      
        at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:240)
        at soot.SootResolver.bringToHierarchy(SootResolver.java:214)    
        at soot.SootResolver.bringToSignatures(SootResolver.java:279)   
        at soot.SootResolver.bringToBodies(SootResolver.java:319)       
        at soot.SootResolver.processResolveWorklist(SootResolver.java:164)
        at soot.SootResolver.resolveClass(SootResolver.java:134)        
        at soot.Scene.loadClass(Scene.java:942)                         
        at soot.Scene.loadClassAndSupport(Scene.java:927)               
        at soot.Scene.loadNecessaryClasses(Scene.java:1753)             
        at ...
```

I have discovered that this issue is due to the "META-INF" directory or the "module-info.class" file being present within a directory set as a `process_dir`. In my work I process a lot of publicly available `.jar` libraries so this error occurs a often.

I have developed a fix in my work which can be viewed here: https://github.com/BobbyRBruce/soot/commit/3b7642583cebc9c0341fa5c5bc0c3422fcbf146d .

I am unsure if this is a good fix for this bug, it may be very specialized to how I use Soot. I could make a pull request of it's ok, but first I'd like to know if there is any easier "more correct" way to fix this? It's interesting to me that this bug hasn't been reported before. Perhaps there is an error in the way I have set things up?

**Comment by anddann** [comment]
Hi @BobbyRBruce thanks for reporting the issue.
Can you please test soot's java9 branch?
It should solve the problem.

**Comment by BobbyRBruce** [comment]
@anddann : Thank you for pointing me towards the Soot Java9 branch. I was not aware of it. Yes, this appears to solve the issue I had encountered.
