### ISSUE TITLE
couldn't find class: java.lang.Object (is your soot-class-path set properly?) 

### ISSUE THREAD

**Issue by Wonsa0823** [Sable/soot#1190]
Hi,
    I'm using the soot-2.5.0, and I find a bug when using the soot in my project, my system is mac os x. And the bug is the following:

Exception in thread "main" java.lang.RuntimeException: couldn't find class: java.lang.Object (is your soot-class-path set properly?) Try adding rt.jar to Soot's classpath, e.g.:
java -cp sootclasses.jar soot.Main -cp .:/path/to/jdk/jre/lib/rt.jar <other options>
	at soot.SootResolver.bringToHierarchy(SootResolver.java:205)
	at soot.SootResolver.bringToSignatures(SootResolver.java:239)
	at soot.SootResolver.bringToBodies(SootResolver.java:280)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:150)
	at soot.SootResolver.resolveClass(SootResolver.java:124)
	at soot.Scene.loadClass(Scene.java:448)
	at soot.Scene.loadClassAndSupport(Scene.java:433)
	at soot.Scene.loadNecessaryClass(Scene.java:1053)
	at soot.Scene.loadNecessaryClasses(Scene.java:1067)
	at soot.Main.run(Main.java:167)
	at soot.Main.main(Main.java:141)

Thanks!

**Comment by sdibernardo** [comment]
I had a similar problem and solved it by extend Soot's classpath by passing the default classpath. `Scene.v().extendSootClassPath(Scene.v().defaultClassPath());`
This should include rt.jar and help resolve your problem.

**Comment by mbenz89** [comment]
Hi!

Generally speaking, it's always a good idea to include some information on how you run Soot when opening an issue here, e.g., console-line options, scenario, and problematic application. 

> I had a similar problem and solved it by extend Soot's classpath by passing the default classpath. Scene.v().extendSootClassPath(Scene.v().defaultClassPath());
This should include rt.jar and help resolve your problem.

If no other sources are explicitly added to the classpath, Soot will automatically choose the default classpath which contains the rt.jar. Otherwise, using `-prepend-classpath` should also solve the problem.

@Wonsa0823 soot-2.5.0 is very very old. Please try to use a newer release. I suggest using the current SNAPSHOT build for the [develop branch](https://github.com/Sable/soot/tree/develop). Maybe that already solves your problem.

**Comment by Wonsa0823** [comment]
OK, thank you very much!
