### ISSUE TITLE
Concurrency issues in Soot tests

### ISSUE THREAD

**Issue by StevenArzt** [Sable/soot#1194]
We just moved our internal Soot build at SIT to a massively parallel new build system. On this system, the Soot test cases randomly fail without any code changes for no apparent reason. I therefore guess we have quite some concurrency issues.

```
[Thread-20] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: Failed to convert <soot.lambdaMetaFactory.Adapt: void lambda$parameterWidening$4(java.lang.Integer)>
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:2040)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:402)
	at soot.PackManager$1.run(PackManager.java:1279)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: This operation requires resolving level HIERARCHY but java.io.PrintStream is at resolving level DANGLING
If you are extending Soot, try to add the following call before calling soot.Main.main(..):
Scene.v().addBasicClass(java.io.PrintStream,HIERARCHY);
Otherwise, try whole-program mode (-w).
	at soot.SootClass.checkLevelIgnoreResolving(SootClass.java:183)
	at soot.jimple.internal.JVirtualInvokeExpr.<init>(JVirtualInvokeExpr.java:43)
	at soot.jimple.Jimple.newVirtualInvokeExpr(Jimple.java:469)
	at soot.asm.AsmMethodSource.convertMethodInsn(AsmMethodSource.java:1319)
	at soot.asm.AsmMethodSource.convert(AsmMethodSource.java:1789)
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:2038)
	... 5 more
```

Afterwards, we get some follow-up issues that are likely caused by the lambda metafactory not generating all required classes and methods:

```
java.lang.RuntimeException: tried to get nonexistent method <soot.lambdaMetaFactory.Adapt: void parameterWidening()>
	at soot.Scene.getMethod(Scene.java:907)
	at soot.testing.framework.AbstractTestingFramework.getMethodForSig(AbstractTestingFramework.java:231)
	at soot.testing.framework.AbstractTestingFramework.createTestTarget(AbstractTestingFramework.java:185)
	at soot.testing.framework.AbstractTestingFramework.prepareTarget(AbstractTestingFramework.java:117)
	at soot.testing.framework.AbstractTestingFramework.prepareTarget(AbstractTestingFramework.java:94)
	at soot.lambdaMetaFactory.LambdaMetaFactoryAdaptTest.parameterWidening(LambdaMetaFactoryAdaptTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:68)
```

We had two runs fail with the issues above, and then a third run (again, no code changes, same configuration, same machine) was successful. I can't see any other reason than concurrency.

**Comment by mbenz89** [comment]
Hi Steven. 

This is an issue we are aware of for quite some time now: #1122
@anddann  and I already debugged and fixed the problem: https://github.com/Sable/soot/pull/1191
It would be great if you could check if the proposed fix also eliminates your problems.

Generally, It's strange that Soot's parallel body creation could exist for such a long time without any proper means of synchronization. The problem originates from a non-synchronized map in the Scene that maps class names to `RefType`. This is a general problem but it rises much more consistently with the LambdaMetaFactory implementation that quite often adds new classes to the Scene during parallel body creation. 

If we fix this and the concurrency issue in SootClass' `methodList`, we are a large step closer to a robust Soot. Looking at the issue tracker, there are quite some issues that are related to the same concurrency problem.

Manuel

**Comment by StevenArzt** [comment]
Great news, the proposed patch indeed seems to work. I got 5 consecutive builds with no errors. I suggest to merge it ASAP, so that we can continue with the develop branch.

**Comment by mbenz89** [comment]
Fixed with https://github.com/Sable/soot/pull/1191. Thanks for testing Steven!
