### ISSUE TITLE
unable to run the command

### ISSUE THREAD

**Issue by umkhanqta** [Sable/soot#1216]
Hi, 
I am new to soot and trying this command on my window system having java 8 and using nightly build of soot. I am getting the following error. Kindly help me out.

**java -jar sootclasses-trunk-jar-with-dependencies.jar -d "D:\2. Research\My thesis\Experimental tools\FlowDroid\Soot\sootOutput" -android-jars "D:\2. Research\My thesis\Experimental tools\FlowDroid\Android Platforms" -allow-phantom-refs -src-prec apk -pp -ire -process-dir "D:\2. Research\My thesis\Experimental tools\FlowDroid\Flow Droid\apk\snake.apk**"
Soot started on Wed Oct 16 16:53:00 KST 2019
java.lang.RuntimeException: None of the basic classes could be loaded! Check your Soot class path!
        at soot.Scene.loadBasicClasses(Scene.java:1675)
        at soot.Scene.loadNecessaryClasses(Scene.java:1760)
        at soot.Main.run(Main.java:241)
        at soot.Main.main(Main.java:141)

**Comment by umkhanqta** [comment]
Hi,
The solution is to use -force-android-jar "D:\2. Research\My thesis\Experimental tools\FlowDroid\Android Platforms\android-26\android.jar"
This will work. I don't know why it didn't detect the platform previously

Thanks
