### ISSUE TITLE
java.lang.RuntimeException: class needed! at soot.Hierarchy.getSubclassesOf(Hierarchy.java:182)

### ISSUE THREAD

**Issue by WilliamChen98** [Sable/soot#1219]
Hi there,
I'm using soot to generate a call graph for a large system. I'm trying to construct the call graph like this:
`argList.addAll(Arrays.asList(new String[] {
				"-w",
				"-allow-phantom-refs",
				"-cp","C:\\Program Files\\Java\\jre1.8.0_221\\lib\\rt.jar",
				"-process-dir",process_path + process_dir,
                "-p","wjtp","enabled:true",
                "-p","wjop","enabled:true",
                "-p","cg","enabled:true",
                "-p","cg","verbose:true",
                "-p","cg","all-reachable:true",
				"-p","cg.spark","enabled:true"
		}));
		
		PackManager.v().getPack("wjtp").add(new Transform("wjtp.myTrans", new SceneTransformer() {

	        @Override
	        protected void internalTransform(String phaseName, Map options) {
	               CHATransformer.v().transform();
	               CallGraph cg = Scene.v().getCallGraph();

	               QueueReader<Edge> edges = cg.listener();
	               Set<String> visited = new HashSet<>();
	               while (edges.hasNext()) {
	                   Edge e = edges.next();
	                   MethodOrMethodContext tgt = e.getTgt();
	                   MethodOrMethodContext src = e.getSrc();

	                   if (!visited.contains(src.toString())) {
	                       visited.add(src.toString());
	                       dot.drawNode(src.toString());
	                   }
	                   if (!visited.contains(tgt.toString())) {
	                       visited.add(tgt.toString());
	                       dot.drawNode(tgt.toString());
	                   }
	                   dot.drawEdge(src.toString(), tgt.toString());
	               }
	        }

	       }));
		
		args = argList.toArray(new String[0]);
		soot.Main.main(args);
				
		dot.plot(process_path + output_name + DotGraph.DOT_EXTENSION);
		System.out.println("finish");`
After a long time of processing, soot threw an exception:
`java.lang.RuntimeException: class needed!
        at soot.Hierarchy.getSubclassesOf(Hierarchy.java:182)
        at soot.Hierarchy.isClassSuperclassOf(Hierarchy.java:449)
        at soot.jimple.toolkits.invoke.InlinerSafetyManager.specialInvokePerformsLookupIn(InlinerSafetyManager.java:293)
        at soot.jimple.toolkits.invoke.InlinerSafetyManager.checkSpecialInlineRestrictions(InlinerSafetyManager.java:53)
        at soot.jimple.toolkits.invoke.InlinerSafetyManager.ensureInlinability(InlinerSafetyManager.java:147)
        at soot.jimple.toolkits.invoke.StaticInliner.internalTransform(StaticInliner.java:101)
        at soot.SceneTransformer.transform(SceneTransformer.java:39)
        at soot.Transform.apply(Transform.java:90)
        at soot.ScenePack.internalApply(ScenePack.java:40)
        at soot.Pack.apply(Pack.java:118)
        at soot.PackManager.runWholeProgramPacks(PackManager.java:566)
        at soot.PackManager.runPacksNormally(PackManager.java:455)
        at soot.PackManager.runPacks(PackManager.java:384)
        at soot.Main.run(Main.java:278)
        at soot.Main.main(Main.java:147)
        at Main.Main.main(Main.java:79)`
It might because that I removed some classes from processing directory, but if I kepp these classes, there would be a java.lang.RuntimeException: Class names not equal! exception. Since I couldn't get the source code, it wold be diffcult for me to fix the class name not equal exception. Is there any solution to the RuntimeException: class needed?
Thanks.

**Comment by WilliamChen98** [comment]
I re-edit the stack trace:
java.lang.RuntimeException: class needed!
        at soot.Hierarchy.getSubclassesOf(Hierarchy.java:182)
        at soot.Hierarchy.isClassSuperclassOf(Hierarchy.java:449)
        at soot.jimple.toolkits.invoke.InlinerSafetyManager.specialInvokePerformsLookupIn(InlinerSafetyManager.java:293)
        at soot.jimple.toolkits.invoke.InlinerSafetyManager.checkSpecialInlineRestrictions(InlinerSafetyManager.java:53)
        at soot.jimple.toolkits.invoke.InlinerSafetyManager.ensureInlinability(InlinerSafetyManager.java:147)
        at soot.jimple.toolkits.invoke.StaticInliner.internalTransform(StaticInliner.java:101)
        at soot.SceneTransformer.transform(SceneTransformer.java:39)
        at soot.Transform.apply(Transform.java:90)
        at soot.ScenePack.internalApply(ScenePack.java:40)
        at soot.Pack.apply(Pack.java:118)
        at soot.PackManager.runWholeProgramPacks(PackManager.java:566)
        at soot.PackManager.runPacksNormally(PackManager.java:455)
        at soot.PackManager.runPacks(PackManager.java:384)
        at soot.Main.run(Main.java:278)
        at soot.Main.main(Main.java:147)
        at Main.Main.main(Main.java:79)

**Comment by WilliamChen98** [comment]
After I canceled the "wjtp" phase and "wjop" phase, the exception is solved.

**Comment by anonymousgroundhog** [comment]
I found that this issue might stem from not checking if the SootClass is not an interface. 
Therefore, you would want to eliminate the checking of any class that is an interface using the `isInterface()` method.
