### ISSUE TITLE
Exception: soot.RefType cannot be cast to soot.ArrayType

### ISSUE THREAD

**Issue by RichardHoOoOo** [Sable/soot#1248]
A Jimple code like this will trigger an exception.

The code: 
```
$r2 = newarray (int)[3];
$i0 = staticinvoke <com.example.Helper: int getInt()>();
$r2[0] = $i0;
```

Basically what I am doing is simply create a local integer array (say $r2) and assign $r2[0] with a local integer that is returned by a static method.  

The exception is:
```
[Thread-9] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: soot.RefType cannot be cast to soot.ArrayType
java.lang.ClassCastException: soot.RefType cannot be cast to soot.ArrayType
	at soot.toDex.StmtVisitor.buildArrayPutInsn(StmtVisitor.java:589)
	at soot.toDex.StmtVisitor.buildPutInsn(StmtVisitor.java:527)
	at soot.toDex.StmtVisitor.caseAssignStmt(StmtVisitor.java:460)
	at soot.jimple.internal.JAssignStmt.apply(JAssignStmt.java:242)
	at soot.toDex.DexPrinter.toInstructions(DexPrinter.java:1511)
	at soot.toDex.DexPrinter.toMethodImplementation(DexPrinter.java:1174)
	at soot.toDex.DexPrinter.toMethods(DexPrinter.java:1083)
	at soot.toDex.DexPrinter.addAsClassDefItem(DexPrinter.java:656)
	at soot.toDex.DexPrinter.add(DexPrinter.java:1646)
	at soot.PackManager.writeClass(PackManager.java:1096)
	at soot.PackManager.lambda$writeOutput$1(PackManager.java:699)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.ClassCastException: soot.RefType cannot be cast to soot.ArrayType
	at soot.toDex.StmtVisitor.buildArrayPutInsn(StmtVisitor.java:589)
	at soot.toDex.StmtVisitor.buildPutInsn(StmtVisitor.java:527)
	at soot.toDex.StmtVisitor.caseAssignStmt(StmtVisitor.java:460)
	at soot.jimple.internal.JAssignStmt.apply(JAssignStmt.java:242)
	at soot.toDex.DexPrinter.toInstructions(DexPrinter.java:1511)
	at soot.toDex.DexPrinter.toMethodImplementation(DexPrinter.java:1174)
	at soot.toDex.DexPrinter.toMethods(DexPrinter.java:1083)
	at soot.toDex.DexPrinter.addAsClassDefItem(DexPrinter.java:656)
	at soot.toDex.DexPrinter.add(DexPrinter.java:1646)
	at soot.PackManager.writeClass(PackManager.java:1096)
	at soot.PackManager.lambda$writeOutput$1(PackManager.java:699)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-9" java.lang.ClassCastException: soot.RefType cannot be cast to soot.ArrayType
	at soot.toDex.StmtVisitor.buildArrayPutInsn(StmtVisitor.java:589)
	at soot.toDex.StmtVisitor.buildPutInsn(StmtVisitor.java:527)
	at soot.toDex.StmtVisitor.caseAssignStmt(StmtVisitor.java:460)
	at soot.jimple.internal.JAssignStmt.apply(JAssignStmt.java:242)
	at soot.toDex.DexPrinter.toInstructions(DexPrinter.java:1511)
	at soot.toDex.DexPrinter.toMethodImplementation(DexPrinter.java:1174)
	at soot.toDex.DexPrinter.toMethods(DexPrinter.java:1083)
	at soot.toDex.DexPrinter.addAsClassDefItem(DexPrinter.java:656)
	at soot.toDex.DexPrinter.add(DexPrinter.java:1646)
	at soot.PackManager.writeClass(PackManager.java:1096)
	at soot.PackManager.lambda$writeOutput$1(PackManager.java:699)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I find if I delete `$r2[0] = $i0;`, the exception will not be triggered.

But what makes this exception?

**Comment by RichardHoOoOo** [comment]
I figure it out. 

What I used to create a local array is 
```
Local arr = Jimple.v().newLocal("name", RefType.v("int[]"));
```

But what should be used is 
```
Local arr = Jimple.v().newLocal("name", ArrayType.v(IntType.v(), 1));
```

That's the cause of **soot.RefType cannot be cast to soot.ArrayType**

But that's too difficult to debug because the output Jimple code looks exactly the same.
