### ISSUE TITLE
java.lang.NullPointerException or IllegalArgument when running soot.Main or soot.tools.CFGViewer

### ISSUE THREAD

**Issue by 234235235** [Sable/soot#1249]
Steps to reproduce:
1.) Simply create Hello World.java file
2.) Compile it with javac
3.) run soot.Main or soot.tools.CFGViewer

Files used to reproduce: 
...

Soot version: <pre>3.3.0</pre>

Command line:
<pre>java -cp S://Programme/Soot/sootclasses-trunk-jar-with-dependencies.jar soot.tools.CFGViewer -cp "S:\Programme\Java\Jdk8\jre\lib" -src-prec java main</pre>

Doesn't work as well with .class files.

Max Memory:
<pre>8158MB</pre>

Stack trace:
<pre>java.lang.NullPointerException
	at soot.JastAddJ.Program.initPaths(Program.java:336)
	at soot.SootResolver.initializeProgram(SootResolver.java:91)
	at soot.SootResolver.getProgram(SootResolver.java:373)
	at soot.JastAddInitialResolver.formAst(JastAddInitialResolver.java:62)
	at soot.JavaClassSource.resolve(JavaClassSource.java:66)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:240)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:214)
	at soot.SootResolver.bringToSignatures(SootResolver.java:279)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:172)
	at soot.SootResolver.resolveClass(SootResolver.java:134)
	at soot.Scene.loadClass(Scene.java:942)
	at soot.Scene.loadClassAndSupport(Scene.java:927)
	at soot.Scene.loadNecessaryClass(Scene.java:1729)
	at soot.Scene.loadNecessaryClasses(Scene.java:1741)
	at soot.Main.run(Main.java:241)
	at soot.Main.main(Main.java:141)
	at soot.tools.CFGViewer.main(CFGViewer.java:101)
</pre>

Also tried with different Java Versions (7,8,13) as well as on windows and on linux vm.

When also adding the classpath of the main file (main.class or main.java doesn't make a difference which is used for soot in this case), I get the following error:

<pre>java -cp S://Programme/Soot/sootclasses-trunk-jar-with-dependencies.jar soot.tools.CFGViewer -cp "S:\blah\;S:\Programme\Java\Jdk8\jre\lib" -src-prec java main</pre>

or in linux:

<pre>java -cp "/root/Downloads/sootclasses-trunk-jar-with-dependencies.jar" soot.Main -cp "/root/xy/TEST/JTT:/root/Programme/Java/JDK8/jdk1.8.0_231/jre/lib" main</pre>

Stack trace:
<pre>java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.&#60;init&#62;(ClassReader.java:185)
	at org.objectweb.asm.ClassReader.&#60;init&#62;(ClassReader.java:168)
	at org.objectweb.asm.ClassReader.&#60;init&#62;(ClassReader.java:439)
	at soot.asm.AsmClassSource.resolve(AsmClassSource.java:65)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:240)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:214)
	at soot.SootResolver.bringToSignatures(SootResolver.java:279)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:172)
	at soot.SootResolver.resolveClass(SootResolver.java:134)
	at soot.Scene.loadClass(Scene.java:942)
	at soot.Scene.loadClassAndSupport(Scene.java:927)
	at soot.Scene.loadNecessaryClass(Scene.java:1729)
	at soot.Scene.loadNecessaryClasses(Scene.java:1741)
	at soot.Main.run(Main.java:241)
	at soot.Main.main(Main.java:141)
</pre>

**Comment by 234235235** [comment]
Okay the problem for the nullpointer was the missing classpath for the main.class file:

<pre> java -cp S://Programme/Soot/sootclasses-trunk-jar-with-dependencies.jar soot.tools.CFGViewer -cp "S:\Programme\Java\Jdk8\jre\lib" -src-prec java main</pre>

to

<pre> java -cp S://Programme/Soot/sootclasses-trunk-jar-with-dependencies.jar soot.tools.CFGViewer -cp "S:\blah\test;S:\Programme\Java\Jdk8\jre\lib" -src-prec java main


The IllegalArgumentException occours when the corresponding java file (main.java) got compiled with javac version > 8, which leads to this Exception by ASM.
