### ISSUE TITLE
erro in class

### ISSUE THREAD

**Issue by Shabnam-t** [Sable/soot#1254]
hello
I try to run this code but it has error
import java.util.Collections;

	import soot.PackManager;
	import soot.Scene;
	import soot.SootClass;
	
	import soot.jimple.toolkits.callgraph.CallGraph;
	
	import soot.options.Options;

	public class Main {

		public static void main(String[] args) {
			final String apppath = "c:\\Users\\SHTAV3\\Desktop\\test.jar";
			soot.G.reset();
			Options.v().set_process_dir(Collections.singletonList(apppath));
			Options.v().set_allow_phantom_refs(true);
			Options.v().set_prepend_classpath(true);
			Options.v().set_validate(true);
			Options.v().set_whole_program(true);
			Options.v().set_app(true);
			Options.v().set_src_prec(Options.src_prec_class);
			Scene.v().loadNecessaryClasses();
			SootClass appclass = Scene.v().loadClassAndSupport("com.eproject.microservices.testcase.Application");
			appclass.setApplicationClass();
			PackManager.v().runPacks();
			CallGraph cg = Scene.v().getCallGraph();
			System.out.println(cg.toString());
			
	}

	}
the error:
Exception in thread "main" java.lang.NoClassDefFoundError: soot/G
	at Main.main(Main.java:19)
Caused by: java.lang.ClassNotFoundException: soot.G
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 1 more

**Comment by anddann** [comment]
Please give more information

**Comment by Shabnam-t** [comment]
I want to test simple example helloworld but i was not worked.

**Comment by anddann** [comment]
which soot version did you use

**Comment by Shabnam-t** [comment]
Hello

my code:
import soot.PackManager;
import soot.Scene;
import soot.SootClass;
import soot.jimple.toolkits.callgraph.CallGraph;
import soot.options.Options;

public class Main {

public static void main(String[] args) {

//  if(args.length == 0)
               {

                //  System.exit(0);
       }



               // Just in case, resolve the PrintStream and System
soot-classes

 Scene.v().addBasicClass("java.io.PrintStream",SootClass.SIGNATURES);

Scene.v().addBasicClass("java.lang.System",SootClass.SIGNATURES);
                 soot.Main.main(args);

 Options.v().set_soot_classpath("C:\\Users\\SHTAV3\\Desktop\\Mainclass.jar"
);
                 //Scene.v().getSootClass("MainClass");
         soot.G.reset();
Options.v().set_allow_phantom_refs(true);
Options.v().set_prepend_classpath(true);
Options.v().set_validate(true);
Options.v().set_whole_program(true);
Options.v().set_app(true);
Options.v().set_src_prec(Options.src_prec_class);
Scene.v().loadNecessaryClasses();
Scene.v().loadClassAndSupport("MainClass");
Options.v().set_output_format(Options.output_format_jimple);
Options.v().set_output_dir("C:\\Users\\SHTAV3\\Desktop");
PackManager.v().runPacks();
CallGraph cg = Scene.v().getCallGraph();
System.out.println(cg.toString());
}
} This is my code
Cheers,

**Comment by anddann** [comment]
Looks like you did not set up your classpath properly.
Do you use maven to setup your project?

**Comment by Shabnam-t** [comment]
Yes

**Comment by anddann** [comment]
Can you post the pom.xml here?

**Comment by Shabnam-t** [comment]
Thank you for your response, it is solved now.

**Comment by anddann** [comment]
do you mind posting your solution? Then others can also benefit ...
