### ISSUE TITLE
ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: Unexpected type [0..1] (Integer1Type)

### ISSUE THREAD

**Issue by FengWu1206** [Sable/soot#1279]
Soot-4.0.0
Facebook.apk
when I use soot-4.0.0 extract facebook.apk cfgs and got the error as follows.
the APK link is as follows:
https://apkpure.com/facebook/com.facebook.katana

Thread-3] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: Unexpected type [0..1] (Integer1Type)
soot.jimple.toolkits.typing.integer.InternalTypingException: Unexpected type [0..1] (Integer1Type)
	at soot.jimple.toolkits.typing.integer.ClassHierarchy.typeNode(ClassHierarchy.java:155)
	at soot.jimple.toolkits.typing.integer.TypeResolver.typeVariable(TypeResolver.java:121)
	at soot.jimple.toolkits.typing.integer.ConstraintCollector.caseAssignStmt(ConstraintCollector.java:406)
	at soot.jimple.internal.JAssignStmt.apply(JAssignStmt.java:242)
	at soot.jimple.toolkits.typing.integer.ConstraintCollector.collect(ConstraintCollector.java:104)
	at soot.jimple.toolkits.typing.integer.TypeResolver.collect_constraints_1(TypeResolver.java:209)
	at soot.jimple.toolkits.typing.integer.TypeResolver.resolve_step_1(TypeResolver.java:178)
	at soot.jimple.toolkits.typing.integer.TypeResolver.resolve(TypeResolver.java:147)
	at soot.jimple.toolkits.typing.fast.TypeResolver.inferTypes(TypeResolver.java:174)
	at soot.jimple.toolkits.typing.TypeAssigner.internalTransform(TypeAssigner.java:121)
	at soot.BodyTransformer.transform(BodyTransformer.java:55)
	at soot.BodyTransformer.transform(BodyTransformer.java:59)
	at soot.dexpler.DexBody.jimplify(DexBody.java:660)
	at soot.dexpler.DexMethod$1.getBody(DexMethod.java:119)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:402)
	at soot.PackManager$1.run(PackManager.java:1279)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-3" soot.jimple.toolkits.typing.integer.InternalTypingException: Unexpected type [0..1] (Integer1Type)

**Comment by anddann** [comment]
Can you please give us the complete command line and arguments you use.

**Comment by mbenz89** [comment]
This issue is known and also reported in #1071 and #1058.

**Comment by FengWu1206** [comment]
cmd = f"java -Xmx4G -Xms2G -jar /usr/local/bin/soot-0.0.1-all.jar " \
              f"-process-path {apk_file} " \
              f"-src-prec apk " \
              f"-android-jars {app.config['ANDROID_SDK_PLATFORMS']} " \
              "-w allow-phantom-refs " \
              "-process-multiple-dex " \
              "-no-output-source-file-attribute " \
              "-no-output-inner-classes-attribute -f n " \
              f"-soot-output-dir {soot_tmp_dir}/ "

**Comment by hunie-son** [comment]
Have you solved that problem?
