### ISSUE TITLE
Unhandled Type of Local variable to Generate 

### ISSUE THREAD

**Issue by jpstotz** [Sable/soot#1284]
The changes of commit 8fef25c50984c15db36ce457f324819e6cf46369 (@mbenz89 and Michael Emmi) have some problems if they encounter a temporary type like `soot.jimple.toolkits.typing.fast.Integer1Type [0..1]`. In this case the LocalGenerator fails with an RuntimeException:

```
java.lang.RuntimeException: Unhandled Type of Local variable to Generate - Not Implemented
	at soot.javaToJimple.LocalGenerator.generateLocal(LocalGenerator.java:141) ~[   :na]
	at soot.jimple.toolkits.typing.fast.TypeResolver$CastInsertionUseVisitor.visit(TypeResolver.java:237) ~[na:na]
	at soot.jimple.toolkits.typing.fast.UseChecker.caseAssignStmt(UseChecker.java:235) ~[na:na]
	at soot.jimple.internal.JAssignStmt.apply(JAssignStmt.java:242) ~[na:na]
	at soot.jimple.toolkits.typing.fast.UseChecker.check(UseChecker.java:127) ~[na:na]
	at soot.jimple.toolkits.typing.fast.TypeResolver.insertCasts(TypeResolver.java:410) ~[na:na]
	at soot.jimple.toolkits.typing.fast.TypeResolver.inferTypes(TypeResolver.java:161) ~[na:na]
	at soot.jimple.toolkits.typing.TypeAssigner.internalTransform(TypeAssigner.java:121) ~[na:na]
	at soot.BodyTransformer.transform(BodyTransformer.java:55) ~[na:na]
	at soot.BodyTransformer.transform(BodyTransformer.java:59) ~[na:na]
	at soot.dexpler.DexBody.jimplify(DexBody.java:663) ~[na:na]
	at soot.dexpler.DexMethod$1.getBody(DexMethod.java:120) ~[na:na]
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:402) ~[na:na]
```

It occurs for example in this method (Jimple raw code):
```
    public void run()
    {
        unknown $u13, $u11, $u0#1, $u2#2, $u-1#4, $u2#7, $u6#8, $u9#10, $u9#11, $u-1#13, $u6#15, $u4#16, $u5#17, $u-1#18, $u6#21, $u12#22, $u12#23, $u12#24, $u-1#25, $u7#27, $u4#28, $u5#30, $u0#32, $u0, $u1, $u2, $u3;

        $u13 := @this: com.jumio.commons.view.ImageSwitcherViewDrawable$1;

        $u0#1 = $u13.<com.jumio.commons.view.ImageSwitcherViewDrawable$1: android.widget.ImageView val$oldImage>;

        $u2#2 = newarray (float)[2];

        $u2#2[0] = 255.0F;

        $u2#2[1] = 0.0F;

        $u-1#4 = staticinvoke <android.animation.ObjectAnimator: android.animation.ObjectAnimator ofFloat(java.lang.Object,java.lang.String,float[])>($u0#1, "alpha", $u2#2);

        virtualinvoke $u-1#4.<android.animation.ObjectAnimator: android.animation.ObjectAnimator setDuration(long)>(130L);

        $u2#7 = $u13.<com.jumio.commons.view.ImageSwitcherViewDrawable$1: android.widget.ImageView val$oldImage>;

        $u6#8 = newarray (float)[2];

        $u6#8[0] = 0;

        $u9#10 = $u13.<com.jumio.commons.view.ImageSwitcherViewDrawable$1: int val$newBmpHeight>;

        $u9#11 = (float) $u9#10;

        $u6#8[1] = $u9#11;

        $u-1#13 = staticinvoke <android.animation.ObjectAnimator: android.animation.ObjectAnimator ofFloat(java.lang.Object,java.lang.String,float[])>($u2#7, "translationY", $u6#8);

        $u0 = new android.view.animation.DecelerateInterpolator;

        $u6#15 = $u0;

        specialinvoke $u0.<android.view.animation.DecelerateInterpolator: void <init>()>();

        virtualinvoke $u-1#13.<android.animation.ObjectAnimator: void setInterpolator(android.animation.TimeInterpolator)>($u6#15);

        virtualinvoke $u-1#13.<android.animation.ObjectAnimator: android.animation.ObjectAnimator setDuration(long)>(130L);

        $u4#16 = $u13.<com.jumio.commons.view.ImageSwitcherViewDrawable$1: android.widget.ImageView val$newImage>;

        $u5#17 = newarray (float)[2];

        $u5#17[0] = 0.0F;

        $u5#17[1] = 255.0F;

        $u-1#18 = staticinvoke <android.animation.ObjectAnimator: android.animation.ObjectAnimator ofFloat(java.lang.Object,java.lang.String,float[])>($u4#16, "alpha", $u5#17);

        virtualinvoke $u-1#18.<android.animation.ObjectAnimator: android.animation.ObjectAnimator setDuration(long)>(160L);

        $u6#21 = $u13.<com.jumio.commons.view.ImageSwitcherViewDrawable$1: android.widget.ImageView val$newImage>;

        $u11 = newarray (float)[2];

        $u12#22 = $u13.<com.jumio.commons.view.ImageSwitcherViewDrawable$1: int val$newBmpHeight>;

        $u12#23 = neg $u12#22;

        $u12#24 = (float) $u12#23;

        $u11[0] = $u12#24;

        $u11[1] = 0.0F;

        $u-1#25 = staticinvoke <android.animation.ObjectAnimator: android.animation.ObjectAnimator ofFloat(java.lang.Object,java.lang.String,float[])>($u6#21, "translationY", $u11);

        $u1 = new android.view.animation.AccelerateInterpolator;

        $u7#27 = $u1;

        specialinvoke $u1.<android.view.animation.AccelerateInterpolator: void <init>()>();

        virtualinvoke $u-1#13.<android.animation.ObjectAnimator: void setInterpolator(android.animation.TimeInterpolator)>($u7#27);

        virtualinvoke $u-1#25.<android.animation.ObjectAnimator: android.animation.ObjectAnimator setDuration(long)>(160L);

        $u2 = new android.animation.AnimatorSet;

        $u4#28 = $u2;

        specialinvoke $u2.<android.animation.AnimatorSet: void <init>()>();

        $u5#30 = newarray (android.animation.Animator)[4];

        $u5#30[0] = $u-1#13;

        $u5#30[1] = $u-1#4;

        $u5#30[2] = $u-1#25;

        $u5#30[3] = $u-1#18;

        virtualinvoke $u4#28.<android.animation.AnimatorSet: void playTogether(android.animation.Animator[])>($u5#30);

        $u3 = new com.jumio.commons.view.ImageSwitcherViewDrawable$1$1;

        $u0#32 = $u3;

        specialinvoke $u3.<com.jumio.commons.view.ImageSwitcherViewDrawable$1$1: void <init>(com.jumio.commons.view.ImageSwitcherViewDrawable$1)>($u13);

        virtualinvoke $u4#28.<android.animation.AnimatorSet: void addListener(android.animation.Animator$AnimatorListener)>($u0#32);

        virtualinvoke $u4#28.<android.animation.AnimatorSet: void start()>();

        return;
    }

```

**Comment by mbenz89** [comment]
Thanks for reporting @jpstotz . I'll quickly fix this.

**Comment by mbenz89** [comment]
Should be fixed with https://github.com/Sable/soot/commit/ed8b46e9b9aa75f10bdaff2e55f27b1e86a71bd2. Can you confirm this?

**Comment by jpstotz** [comment]
Thank you very much Manuel for the quick fix. 
Yes indeed this seem to fix the problem. I tested a few apps and they all went smoothly though the analysis.
