### ISSUE TITLE
Is it possible to add all jars in a directory as soot class path in windows?

### ISSUE THREAD

**Issue by jl0x61** [Sable/soot#1289]
I use this command:
```
java -cp sootclasses-trunk-jar-with-dependencies.jar soot.tools.CFGViewer --soot-classpath .;"C:\Program Files\Java\jre1.8.0_241\lib\rt.jar";"D:\jdt_jar\org.eclipse.jdt.core_3.20.0.v20191203-2131.jar";"D:\tmp\hbase-2.2.3\lib\*" -process-dir "D:\tmp\hbase-2.2.3\lib\hbase-zookeeper-2.2.3.jar"
```
but the error message is:
```
soot.CompilationDeathException: Couldn't resolve classpath entry D:\tmp\hbase-2.2.3\lib\*: java.io.IOException: Invalid argument
        at soot.SourceLocator.explodeClassPath(SourceLocator.java:167)
        at soot.SourceLocator.getClassSource(SourceLocator.java:178)
        at soot.Scene.tryLoadClass(Scene.java:959)
        at soot.Scene.loadBasicClasses(Scene.java:1700)
        at soot.Scene.loadNecessaryClasses(Scene.java:1799)
        at soot.Main.run(Main.java:241)
        at soot.Main.main(Main.java:141)
        at soot.tools.CFGViewer.main(CFGViewer.java:101)
```
Any help will be appreciated!

**Comment by EnhydraGod** [comment]
hi,
i also want to add all jars in a directory, have you find a way to resolve it?

**Comment by mbenz89** [comment]
Hi.

This is unfortunately not implemented to this day. The classpath is processed in [`soot.Scene#getSootClassPath`](https://github.com/Sable/soot/blob/develop/src/main/java/soot/Scene.java#L301).

We would be happy to accept a pull request on this feature if you want to implement it :).
