### ISSUE TITLE
Lambda newinvokespecial exception

### ISSUE THREAD

**Issue by raintung** [Sable/soot#1292]
The issue source:

```
import java.util.List;

public class testLambdaNew {
	class test {
		public test(String s) {
			System.out.println("Hello " + s);
		}
	}
	public void go(List<String> list){
		list.stream().forEach(test::new);
	}
}
```

The exception:

```
Caused by: java.lang.RuntimeException: Box InvokeExprBox(null) cannot contain value: $r4(class soot.jimple.internal.JimpleLocal)
	at soot.AbstractValueBox.setValue(AbstractValueBox.java:41)
	at soot.jimple.internal.InvokeExprBox.<init>(InvokeExprBox.java:31)
	at soot.jimple.Jimple.newInvokeExprBox(Jimple.java:728)
	at soot.jimple.internal.JInvokeStmt.<init>(JInvokeStmt.java:46)
	at soot.jimple.Jimple.newInvokeStmt(Jimple.java:608)
	at soot.LambdaMetaFactory$ThunkMethodSource.invokeImplMethod(LambdaMetaFactory.java:672)
	at soot.LambdaMetaFactory$ThunkMethodSource.getInvokeBody(LambdaMetaFactory.java:486)
	at soot.LambdaMetaFactory$ThunkMethodSource.getBody(LambdaMetaFactory.java:337)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:402)
	at soot.LambdaMetaFactory.makeLambdaHelper(LambdaMetaFactory.java:239)
	at soot.asm.AsmMethodSource.convertInvokeDynamicInsn(AsmMethodSource.java:1420)
	at soot.asm.AsmMethodSource.convert(AsmMethodSource.java:1791)
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:2038)
```

**Comment by mbenz89** [comment]
Fixed by  #1299 (origin #1296)
