### ISSUE TITLE
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;I)V

### ISSUE THREAD

**Issue by mjblackhorse** [Sable/soot#1340]
I'm trying to implement a SceneTransofromer. 
The project can be  built successfully. However, when I tried to run a test, I always got the following error:
```
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;I)V

	at com.google.common.cache.CacheBuilder.initialCapacity(CacheBuilder.java:355)
	at soot.SourceLocator.<init>(SourceLocator.java:67)
	at soot.Singletons.soot_SourceLocator(Singletons.java:238)
	at soot.SourceLocator.v(SourceLocator.java:133)
	at soot.Scene.tryLoadClass(Scene.java:967)
	at soot.Scene.loadBasicClasses(Scene.java:1708)
	at soot.Scene.loadNecessaryClasses(Scene.java:1807)
	at cn.edu.nju.ics.layoutchecker.LayoutMapper.buildEntryPoints(LayoutMapper.java:90)
	at cn.edu.nju.ics.layoutchecker.LayoutMapper.performSootAnalysis(LayoutMapper.java:102)
	at cn.edu.nju.ics.layoutchecker.LayoutMapper.internalTransform(LayoutMapper.java:73)
	at soot.SceneTransformer.transform(SceneTransformer.java:36)
	at soot.Transform.apply(Transform.java:102)
	at soot.ScenePack.internalApply(ScenePack.java:35)
	at soot.Pack.apply(Pack.java:117)
	at cn.edu.nju.ics.layoutchecker.LayoutMapper.run(LayoutMapper.java:217)
	at cn.edu.nju.ics.layoutchecker.LayoutMapperTest.test(LayoutMapperTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)

```
Here is my code snippte：

```
public class LayoutMapper extends SceneTransformer {

    static Logger logger ;

    ApkHandler handler;
    static {
        logger = LoggerFactory.getLogger(LayoutMapper.class);
    }

	...

    public LayoutMapper(String apkFilePath) {
        G.reset();
        this.handler=new ApkHandler(apkFilePath);
        this.handler.createApkFile();
        this.handler.loadManifestFile();
        Config.apkFilePath = apkFilePath;
    }

    /* (non-Javadoc)
     * @see soot.SceneTransformer#internalTransform(java.lang.String, java.util.Map)
     */
    @Override
    protected void internalTransform(String phaseName, Map<String, String> options) {
        this.handler.createApkFile();
        this.handler.loadManifestFile();
        Config.updateAndroidJAR(handler.targetSdkVersion);
        LinkedHashSet<String >compNames=new LinkedHashSet<>();
        for (String activity : handler.activities) {
            compNames.add(activity);
        }
        for (String compName : compNames) {
            String fullCompName = null;
            if (compName.startsWith(".")) {
                fullCompName = handler.mainPackageName + compName;
            } else {
                fullCompName = compName;
            }
            fullActivityNames.add(fullCompName);
        }
        if (sootAnalysisEnabled) {
            performSootAnalysis();
        }

    }
   
    public void buildEntryPoints(){
        Config.applyWholeProgramSootOptions();
        Scene.v().loadNecessaryClasses();
        LinkedList<SootMethod>entrypoints=new LinkedList<>();
        for(String activity:fullActivityNames) {
            SootClass sootClass = Scene.v().getSootClass(activity);
            SootMethod method = sootClass.getMethodByName("onCreate");
            System.out.println(method);
            entrypoints.add(method);
        }
        Scene.v().setEntryPoints(entrypoints);
    }

    public void performSootAnalysis() {
        buildEntryPoints();
		...
    }

    
    public void run() {
        this.handler.decode();
        Options.v().set_whole_program(true);
        //Options.v().set_verbose(true);
        Options.v().set_output_format(Options.v().output_format_none);
        PackManager.v().getPack("wjtp")
                .add(new Transform("wjtp.layoutmapper", this));
        PackManager.v().getPack("wjtp").apply();
    }
}

```
The build.gradle file:
```
version '1.0-SNAPSHOT'

apply plugin: 'java'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    compile 'ca.mcgill.sable:soot:4.1.+'
    compile 'net.dongliu:apk-parser:2.6.10'
    compile group: 'org.jdom', name: 'jdom2', version: '2.0.6'
    testCompile group: 'junit', name: 'junit', version: '4.13'

    compile files('libs/apktool_2.4.1.jar')
}

```

I've tried different version of soot and changed many apks, but the error keeps happen.

Is there anything wrong in my code ?

**Comment by mjblackhorse** [comment]
dependency tree of the project is:
```
testCompileClasspath - Compile classpath for source set 'test'.
+--- ca.mcgill.sable:soot:4.+ -> 4.1.0
|    +--- commons-io:commons-io:2.6
|    +--- org.smali:dexlib2:2.3.4
|    |    +--- com.google.code.findbugs:jsr305:1.3.9 -> 3.0.2
|    |    \--- com.google.guava:guava:27.1-android
|    |         +--- com.google.guava:failureaccess:1.0.1
|    |         +--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
|    |         +--- com.google.code.findbugs:jsr305:3.0.2
|    |         +--- org.checkerframework:checker-compat-qual:2.5.2
|    |         +--- com.google.errorprone:error_prone_annotations:2.2.0
|    |         +--- com.google.j2objc:j2objc-annotations:1.1
|    |         \--- org.codehaus.mojo:animal-sniffer-annotations:1.17
|    +--- org.ow2.asm:asm:7.1
|    +--- org.ow2.asm:asm-tree:7.1
|    |    \--- org.ow2.asm:asm:7.1
|    +--- org.ow2.asm:asm-util:7.1
|    |    +--- org.ow2.asm:asm:7.1
|    |    +--- org.ow2.asm:asm-tree:7.1 (*)
|    |    \--- org.ow2.asm:asm-analysis:7.1
|    |         \--- org.ow2.asm:asm-tree:7.1 (*)
|    +--- org.ow2.asm:asm-commons:7.1
|    |    +--- org.ow2.asm:asm:7.1
|    |    +--- org.ow2.asm:asm-tree:7.1 (*)
|    |    \--- org.ow2.asm:asm-analysis:7.1 (*)
|    +--- xmlpull:xmlpull:1.1.3.4d_b4_min
|    +--- de.upb.cs.swt:axml:2.0.0
|    +--- ca.mcgill.sable:polyglot:2006
|    +--- de.upb.cs.swt:heros:1.2.0
|    |    +--- org.functionaljava:functionaljava:4.2
|    |    +--- com.google.guava:guava:19.0 -> 27.1-android (*)
|    |    \--- org.slf4j:slf4j-api:1.7.5
|    +--- ca.mcgill.sable:jasmin:3.0.2
|    |    \--- ca.mcgill.sable:java_cup:0.9.2
|    +--- org.slf4j:slf4j-api:1.7.5
|    +--- javax.annotation:javax.annotation-api:1.3.2
|    +--- javax.xml.bind:jaxb-api:2.4.0-b180725.0427 -> 2.4.0-b180830.0359
|    |    \--- javax.activation:javax.activation-api:1.2.0
|    \--- org.glassfish.jaxb:jaxb-runtime:2.4.0-b180830.0438
|         +--- javax.xml.bind:jaxb-api:2.4.0-b180830.0359 (*)
|         +--- org.glassfish.jaxb:txw2:2.4.0-b180830.0438
|         +--- com.sun.istack:istack-commons-runtime:3.0.7
|         +--- org.jvnet.staxex:stax-ex:1.8
|         +--- com.sun.xml.fastinfoset:FastInfoset:1.2.15
|         \--- javax.activation:javax.activation-api:1.2.0
+--- net.dongliu:apk-parser:2.6.10
+--- org.jdom:jdom2:2.0.6
\--- junit:junit:4.13
     \--- org.hamcrest:hamcrest-core:1.3

```

**Comment by mjblackhorse** [comment]
I've found the problem.

apktool_2.4.1.jar contains package of com.google.guava:guava
