### ISSUE TITLE
soot.SootResolver$SootClassNotFoundException: couldn't find class: Foo (is your soot-class-path set properly?)

### ISSUE THREAD

**Issue by 0range228** [Sable/soot#1344]
Hi~

I want to analysis my java project whose structure like this:
```
- libs
--rt.jar(from JRE)
--soot-trunk.jar
-src
--SootTest
---Foo.class
```
So I run this command in `~/Desktop/soot_test/src/SootTest`:
`java -cp ../../libs/sootclasses-trunk-jar-with-dependencies.jar:../../libs/rt.jar soot.Main -pp Foo`

But I still get WRONG!

Can anyone tell me how to write the RIGHT ANSWER,please?
It borings me for a long time!

**Comment by Wangxiz** [comment]
It seems that you should add `.` to your soot-class-path:

```
java -cp ../../libs/soot-trunk.jar:../../libs/rt.jar soot.Main -cp . -pp Foo
```

**Comment by 0range228** [comment]
@Wangxiz Unfortunately,it dosen't work.
Foo.java just like this:
```
package Emp;
import sun.tools.jar.resources.jar;
public class Foo {

    public static void main(String[] args) {
        Foo f = new Foo();
        int a = 7;
        int b = 14;
        int x = (f.bar(21) + a) * b;
    }
    public int bar(int n) {
        return n + 42;
    }

}
```
And you can find i change its package,for now it's `Emp`；
And now my command is:
```
java -cp sootclasses-trunk-jar-with-dependencies.jar soot.Main -cp . -pp Emp.Foo
```

it still failed:
```
java -cp sootclasses-trunk-jar-with-dependencies.jar soot.Main -cp . -pp Emp.Foo
Soot started on Fri May 01 23:22:28 CST 2020
soot.SootResolver$SootClassNotFoundException: couldn't find class: Emp.Foo (is your soot-class-path set properly?)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:245)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:221)
	at soot.SootResolver.bringToSignatures(SootResolver.java:292)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:179)
	at soot.SootResolver.resolveClass(SootResolver.java:141)
	at soot.Scene.loadClass(Scene.java:1067)
	at soot.Scene.loadClassAndSupport(Scene.java:1052)
	at soot.Scene.loadNecessaryClass(Scene.java:1834)
	at soot.Scene.loadNecessaryClasses(Scene.java:1846)
	at soot.Main.run(Main.java:241)
	at soot.Main.main(Main.java:141)
```
I really don't know how to do next? 
Please...

**Comment by Wangxiz** [comment]
@0range228 I think you might have misplaced `Foo.class` (or `Foo.java`), which should be placed  in package dir `Emp`.

You can try the following file layout:

```
basedir
|- Emp
  |- Foo.class
  |- Foo.java
|- sootclasses-trunk-jar-with-dependencies.jar
```

and run:

```
cd path/to/basedir
java -cp sootclasses-trunk-jar-with-dependencies.jar soot.Main -cp . -pp Emp.Foo
```

then it should work, and it worked well for me.

**Comment by 0range228** [comment]
@Wangxiz Thanks a lot, now it works fine!
