### ISSUE TITLE
Program exists without any errors on Scene.v().loadClassAndSupport()

### ISSUE THREAD

**Issue by brennowilliam** [Sable/soot#1349]
Hi,

I'm running into an issue that I'm not able to figure out. 

The code won't exits without any errors when calling **Scene.v().loadClassAndSupport();**

JDK version: 1.8.0_251
Soot Version: 4.0.0

```
public class Main {
    public static void main(String[] args) {
        Options.v()
                .set_soot_classpath(System.getProperty("user.dir") + File.separator + "src" + File.separator + "com" + File.separator + "company" + File.pathSeparator
                        + System.getenv("JAVA_HOME") + File.separator + "jre/lib/rt.jar" + File.pathSeparator
                        + System.getProperty("user.dir") + File.separator + "src" + File.separator + "com" + File.separator + "company" + File.separator + "soot-4.0.0-jar-with-dependencies.jar"
                        + File.pathSeparator + System.getenv("JAVA_HOME") + File.separator + "jre/lib/jce.jar");

        Options.v().set_whole_program(true);

        Options.v().set_ignore_resolving_levels(true);

        Scene.v().loadNecessaryClasses();

        **SootClass cl = Scene.v().loadClassAndSupport("Main");**
       
        cl.setApplicationClass();

        SootMethod method = cl.getMethodByName("testFunction");

        Body body = method.retrieveActiveBody();

        UnitGraph graph = new BriefUnitGraph(body);

        Iterator<Unit> iterator = graph.iterator();

        BackwardFlowAnalysis<Unit, FlowSet<Local>> flowAnalysis = new MyBackwardFlowAnalysis<>(graph);
        //....
    }

   // ....
}
```

It will never reach any statements after the loadClassAndSupport.

I've tried running JDK 9 and 10. I have also tried different soot builds and it still doesn't work.

Since there is no errors, it is hard to find what I'm doing wrong. Any ideas?

Thank you

**Comment by ericbodden** [comment]
Hi. May it be possible that you are running into some weird form of infinite recursion? Have you tried attaching a debugger?

In general I would never recommend calling loadClassAndSupport manually. Instead better call Soot’s main method and let Soot do its magic.

Cheers
Eric

**Comment by mbenz89** [comment]
That's indeed a weird place causing an infinite recursion.

Btw. If you use  `Scene.v().loadNecessaryClasses();`, all classes on your classpath are already loaded and you should be able to use `Scene.v().getSootClass(clazzName)` to request a specific class.

Another issue in your code might be that you have no process directory set. Soot will mark all classes put in the process directory as application class when loading classes. Classes set by the class path options will be library classes and thereby not directly targeted by many analysies.

**Comment by brennowilliam** [comment]
@mbenz89, @ericbodden I've changed a little bit on how my class_path is set.

Now, I get the following error and I'm not sure why. It doesn't get pass the loadClassAndSupport.

Could you point me in the right direction here?

Note: If change to JDK 9, it gives me a nullPointer exception error instead of the one on the screenshot.

<img width="1326" alt="Screen Shot 2020-05-05 at 10 47 54 PM" src="https://user-images.githubusercontent.com/4711636/81131735-828a8e80-8f22-11ea-9a63-c703be0e3977.png">

<img width="605" alt="Screen Shot 2020-05-05 at 10 48 54 PM" src="https://user-images.githubusercontent.com/4711636/81131768-9f26c680-8f22-11ea-8e9b-e6290baebe9f.png">

**Comment by liuyuanOUC** [comment]
I guess your `soot_class_path` doesn't contain the classes that you want to analyze.

Maybe you want to refer to this [issue](https://github.com/Sable/soot/issues/1346#event-3390123017).

**Comment by gwenty** [comment]
Hi,

I have the same problem with error:

```
java.lang.RuntimeException: 
Aborting: can't find classfile Main
	at soot.Scene.getSootClass(Scene.java:508)
	at TestCallers.main(TestCallers.java:46)
```

Caused by the code 

```
public class TestCallers {

	public static void main(String[] args) {
                G.reset();	
		Options.v().set_prepend_classpath(true);
	        String sourceDirectory = System.getProperty("user.dir")  + File.separator + "src"; //src only needed in eclipse otherwise already running from src directory

		System.out.println(Scene.v().defaultClassPath()); //only seems useful in Eclipse, otherwise this produces 
		Options.v().set_soot_classpath(Scene.v().defaultClassPath() + File.pathSeparator + sourceDirectory);
                System.out.println(Scene.v().getSootClassPath());
		SootClass sc = Scene.v().getSootClass("Main");
		System.out.println("HH");
	}

}
```

The Main class does not do anything special and it is in the same directory as Testcallers.

The bin, src, soot jar and rt.jar are in the soot classpath. Is there any missing? I have tried running it with Eclipse (java12) and in the command line on Windows (java12 and java7). And I have run it in the command line on Linux(java14).

And this is what I run in the command line 
javac -cp .\sootclasses-trunk-jar-with-dependencies.jar TestCallers.java Main.java
java -cp ".\sootclasses-trunk-jar-with-dependencies.jar;." TestCallers

(as a side note, loadClassAndSupport gives me a nullpointer exception)

Could anyone please point me in the right direction?
