### ISSUE TITLE
Exception when using ArrayBoundsChecker

### ISSUE THREAD

**Issue by tiziw** [Sable/soot#1354]
Hi,

When enabling the ArrayBounds checker optimization it sometimes throws a NullPointerException. It happens randomly, sometimes the program runs fine.

`[Thread-6] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: null
java.lang.NullPointerException
	at soot.jimple.toolkits.annotation.arraycheck.ArrayBoundsCheckerAnalysis.doAnalysis(ArrayBoundsCheckerAnalysis.java:372)
	at soot.jimple.toolkits.annotation.arraycheck.ArrayBoundsCheckerAnalysis.<init>(ArrayBoundsCheckerAnalysis.java:170)
	at soot.jimple.toolkits.annotation.arraycheck.ArrayBoundsChecker.internalTransform(ArrayBoundsChecker.java:104)
	at soot.BodyTransformer.transform(BodyTransformer.java:51)
	at soot.Transform.apply(Transform.java:120)
	at soot.BodyPack.internalApply(BodyPack.java:50)
	at soot.Pack.apply(Pack.java:125)
	at soot.PackManager.runBodyPacks(PackManager.java:1010)
	at soot.PackManager.lambda$runBodyPacks$0(PackManager.java:660)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "main" java.lang.NullPointerException
	at soot.jimple.toolkits.annotation.arraycheck.ArrayBoundsCheckerAnalysis.doAnalysis(ArrayBoundsCheckerAnalysis.java:372)
	at soot.jimple.toolkits.annotation.arraycheck.ArrayBoundsCheckerAnalysis.<init>(ArrayBoundsCheckerAnalysis.java:170)
	at soot.jimple.toolkits.annotation.arraycheck.ArrayBoundsChecker.internalTransform(ArrayBoundsChecker.java:104)
	at soot.BodyTransformer.transform(BodyTransformer.java:51)
	at soot.Transform.apply(Transform.java:120)
	at soot.BodyPack.internalApply(BodyPack.java:50)
	at soot.Pack.apply(Pack.java:125)
	at soot.PackManager.runBodyPacks(PackManager.java:1010)
	at soot.PackManager.lambda$runBodyPacks$0(PackManager.java:660)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-6" java.lang.NullPointerException
	at soot.jimple.toolkits.annotation.arraycheck.ArrayBoundsCheckerAnalysis.doAnalysis(ArrayBoundsCheckerAnalysis.java:372)
	at soot.jimple.toolkits.annotation.arraycheck.ArrayBoundsCheckerAnalysis.<init>(ArrayBoundsCheckerAnalysis.java:170)
	at soot.jimple.toolkits.annotation.arraycheck.ArrayBoundsChecker.internalTransform(ArrayBoundsChecker.java:104)
	at soot.BodyTransformer.transform(BodyTransformer.java:51)
	at soot.Transform.apply(Transform.java:120)
	at soot.BodyPack.internalApply(BodyPack.java:50)
	at soot.Pack.apply(Pack.java:125)
	at soot.PackManager.runBodyPacks(PackManager.java:1010)
	at soot.PackManager.lambda$runBodyPacks$0(PackManager.java:660)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

Flags used:
`        PhaseOptions.v().setPhaseOption("jap.npc", "enabled:true")
        PhaseOptions.v().setPhaseOption("jap.abc", "enabled:true")
        PhaseOptions.v().setPhaseOption("jap.abc", "with-cse:true")
        PhaseOptions.v().setPhaseOption("jap.abc", "with-classfield:true")
`
When disabling with-classfield and with-cse it still happens.

The bug started to occur after I added this custom transformation:
```
        PackManager.v().getPack("wjtp").add(Transform("wjtp.setup", object: SceneTransformer() {
            override fun internalTransform(p0: String, p1: MutableMap<String, String>) {
                Scene.v().reachableMethods.listener().asSequence().map {it.method().declaringClass}.distinct().forEach {
                    it.setApplicationClass()
                }
            }

        }))
```

The reason I added that optimization is, I'm using Soot with a custom (java) runtime to generate C code. Without setting all classes (which I generate into source code, including the runtime) to Application Classes, optimizations (BodyTransformer's) only get applied to the Main class and not the runtime classes, which I also need to be optimized. I can only know using the callgraph which classes end up being part of the application ((in)directly used by the Main class). I added this transformation to do that in the phase when the callgraph is available. Did I do something wrong? Is there a better way to do it? Before I would just my (custom) optimizations after all the packs were finished and modify the bodies, but I suspect the jop/wjop packs don't optimize the runtime classes since they're not application classes.

Thanks!

I'm also using Soot version 4.1.0.

**Comment by tiziw** [comment]
Just had the error, but a bit more detailed:

`heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: null
java.lang.NullPointerException
	at soot.toolkits.graph.SlowPseudoTopologicalOrderer.visitNode(SlowPseudoTopologicalOrderer.java:186)
	at soot.toolkits.graph.SlowPseudoTopologicalOrderer.computeOrder(SlowPseudoTopologicalOrderer.java:112)
	at soot.toolkits.graph.SlowPseudoTopologicalOrderer.newList(SlowPseudoTopologicalOrderer.java:76)
	at soot.jimple.toolkits.annotation.arraycheck.ArrayBoundsCheckerAnalysis.doAnalysis(ArrayBoundsCheckerAnalysis.java:273)
	at soot.jimple.toolkits.annotation.arraycheck.ArrayBoundsCheckerAnalysis.<init>(ArrayBoundsCheckerAnalysis.java:170)
	at soot.jimple.toolkits.annotation.arraycheck.ArrayBoundsChecker.internalTransform(ArrayBoundsChecker.java:104)
	at soot.BodyTransformer.transform(BodyTransformer.java:51)
	at soot.Transform.apply(Transform.java:120)
	at soot.BodyPack.internalApply(BodyPack.java:50)
	at soot.Pack.apply(Pack.java:125)
	at soot.PackManager.runBodyPacks(PackManager.java:1010)
	at soot.PackManager.lambda$runBodyPacks$0(PackManager.java:660)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

If there's a workaround I can use, I'm also fine with that. I can imagine that the ArrayBounds analysis is rarely used and thus not actively maintained.

**Comment by tiziw** [comment]
Hello, I've managed to circumvent the issue. I suspected it was a concurrency problem, as I was debugging the class and I saw that a datastructure that the optimization used, SlowPseudoTopologicalOrderer sometimes missed a required Block instance, which caused the NullPointerException. 

I've copied the whole package into my project and replaced [line](https://github.com/Sable/soot/blob/master/src/main/java/soot/jimple/toolkits/annotation/arraycheck/ArrayBoundsCheckerAnalysis.java#L273) that contains the SlowPseudoTopologicalOrderer.v() call with new SlowPseudoTopologicalOrderer() so each time it generates a new object. This might not be good for gc, but it works. My assumption is that the code for the class (From 2000 according to the copyright notice), somehow broke when Soot added support for multithreading, since git history shows no useful commits to that class.

I hope this can be of any use to the devs, if there are no plans to change the class/optimization as it's not worth being maintained, then feel free to close the issue.

**Comment by MarcMil** [comment]
Can be closed @StevenArzt
