### ISSUE TITLE
Soot fails to analyze apk file

### ISSUE THREAD

**Issue by ahmadshahzad** [Sable/soot#201]
Hi,
I am trying to analyze apk files, but soot fails on analyzing apk file, like mozilla firefox and throws RunTimeException.

Code which I am writing to analyze apk.

    public class Main {
    
        public static void main(String[] args) {
        try {
            Pack pack = PackManager.v().getPack("jtp");
            pack.add(new Transform("jtp.myTransform", new BodyTransformer() {
                protected void internalTransform(Body b, String phase, Map options) {

                }
            }));
            soot.Main.main(new String[]{"-src-prec","apk","-process-dir", "org.mozilla.firefox.apk","-d","sootOutput","-f","dex",
                    "-android-jars","C:\\Program Files (x86)\\Android\\android-sdk\\platforms"}); //,"-allow-phantom-refs" add it or not it doesn't make any difference
            G.reset();
        } catch (Exception e) {
            e.printStackTrace();
        }
        }
    }

Exception stack: (Firefox app)
```
    java.lang.RuntimeException: oops,  base type must be PrimType or RefType but not 'null_type'
	at soot.ArrayType.<init>(ArrayType.java:59)
	at soot.ArrayType.v(ArrayType.java:83)
	at soot.Type.makeArrayType(Type.java:74)
	at soot.jimple.toolkits.typing.fast.UseChecker.caseAssignStmt(UseChecker.java:273)
	at soot.jimple.internal.JAssignStmt.apply(JAssignStmt.java:223)
	at soot.jimple.toolkits.typing.fast.UseChecker.check(UseChecker.java:129)
	at soot.jimple.toolkits.typing.fast.TypeResolver.insertCasts(TypeResolver.java:402)
	at soot.jimple.toolkits.typing.fast.TypeResolver.minCasts(TypeResolver.java:413)
	at soot.jimple.toolkits.typing.fast.TypeResolver.inferTypes(TypeResolver.java:149)
	at soot.jimple.toolkits.typing.TypeAssigner.internalTransform(TypeAssigner.java:102)
	at soot.BodyTransformer.transform(BodyTransformer.java:51)
	at soot.BodyTransformer.transform(BodyTransformer.java:58)
	at soot.BodyTransformer.transform(BodyTransformer.java:63)
	at soot.dexpler.DexBody.jimplify(DexBody.java:571)
	at soot.dexpler.DexMethod$1.getBody(DexMethod.java:146)
	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:324)
	at soot.PackManager.retrieveAllBodies(PackManager.java:1113)
	at soot.PackManager.runPacksNormally(PackManager.java:445)
	at soot.PackManager.runPacks(PackManager.java:388)
	at soot.Main.run(Main.java:203)
	at soot.Main.main(Main.java:146)
	at Main.main(Main.java:15)
```

**Comment by StevenArzt** [comment]
That seems to work with the newest version of Soot, so I close this issue.
