### ISSUE TITLE
ANR caused by transformed APK file (gpslogger-49.apk)

### ISSUE THREAD

**Issue by Jin-Li-ICT** [Sable/soot#215]
I only use comman line option to transform the gpslogger.apk file.

java -jar soot.jar -src-prec apk -android-jars mysdkpath -process-dir myapkfile -allow-phantom-refs -output-format dex

Then, I install the signed apk file on my device, 
1,lauch the app. 
2,run a while
3,leave the activity
4, back to the app, then ANR is occured.

relevent logs:
threadid=3: reacting to signal 3
JIT unchain all for threadid=1
threadid=3: spin on suspend #2 threadid=1 (pcf=0)
"Signal Catcher" daemon prio=5 tid=3 RUNNABLE | group="system" sCount=0 dsCount=0 obj=0x419061c0 self=0x5ac9d608
 | sysTid=7814 nice=0 sched=0/0 cgrp=apps handle=1523115664
 | state=R schedstat=( 1585572 3586355 33 ) utm=0 stm=0 core=0
at dalvik.system.NativeStart.run(Native Method)
"main" prio=5 tid=1 RUNNABLE JIT
  | group="main" sCount=1 dsCount=0 obj=0x41664710 self=0x4164f5b8
  | sysTid=7809 nice=0 sched=0/0 cgrp=apps handle=1074716668
  | state=R schedstat=( 22018573739 961469736 6689 ) utm=2175 stm=26 core=0
at ch.qos.logback.core.pattern.parser.TokenStream.handleLiteralState(dalvik_source_gpslogger-49.apk:~-1)
at ch.qos.logback.core.pattern.parser.TokenStream.tokenize(dalvik_source_gpslogger-49.apk:-1)
at ch.qos.logback.core.pattern.parser.Parser.<init>(dalvik_source_gpslogger-49.apk:-1)
at ch.qos.logback.core.rolling.helper.FileNamePattern.parse(dalvik_source_gpslogger-49.apk:-1)
at ch.qos.logback.core.rolling.helper.FileNamePattern.<init>(dalvik_source_gpslogger-49.apk:-1)
at ch.qos.logback.core.rolling.TimeBasedRollingPolicy.start(dalvik_source_gpslogger-49.apk:-1)
at com.mendhak.gpslogger.common.Utilities.ConfigureLogbackDirectly(Utilities.java:92)
at com.mendhak.gpslogger.GpsLoggingService.onCreate(GpsLoggingService.java:97)
at android.app.ActivityThread.handleCreateService(ActivityThread.java:2580)
at android.app.ActivityThread.access$1600(ActivityThread.java:144)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5136)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
at dalvik.system.NativeStart.main(Native Method)
Fatal signal 6 (SIGABRT) at 0x0000037c (code=0), thread 7809 (ndhak.gpslogger)

I run the original apk,  everything is ok.
I don't know if it is a bug of soot?  If not, how can I debug it?

APK file:   https://github.com/mendhak/gpslogger

**Comment by Alexandre-Bartel** [comment]
This issue does not happen with the latest version of Soot a3c4872cc8cd48749f18c1abe41356242c8e364a.
