### ISSUE TITLE
Exception at soot.AbstractValueBox.setValue(AbstractValueBox.java:43)

### ISSUE THREAD

**Issue by martinschaef** [Sable/soot#219]
I get the following exception when trying to parse the program below:

**Exception in thread "main" java.lang.RuntimeException: Box ImmediateBox(null) cannot contain value: temp$5 + 1(class soot.jimple.internal.JAddExpr)
    at soot.AbstractValueBox.setValue(AbstractValueBox.java:43)
    at soot.jimple.internal.ImmediateBox.<init>(ImmediateBox.java:39)
    at soot.jimple.Jimple.newImmediateBox(Jimple.java:666)
    at soot.jimple.internal.JStaticInvokeExpr.<init>(JStaticInvokeExpr.java:46)
    at soot.jimple.Jimple.newStaticInvokeExpr(Jimple.java:344)**

Here is the code:

``` java
public class SimpleThreads {

    private static int shared = 0;
    static void threadMessage(String message) {
        String threadName =
            Thread.currentThread().getName();
        System.out.format("%s: %s%n",
                          threadName,
                          message);
    }

    private static class MessageLoop
        implements Runnable {
        public void run() {
            String importantInfo[] = {
                "Mares eat oats",
                "Does eat oats",
                "Little lambs eat ivy",
                "A kid will eat ivy too"
            };
            try {
                for (int i = 0;
                     i < importantInfo.length;
                     i++) {
                    Thread.sleep(4000);
                    threadMessage(importantInfo[i]);
                    shared++;
                }
            } catch (InterruptedException e) {
                threadMessage("I wasn't done!");
            }
        }
    }

    public static void main(String args[])
        throws InterruptedException {

        long patience = 1000 * 60 * 60;
        threadMessage("Starting MessageLoop thread");
        long startTime = System.currentTimeMillis();
        shared++;
        Thread t = new Thread(new MessageLoop());
        t.start();
        shared++;
        threadMessage("Waiting for MessageLoop thread to finish");
        while (t.isAlive()) {
            threadMessage("Still waiting...");
            t.join(1000);
            if (((System.currentTimeMillis() - startTime) > patience)
                  && t.isAlive()) {
                threadMessage("Tired of waiting!");
                t.interrupt();
                t.join();
            }
        }
        threadMessage("Finally!");
    }
}
```

**Comment by anddann** [comment]
Parsing the bytecode works with release 4.0.
Unfortunately, the source code frontend is outdated.
