### ISSUE TITLE
java.lang.RuntimeException when trying to process WhatsApp.apk

### ISSUE THREAD

**Issue by yongabc** [Sable/soot#282]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: trunk

Command line:
--soot-classpath ./WhatsApp.apk: -d ./wout -android-jars /home/zy/adt/sdk/platforms -allow-phantom-refs -src-prec apk -ire -f J -process-dir ./WhatsApp.apk

Max Memory:
1820MB

Stack trace:
java.lang.RuntimeException: tried to get nonexistent method <java.lang.NullPointerException: void <init>(java.lang.String)>
	at soot.Scene.getMethod(Scene.java:619)
	at soot.dexpler.Util.addExceptionAfterUnit(Util.java:294)
	at soot.jimple.toolkits.typing.TypeAssigner.replaceNullType(TypeAssigner.java:185)
	at soot.jimple.toolkits.typing.TypeAssigner.internalTransform(TypeAssigner.java:118)
	at soot.BodyTransformer.transform(BodyTransformer.java:51)
	at soot.BodyTransformer.transform(BodyTransformer.java:58)
	at soot.BodyTransformer.transform(BodyTransformer.java:63)
	at soot.dexpler.DexBody.jimplify(DexBody.java:584)
	at soot.dexpler.DexMethod$1.getBody(DexMethod.java:149)
	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:324)
	at soot.PackManager.retrieveAllBodies(PackManager.java:1135)
	at soot.PackManager.runPacksNormally(PackManager.java:458)
	at soot.PackManager.runPacks(PackManager.java:391)
	at soot.Main.run(Main.java:244)
	at soot.Main.main(Main.java:152)

**Comment by StevenArzt** [comment]
The new Soot builds cache the UnitGraph whever possible. This shoud alleviate the performance problem at least a bit.
