### ISSUE TITLE
soot.SootResolver$SootClassNotFoundException when ...

### ISSUE THREAD

**Issue by MikeShah** [Sable/soot#284]
Steps to reproduce:
1.) This is my command line: java -cp soot-trunk.jar soot.Main -cp /Library/Java/JavaVirtualMachines/jdk1.7.0_60.jdk/Contents/Home/jre/lib/rt.jar:"../benchmarks/Sunflow/sunflow/classes/":"../benchmarks/Sunflow/sunflow/classes/org/":"../benchmarks/Sunflow/sunflow/classes/org/sunflow/":"../benchmarks/Sunflow/sunflow/" -f J -app -dump-cfg ALL -process-dir "../benchmarks/Sunflow/sunflow/classes/"

2.) I am in a directory that contains soot-trunk.jar from September 30, 2014. I am then setting the java classpath that contains the .class files to the program.  The program has already been successfully compiled with Java. I then want to analyze all of these classes in a directory and each of the subdirectories in  (../benchmarks/Sunflow/sunflow/classes"). 

I always get an error: "couldn't find class: org.sunflow.Benchmark$BenchmarkScene (is your soot-class-path set properly?)" when I am sure that I should be able to analyze the .class files, dump the CFGs and then output the jimple.

Files used to reproduce: 
sunflow benchmark

Soot version: trunk

Command line:
-cp /Library/Java/JavaVirtualMachines/jdk1.7.0_60.jdk/Contents/Home/jre/lib/rt.jar:../benchmarks/Sunflow/sunflow/classes/:../benchmarks/Sunflow/sunflow/classes/org/:../benchmarks/Sunflow/sunflow/classes/org/sunflow/:../benchmarks/Sunflow/sunflow/ -f J -app -dump-cfg ALL -process-dir ../benchmarks/Sunflow/sunflow/classes/

Max Memory:
910MB

Stack trace:
soot.SootResolver$SootClassNotFoundException: couldn't find class: org.sunflow.Benchmark$BenchmarkScene (is your soot-class-path set properly?)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:220)
	at soot.SootResolver.bringToSignatures(SootResolver.java:255)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:169)
	at soot.SootResolver.resolveClass(SootResolver.java:130)
	at soot.Scene.loadClass(Scene.java:673)
	at soot.Scene.loadClassAndSupport(Scene.java:659)
	at soot.Scene.loadNecessaryClasses(Scene.java:1319)
	at soot.Main.run(Main.java:214)
	at soot.Main.main(Main.java:152)

**Comment by ericbodden** [comment]
What's the status of this?

**Comment by MikeShah** [comment]
Hi Eric,

I believe this issue has now been resolved by using Java version 7.
Unfortunately, Java 1.8.20 still does not work with Soot as far as I have
tested.

-Mike

_______________________________
Mike Shah
Ph.D. Student
Tufts University
http://michaeldshah.net

**Comment by StevenArzt** [comment]
Java 8 support is work in progress. Since the original issue seems to have been resolved, I close this issue report.

**Comment by majestyhao** [comment]
Hi,

When I run "Scene.v().loadClassAndSupport("MyClass");" under Eclipse it pops error says "couldn't find class: playSoot.MyClass (is your soot-class-path set properly?)", after leveraging lib "soot-trunt.jar". It works fine when I used the default SOOTCLASS from eclipse plugin.

**Comment by StevenArzt** [comment]
@majestyhao Please open dedicated issues for your problems and don't put them into existing ones as otherwise, the list gets very confusing, especially since this issue has already been closed.

Concerning the error: Please don't use loadClassAndSupport directly unless you really need to and there is a good reason to do so. Instead, place your code into a transformer and call Soot's normal main() method.

**Comment by terry2012** [comment]
@rockflying I have a same issue as you. How did you address it?
Everything is fine for soot-2.5.0.jar, but once I replaced it with soot-trunk.jar, I got this error:
<code>couldn't find class: XXX (is your soot-class-path set properly?)</code>

Indeed, I checked the soot class in the program:
<code>System.out.println("Soot class path " + Scene.v().getSootClassPath());</code>

And found that when I am using soot-trunk.jar, the class path is only as follows:
<code>/usr/lib/jvm/java-7-oracle/jre/lib/rt.jar:/usr/lib/jvm/java-7-oracle/jre/lib/jce.jar</code>
But when I use soot-2.5.0.jar, the outputted class path is the same as my command line specified by <code>'java -cp ...'</code>

@StevenArzt Any hint for addressing this problem? Thanks a lot.
My OS is Ubuntu 15.10.

**Comment by xuehenIT** [comment]
how can i resolve this problem???
Exception in thread "main" soot.SootResolver$SootClassNotFoundException: couldn't find class: org.apache.http.HttpResponse (is your soot-class-path set properly?)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:228)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:208)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:173)
	at soot.SootResolver.resolveClass(SootResolver.java:133)

**Comment by Mahita2518** [comment]
how can i resolve the below exception??
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" soot.SootResolver$SootClassNotFoundException: couldn't find class: fibonacci (is your soot-class-path set properly?)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:264)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:240)
	at soot.SootResolver.bringToSignatures(SootResolver.java:310)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:195)
	at soot.SootResolver.resolveClass(SootResolver.java:152)
	at soot.Scene.loadClass(Scene.java:1004)
	at soot.Scene.loadClassAndSupport(Scene.java:991)
	at trail10.SootHeapClass.main(SootHeapClass.java:42)
