### ISSUE TITLE
Type Mask Not Found Exception for APK File

### ISSUE THREAD

**Issue by StevenArzt** [Sable/soot#285]
When running the "AndroidTest2.apk" file through Soot, we get a Type Mask Not Found Exception:

Exception in thread "main" java.lang.RuntimeException: Type mask not found for type java.beans.IntrospectionException
	at soot.jimple.spark.internal.TypeManager.get(TypeManager.java:103)
	at soot.jimple.spark.sets.HybridPointsToSet.nativeAddAll(HybridPointsToSet.java:59)
	at soot.jimple.spark.sets.HybridPointsToSet.addAll(HybridPointsToSet.java:84)
	at soot.jimple.spark.sets.PointsToSetInternal.addAll(PointsToSetInternal.java:37)
	at soot.jimple.spark.sets.HybridPointsToSet.superAddAll(HybridPointsToSet.java:44)
	at soot.jimple.spark.sets.HybridPointsToSet.addAll(HybridPointsToSet.java:81)
	at soot.jimple.spark.sets.DoublePointsToSet.addAll(DoublePointsToSet.java:61)
	at soot.jimple.spark.solver.PropWorklist.handleVarNode(PropWorklist.java:133)
	at soot.jimple.spark.solver.PropWorklist.propagate(PropWorklist.java:52)
	at soot.jimple.spark.SparkTransformer.internalTransform(SparkTransformer.java:152)
	at soot.SceneTransformer.transform(SceneTransformer.java:39)
	at soot.Transform.apply(Transform.java:90)
	at soot.RadioScenePack.internalApply(RadioScenePack.java:57)
	at soot.jimple.toolkits.callgraph.CallGraphPack.internalApply(CallGraphPack.java:49)
	at soot.Pack.apply(Pack.java:116)
	at soot.jimple.infoflow.Infoflow.computeInfoflow(Infoflow.java:283)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(Unknown Source)
	at soot.jimple.infoflow.android.TestApps.Test.runAnalysis(Unknown Source)
	at soot.jimple.infoflow.android.TestApps.Test.main(Unknown Source)

I have the APK file and the issue is reproducable.

**Comment by StevenArzt** [comment]
Fixed in the most recent version.
