### ISSUE TITLE
java.lang.RuntimeException when analyzing tomcat from class files

### ISSUE THREAD

**Issue by martinschaef** [Sable/soot#286]
Steps to reproduce:
1.) download tomcat from https://github.com/apache/tomcat and build it (to a point where you have class files)
2.) run the latest version of soot with the commands below. The bug was not there on earlier version (maybe 4 weeks ago).

Soot version: trunk

Command line:
-keep-line-number -pp -output-format none -allow-phantom-refs -cp /Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre/lib/jce.jar::/tmp/tomcat/output/classes /Users/schaef/Documents/tmp/tomcat/output/classes

Max Memory:
4062MB

Stack trace:
java.lang.RuntimeException: Attempt to create RefType containing a / --> /Users/schaef/Documents/tmp/tomcat/output/classes
	at soot.RefType.<init>(RefType.java:55)
	at soot.RefType.v(RefType.java:69)
	at soot.SootClass.<init>(SootClass.java:97)
	at soot.SootClass.<init>(SootClass.java:111)
	at soot.SootResolver.makeClassRef(SootResolver.java:112)
	at soot.SootResolver.resolveClass(SootResolver.java:128)
	at soot.Scene.loadClass(Scene.java:673)
	at soot.Scene.loadClassAndSupport(Scene.java:658)
	at soot.Scene.loadNecessaryClass(Scene.java:1294)
	at soot.Scene.loadNecessaryClasses(Scene.java:1305)
	at soot.Main.run(Main.java:214)
	at soot.Main.main(Main.java:152)
	at org.joogie.runners.SootRunner.run(SootRunner.java:325)
	at org.joogie.runners.SootRunner.runWithClass(SootRunner.java:178)
	at org.joogie.Dispatcher.runSoot(Dispatcher.java:131)
	at org.joogie.Dispatcher.run(Dispatcher.java:58)
	at jar2bpl_test.TomactTest.testJavaDirectory(TomactTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

**Comment by StevenArzt** [comment]
Since there has not been any further activity for quite a while, I close this thread.
