### ISSUE TITLE
NoSuchMethodError: android.content.res.StringBlock.read

### ISSUE THREAD

**Issue by jeckyt** [Sable/soot#305]
Hi,
i'm trying to use soot for instrumenting apk file and i started with the AndroidInstrument driver example.after i've added all the needed jars and i run the program i'm getting the below exception 
Soot started on Tue Dec 16 19:12:47 IST 2014
Exception in thread "main" java.lang.NoSuchMethodError: android.content.res.StringBlock.read(Landroid/content/res/IntReader;)Landroid/content/res/StringBlock;
	at android.content.res.AXmlResourceParser.doNext(AXmlResourceParser.java:767)
	at android.content.res.AXmlResourceParser.next(AXmlResourceParser.java:72)
	at soot.Scene.getTargetSDKVersion(Scene.java:363)
	at soot.Scene.getAndroidJarPath(Scene.java:314)
	at soot.Scene.defaultClassPath(Scene.java:492)
	at soot.Scene.getSootClassPath(Scene.java:230)
	at soot.SourceLocator.getClassSource(SourceLocator.java:67)
	at soot.Scene.tryLoadClass(Scene.java:649)
	at soot.Scene.loadBasicClasses(Scene.java:1250)
	at soot.Scene.loadNecessaryClasses(Scene.java:1329)
	at soot.Main.run(Main.java:214)
	at soot.Main.main(Main.java:152)
	at AndroidInstrument.main(AndroidInstrument.java:90)

**Comment by TrangJun** [comment]
I have met this problem too. I use soot version trunk. Can you help me?
