### ISSUE TITLE
Unsupported  major.minor version 51.0

### ISSUE THREAD

**Issue by codemiles** [Sable/soot#310]
Hey guys,
I am trying to run soot on Hadoop 0.14, I think it is Java 4.  Am using Soot-trunk.jar from https://ssebuild.cased.de/nightly/soot/lib/
It should work fine right? What I know that this new Soot support until Java7. ? right?

D:\TestHadoop\hadoop0.1to0.8\hadoop0.14.0>Exception in thread "main" java.lang.U
nsupportedClassVersionError: org/jf/dexlib2/writer/io/DexDataStore : Unsupported
 major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(Unknown Source)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$000(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at soot.PackManager.<init>(PackManager.java:537)
        at soot.Singletons.soot_PackManager(Singletons.java:472)
        at soot.PackManager.v(PackManager.java:344)
        at soot.Main.processCmdLine(Main.java:95)
        at soot.Main.run(Main.java:208)
        at soot.Main.main(Main.java:152)

**Comment by StevenArzt** [comment]
Your stack trace shows that Soot is using the JastAdd frontend for Java source code. Please try again with compiled class files and the Soot command-line option "-src-prec only-class". The bytecode frontend should be much more stable.

**Comment by codemiles** [comment]
Hi Stev, 
I think yes, I can send you Hadoop0.14 Complied project for eclipse to check on i, generally I want to parse .java , not .class. Please give me your email, if you want me to send that compiled Hadoop as example.

**Comment by StevenArzt** [comment]
Whether it works with the compiled class files is something you can easily try on your own, I gave you the correct command line option above.

I know that Soot has issues with parsing modern .java files. We need to upgrade the respective frontend to make this work again which is under discussion here: https://github.com/Sable/soot/issues/300. At the moment, I regret to admit that you might not be able to parse the .java files of big projects, sorry. If you want to contribute to get the working again, please look into the link above.

**Comment by ericbodden** [comment]
This issue has been silent for a long time. @codemiles please reopen if it's still an issue.
