### ISSUE TITLE
java.lang.IllegalStateException when ...

### ISSUE THREAD

**Issue by MarcMil** [Sable/soot#312]
Files used to reproduce: 
md5sum is 8e979db0258160b38b88c53427d6e452
File name: -7395469583902704672_Orlando Magic Daily.apk

Soot version: trunk

Command line:
-src-prec apk --allow-phantom-refs -output-format jimple -force-android-jar /home/marc/adt-bundle-linux-x86_64-20140702/sdk/platforms/android-16/ --process-dir /home/marc/Problematic/-7395469583902704672_Orlando Magic Daily.apk

Max Memory:
3559MB

Stack trace:
java.lang.IllegalStateException: UnitThrowAnalysis StmtSwitch: type of throw argument is not a RefType!
	at soot.toolkits.exceptions.AbstractThrowAnalysis.mightThrowExplicitly(AbstractThrowAnalysis.java:65)
	at soot.toolkits.exceptions.UnitThrowAnalysis$UnitSwitch.caseThrowStmt(UnitThrowAnalysis.java:706)
	at soot.jimple.internal.JThrowStmt.apply(JThrowStmt.java:70)
	at soot.toolkits.exceptions.UnitThrowAnalysis.mightThrow(UnitThrowAnalysis.java:241)
	at soot.toolkits.graph.ExceptionalUnitGraph.getExceptionDests(ExceptionalUnitGraph.java:818)
	at soot.toolkits.graph.ExceptionalUnitGraph.buildHeadsAndTails(ExceptionalUnitGraph.java:779)
	at soot.toolkits.graph.ExceptionalUnitGraph.initialize(ExceptionalUnitGraph.java:293)
	at soot.toolkits.graph.ExceptionalUnitGraph.<init>(ExceptionalUnitGraph.java:159)
	at soot.toolkits.graph.ExceptionalUnitGraph.<init>(ExceptionalUnitGraph.java:192)
	at soot.dexpler.DexNullTransformer.internalTransform(DexNullTransformer.java:96)
	at soot.BodyTransformer.transform(BodyTransformer.java:51)
	at soot.BodyTransformer.transform(BodyTransformer.java:58)
	at soot.BodyTransformer.transform(BodyTransformer.java:63)
	at soot.dexpler.DexBody.jimplify(DexBody.java:523)
	at soot.dexpler.DexMethod$1.getBody(DexMethod.java:150)
	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:324)
	at soot.PackManager.retrieveAllBodies(PackManager.java:1140)
	at soot.PackManager.runPacksNormally(PackManager.java:458)
	at soot.PackManager.runPacks(PackManager.java:391)
	at soot.Main.run(Main.java:244)
	at soot.Main.main(Main.java:152)

**Comment by MarcMil** [comment]
Seems to be fixed; cannot reproduce it anymore. :)
