### ISSUE TITLE
soot.tools.CFGViewer error with : java.lang.RuntimeException: no apk file given

### ISSUE THREAD

**Issue by WangYeOtw** [Sable/soot#313]
I can run command to use soot to generate  jimple from apk,
and now,i want to generate dots ,and with the command:

java -Xss50m -Xmx1500m -cp .\soot.jar  soot.tools.CFGViewer --soot-classpath .;.\rt.jar;.\jsse.jar;jce.jar;.\AXMLPrinter2.jar;.\;baksmail.jar  -android-jars C:\test\android-sdk --graph=ExceptionalUnitGraph  -allow-phantom-refs -ire  -src-prec apk -process-dir C:\test\SootShow.apk

and i get the error:
Exception in thread "main" java.lang.RuntimeException: no apk file given
        at soot.Scene.defaultClassPath(Scene.java:472)
        at soot.Scene.getSootClassPath(Scene.java:226)
        at soot.SootResolver.<init>(SootResolver.java:81)
        at soot.Singletons.soot_SootResolver(Singletons.java:802)
        at soot.SootResolver.v(SootResolver.java:91)
        at soot.Scene.tryLoadClass(Scene.java:638)
        at soot.Scene.loadBasicClasses(Scene.java:1210)
        at soot.Scene.loadNecessaryClasses(Scene.java:1289)
        at soot.Main.run(Main.java:173)
        at soot.Main.main(Main.java:146)
        at soot.tools.CFGViewer.main(CFGViewer.java:101)

look forward to  answer,thx!!!

**Comment by StevenArzt** [comment]
There was actually an issue in the CFG Viewer that made things fail on Windows. I fixed that a couple of weeks ago.
