### ISSUE TITLE
dexpler transformation issue

### ISSUE THREAD

**Issue by flankerhqd** [Sable/soot#316]
Test sample apks:

http://box.myqsc.com/-46934968

Trace:

```
soot.jimple.toolkits.typing.integer.InternalTypingException was thrown.
Unexpected type null
	at soot.jimple.toolkits.typing.integer.ClassHierarchy.typeNode(ClassHierarchy.java:179)
	at soot.jimple.toolkits.typing.integer.TypeResolver.typeVariable(TypeResolver.java:109)
	at soot.jimple.toolkits.typing.integer.ConstraintCollector.caseAssignStmt(ConstraintCollector.java:167)
	at soot.jimple.internal.JAssignStmt.apply(JAssignStmt.java:238)
	at soot.jimple.toolkits.typing.integer.ConstraintCollector.collect(ConstraintCollector.java:107)
	at soot.jimple.toolkits.typing.integer.TypeResolver.collect_constraints_1(TypeResolver.java:227)
	at soot.jimple.toolkits.typing.integer.TypeResolver.resolve_step_1(TypeResolver.java:180)
	at soot.jimple.toolkits.typing.integer.TypeResolver.resolve(TypeResolver.java:140)
	at soot.jimple.toolkits.typing.fast.TypeResolver.inferTypes(TypeResolver.java:185)
	at soot.jimple.toolkits.typing.TypeAssigner.internalTransform(TypeAssigner.java:132)
	at soot.BodyTransformer.transform(BodyTransformer.java:52)
	at soot.BodyTransformer.transform(BodyTransformer.java:59)
	at soot.BodyTransformer.transform(BodyTransformer.java:64)
	at soot.dexpler.DexBody.jimplify(DexBody.java:542)
	at soot.dexpler.DexMethod$1.getBody(DexMethod.java:142)
	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:326)
	at soot.PackManager.retrieveAllBodies(PackManager.java:1140)
	at soot.PackManager.runPacksNormally(PackManager.java:458)
	at soot.PackManager.runPacks(PackManager.java:391)
```

**Comment by StevenArzt** [comment]
Apparently, the code in the APK is broken. In smali, we have:

```
    const/4 v1, 0x2
    const/4 v8, 0x0
    aget-byte v4, v8, v1
```

This means that someone tries to get a value from a null array. Of course, Soot should not fail on such code and I'll have a look at what we can do here, but the original APK will definitely always throw a NullPointerException whenever this code is invoked.

**Comment by flankerhqd** [comment]
fix verified, thanks!
