### ISSUE TITLE
java.lang.IllegalArgumentException when ...

### ISSUE THREAD

**Issue by MarcMil** [Sable/soot#331]
Steps to reproduce:
Run soot on the apk file

Files used to reproduce: 
SMSend_APK_Protect.apk md5: 67235b16bc2fab6836847ea51703e298

Soot version: trunk

Command line:
-src-prec apk --allow-phantom-refs -output-format jimple -force-android-jar /home/marc/adt-bundle-linux-x86_64-20140702/sdk/platforms/android-16/ --process-dir /home/marc/Apps/sample_share/SMSend_APK_Protect.apk

Max Memory:
3559MB

Stack trace:
java.lang.IllegalArgumentException: Opcode: INVOKE_SUPER_QUICK @ 0x26
	at soot.dexpler.instructions.InstructionFactory.fromOpcode(InstructionFactory.java:370)
	at soot.dexpler.instructions.InstructionFactory.fromInstruction(InstructionFactory.java:44)
	at soot.dexpler.DexBody.<init>(DexBody.java:183)
	at soot.dexpler.DexMethod.makeSootMethod(DexMethod.java:140)
	at soot.dexpler.DexClass.makeSootClass(DexClass.java:142)
	at soot.dexpler.DexlibWrapper.makeSootClass(DexlibWrapper.java:137)
	at soot.dexpler.DexResolver.resolveFromFile(DexResolver.java:60)
	at soot.DexClassSource.resolve(DexClassSource.java:52)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:230)
	at soot.SootResolver.bringToSignatures(SootResolver.java:255)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:169)
	at soot.SootResolver.resolveClass(SootResolver.java:130)
	at soot.dexpler.DexlibWrapper.initialize(DexlibWrapper.java:121)
	at soot.dexpler.DexResolver.resolveFromFile(DexResolver.java:57)
	at soot.DexClassSource.resolve(DexClassSource.java:52)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:230)
	at soot.SootResolver.bringToSignatures(SootResolver.java:255)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:169)
	at soot.SootResolver.resolveClass(SootResolver.java:130)
	at soot.Scene.loadClass(Scene.java:693)
	at soot.Scene.loadClassAndSupport(Scene.java:678)
	at soot.Scene.loadNecessaryClasses(Scene.java:1352)
	at soot.Main.run(Main.java:214)
	at soot.Main.main(Main.java:152)

**Comment by StevenArzt** [comment]
I think there are two issues here. Firstly, we do not support all of the odex opcodes. This is something we should implement in Soot. Secondly, apkprotect messes around with the APK file, so even if we add this opcode, there's probably more. I'll see what I can do about the opcode, but I don't think it will be sufficient to make this APK work.

**Comment by StevenArzt** [comment]
Problem with these odex instructions: They are of the format "call method with vtable entry X on register y". To get the target method, we need types. The code is however not typed till much later. This needs more attention at some point.
