### ISSUE TITLE
About soot solutions on Android Apk exceptions

### ISSUE THREAD

**Issue by WangYeOtw** [Sable/soot#349]
The command like this:

java -Xss50m -Xmx2g -cp .\soot.jar;.\AXMLPrinter2.jar;.\;baksmail.jar soot.Main -android-jars E:\soot-test\android-sdk -allow-phantom-refs  -f jimple -src-prec apk -ire -process-dir E:\soot-test\mamaquan.apk

mamaquan.apk can download from : http://imgs.mama.cn/android/mamaquan.apk

And i got this exceptions  :

org.jf.dexlib2.dexbacked.DexBackedDexFile$InvalidItemIndex: Field index out of b
ounds: 40467
        at org.jf.dexlib2.dexbacked.DexBackedDexFile.getFieldIdItemOffset(DexBac
kedDexFile.java:180)
        at org.jf.dexlib2.dexbacked.reference.DexBackedFieldReference.<init>(Dex
BackedFieldReference.java:46)
        at org.jf.dexlib2.dexbacked.reference.DexBackedReference.makeReference(D
exBackedReference.java:51)
        at org.jf.dexlib2.dexbacked.instruction.DexBackedInstruction22c.getRefer
ence(DexBackedInstruction22c.java:63)
        at soot.dexpler.instructions.FieldInstruction.introducedTypes(FieldInstr
uction.java:153)
        at soot.dexpler.DexBody.usedTypes(DexBody.java:218)
        at soot.dexpler.DexMethod.makeSootMethod(DexMethod.java:142)
        at soot.dexpler.DexClass.makeSootClass(DexClass.java:142)
        at soot.dexpler.DexlibWrapper.makeSootClass(DexlibWrapper.java:137)
        at soot.dexpler.DexResolver.resolveFromFile(DexResolver.java:60)
        at soot.DexClassSource.resolve(DexClassSource.java:52)
        at soot.SootResolver.bringToHierarchy(SootResolver.java:230)
        at soot.SootResolver.bringToSignatures(SootResolver.java:255)
        at soot.SootResolver.processResolveWorklist(SootResolver.java:169)
        at soot.SootResolver.resolveClass(SootResolver.java:130)
        at soot.dexpler.DexlibWrapper.initialize(DexlibWrapper.java:121)
        at soot.dexpler.DexResolver.resolveFromFile(DexResolver.java:57)
        at soot.DexClassSource.resolve(DexClassSource.java:52)
        at soot.SootResolver.bringToHierarchy(SootResolver.java:230)
        at soot.SootResolver.bringToSignatures(SootResolver.java:255)
        at soot.SootResolver.processResolveWorklist(SootResolver.java:169)
        at soot.SootResolver.resolveClass(SootResolver.java:130)
        at soot.Scene.loadClass(Scene.java:693)
        at soot.Scene.loadClassAndSupport(Scene.java:678)
        at soot.Scene.loadNecessaryClasses(Scene.java:1352)
        at soot.Main.run(Main.java:214)
        at soot.Main.main(Main.java:152)

It seems  soot found some error which hiding in  mamaquan.apk , which led soot to crash and exit.
However, I think , while  we catch this exception, print it, continue to execute ,that maybe better?
Why soot doesn't do like this?

The same command, with other APK :
http://gdown.baidu.com/data/wisegame/ce1553c55d8628b9/WiFibanlv_283.apk

got the below exception:

java.lang.ArrayIndexOutOfBoundsException: 0
       at org.jf.dexlib2.dexbacked.util.DebugInfo$DebugInfoImpl$3.readNextItem(
ebugInfo.java:181)
       at org.jf.dexlib2.dexbacked.util.DebugInfo$DebugInfoImpl$3.readNextItem(
ebugInfo.java:153)
       at org.jf.dexlib2.dexbacked.util.VariableSizeLookaheadIterator.computeNe
t(VariableSizeLookaheadIterator.java:60)
       at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractI
erator.java:143)
       at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.j
va:138)
       at soot.dexpler.DexBody.<init>(DexBody.java:195)
       at soot.dexpler.DexMethod.makeSootMethod(DexMethod.java:140)
       at soot.dexpler.DexClass.makeSootClass(DexClass.java:135)
       at soot.dexpler.DexlibWrapper.makeSootClass(DexlibWrapper.java:137)
       at soot.dexpler.DexResolver.resolveFromFile(DexResolver.java:60)
       at soot.DexClassSource.resolve(DexClassSource.java:52)
       at soot.SootResolver.bringToHierarchy(SootResolver.java:230)
       at soot.SootResolver.bringToSignatures(SootResolver.java:255)
       at soot.SootResolver.processResolveWorklist(SootResolver.java:169)
       at soot.SootResolver.resolveClass(SootResolver.java:130)
       at soot.dexpler.DexlibWrapper.initialize(DexlibWrapper.java:121)
       at soot.dexpler.DexResolver.resolveFromFile(DexResolver.java:57)
       at soot.DexClassSource.resolve(DexClassSource.java:52)
       at soot.SootResolver.bringToHierarchy(SootResolver.java:230)
       at soot.SootResolver.bringToSignatures(SootResolver.java:255)
       at soot.SootResolver.processResolveWorklist(SootResolver.java:169)
       at soot.SootResolver.resolveClass(SootResolver.java:130)
       at soot.Scene.loadClass(Scene.java:693)
       at soot.Scene.loadClassAndSupport(Scene.java:678)
       at soot.Scene.loadNecessaryClasses(Scene.java:1352)
       at soot.Main.run(Main.java:214)
       at soot.Main.main(Main.java:152)

**Comment by StevenArzt** [comment]
This application has been transformed by APKProtect, This means that the code is broken - what you have is a loader that calls native code which "fixes" the APK before the code is actually executed. We do not support such kinds of obfuscations and "protections" yet. Soot tries to analyze the code as it is and fails because the code is broken. What you can do is manually de-obfuscte the app and then run it through Soot.
