### ISSUE TITLE
Better error message

### ISSUE THREAD

**Issue by ericbodden** [Sable/soot#353]
We should have a better error message for the following issue mentioned on the mailing list.

=============

I forgot add tmpRef to locals ... 

body.getLocals().add(tmpRef);

It solve problem! :) 

2015-02-02 2:00 GMT+03:00 Roman Petriev <vvpiroman@gmail.com>:
No one of parameters is null ... 
Stack trace:
java.lang.NullPointerException
        at soot.AbstractValueBox.setValue(AbstractValueBox.java:43)
        at soot.Body.importBodyContentsFrom(Body.java:225)
        at soot.jimple.JimpleBody.clone(JimpleBody.java:90)
        at soot.PackManager.convertJimpleBodyToBaf(PackManager.java:967)
        at soot.PackManager.runBodyPacks(PackManager.java:929)
        at soot.PackManager.runBodyPacks(PackManager.java:606)
        at soot.PackManager.runBodyPacks(PackManager.java:507)
        at soot.PackManager.runPacksNormally(PackManager.java:484)
        at soot.PackManager.runPacks(PackManager.java:391)
        at soot.Main.run(Main.java:244)
        at soot.Main.main(Main.java:152)
        at soot.jbco.Main.main(Main.java:274)

2015-02-02 1:09 GMT+03:00 Bodden, Eric <eric.bodden@sit.fraunhofer.de>:
Hmmm, I can't see anything immediately wrong, but...

> Actually Result:
> java.lang.NullPointerException at line in my transformation:
> units.insertAfter(Jimple.v().newInvokeStmt(Jimple.v().newVirtualInvokeExpr(tmpRef, toCall.makeRef(), intLocal)), as3);

... at this line of yours, which pointer exactly is null? Did you check with a debugger?

Cheers,
Eric

**Comment by ericbodden** [comment]
Fixed in df80cdf
