### ISSUE TITLE
java.lang.ClassCastException: soot.jimple.NullConstant cannot be cast to soot.Local

### ISSUE THREAD

**Issue by WangYeOtw** [Sable/soot#360]
While use  the latest Soot from https://ssebuild.cased.de/nightly/soot/lib/  to analysis Android APP : http://www.tebon.com.cn/download/sjzq/_1346634760905_dbzq1.apk

Got error like this:
        java.lang.ClassCastException: soot.jimple.NullConstant cannot be cast to soot.Local

	at soot.dexpler.DexNullArrayRefTransformer.internalTransform(DexNullArrayRefTransformer.java:101)

	at soot.BodyTransformer.transform(BodyTransformer.java:51)

	at soot.BodyTransformer.transform(BodyTransformer.java:58)

	at soot.BodyTransformer.transform(BodyTransformer.java:63)

	at soot.dexpler.DexBody.jimplify(DexBody.java:531)

	at soot.dexpler.DexMethod$1.getBody(DexMethod.java:150)

	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)

	at soot.SootMethod.retrieveActiveBody(SootMethod.java:324)

	at soot.PackManager.retrieveAllBodies(PackManager.java:1140)

	at soot.PackManager.runPacksNormally(PackManager.java:458)

	at soot.PackManager.runPacks(PackManager.java:391)

	at soot.Main.run(Main.java:244)

	at soot.Main.main(Main.java:152)

***************************************************************************************************

And i found the same error (https://github.com/Sable/soot/issues/201) with Google Maps
But here , soot is the latest version, the error still exists.

**Comment by StevenArzt** [comment]
The download link doesn't seem to work. Please send the APK file via e-mail to Steven.Arzt@cased.de

**Comment by WangYeOtw** [comment]
@StevenArzt , have sent the apk file from sherryduan5651@gmail.com  to your mail box.

**Comment by 2048li** [comment]
Hi, I still have the same problem after you fixed:

Exception in thread "main" java.lang.ClassCastException: soot.jimple.NullConstant cannot be cast to soot.Local
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder$DefaultReflectionModel.classForName(OnFlyCallGraphBuilder.java:101)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.getImplicitTargets(OnFlyCallGraphBuilder.java:620)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processNewMethod(OnFlyCallGraphBuilder.java:532)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processReachables(OnFlyCallGraphBuilder.java:420)
	at soot.jimple.toolkits.callgraph.CallGraphBuilder.build(CallGraphBuilder.java:96)
	at soot.jimple.toolkits.callgraph.CHATransformer.internalTransform(CHATransformer.java:46)
	at soot.SceneTransformer.transform(SceneTransformer.java:39)
	at soot.Transform.apply(Transform.java:90)
	at soot.RadioScenePack.internalApply(RadioScenePack.java:57)
	at soot.jimple.toolkits.callgraph.CallGraphPack.internalApply(CallGraphPack.java:49)
	at soot.Pack.apply(Pack.java:118)
	at soot.PackManager.runWholeProgramPacks(PackManager.java:570)
	at soot.PackManager.runPacksNormally(PackManager.java:461)
	at soot.PackManager.runPacks(PackManager.java:396)
	at com.shentanli.example.soot.sootMain.main(sootMain.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

The APK I used can be downloaded from here: https://pan.baidu.com/s/1kUQneR1.
