### ISSUE TITLE
java.lang.RuntimeException: Attempt to create VarNode of type long when trying to analysis apk

### ISSUE THREAD

**Issue by edwardsukhoi** [Sable/soot#365]
Hi:

I used the nightly build version to run the sample apk, however exceptions occured.

Command line: 

```
java -cp soot-trunk.jar:soot-infoflow.jar:soot-infoflow-android.jar:slf4j-api-1.7.5.jar:slf4j-simple-1.7.5.jar:axml-2.0.jar soot.jimple.infoflow.android.TestApps.Test /home/test/com.twitter.android.apk  /home/test/android-sdk-linux/platforms/ --nocallbacks --layoutmode none
```

Crash trace:

```
[Call Graph] For information on where the call graph may be incomplete, use the verbose option to the cg phase.
[Spark] Pointer Assignment Graph in 1.2 seconds.
[Spark] Type masks in 0.1 seconds.
[Spark] Pointer Graph simplified in 0.0 seconds.
Exception in thread "main" java.lang.RuntimeException: Attempt to create VarNode of type long
	at soot.jimple.spark.pag.VarNode.<init>(VarNode.java:106)
	at soot.jimple.spark.pag.LocalVarNode.<init>(LocalVarNode.java:44)
	at soot.jimple.spark.pag.PAG.makeLocalVarNode(PAG.java:552)
	at soot.jimple.spark.builder.MethodNodeFactory.caseLocal(MethodNodeFactory.java:219)
	at soot.jimple.internal.JimpleLocal.apply(JimpleLocal.java:136)
	at soot.jimple.spark.builder.MethodNodeFactory.caseCastExpr(MethodNodeFactory.java:190)
	at soot.jimple.internal.AbstractCastExpr.apply(AbstractCastExpr.java:134)
	at soot.jimple.spark.builder.MethodNodeFactory$1.caseAssignStmt(MethodNodeFactory.java:78)
	at soot.jimple.internal.JAssignStmt.apply(JAssignStmt.java:238)
	at soot.jimple.spark.builder.MethodNodeFactory.handleStmt(MethodNodeFactory.java:69)
	at soot.jimple.spark.pag.MethodPAG.buildNormal(MethodPAG.java:179)
	at soot.jimple.spark.pag.MethodPAG.build(MethodPAG.java:148)
	at soot.jimple.spark.solver.OnFlyCallGraph.processReachables(OnFlyCallGraph.java:64)
	at soot.jimple.spark.solver.OnFlyCallGraph.build(OnFlyCallGraph.java:56)
	at soot.jimple.spark.solver.PropWorklist.handleVarNode(PropWorklist.java:122)
	at soot.jimple.spark.solver.PropWorklist.propagate(PropWorklist.java:52)
	at soot.jimple.spark.SparkTransformer.internalTransform(SparkTransformer.java:152)
	at soot.SceneTransformer.transform(SceneTransformer.java:39)
	at soot.Transform.apply(Transform.java:90)
	at soot.RadioScenePack.internalApply(RadioScenePack.java:57)
	at soot.jimple.toolkits.callgraph.CallGraphPack.internalApply(CallGraphPack.java:49)
	at soot.Pack.apply(Pack.java:116)
	at soot.jimple.infoflow.Infoflow.runAnalysis(Infoflow.java:555)
	at soot.jimple.infoflow.Infoflow.computeInfoflow(Infoflow.java:322)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(Unknown Source)
	at soot.jimple.infoflow.android.TestApps.Test.runAnalysis(Unknown Source)
	at soot.jimple.infoflow.android.TestApps.Test.main(Unknown Source)
```

sample apk:

http://box.myqsc.com/-43857373

Thanks!

**Comment by Alexandre-Bartel** [comment]
I can't access the apk. Could you send it to me directly?
Is this still an issue with the latest version?
