### ISSUE TITLE
'Warning - Syntax error' -> 'Error - Couldn't repair and continue parse' and 'JAS Error Badly formatted number' errors

### ISSUE THREAD

**Issue by lostdj** [Sable/soot#367]
```
java -cp soot-trunk.jar soot.Main -include-all -cp myjdk.jar:myfx:myfx-graphics:myfx-controls -O -p wjtp on -p wjop on -process-dir myfx-graphics -d myfx-graphics-soot

...

riting to myfx-graphics-soot/javafx/scene/Node.class
Jasmin:105: JAS Error Badly formatted number.

^
jas.jasError: Badly formatted number
        at jasmin.Scanner.tryParseAsNumber(Scanner.java:383)
        at jasmin.Scanner.next_token(Scanner.java:308)
        at jasmin.parser.scan(parser.java:660)
        at java_cup.runtime.lr_parser.parse(lr_parser.java:563)
        at jasmin.ClassFile.readJasmin(ClassFile.java:1215)
        at jasmin.Main.assemble(Main.java:31)
        at soot.util.JasminOutputStream.flush(JasminOutputStream.java:35)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at java.io.PrintWriter.flush(PrintWriter.java:320)
        at soot.PackManager.writeClass(PackManager.java:1071)
        at soot.PackManager.writeOutput(PackManager.java:617)
        at soot.PackManager.writeOutput(PackManager.java:526)
        at soot.Main.run(Main.java:246)
        at soot.Main.main(Main.java:152)
Jasmin: Found 1 errors
Writing to myfx-graphics-soot/javafx/scene/AccessibleRole.class

...

Writing to myfx-graphics-soot/javafx/animation/RotateTransition.class
Jasmin:35: Warning - Syntax error.

^
Jasmin:35: Error - Couldn't repair and continue parse.

^
Jasmin: Found 2 errors
Writing to myfx-graphics-soot/javafx/animation/ScaleTransition$1.class
Writing to myfx-graphics-soot/javafx/animation/ScaleTransition.class
Jasmin:38: Warning - Syntax error.

^
Jasmin:38: Error - Couldn't repair and continue parse.

^
Jasmin: Found 2 errors
Writing to myfx-graphics-soot/javafx/animation/ParallelTransition$1.class
```

The classes I'm trying to transform were preprocessed with Retrolambda before that. The JDK was not.

The whole offending pack: https://www.dropbox.com/s/i3pi4fqh9llwcw9/myfx.zip?dl=0

**Comment by StevenArzt** [comment]
I cannot reproduce the issue. Firstly, I needed to add -allow-phantom-refs to your command-line, as Soot would otherwise complain about missing JDK classes since the JDK is not on your Soot classpath. With this change, Soot runs just fine.

To help reproduce the problem, I extended Jasmin to print out the offending number if such an error occurs.

**Comment by lostdj** [comment]
But it is in CP, `myjdk.jar` is a OpenJDK 9 build.

**Comment by StevenArzt** [comment]
OK, I found the issue now.

**Comment by lostdj** [comment]
Sorry, I was waiting for a nightly.

It works now. Thanks!
