### ISSUE TITLE
NoSuchMethodError: soot.toolkits.scalar.BoundedFlowSet.topSet

### ISSUE THREAD

**Issue by lostdj** [Sable/soot#370]
Using the same classes from #367 and with all `-p jop.*` options turned on:
```
Transforming javafx.concurrent.Task$$Lambda$1... 
Exception in thread "main" java.lang.NoSuchMethodError: soot.toolkits.scalar.BoundedFlowSet.topSet()Ljava/lang/Object;
        at soot.jimple.toolkits.scalar.pre.UpSafetyAnalysis.newInitialFlow(UpSafetyAnalysis.java:93)
        at soot.toolkits.scalar.ForwardFlowAnalysis.doAnalysis(ForwardFlowAnalysis.java:71)
        at soot.jimple.toolkits.scalar.pre.UpSafetyAnalysis.<init>(UpSafetyAnalysis.java:89)
        at soot.jimple.toolkits.scalar.pre.UpSafetyAnalysis.<init>(UpSafetyAnalysis.java:67)
        at soot.jimple.toolkits.scalar.pre.BusyCodeMotion.internalTransform(BusyCodeMotion.java:105)
        at soot.BodyTransformer.transform(BodyTransformer.java:51)
        at soot.Transform.apply(Transform.java:105)
        at soot.BodyPack.internalApply(BodyPack.java:49)
        at soot.Pack.apply(Pack.java:126)
        at soot.PackManager.runBodyPacks(PackManager.java:915)
        at soot.PackManager.runBodyPacks(PackManager.java:606)
        at soot.PackManager.runBodyPacks(PackManager.java:507)
        at soot.PackManager.runPacksNormally(PackManager.java:484)
        at soot.PackManager.runPacks(PackManager.java:391)
        at soot.Main.run(Main.java:244)
        at soot.Main.main(Main.java:152)
```

**Comment by StevenArzt** [comment]
Are you using the nightly build or have you compiled Soot on your own?

**Comment by lostdj** [comment]
I'm using the latest nightly.

**Comment by StevenArzt** [comment]
That is weird. I have double-checked the classes in the nightly build with JD GUI and both the class and the method are there.

**Comment by lostdj** [comment]
Well, it can throw the same exception on a method attributes mismatch.

**Comment by StevenArzt** [comment]
I just ran the last Soot nightly build with the following command-line and it worked:

```
java -ea -Xmx150g -cp ../soot-trunk.jar soot.Main -cp myjdk.jar:myfx:myfx-graphics:myfx-controls -O -p jop enabled:true -process-dir myfx-graphics -d myfx-graphics-soot
```

Is there any difference to your command line?

**Comment by lostdj** [comment]
There is: `-p jop on -p jop.cse on -p jop.bcm on -p jop.lcm on -p jop.cp on -p jop.cpf on -p jop.cbf on -p jop.dae on -p jop.nce on -p jop.uce1 on -p jop.ubf1 on -p jop.uce2 on -p jop.ubf2 on -p jop.ule on`.

**Comment by StevenArzt** [comment]
OK, I now found some issues  - not the one you reported, but some others that occurred when I ran the command-line you posted. Soot produced invalid Jimple code and then failed on it during the validation step. That should be fixed now. A new nightly build is already available (I triggered the build manually). Please try again if your issue is now solved as well.

**Comment by lostdj** [comment]
All perfect now, thanks!

**Comment by lostdj** [comment]
Can I also ask a stupid question?

What would be the fullest set of optimization options beside those I'm using above? I see there's `-p sop`, for example, but suppose it doesn't make sense to turn it on with all `jop` opts, since `sop.cpf` does the same job as `jop.cpf`?

**Comment by StevenArzt** [comment]
The sop pack is the Shimple optimization pack while the jop pack is the Jimple optimization pack. Which pack you should enable depends on the intermediate representation you want to use. Normally, that's Jimple unless you need an SSA form. You can read up on Shimple here: https://github.com/Sable/soot/wiki/A-brief-overview-of-Shimple

**Comment by lostdj** [comment]
Yes, but does it make sense to turn both of them on in one command line, or they require separate runs?

**Comment by StevenArzt** [comment]
If you're not even using Shimple, there is no need to turn on the Shimple optimizations at all. Unless your output format is set to shimple, the sop.* packs will never run anyway, even if you enable them, because they are lacking the required Shimple bodies.

**Comment by lostdj** [comment]
I don't. Both input and ouput are .class files.

Thanks again.
