### ISSUE TITLE
several exceptions when processing recent JDK

### ISSUE THREAD

**Issue by ericbodden** [Sable/soot#388]
Steps to reproduce:
use command line below

Files used to reproduce: 
JDK 8

Soot version: trunk

Command line:
-allow-phantom-refs -include-all -d /tmp -process-dir /Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home/jre/lib/rt.jar -cp /Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home/jre/lib/jsse.jar

Max Memory:
7918MB

Among the following exception there are several JASMIN parsing errors.

Stack trace:
java.lang.RuntimeException: invalid fromType java.time.format.DateTimeParseContext
	at soot.baf.internal.BPrimitiveCastInst$1.defaultCase(BPrimitiveCastInst.java:96)
	at soot.TypeSwitch.caseRefType(TypeSwitch.java:76)
	at soot.RefType.apply(RefType.java:156)
	at soot.baf.internal.BPrimitiveCastInst.getName(BPrimitiveCastInst.java:92)
	at soot.baf.internal.BPrimitiveCastInst.toString(BPrimitiveCastInst.java:193)
	at soot.baf.JasminClass$1.casePrimitiveCastInst(JasminClass.java:1446)
	at soot.baf.internal.BPrimitiveCastInst.apply(BPrimitiveCastInst.java:199)
	at soot.baf.JasminClass.emitInst(JasminClass.java:331)
	at soot.baf.JasminClass.emitMethodBody(JasminClass.java:269)
	at soot.AbstractJasminClass.emitMethod(AbstractJasminClass.java:769)
	at soot.AbstractJasminClass.<init>(AbstractJasminClass.java:648)
	at soot.baf.JasminClass.<init>(JasminClass.java:95)
	at soot.PackManager.writeClass(PackManager.java:1038)
	at soot.PackManager.writeOutput(PackManager.java:619)
	at soot.PackManager.writeOutput(PackManager.java:528)
	at soot.Main.run(Main.java:246)
	at soot.Main.main(Main.java:152)

**Comment by anddann** [comment]
At least we support Java 8,9,11 Bytecode now.
