### ISSUE TITLE
java.lang.RuntimeException when ...

### ISSUE THREAD

**Issue by ochipara** [Sable/soot#389]
Steps to reproduce:
Run the IFDSReachingDefinitions reaching definition example.

Files used to reproduce: 

Soot version: trunk

Command line:
-w -cp /Users/ochipara/tmp/workspace/SootTest/bin:/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre/lib/jce.jar -main-class TestFor TestFor

Max Memory:
3641MB

Stack trace:
java.lang.RuntimeException: There were exceptions during IDE analysis. Exiting.
	at heros.solver.IDESolver.runExecutorAndAwaitCompletion(IDESolver.java:264)
	at heros.solver.IDESolver.awaitCompletionComputeValuesAndShutdown(IDESolver.java:233)
	at heros.solver.IDESolver.solve(IDESolver.java:207)
	at soot.jimple.toolkits.ide.JimpleIFDSSolver.solve(JimpleIFDSSolver.java:54)
	at ReachingDefinitions$1.internalTransform(ReachingDefinitions.java:41)
	at soot.SceneTransformer.transform(SceneTransformer.java:39)
	at soot.Transform.apply(Transform.java:90)
	at soot.ScenePack.internalApply(ScenePack.java:40)
	at soot.Pack.apply(Pack.java:116)
	at soot.PackManager.runWholeProgramPacks(PackManager.java:564)
	at soot.PackManager.runPacksNormally(PackManager.java:456)
	at soot.PackManager.runPacks(PackManager.java:391)
	at soot.Main.run(Main.java:244)
	at soot.Main.main(Main.java:152)
	at ReachingDefinitions.main(ReachingDefinitions.java:49)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at java.util.Collections$UnmodifiableList.get(Collections.java:1211)
	at soot.SootMethod.getParameterType(SootMethod.java:266)
	at soot.jimple.toolkits.ide.exampleproblems.IFDSReachingDefinitions$1$2.computeTargets(IFDSReachingDefinitions.java:111)
	at soot.jimple.toolkits.ide.exampleproblems.IFDSReachingDefinitions$1$2.computeTargets(IFDSReachingDefinitions.java:1)
	at heros.ZeroedFlowFunctions$ZeroedFlowFunction.computeTargets(ZeroedFlowFunctions.java:58)
	at heros.solver.IDESolver.computeCallFlowFunction(IDESolver.java:397)
	at heros.solver.IDESolver.processCall(IDESolver.java:330)
	at heros.solver.IDESolver.access$0(IDESolver.java:313)
	at heros.solver.IDESolver$PathEdgeProcessingTask.run(IDESolver.java:856)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

**Comment by ericbodden** [comment]
This is a problem w.r.t. some call site calling <sun.security.action.GetPropertyAction: java.lang.Object run()>. There is an inconsistency in the number of call arguments.

**Comment by StevenArzt** [comment]
The IFDS example analyses do not treat special call edges such as Thread.run() properly. This just hasn't been implement yet as it's not productive code, but rather a small example. We should still extend it at some point.

**Comment by ochipara** [comment]
Dear Steven,

I would assume that the reason for having example is to help novices like me get started and provide best-pratices in how to use heros/IFDS. If you run an example and it crashes on the simplest program, then there is some loss of confidence in the framework. So, just to thrown in my two cents, I would suggest that having a complete example would be quite useful.

Thanks,
— Octav





On Apr 13, 2015, at 10:13 AM, Steven Arzt <notifications@github.com<mailto:notifications@github.com>> wrote:


The IFDS example analyses do not treat special call edges such as Thread.run() properly. This just hasn't been implement yet as it's not productive code, but rather a small example. We should still extend it at some point.

**Comment by StevenArzt** [comment]
I agree, we should get this sorted out at some point. If you are looking for a complete example that treats all known special edge types properly, you can look at the FlowDroid implementation. This code is rather complex, though. That's the main problem with going beyond a minimal example: Suddenly, it's a lot of stuff here and there that you need and the main concepts get lost in all the details.

**Comment by pavanupb** [comment]
@ochipara Is this still relevant?
