### ISSUE TITLE
Soot throw out  java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by WangYeOtw** [Sable/soot#390]
the apk without protect,and you can download from:
https://drive.google.com/file/d/0B_Vmb8dYf9cGaGxXZFU1cG82WFU/view?usp=sharing

Exception info:
java.lang.ArrayIndexOutOfBoundsException: 7
        at soot.dexpler.DexBody.getRegisterLocal(DexBody.java:304)
        at soot.dexpler.instructions.Binop2addrInstruction.jimplify(Binop2addrIn
struction.java:63)
        at soot.dexpler.DexBody.jimplify(DexBody.java:430)
        at soot.dexpler.DexMethod$1.getBody(DexMethod.java:150)
        at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
        at soot.SootMethod.retrieveActiveBody(SootMethod.java:324)
        at soot.PackManager.retrieveAllBodies(PackManager.java:1140)
        at soot.PackManager.runPacksNormally(PackManager.java:458)
        at soot.PackManager.runPacks(PackManager.java:391)
        at soot.Main.run(Main.java:244)
        at soot.Main.main(Main.java:152)

**Comment by StevenArzt** [comment]
This APK is broken as well. In method ```<a.a.a: java.lang.String bc()>``` we have the following smali code:

```
# virtual methods
.method public bc()Ljava/lang/String;
    .registers 7

    .prologue
    .line 5
    #unknown opcode: 0xff
    nop

    add-double/2addr v2, p1

    nop
```

This method does not take any parameters, but accesses the first one of them. Additionally, we also have an invalid opcode. Are you sure that no obfuscator or protector has been run on this APK file?

**Comment by WangYeOtw** [comment]
The apk has obfuscator , no protector . I guess the app add some not reachable methods with invalid opcodes and malformed instructions to defend it from static analysis .

**Comment by flankerhqd** [comment]
You can just nop-out the method using setPhantom to tell soot ignore this meaningless method.
