### ISSUE TITLE
Soot throw out  java.lang.ClassCastException

### ISSUE THREAD

**Issue by WangYeOtw** [Sable/soot#391]
APk without protect, and you can download the apk from :
https://drive.google.com/file/d/0B_Vmb8dYf9cGbXlsWlFRdElXWGc/view?usp=sharing

java.lang.ClassCastException: soot.ByteType cannot be cast to soot.ArrayType
        at soot.dexpler.instructions.FilledNewArrayInstruction.jimplify(FilledNe
wArrayInstruction.java:72)
        at soot.dexpler.DexBody.jimplify(DexBody.java:430)
        at soot.dexpler.DexMethod$1.getBody(DexMethod.java:150)
        at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
        at soot.SootMethod.retrieveActiveBody(SootMethod.java:324)
        at soot.PackManager.retrieveAllBodies(PackManager.java:1140)
        at soot.PackManager.runPacksNormally(PackManager.java:458)
        at soot.PackManager.runPacks(PackManager.java:391)
        at soot.Main.run(Main.java:244)
        at soot.Main.main(Main.java:152)

**Comment by StevenArzt** [comment]
The code looks invalid even in smali (method <a.a.a: java.lang.String bc()>):

```
.method public bc()Ljava/lang/String;
    .registers 7

    .prologue
    .line 5
    #unknown opcode: 0xff
    nop

    filled-new-array {}, B
```

We have an unknown opcode and a malformed filled-new-array instruction. The type must be an array type according to the Dalvik specification, but here, it's a byte.

**Comment by WangYeOtw** [comment]
Hi  Steven, is there any way to know which class the Soot deal with when it throw out exception ?

**Comment by StevenArzt** [comment]
If you have the source code of Soot, you can run it in a debugger and check which method body it is processing when the exception happens.

**Comment by WangYeOtw** [comment]
I guess the app add some not reachable methods with invalid opcodes and malformed instructions to defend it from static analysis .
