### ISSUE TITLE
BUG in Whole Program Mode: Failed to convert <java.time.chrono.AbstractChronology: void <clinit>()>

### ISSUE THREAD

**Issue by ZenHuang** [Sable/soot#393]
Arguments:
-w -pp -cp .;D:\test\bin; extend.D

Output:

Soot started on Fri Apr 17 19:06:47 CST 2015
No main class given. Inferred 'extend.D' as main class.
[Call Graph] For information on where the call graph may be incomplete, use the verbose option to the cg phase.
java.lang.RuntimeException: Failed to convert <java.time.chrono.AbstractChronology: void <clinit>()>
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:1772)
	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:322)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processNewMethod(OnFlyCallGraphBuilder.java:529)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processReachables(OnFlyCallGraphBuilder.java:420)
	at soot.jimple.toolkits.callgraph.CallGraphBuilder.build(CallGraphBuilder.java:84)
	at soot.jimple.toolkits.callgraph.CHATransformer.internalTransform(CHATransformer.java:43)
	at soot.SceneTransformer.transform(SceneTransformer.java:39)
	at soot.Transform.apply(Transform.java:90)
	at soot.RadioScenePack.internalApply(RadioScenePack.java:57)
	at soot.jimple.toolkits.callgraph.CallGraphPack.internalApply(CallGraphPack.java:49)
	at soot.Pack.apply(Pack.java:116)
	at soot.PackManager.runWholeProgramPacks(PackManager.java:563)
	at soot.PackManager.runPacksNormally(PackManager.java:456)
	at soot.PackManager.runPacks(PackManager.java:391)
	at soot.Main.run(Main.java:243)
	at soot.Main.main(Main.java:152)
	at test.SootTest.main(SootTest.java:26)
Caused by: java.lang.RuntimeException: 
Aborting: can't find classfile java.lang.invoke.LambdaMetafactory
	at soot.Scene.getSootClass(Scene.java:778)
	at soot.asm.AsmMethodSource.toSootMethodRef(AsmMethodSource.java:1310)
	at soot.asm.AsmMethodSource.convertInvokeDynamicInsn(AsmMethodSource.java:1236)
	at soot.asm.AsmMethodSource.convert(AsmMethodSource.java:1605)
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:1770)
	... 17 more

**Comment by StevenArzt** [comment]
Your Soot classpath seems incorrect. There is a blank between the last semicolon and "extend.D". Do you want "extend.D" as another directory on your Soot classpath? Or is this the name of the class you want to use as main class ("D" in package "extend"?). You definitely need an entry point (some sort of main class) if you want to use whole-program mode and get a callgraph unless you want to use all public methods as entry points for CHA.

**Comment by ZenHuang** [comment]
Thank you very much, but it doesn't work :(
I typed the blank on purpose because the class "D" in package "extend" is exactly the class that I wanna load. Class "D" has its main method and the log also shows that Soot have inferred 'extend.D' as main class (Moreover, I just tried to use -main-class option but the result hasn't changed). So I think I have used correct arguments but it just cannot convert that method.
Maybe the reason is that I am using Java 8?

Thanks again. Best wishes.

**Comment by StevenArzt** [comment]
Soot complains that it cannot find the class ```java.lang.invoke.LambdaMetafactory```. This means that the JDK classes are not on your Soot classpath and that you do not allow creating phantom references either. You can either add the JDK (rt.jar) to your classpath or add the "-allow-phantom-refs" option to Soot.

**Comment by StevenArzt** [comment]
I close this issue as the discussion has shifted to #406.
