### ISSUE TITLE
java.lang.ClassCastException when ...

### ISSUE THREAD

**Issue by FourPee** [Sable/soot#396]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: trunk

Command line:
-cp android.jar;maps.jar;src1 -f d -pp -process-dir src1

Max Memory:
3623MB

Stack trace:
java.lang.ClassCastException: soot.dava.internal.SET.SETIfElseNode cannot be cast to soot.dava.internal.SET.SETStatementSequenceNode
    at soot.dava.toolkits.base.finders.AbruptEdgeFinder.find_Breaks(AbruptEdgeFinder.java:78)
    at soot.dava.internal.SET.SETNode.find_AbruptEdges(SETNode.java:270)
    at soot.dava.internal.SET.SETNode.find_AbruptEdges(SETNode.java:249)
    at soot.dava.internal.SET.SETNode.find_AbruptEdges(SETNode.java:249)
    at soot.dava.internal.SET.SETNode.find_AbruptEdges(SETNode.java:249)
    at soot.dava.internal.SET.SETNode.find_AbruptEdges(SETNode.java:249)
    at soot.dava.toolkits.base.finders.AbruptEdgeFinder.find(AbruptEdgeFinder.java:39)
    at soot.dava.DavaBody.<init>(DavaBody.java:333)
    at soot.dava.Dava.newBody(Dava.java:84)
    at soot.PackManager.runBodyPacks(PackManager.java:946)
    at soot.PackManager.runBodyPacks(PackManager.java:608)
    at soot.PackManager.runBodyPacks(PackManager.java:507)
    at soot.PackManager.runPacksNormally(PackManager.java:484)
    at soot.PackManager.runPacks(PackManager.java:391)
    at soot.Main.run(Main.java:243)
    at soot.Main.main(Main.java:152)

**Comment by StevenArzt** [comment]
On which inputs did you run Soot? Please provide all required input files or at least a minimal example that allows us to reproduce the issue. Knowing your exact Soot command line would also help a lot.
