### ISSUE TITLE
java.lang.RuntimeException at soot.AbstractValueBox.setValue(AbstractValueBox.java:44)

### ISSUE THREAD

**Issue by 0-14N** [Sable/soot#409]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: trunk

Command line:
-android-jars /home/chenxiong/Android/Sdk/platforms -process-dir /home/chenxiong/Downloads/anzhi/com.dobi-22.apk -d /home/chenxiong/workspaces/eclipse-luna/CallTracer//com.dobi-22.apk -force-android-jar /home/chenxiong/Android/Sdk/platforms/android-22/android.jar

Max Memory:
7282MB

Stack trace:
java.lang.RuntimeException: Box JimpleLocalBox($u0#6) cannot contain value: null(class soot.jimple.NullConstant)
	at soot.AbstractValueBox.setValue(AbstractValueBox.java:44)
	at soot.jimple.toolkits.scalar.CopyPropagator.internalTransform(CopyPropagator.java:180)
	at soot.BodyTransformer.transform(BodyTransformer.java:51)
	at soot.BodyTransformer.transform(BodyTransformer.java:58)
	at soot.BodyTransformer.transform(BodyTransformer.java:63)
	at soot.dexpler.DexBody.jimplify(DexBody.java:525)
	at soot.dexpler.DexMethod$1.getBody(DexMethod.java:150)
	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:322)
	at soot.PackManager.retrieveAllBodies(PackManager.java:1144)
	at soot.PackManager.runPacksNormally(PackManager.java:458)
	at soot.PackManager.runPacks(PackManager.java:391)
	at soot.Main.run(Main.java:248)
	at soot.Main.main(Main.java:152)
	at com.gtisc.calltracer.CallTracer.main(CallTracer.java:277)

**Comment by Alexandre-Bartel** [comment]
Thank for reporting this. Could you share the apk or send it to me directly?

**Comment by Alexandre-Bartel** [comment]
Fixed with 22ab9c35ad01851c552ffb2d3bd7d986ff96eb64
