### ISSUE TITLE
soot.ResolutionFailedException at soot.AbstractSootFieldRef.checkStatic(AbstractSootFieldRef.java:87)

### ISSUE THREAD

**Issue by 0-14N** [Sable/soot#410]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: trunk

Command line:
-android-jars /home/chenxiong/Android/Sdk/platforms -process-dir /home/chenxiong/Downloads/anzhi/com.lingzhimobile.nutritionfoodguide-20.apk -d /home/chenxiong/workspaces/eclipse-luna/CallTracer/sootOutput/com.lingzhimobile.nutritionfoodguide-20.apk -force-android-jar /home/chenxiong/Android/Sdk/platforms/android-22/android.jar

Max Memory:
7282MB

Stack trace:
soot.ResolutionFailedException: Resolved <com.parse.PushService: com.parse.PushConnection connection> to <com.parse.PushService: com.parse.PushConnection connection> which has wrong static-ness
	at soot.AbstractSootFieldRef.checkStatic(AbstractSootFieldRef.java:87)
	at soot.AbstractSootFieldRef.resolve(AbstractSootFieldRef.java:102)
	at soot.AbstractSootFieldRef.resolve(AbstractSootFieldRef.java:81)
	at soot.jimple.StaticFieldRef.getField(StaticFieldRef.java:74)
	at soot.toDex.StmtVisitor.buildStaticFieldGetInsn(StmtVisitor.java:461)
	at soot.toDex.StmtVisitor.buildGetInsn(StmtVisitor.java:387)
	at soot.toDex.StmtVisitor.caseAssignStmt(StmtVisitor.java:369)
	at soot.jimple.internal.JAssignStmt.apply(JAssignStmt.java:238)
	at soot.toDex.DexPrinter.toInstructions(DexPrinter.java:1152)
	at soot.toDex.DexPrinter.toMethodImplementation(DexPrinter.java:1035)
	at soot.toDex.DexPrinter.toMethods(DexPrinter.java:932)
	at soot.toDex.DexPrinter.addAsClassDefItem(DexPrinter.java:496)
	at soot.toDex.DexPrinter.add(DexPrinter.java:1281)
	at soot.PackManager.writeClass(PackManager.java:997)
	at soot.PackManager.writeOutput(PackManager.java:619)
	at soot.PackManager.writeOutput(PackManager.java:525)
	at soot.Main.run(Main.java:250)
	at soot.Main.main(Main.java:152)
	at com.gtisc.calltracer.CallTracer.main(CallTracer.java:277)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)

**Comment by Alexandre-Bartel** [comment]
Could you share the apk?

**Comment by Alexandre-Bartel** [comment]
Seems like the code wants to get a static field "connection" from class "PushService":
 0935e6: 6201 8209   |004b: sget-object v1, Lcom/parse/PushService;.connection:Lcom/parse/PushConnection;

However, the field is defined as instance field and not static field, hence the problem.
  Class descriptor  : 'Lcom/parse/PushService;'
[...]
  Instance fields   -
    #0              : (in Lcom/parse/PushService;)
      name          : 'connection'
      type          : 'Lcom/parse/PushConnection;'
      access        : 0x0002 (PRIVATE)


This is not a bug in Soot but seems to be broken code in the application.

**Comment by Alexandre-Bartel** [comment]
The Jimple code can now be checked for such buggy code with the -validate option which now has a validator for field references (a3c4872cc8cd48749f18c1abe41356242c8e364a).
