### ISSUE TITLE
java.lang.NullPointerException at soot.dexpler.DexAnnotation.handleClassAnnotation(DexAnnotation.java:157)

### ISSUE THREAD

**Issue by 0-14N** [Sable/soot#411]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: trunk

Command line:
-android-jars /home/chenxiong/Android/Sdk/platforms -process-dir /home/chenxiong/Downloads/anzhi/com.jmi.android.jiemi-16.apk -d /home/chenxiong/workspaces/eclipse-luna/CallTracer/sootOutput/com.jmi.android.jiemi-16.apk -force-android-jar /home/chenxiong/Android/Sdk/platforms/android-22/android.jar

Max Memory:
7282MB

Stack trace:
java.lang.NullPointerException
	at soot.dexpler.DexAnnotation.handleClassAnnotation(DexAnnotation.java:157)
	at soot.dexpler.DexClass.makeSootClass(DexClass.java:151)
	at soot.dexpler.DexlibWrapper.makeSootClass(DexlibWrapper.java:137)
	at soot.dexpler.DexResolver.resolveFromFile(DexResolver.java:60)
	at soot.DexClassSource.resolve(DexClassSource.java:52)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:237)
	at soot.SootResolver.bringToSignatures(SootResolver.java:264)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:168)
	at soot.SootResolver.resolveClass(SootResolver.java:129)
	at soot.dexpler.DexlibWrapper.initialize(DexlibWrapper.java:121)
	at soot.dexpler.DexResolver.resolveFromFile(DexResolver.java:57)
	at soot.DexClassSource.resolve(DexClassSource.java:52)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:237)
	at soot.SootResolver.bringToSignatures(SootResolver.java:264)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:168)
	at soot.SootResolver.resolveClass(SootResolver.java:129)
	at soot.Scene.loadClass(Scene.java:702)
	at soot.Scene.loadClassAndSupport(Scene.java:687)
	at soot.Scene.loadNecessaryClasses(Scene.java:1362)
	at soot.Main.run(Main.java:218)
	at soot.Main.main(Main.java:152)
	at com.gtisc.calltracer.CallTracer.main(CallTracer.java:277)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)

**Comment by Alexandre-Bartel** [comment]
Could you send the apk?

**Comment by Alexandre-Bartel** [comment]
Fixed with 12f7cae403e434e5310e972d390c8e251c53d125
