### ISSUE TITLE
ava.lang.AssertionError 	at soot.dexpler.DexAnnotation.handleAnnotation(DexAnnotation.java:415)

### ISSUE THREAD

**Issue by 0-14N** [Sable/soot#413]
Command: 

java -Xms2G -Xmx8G -ea -jar /home/chenxiong/tools/CallTracer.jar -apk /home/chenxiong/Downloads/anzhi/com.happybluefin.balloon-102.apk -androidJarDir /home/chenxiong/Android/Sdk/platforms -outDir /home/chenxiong/workspaces/eclipse-luna/CallTracer/sootOutput

Exception:

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.AssertionError
	at soot.dexpler.DexAnnotation.handleAnnotation(DexAnnotation.java:415)
	at soot.dexpler.DexAnnotation.handleClassAnnotation(DexAnnotation.java:106)
	at soot.dexpler.DexClass.makeSootClass(DexClass.java:151)
	at soot.dexpler.DexlibWrapper.makeSootClass(DexlibWrapper.java:137)
	at soot.dexpler.DexResolver.resolveFromFile(DexResolver.java:60)
	at soot.DexClassSource.resolve(DexClassSource.java:52)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:237)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:171)
	at soot.SootResolver.resolveClass(SootResolver.java:129)
	at soot.dexpler.DexlibWrapper.initialize(DexlibWrapper.java:121)
	at soot.dexpler.DexResolver.resolveFromFile(DexResolver.java:57)
	at soot.DexClassSource.resolve(DexClassSource.java:52)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:237)
	at soot.SootResolver.bringToSignatures(SootResolver.java:264)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:168)
	at soot.SootResolver.resolveClass(SootResolver.java:129)
	at soot.Scene.loadClass(Scene.java:702)
	at soot.Scene.loadClassAndSupport(Scene.java:687)
	at soot.Scene.loadNecessaryClasses(Scene.java:1362)
	at soot.Main.run(Main.java:218)
	at soot.Main.main(Main.java:152)
	at com.gtisc.calltracer.CallTracer.main(CallTracer.java:277)
	... 5 more

**Comment by Alexandre-Bartel** [comment]
Again, could you send the apk?

**Comment by Alexandre-Bartel** [comment]
I cannot reproduce this issue. Probably fixed through 12f7cae403e434e5310e972d390c8e251c53d125.
