### ISSUE TITLE
java.lang.RuntimeException: Assertion failed. at soot.toolkits.graph.SimpleDominatorsFinder.getImmediateDominator(SimpleDominatorsFinder.java:94)

### ISSUE THREAD

**Issue by GUIpsp** [Sable/soot#416]
java.lang.RuntimeException: Assertion failed.
        at soot.toolkits.graph.SimpleDominatorsFinder.getImmediateDominator(SimpleDominatorsFinder.java:94)
        at soot.toolkits.graph.DominatorTree.fetchParent(DominatorTree.java:227)
        at soot.toolkits.graph.DominatorTree.buildTree(DominatorTree.java:191)
        at soot.toolkits.graph.DominatorTree.<init>(DominatorTree.java:67)
        at soot.shimple.DefaultShimpleFactory.getDominatorTree(DefaultShimpleFactory.java:158)
        at soot.shimple.internal.PhiNodeManager.update(PhiNodeManager.java:57)
        at soot.shimple.internal.PhiNodeManager.insertTrivialPhiNodes(PhiNodeManager.java:71)
        at soot.shimple.internal.ShimpleBodyBuilder.transform(ShimpleBodyBuilder.java:99)
        at soot.shimple.ShimpleBody.rebuild(ShimpleBody.java:133)
        at soot.shimple.ShimpleBody.<init>(ShimpleBody.java:102)
        at soot.shimple.Shimple.newBody(Shimple.java:88)
        at soot.PackManager.runBodyPacks(PackManager.java:895)
        at soot.PackManager.runBodyPacks(PackManager.java:608)
        at soot.PackManager.runBodyPacks(PackManager.java:507)
        at soot.PackManager.runPacksNormally(PackManager.java:484)
        at soot.PackManager.runPacks(PackManager.java:391)
        at soot.Main.run(Main.java:248)
        at soot.Main.main(Main.java:152)

**Comment by nignag** [comment]
Hi, it would be great if you can test the slightly extended version https://gist.github.com/nignag/63bcfd5349cf79a70be6 fails with an broken graph?

**Comment by GUIpsp** [comment]
@nignag I can't compile with your changes:

    Error:(86, 48) java: cannot find symbol
    symbol:   method isSubSet(soot.toolkits.scalar.FlowSet<N>)
    location: interface soot.toolkits.scalar.FlowSet<N>

**Comment by nignag** [comment]
Ups, maybe https://gist.github.com/nignag/63bcfd5349cf79a70be6/32b300b434b6db8677c1790ba8369fc32d16dec9 works the intended way

**Comment by GUIpsp** [comment]
Sorry, haven't had time to test your changes.

**Comment by GUIpsp** [comment]
That didn't fix it for me:

    java.lang.RuntimeException: Assertion failed.
        at soot.toolkits.graph.SimpleDominatorsFinder.getImmediateDominator(SimpleDominatorsFinder.java:100)
        at soot.toolkits.graph.DominatorTree.fetchParent(DominatorTree.java:227)
        at soot.toolkits.graph.DominatorTree.buildTree(DominatorTree.java:191)
        at soot.toolkits.graph.DominatorTree.<init>(DominatorTree.java:67)
        at soot.shimple.DefaultShimpleFactory.getDominatorTree(DefaultShimpleFactory.java:158)
        at soot.shimple.internal.PhiNodeManager.update(PhiNodeManager.java:57)
        at soot.shimple.internal.PhiNodeManager.insertTrivialPhiNodes(PhiNodeManager.java:71)
        at soot.shimple.internal.ShimpleBodyBuilder.transform(ShimpleBodyBuilder.java:99)
        at soot.shimple.ShimpleBody.rebuild(ShimpleBody.java:133)
        at soot.shimple.ShimpleBody.<init>(ShimpleBody.java:102)
        at soot.shimple.Shimple.newBody(Shimple.java:88)
        at soot.PackManager.runBodyPacks(PackManager.java:899)
        at soot.PackManager.runBodyPacks(PackManager.java:611)
        at soot.PackManager.runBodyPacks(PackManager.java:510)
        at soot.PackManager.runPacksNormally(PackManager.java:487)
        at soot.PackManager.runPacks(PackManager.java:394)
        at soot.Main.run(Main.java:248)
        at soot.Main.main(Main.java:152)

**Comment by GUIpsp** [comment]
@nignag 
Here are all the blocks:

Transforming a...
Block 0:
[preds: ] [succs: 1 ]

Block 1:
[preds: 0 ] [succs: 14 ]
i0 := @parameter0: int;
i1 := @parameter1: int;
i2 := @parameter2: int;
i3 = i1 - i0;
goto [?= (branch)];

Block 2:
[preds: 7 ] [succs: 3 51 ]
$r11 = staticinvoke <p: java.lang.String e(int,byte)>(16723968, -8);

Block 3:
[preds: 2 ] [succs: 52 ]
return $r11;

Block 4:
[preds: 15 ] [succs: 5 51 ]
$r12 = staticinvoke <p: java.lang.String e(int,byte)>(16711680, -35);

Block 5:
[preds: 4 ] [succs: 52 ]
return $r12;

Block 6:
[preds: 14 ] [succs: 7 10 ]
if i3 >= -6 goto (branch);

Block 7:
[preds: 6 ] [succs: 2 51 ]
goto [?= $r11 = staticinvoke <p: java.lang.String e(int,byte)>(16723968, -8)];

Block 8:
[preds: 11 ] [succs: 9 51 ]
$r10 = staticinvoke <p: java.lang.String e(int,byte)>(16740352, -46);

Block 9:
[preds: 8 ] [succs: 52 ]
return $r10;

Block 10:
[preds: 6 ] [succs: 11 40 ]
if i3 >= -3 goto (branch);

Block 11:
[preds: 10 ] [succs: 8 51 ]
goto [?= $r10 = staticinvoke <p: java.lang.String e(int,byte)>(16740352, -46)];

Block 12:
[preds: 43 ] [succs: 13 51 ]
$r1 = staticinvoke <p: java.lang.String e(int,byte)>(12648192, -22);

Block 13:
[preds: 12 ] [succs: 52 ]
return $r1;

Block 14:
[preds: 1 ] [succs: 15 6 ]
if i3 >= -9 goto (branch);

Block 15:
[preds: 14 ] [succs: 16 4 51 ]
if i2 > -126503352 goto $r12 = staticinvoke <p: java.lang.String e(int,byte)>(16711680, -35);

Block 16:
[preds: 15 ] [succs: 17 51 ]
$r13 = new java.lang.IllegalStateException;

Block 17:
[preds: 16 ] [succs: 18 51 ]
specialinvoke $r13.<java.lang.IllegalStateException: void <init>()>();

Block 18:
[preds: 17 ] [succs: 52 51 ]
throw $r13;

Block 19:
[preds: 41 ] [succs: 20 51 ]
$r9 = staticinvoke <p: java.lang.String e(int,byte)>(16756736, -83);

Block 20:
[preds: 19 ] [succs: 52 ]
return $r9;

Block 21:
[preds: 40 ] [succs: 22 28 ]
if i3 <= 9 goto (branch);

Block 22:
[preds: 21 ] [succs: 23 47 51 ]
if i2 > -126503352 goto $r7 = staticinvoke <p: java.lang.String e(int,byte)>(65280, -19);

Block 23:
[preds: 22 ] [succs: 24 51 ]
$r8 = new java.lang.IllegalStateException;

Block 24:
[preds: 23 ] [succs: 25 51 ]
specialinvoke $r8.<java.lang.IllegalStateException: void <init>()>();

Block 25:
[preds: 24 ] [succs: 52 51 ]
throw $r8;

Block 26:
[preds: 36 ] [succs: 27 51 ]
$r3 = staticinvoke <p: java.lang.String e(int,byte)>(8453888, -3);

Block 27:
[preds: 26 ] [succs: 52 ]
return $r3;

Block 28:
[preds: 21 ] [succs: 29 35 ]
if i3 <= 6 goto (branch);

Block 29:
[preds: 28 ] [succs: 30 33 51 ]
if i2 > -126503352 goto $r5 = staticinvoke <p: java.lang.String e(int,byte)>(4259584, -9);

Block 30:
[preds: 29 ] [succs: 31 51 ]
$r6 = new java.lang.IllegalStateException;

Block 31:
[preds: 30 ] [succs: 32 51 ]
specialinvoke $r6.<java.lang.IllegalStateException: void <init>()>();

Block 32:
[preds: 31 ] [succs: 52 51 ]
throw $r6;

Block 33:
[preds: 29 ] [succs: 34 51 ]
$r5 = staticinvoke <p: java.lang.String e(int,byte)>(4259584, -9);

Block 34:
[preds: 33 ] [succs: 52 ]
return $r5;

Block 35:
[preds: 28 ] [succs: 36 42 ]
if i3 <= 3 goto (branch);

Block 36:
[preds: 35 ] [succs: 37 26 51 ]
if i2 > -126503352 goto $r3 = staticinvoke <p: java.lang.String e(int,byte)>(8453888, -3);

Block 37:
[preds: 36 ] [succs: 38 51 ]
$r4 = new java.lang.IllegalStateException;

Block 38:
[preds: 37 ] [succs: 39 51 ]
specialinvoke $r4.<java.lang.IllegalStateException: void <init>()>();

Block 39:
[preds: 38 ] [succs: 52 51 ]
throw $r4;

Block 40:
[preds: 10 ] [succs: 41 21 ]
if i3 >= 0 goto (branch);

Block 41:
[preds: 40 ] [succs: 19 51 ]
goto [?= $r9 = staticinvoke <p: java.lang.String e(int,byte)>(16756736, -83)];

Block 42:
[preds: 35 ] [succs: 43 49 51 ]
if i3 <= 0 goto $r0 = staticinvoke <p: java.lang.String e(int,byte)>(16776960, -19);

Block 43:
[preds: 42 ] [succs: 44 12 51 ]
if i2 > -126503352 goto $r1 = staticinvoke <p: java.lang.String e(int,byte)>(12648192, -22);

Block 44:
[preds: 43 ] [succs: 45 51 ]
$r2 = new java.lang.IllegalStateException;

Block 45:
[preds: 44 ] [succs: 46 51 ]
specialinvoke $r2.<java.lang.IllegalStateException: void <init>()>();

Block 46:
[preds: 45 ] [succs: 52 51 ]
throw $r2;

Block 47:
[preds: 22 ] [succs: 48 51 ]
$r7 = staticinvoke <p: java.lang.String e(int,byte)>(65280, -19);

Block 48:
[preds: 47 ] [succs: 52 ]
return $r7;

Block 49:
[preds: 42 ] [succs: 50 51 ]
$r0 = staticinvoke <p: java.lang.String e(int,byte)>(16776960, -19);

Block 50:
[preds: 49 ] [succs: 52 ]
return $r0;

Block 51:
[preds: 7 2 15 4 11 8 43 12 16 17 18 41 19 23 24 25 36 26 30 31 32 29 33 37 38 39 44 45 46 22 47 42 49 ] [succs: 52 ]
$r14 := @caughtexception;
$r15 = new java.lang.StringBuilder;
specialinvoke $r15.<java.lang.StringBuilder: void <init>()>();
$r16 = virtualinvoke $r15.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("a.cv(");
$r17 = virtualinvoke $r16.<java.lang.StringBuilder: java.lang.StringBuilder append(char)>(41);
$r18 = virtualinvoke $r17.<java.lang.StringBuilder: java.lang.String toString()>();
$r19 = staticinvoke <k: ee a(java.lang.Throwable,java.lang.String)>($r14, $r18);
throw $r19;

Block 52:
[preds: 3 5 9 13 18 20 25 27 32 34 39 46 48 50 51 ] [succs: ]

**Comment by GUIpsp** [comment]
All blocks match the condition `graphEdgesAreValid(n)`

**Comment by nignag** [comment]
Hi,
#424 should fix it.

**Comment by GUIpsp** [comment]
Even with #424 applied, I still get this exception.

**Comment by nignag** [comment]
Hmm, 
i don't see anything special. 
GUIpsp could you post the Jimple body too?

**Comment by GUIpsp** [comment]
@nignag I'm assuming you want it from `-f jimple` ?

**Comment by nignag** [comment]
yes, that would be great

**Comment by GUIpsp** [comment]
@nignag http://sprunge.us/JDIQ This?

**Comment by nignag** [comment]
thx!
Is the Exception thrown on "Block 51"?

**Comment by GUIpsp** [comment]
No clue, the exception is the only output I get.

**Comment by nignag** [comment]
OK, after some testing the only dominator of Block51 seems to be Block51.
After inserting a nop as the first unit (after i2 := @parameter2: int;) the problem seems to be solved

**Comment by GUIpsp** [comment]
@StevenArzt Opinion?

**Comment by GUIpsp** [comment]
Wait, this already got fixed I think. Closing :)
