### ISSUE TITLE
java.lang.RuntimeException

### ISSUE THREAD

**Issue by WangYeOtw** [Sable/soot#423]
I analysis  the APK : 
https://drive.google.com/file/d/0B_Vmb8dYf9cGQ3dHcDR5UjR6VTQ/view?usp=sharing

with the below optations :
Options.v().set_soot_classpath(android_jar_path);
Options.v().set_src_prec(Options.src_prec_apk);
Options.v().set_allow_phantom_refs(true);
Options.v().set_force_android_jar(android_jar_path);
Options.v().set_process_dir(apk_list);

but  
"Options.v().set_force_android_jar(android_jar_path);" and "Options.v().set_soot_classpath(android_jar_path);" specifies the same jar,so , I del : "Options.v().set_soot_classpath(android_jar_path);"

after that, I got the error, I don't know why, what's the different between  "set_force_android_jar" and "set_soot_classpath" while analysis APK, especially with this APK.

The error:

java.lang.RuntimeException: Failed to convert <org.apache.http.client.utils.URLEncodedUtils: java.lang.String decode(java.lang.String,java.lang.String)>
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:1772)
	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:322)
	at soot.PackManager.retrieveAllBodies(PackManager.java:1144)
	at soot.PackManager.runPacksNormally(PackManager.java:458)
	at soot.PackManager.runPacks(PackManager.java:391)
	at soot.Main.run(Main.java:243)
	at soot.Main.main(Main.java:152)
	......

Caused by: java.lang.IllegalArgumentException: Invalid local index: 3
	at soot.asm.AsmMethodSource.getLocal(AsmMethodSource.java:190)
	at soot.asm.AsmMethodSource.convertVarLoadInsn(AsmMethodSource.java:1424)
	at soot.asm.AsmMethodSource.convertVarInsn(AsmMethodSource.java:1456)
	at soot.asm.AsmMethodSource.convert(AsmMethodSource.java:1618)
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:1770)
	... 9 more

**Comment by StevenArzt** [comment]
Which Android JAR file are you using? Is it one of the official platform JARs from the Android SDK? If so, which version?

**Comment by StevenArzt** [comment]
I cannot reproduce the issue. My Soot options are:

```
-process-dir "D:\Arbeit\APKs\com.alipay.android.client.pad_145804.apk" -android-jars "D:\Tools\adt-bundle-windows-x86_64-20140321\sdk\platforms" -allow-phantom-refs -output-format dex -src-prec apk -validate
```

**Comment by LouisonGitzinger** [comment]
Hi, I'm experiencing the exact same error : 
Here is my config : 
`SetupApplication app = new SetupApplication(pathToAndroidPlatforms, pathToApk);
		if (enableCallgraph) {
			try {
				app.calculateSourcesSinksEntrypoints(pathToSourcesAndSinks);
			} catch (IOException e) {
				e.printStackTrace();
			} catch (XmlPullParserException e) {
				e.printStackTrace();
			}
		}
		soot.G.reset();

		List<SootMethod> entryPoints = new ArrayList<SootMethod>();

		Options.v().set_allow_phantom_refs(true); //allow soot class creation for missing classes
		Options.v().set_whole_program(true); //whole-program optimization
		Options.v().set_output_dir(sootOutputDirectory); // set the soot analysis results directory
		Options.v().set_debug(true); // debug mode
		Options.v().set_validate(true); // ?
		Options.v().set_src_prec(Options.src_prec_apk); // only apk are accepted for soot analysis
		Options.v().set_android_jars(pathToAndroidPlatforms); // Load android platforms
		Options.v().set_process_dir(Collections.singletonList(pathToApk)); // loading apk to soot
//		Options.v().setPhaseOption("cg.spark", "on");
		Options.v().set_output_format(Options.output_format_jimple);

		// Load some necessary classes for analysis
		Scene.v().loadNecessaryClasses();
		Scene.v().loadBasicClasses();
		for (SootClass sc : Scene.v().getClasses()) {
			System.out.println(sc.getName());
			Scene.v().loadClassAndSupport(sc.getName());

			if (!sc.getName().startsWith("android.support")) {
				for (SootMethod sm : sc.getMethods()) {
					if (sm.isConcrete()) {
						entryPoints.add(sm);
					}
				}
			}
		}

		if (enableCallgraph) {

			SootMethod entryPoint = app.getEntryPointCreator().createDummyMain();
			Options.v().set_main_class(entryPoint.getSignature());
			Scene.v().setEntryPoints(Collections.singletonList(entryPoint));

//		 run full soot analysis
			PackManager.v().runPacks();

		}`

here is the apk i am analyzing : https://drive.google.com/open?id=0B-0AKM8jeYcBRUlXb3hvOHFfX1U

The error, (just in case) :

 `Exception in thread "main" java.lang.RuntimeException: Failed to convert <org.apache.http.client.utils.URLEncodedUtils: java.lang.String encode(java.lang.String,java.lang.String)>
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:1883)
	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:116)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:355)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processNewMethod(OnFlyCallGraphBuilder.java:1058)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processReachables(OnFlyCallGraphBuilder.java:533)
	at soot.jimple.toolkits.callgraph.CallGraphBuilder.build(CallGraphBuilder.java:104)
	at soot.jimple.toolkits.callgraph.CHATransformer.internalTransform(CHATransformer.java:46)
	at soot.SceneTransformer.transform(SceneTransformer.java:39)
	at soot.Transform.apply(Transform.java:90)
	at soot.RadioScenePack.internalApply(RadioScenePack.java:57)
	at soot.jimple.toolkits.callgraph.CallGraphPack.internalApply(CallGraphPack.java:49)
	at soot.Pack.apply(Pack.java:118)
	at soot.PackManager.runWholeProgramPacks(PackManager.java:581)
	at soot.PackManager.runPacksNormally(PackManager.java:472)
	at soot.PackManager.runPacks(PackManager.java:401)
	at utils.Config.configureSoot(Config.java:259)
	at app.Driver.main(Driver.java:19)
Caused by: java.lang.IllegalArgumentException: Invalid local index: 3
	at soot.asm.AsmMethodSource.getLocal(AsmMethodSource.java:197)
	at soot.asm.AsmMethodSource.convertVarLoadInsn(AsmMethodSource.java:1441)
	at soot.asm.AsmMethodSource.convertVarInsn(AsmMethodSource.java:1473)
	at soot.asm.AsmMethodSource.convert(AsmMethodSource.java:1652)
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:1881)`

Thank you in advance for your help !
