### ISSUE TITLE
Shimple exception

### ISSUE THREAD

**Issue by flycrane** [Sable/soot#429]
Hi Guys,

I am using soot with an apk(http://dl.ops.baidu.com/baidustu_AndroidPhone_v3.5.0(201503241)_1920211g.apk) and exception happened here, please help.

Signature: <com.google.gson.internal.UnsafeAllocator: void <init>()>
Exception in thread "main" java.lang.RuntimeException: Assertion failed.
	at soot.shimple.internal.PhiNodeManager.dominates(PhiNodeManager.java:359)
	at soot.shimple.internal.PhiNodeManager.trimPhiNode(PhiNodeManager.java:288)
	at soot.shimple.internal.PhiNodeManager.trimExceptionalPhiNodes(PhiNodeManager.java:227)
	at soot.shimple.internal.ShimpleBodyBuilder.transform(ShimpleBodyBuilder.java:116)
	at soot.shimple.ShimpleBody.rebuild(ShimpleBody.java:133)
	at soot.shimple.ShimpleBody.<init>(ShimpleBody.java:102)
	at soot.shimple.Shimple.newBody(Shimple.java:88)
	at soot.PackManager.runBodyPacks(PackManager.java:892)
	at soot.PackManager.runBodyPacks(PackManager.java:606)
	at soot.PackManager.runBodyPacks(PackManager.java:507)
	at soot.PackManager.runPacksNormally(PackManager.java:484)
	at soot.PackManager.runPacks(PackManager.java:391)
	at AndroidInstrument.main(AndroidInstrument.java:80)

I am using shimple here, cause I want a SSA form

**Comment by StevenArzt** [comment]
Can you please give your complete Soot command line?

**Comment by flycrane** [comment]
below is my settings:

Options.v().set_src_prec(Options.src_prec_apk);
Options.v().set_output_format(Options.output_format_shimple);
Options.v().set_allow_phantom_refs(true);
Options.v().set_android_jars("c:\\Work\\Tools\\eclipse-java-luna\\sdk\\platforms");
Options.v().set_output_dir("c:\\Work\\soot\\testout");
Options.v().set_process_dir(Collections.singletonList("c:\\Work\\soot\\baidustu.apk"));
Options.v().set_exclude(Collections.singletonList("android.support."));
Scene.v().loadNecessaryClasses(); 

PackManager.v().getPack("stp").add(new Transform("stp.myInstrumenter", new IntraPendingIntentScan()));
PackManager.v().runPacks();		
PackManager.v().writeOutput();
G.v().out.println("end");


and the class IntraPendingIntentScan is dummy.
