### ISSUE TITLE
java.lang.ClassCastException: soot.jimple.internal.JIdentityStmt cannot be cast to soot.jimple.AssignStmt

### ISSUE THREAD

**Issue by nignag** [Sable/soot#455]
Files used to reproduce: 
http://ftp.gnu.org/gnu/kawa/kawa-2.0.jar
(sha512: d49d3b1f8105c9bce6e224f7f352d6d737e22e5936f593c90b2238aeb571050123af35ff9955bc8e518dd6b6aee13bd7752224235eb3bcd6db4310e45e17c2d4)

Soot version: trunk

Command line:
<pre>
-output-format n -allow-phantom-refs -include-all -prepend-classpath -soot-classpath kawa/kawa-2.0.jar:. -process-dir kawa/kawa-2.0.jar
</pre>

Max Memory:
3641MB

Stack trace:
<pre>
java.lang.RuntimeException: Failed to convert &lt;gnu.kawa.slib.syntaxutils: gnu.expr.Expression rewriteForm$V(java.lang.Object,java.lang.Object[])&gt;
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:1776)
	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:322)
	at soot.PackManager.retrieveAllBodies(PackManager.java:1158)
	at soot.PackManager.runPacksNormally(PackManager.java:459)
	at soot.PackManager.runPacks(PackManager.java:392)
	at soot.Main.run(Main.java:248)
	at soot.Main.main(Main.java:150)
Caused by: java.lang.ClassCastException: soot.jimple.internal.JIdentityStmt cannot be cast to soot.jimple.AssignStmt
	at soot.asm.StackFrame.mergeIn(StackFrame.java:174)
	at soot.asm.AsmMethodSource.convertVarStoreInsn(AsmMethodSource.java:1452)
	at soot.asm.AsmMethodSource.convertVarInsn(AsmMethodSource.java:1462)
	at soot.asm.AsmMethodSource.convert(AsmMethodSource.java:1622)
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:1774)
	... 7 more
</pre>

**Comment by Alexandre-Bartel** [comment]
Fixed with 87e984435f9e45b905ecf21ebef0041fbeb35915.

**Comment by nignag** [comment]
thx
