### ISSUE TITLE
ASM-Backend input: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by MarcMil** [Sable/soot#460]
I have sent the test files to Steven.

```
java -jar soot-trunk.jar --allow-phantom-refs -src-prec c -asm-backend --process-dir /home/marc/test/
java.lang.ArrayIndexOutOfBoundsException: -26230
    at org.objectweb.asm.ClassReader.readLabel(ClassReader.java:2174)
    at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1059)
    at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1017)
    at org.objectweb.asm.ClassReader.accept(ClassReader.java:693)
    at org.objectweb.asm.ClassReader.accept(ClassReader.java:506)
    at soot.asm.AsmClassSource.resolve(AsmClassSource.java:70)
    at soot.SootResolver.bringToHierarchy(SootResolver.java:237)
    at soot.SootResolver.bringToSignatures(SootResolver.java:264)
    at soot.SootResolver.processResolveWorklist(SootResolver.java:168)
    at soot.SootResolver.resolveClass(SootResolver.java:129)
    at soot.Scene.loadClass(Scene.java:702)
    at soot.Scene.loadClassAndSupport(Scene.java:687)
    at soot.Scene.loadNecessaryClasses(Scene.java:1362)
    at soot.Main.run(Main.java:243)
    at soot.Main.main(Main.java:147)
```

**Comment by kilaka** [comment]
It's because you're using Java 8 with asm probably supporting up to Java 7
More info here: http://stackoverflow.com/questions/26496338/strange-java-lang-arrayindexoutofboundsexception-thrown-on-jetty-startup
