### ISSUE TITLE
[Exception] Process java source code using jdk 8

### ISSUE THREAD

**Issue by csytang** [Sable/soot#465]
I use the following command to process java file
   -src-prec java  -cp "/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/jce.jar" -process-dir "/Users/.../test/src" -f jimple

 I got error when process java source
java.lang.ClassCastException: soot.JastAddJ.CONSTANT_Utf8_Info cannot be cast to soot.JastAddJ.CONSTANT_Class_Info
    at soot.JastAddJ.BytecodeParser.parseThisClass(BytecodeParser.java:437)
    at soot.JastAddJ.BytecodeParser.parseTypeDecl(BytecodeParser.java:404)
    at soot.JastAddJ.BytecodeParser.parse(BytecodeParser.java:331)
    at soot.JastAddJ.BytecodeParser.parse(BytecodeParser.java:301)
    at soot.JastAddJ.Attributes$TypeAttributes.innerClasses(Attributes.java:412)
    at soot.JastAddJ.Attributes$TypeAttributes.processAttribute(Attributes.java:316)
    at soot.JastAddJ.Attributes.attributes(Attributes.java:61)
    at soot.JastAddJ.Attributes$TypeAttributes.<init>(Attributes.java:307)
    at soot.JastAddJ.BytecodeParser.parse(BytecodeParser.java:337)
    at soot.JastAddJ.BytecodeParser.read(BytecodeParser.java:27)
    at soot.JastAddJ.PathPart.getCompilationUnit(PathPart.java:115)
    at soot.JastAddJ.Program.getCompilationUnit(Program.java:887)
    at soot.JastAddJ.Program.getLibCompilationUnit_compute(Program.java:1531)
    at soot.JastAddJ.Program.getLibCompilationUnit(Program.java:1514)
    at soot.JastAddJ.Program.lookupLibType_compute(Program.java:1479)
    at soot.JastAddJ.Program.lookupLibType(Program.java:1447)
    at soot.JastAddJ.Program.lookupType_compute(Program.java:1426)
    at soot.JastAddJ.Program.lookupType(Program.java:1407)
    at soot.JastAddJ.Program.Define_TypeDecl_lookupType(Program.java:1995)
    at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
    at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
    at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
    at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
    at soot.JastAddJ.Expr.lookupType(Expr.java:1186)
    at soot.JastAddJ.TypeAccess.decls_compute(TypeAccess.java:425)
    at soot.JastAddJ.TypeAccess.decls(TypeAccess.java:414)
It can work with jdk 7, but not 8

**Comment by StevenArzt** [comment]
Soot's front-end for Java source code is not up-to-date at the moment. We, however, do have very stable front-ends for Java bytecode. Would it also be possible for you to use bytecode instead of source code?

**Comment by csytang** [comment]
I surely use the source code instead of the byte code. It works fine when I change to jdk 7. But the problem occurs when I try my program using idk 8.

**Comment by StevenArzt** [comment]
Soot's source code front-end is not compatible with Java 8 yet. The easiest way to circumvent the problem would be to use byte code instead of source code. Other than that, we would need someone to work on a new source front-end.

**Comment by campiador** [comment]
@StevenArzt I get the same issue when I use java-8-oracle for executing Soot to instrument an Android APK. Can you please show me how to use byte code to circumvent the issue?
