### ISSUE TITLE
RuntimeException: Failed to apply jb when analyzing APK files

### ISSUE THREAD

**Issue by dengfengli** [Sable/soot#472]
I try to use FlowDroid to analyze Android malware in Bgserv family and flowDroid prints the following exception trace:

Exception in thread "main" java.lang.RuntimeException: Failed to apply jb to <com.android.internal.telephony.gsm.SmsMessage: com.android.internal.telephony.gsm.SmsMessage$SubmitPdu getSubmitPdu(java.lang.String,java.lang.String,java.lang.String,boolean,byte[])>
    at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:1804)
    at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
    at soot.SootMethod.retrieveActiveBody(SootMethod.java:322)
    at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processNewMethod(OnFlyCallGraphBuilder.java:529)
    at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processReachables(OnFlyCallGraphBuilder.java:420)
    at soot.jimple.spark.solver.OnFlyCallGraph.build(OnFlyCallGraph.java:55)
    at soot.jimple.spark.solver.PropWorklist.handleVarNode(PropWorklist.java:122)
    at soot.jimple.spark.solver.PropWorklist.propagate(PropWorklist.java:52)
    at soot.jimple.spark.SparkTransformer.internalTransform(SparkTransformer.java:152)
    at soot.SceneTransformer.transform(SceneTransformer.java:39)
    at soot.Transform.apply(Transform.java:90)
    at soot.RadioScenePack.internalApply(RadioScenePack.java:57)
    at soot.jimple.toolkits.callgraph.CallGraphPack.internalApply(CallGraphPack.java:49)
    at soot.Pack.apply(Pack.java:121)
    at soot.jimple.infoflow.android.SetupApplication.calculateCallbackMethods(SetupApplication.java:448)
    at soot.jimple.infoflow.android.SetupApplication.calculateSourcesSinksEntrypoints(SetupApplication.java:359)
    at soot.jimple.infoflow.android.SetupApplication.calculateSourcesSinksEntrypoints(SetupApplication.java:325)
    at soot.jimple.infoflow.android.TestApps.Test.runAnalysis(Test.java:521)
    at soot.jimple.infoflow.android.TestApps.Test.main(Test.java:206)
Caused by: java.lang.RuntimeException: oops,  base type must be PrimType or RefType but not 'bottom_type'
    at soot.ArrayType.<init>(ArrayType.java:60)
    at soot.ArrayType.v(ArrayType.java:86)
    at soot.Type.makeArrayType(Type.java:76)
    at soot.jimple.toolkits.typing.fast.UseChecker.caseAssignStmt(UseChecker.java:232)
    at soot.jimple.internal.JAssignStmt.apply(JAssignStmt.java:238)
    at soot.jimple.toolkits.typing.fast.UseChecker.check(UseChecker.java:122)
    at soot.jimple.toolkits.typing.fast.TypeResolver.insertCasts(TypeResolver.java:411)
    at soot.jimple.toolkits.typing.fast.TypeResolver.minCasts(TypeResolver.java:422)
    at soot.jimple.toolkits.typing.fast.TypeResolver.inferTypes(TypeResolver.java:158)
    at soot.jimple.toolkits.typing.TypeAssigner.internalTransform(TypeAssigner.java:131)
    at soot.BodyTransformer.transform(BodyTransformer.java:51)
    at soot.Transform.apply(Transform.java:105)
    at soot.JimpleBodyPack.applyPhaseOptions(JimpleBodyPack.java:66)
    at soot.JimpleBodyPack.internalApply(JimpleBodyPack.java:89)
    at soot.Pack.apply(Pack.java:132)
    at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:1802)
    ... 18 more

**Comment by Alexandre-Bartel** [comment]
Please send the apk to alexandre.bartel@ec-spride.de.
