### ISSUE TITLE
soot.SootResolver$SootClassNotFoundException when ...

### ISSUE THREAD

**Issue by saurabhsinghmaurya** [Sable/soot#476]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: <pre>trunk</pre>

Command line:
<pre>Saurabh.class</pre>

Max Memory:
<pre>846MB</pre>

Stack trace:
<pre>soot.SootResolver$SootClassNotFoundException: couldn&#39;t find class: Saurabh.class (is your soot-class-path set properly?)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:226)
	at soot.SootResolver.bringToSignatures(SootResolver.java:264)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:168)
	at soot.SootResolver.resolveClass(SootResolver.java:129)
	at soot.Scene.loadClass(Scene.java:706)
	at soot.Scene.loadClassAndSupport(Scene.java:691)
	at soot.Scene.loadNecessaryClass(Scene.java:1343)
	at soot.Scene.loadNecessaryClasses(Scene.java:1354)
	at soot.Main.run(Main.java:243)
	at soot.Main.main(Main.java:147)
</pre>

**Comment by Alexandre-Bartel** [comment]
Could you please provide the command line you use to launch Soot, the full path to Saurabh.class and the package name under which this class is declared?

**Comment by saurabhsinghmaurya** [comment]
thanks
it is working now.

**Comment by Alexandre-Bartel** [comment]
Great. Then please describe your solution here and close the issue.

**Comment by saurabhsinghmaurya** [comment]
For invoking  soot, this is the command line .
java -cp soot-trunk.jar  soot.Main -f J -cp <input class dir> -pp <class name> or 
java -jar soot-trunk.jar -f J -cp <input class dir> -pp <class name>
