### ISSUE TITLE
NoSuchMethodError in nightly build in soot

### ISSUE THREAD

**Issue by MarcMil** [Sable/soot#487]
The newest nightly build seems to have problems...

```
java -jar soot-trunk.jar -src-prec apk -android-jars /home/marc/adt-bundle-linux-x86_64-20140702/sdk/platforms/ -process-dir bla.apk

Exception in thread "main" java.lang.NoSuchMethodError: org.jf.dexlib2.iface.ClassDef.getInterfaces()Ljava/util/Set;
	at soot.dexpler.DexClass.makeSootClass(DexClass.java:101)
	at soot.dexpler.DexlibWrapper.makeSootClass(DexlibWrapper.java:137)
	at soot.dexpler.DexResolver.resolveFromFile(DexResolver.java:60)
	at soot.DexClassSource.resolve(DexClassSource.java:52)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:239)
	at soot.SootResolver.bringToSignatures(SootResolver.java:266)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:170)
	at soot.SootResolver.resolveClass(SootResolver.java:131)
	at soot.dexpler.DexlibWrapper.initialize(DexlibWrapper.java:121)
	at soot.dexpler.DexResolver.resolveFromFile(DexResolver.java:57)
	at soot.DexClassSource.resolve(DexClassSource.java:52)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:239)
	at soot.SootResolver.bringToSignatures(SootResolver.java:266)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:170)
	at soot.SootResolver.resolveClass(SootResolver.java:131)
	at soot.Scene.loadClass(Scene.java:706)
	at soot.Scene.loadClassAndSupport(Scene.java:691)
	at soot.Scene.loadNecessaryClasses(Scene.java:1366)
	at soot.Main.run(Main.java:243)
	at soot.Main.main(Main.java:147)
```

**Comment by StevenArzt** [comment]
fixed.
