### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException in DavaFlowSet when decompiling an APK

### ISSUE THREAD

**Issue by elephantom** [Sable/soot#502]
I am using an apk (found below) and AndroidInstrument.java.
I compile AndroidInstrument with soot-trunk.jar and then run the command line below.

I patched the issue by adding some checks in DavaFlowSet.remove() -- happy to pass these along if they are useful, but they aren't fixing whatever the root of the issue is.

Files used to reproduce: 
I used this apk: https://f-droid.org/repository/browse/?fdid=org.billthefarmer.accordion

Soot version: <pre>trunk</pre>

Command line:
<pre>-android-jars /my/dir/path -allow-phantom-refs -p db.transformations enabled:true -process-dir apks/org.billthefarmer.accordion_106.apk</pre>

Max Memory:
<pre>1746MB</pre>

Stack trace:
<pre>java.lang.ArrayIndexOutOfBoundsException: 8
	at soot.dava.toolkits.base.AST.structuredAnalysis.DavaFlowSet.remove(DavaFlowSet.java:181)
	at soot.dava.toolkits.base.AST.structuredAnalysis.DavaFlowSet$1.remove(DavaFlowSet.java:747)
	at soot.dava.toolkits.base.AST.structuredAnalysis.ReachingDefs.kill(ReachingDefs.java:185)
	at soot.dava.toolkits.base.AST.structuredAnalysis.ReachingDefs.processStatement(ReachingDefs.java:158)
	at soot.dava.toolkits.base.AST.structuredAnalysis.StructuredAnalysis.processAbruptStatements(StructuredAnalysis.java:364)
	at soot.dava.toolkits.base.AST.structuredAnalysis.StructuredAnalysis.process(StructuredAnalysis.java:213)
	at soot.dava.toolkits.base.AST.structuredAnalysis.StructuredAnalysis.processASTStatementSequenceNode(StructuredAnalysis.java:390)
	at soot.dava.toolkits.base.AST.structuredAnalysis.StructuredAnalysis.processASTNode(StructuredAnalysis.java:271)
	at soot.dava.toolkits.base.AST.structuredAnalysis.StructuredAnalysis.process(StructuredAnalysis.java:240)
	at soot.dava.toolkits.base.AST.structuredAnalysis.StructuredAnalysis.processSingleSubBodyNode(StructuredAnalysis.java:301)
	at soot.dava.toolkits.base.AST.structuredAnalysis.StructuredAnalysis.processASTMethodNode(StructuredAnalysis.java:377)
	at soot.dava.toolkits.base.AST.structuredAnalysis.StructuredAnalysis.processASTNode(StructuredAnalysis.java:269)
	at soot.dava.toolkits.base.AST.structuredAnalysis.StructuredAnalysis.process(StructuredAnalysis.java:208)
	at soot.dava.toolkits.base.AST.structuredAnalysis.ReachingDefs.&#60;init&#62;(ReachingDefs.java:69)
	at soot.dava.toolkits.base.AST.traversals.ASTUsesAndDefs.&#60;init&#62;(ASTUsesAndDefs.java:72)
	at soot.dava.toolkits.base.AST.traversals.CopyPropagation.setup(CopyPropagation.java:112)
	at soot.dava.toolkits.base.AST.traversals.CopyPropagation.&#60;init&#62;(CopyPropagation.java:97)
	at soot.dava.DavaBody.applyStructuralAnalyses(DavaBody.java:649)
	at soot.dava.DavaBody.analyzeAST(DavaBody.java:431)
	at soot.PackManager.postProcessDAVA(PackManager.java:698)
	at soot.PackManager.writeOutput(PackManager.java:522)
	at soot.Main.run(Main.java:273)
	at soot.Main.main(Main.java:147)
	at AndroidInstrument.main(AndroidInstrument.java:83)
</pre>Please be as precise as possible when giving us

**Comment by StevenArzt** [comment]
Works in plain Soot. I used the following command-line options when launching Soot from Eclipse in Debug mode:

```
-process-dir "D:\Arbeit\APKs\org.billthefarmer.accordion_106.apk" -android-jars "D:\Tools\adt-bundle-windows-x86_64-20140321\sdk\platforms" -allow-phantom-refs -output-format dex -src-prec apk -force-overwrite -validate  -p db.transformations enabled:true
```

Can you send me a minimal working example, i.e., your AndroidInstrument program reduced to the minimum code size necessary to reproduce the issue?

**Comment by elephantom** [comment]
I emailed you about this and #483. Thanks!

**Comment by elephantom** [comment]
Awesome, thanks so much for this!! (And sorry for the delayed reply.)
