### ISSUE TITLE
java.lang.NullPointerException when outputting dava

### ISSUE THREAD

**Issue by elephantom** [Sable/soot#510]
Steps to reproduce:
I'm using AndroidInstrument.java to analyze APKs. The particular apk that causes this issue is app.easytoken_919.apk, found on fdroid at https://f-droid.org/repo/app.easytoken_919.apk 

The only difference in AndroidInstrument.java is that my output format is set to dava instead of dex, as in the example.

Thanks for your help!

Soot version: <pre>trunk</pre>

Command line:
<pre>-android-jars /path/to/my/android-sdk-linux/platforms -allow-phantom-refs -p db.transformations enabled:true -process-dir apks/app.easytoken_919.apk</pre>

Max Memory:
<pre>1746MB</pre>

Stack trace:
<pre>java.lang.NullPointerException
	at soot.dava.internal.SET.SETControlFlowNode.resolve(SETControlFlowNode.java:54)
	at soot.dava.internal.SET.SETNode.nest(SETNode.java:295)
	at soot.dava.internal.SET.SETNode.nest(SETNode.java:316)
	at soot.dava.internal.SET.SETNode.nest(SETNode.java:316)
	at soot.dava.toolkits.base.finders.IfFinder.find(IfFinder.java:97)
	at soot.dava.DavaBody.&#60;init&#62;(DavaBody.java:327)
	at soot.dava.Dava.newBody(Dava.java:84)
	at soot.PackManager.runBodyPacks(PackManager.java:950)
	at soot.PackManager.runBodyPacks(PackManager.java:611)
	at soot.PackManager.runBodyPacks(PackManager.java:508)
	at soot.PackManager.runPacksNormally(PackManager.java:485)
	at soot.PackManager.runPacks(PackManager.java:392)
	at soot.Main.run(Main.java:271)
	at soot.Main.main(Main.java:147)
	at AndroidInstrument.main(AndroidInstrument.java:83)
</pre>

**Comment by elephantom** [comment]
Awesome, thanks so much!
