### ISSUE TITLE
Exception while building RTA CallGraph

### ISSUE THREAD

**Issue by vitaliiavdiienko** [Sable/soot#514]
Hi all,

while building a CallGraph with using of RTA algorithm I receive the following exception:

```java
[Call Graph] For information on where the call graph may be incomplete, use the verbose option to the cg phase.
		Exception in thread "main" java.lang.RuntimeException
		at soot.jimple.spark.pag.MethodPAG.addToPAG(MethodPAG.java:63)
		at soot.jimple.spark.builder.ContextInsensitiveBuilder.build(ContextInsensitiveBuilder.java:90)
		at soot.jimple.spark.SparkTransformer.internalTransform(SparkTransformer.java:84)
		at soot.SceneTransformer.transform(SceneTransformer.java:39)
		at soot.Transform.apply(Transform.java:90)
		at soot.RadioScenePack.internalApply(RadioScenePack.java:57)
		at soot.jimple.toolkits.callgraph.CallGraphPack.internalApply(CallGraphPack.java:49)
		at soot.Pack.apply(Pack.java:121)
		at soot.PackManager.runWholeProgramPacks(PackManager.java:566)
		at soot.PackManager.runPacksNormally(PackManager.java:457)
		at soot.PackManager.runPacks(PackManager.java:392)
```
I am initializing analysis using the following way:
```java
...
Options.v().set_whole_program(true); 
Scene.v().loadNecessaryClasses();
Options.v().setPhaseOption("cg.spark", "on");
Options.v().setPhaseOption("cg.spark", "rta:true");
Options.v().setPhaseOption("cg.spark", "on-fly-cg:false");

PackManager.v().runPacks();
```

Can you help with understanding what is wrong here?

Thank you in advance.

Vitalii

**Comment by StevenArzt** [comment]
Can you try again with the newest version of Soot? If it still doesn't work, can you please provide a more complete example? I cannot really reproduce the exception.

**Comment by vitaliiavdiienko** [comment]
Hi Steven,

sent you details by email.
