### ISSUE TITLE
Exception when parsing Cassandra bytecode

### ISSUE THREAD

**Issue by martinschaef** [Sable/soot#521]
I get the exception below when I try to load some classes from Cassandra.
As process-dir I use cassandra/build/classes/main 

java.lang.RuntimeException: Failed to apply jb to <org.apache.cassandra.config.ViewDefinition: java.util.List whereClauseToRelations(java.lang.String)>
Exception in thread "main" java.lang.RuntimeException: Failed to apply jb to <org.apache.cassandra.config.ViewDefinition: java.util.List whereClauseToRelations(java.lang.String)>
    at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:1804)
    at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
    at soot.SootMethod.retrieveActiveBody(SootMethod.java:322)
       ...
Caused by: java.lang.RuntimeException: Exception reference used other than as the first statement of an exception handler.
    at soot.jimple.toolkits.typing.fast.AugEvalFunction.eval_(AugEvalFunction.java:159)
    at soot.jimple.toolkits.typing.fast.AugEvalFunction.eval(AugEvalFunction.java:41)
    at soot.jimple.toolkits.typing.fast.TypeResolver.applyAssignmentConstraints(TypeResolver.java:480)
    at soot.jimple.toolkits.typing.fast.TypeResolver.inferTypes(TypeResolver.java:150)
    at soot.jimple.toolkits.typing.TypeAssigner.internalTransform(TypeAssigner.java:131)
    at soot.BodyTransformer.transform(BodyTransformer.java:51)
    at soot.Transform.apply(Transform.java:105)
    at soot.JimpleBodyPack.applyPhaseOptions(JimpleBodyPack.java:72)
    at soot.JimpleBodyPack.internalApply(JimpleBodyPack.java:95)
    at soot.Pack.apply(Pack.java:132)
    at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:1802)
    ... 6 more

**Comment by martinschaef** [comment]
And another one also in cassandra:
Caused by: java.lang.AssertionError: Not dummy operand, timestamp -- mutation
	at soot.asm.AsmMethodSource.popDual(AsmMethodSource.java:245)
	at soot.asm.AsmMethodSource.popImmediateDual(AsmMethodSource.java:304)
	at soot.asm.AsmMethodSource.popImmediate(AsmMethodSource.java:308)
	at soot.asm.AsmMethodSource.convertInvokeDynamicInsn(AsmMethodSource.java:1255)
	at soot.asm.AsmMethodSource.convert(AsmMethodSource.java:1605)
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:1770)
	... 6 more

**Comment by anddann** [comment]
I'm able to parse cassandra bytecode with release 4.0
