### ISSUE TITLE
java.lang.RuntimeException when processing class files with array accesses on null arrays

### ISSUE THREAD

**Issue by benjholla** [Sable/soot#527]
Steps to reproduce:
1) Create the following Java file named "TestNullArray.java".

<pre>public class TestNullArray {
	public static void main(String[] args) {
		Object[] a = null;
		Object o1 = null;
		a[0] = null;
		Object o2 = a[0]; 
		System.out.println(o2.toString());
	}
}</pre>

2) Compile the program with "javac TestNullArray.java ". I've confirmed this using Java 7 on Mac and Windows. For this report I am using my Mac.

<pre>$ java -version
java version "1.7.0_45"
Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
Java HotSpot(TM) 64-Bit Server VM (build 24.45-b08, mixed mode)</pre>

3) Attempt to create Jimple for the TestArrayNull.class file and observe the runtime exception.

<pre>java -cp soot-trunk.jar soot.Main -src-prec class -process-dir path/to/directory-containing-test/ -output-format jimple</pre>

I've also tried using the latest Soot Eclipse plugin (from the develop branch) to use the Project > Soot -> Process All Class Files > Create Jimple For Project menu, but the process just hangs indefinitely once it begins to process the TestNullArray class.

Soot version: <pre>trunk</pre> (as of 1/27/16 from http://ssebuild.cased.de/nightly/soot/)

Command line:
<pre>-src-prec class -process-dir /Users/benjholla/Desktop/test -output-format jimple</pre>

Max Memory:
<pre>3641MB</pre>

Stack trace:
<pre>java.lang.RuntimeException: Failed to apply jb to &#60;TestNullArray: void main(java.lang.String[])&#62;
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:1804)
	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:322)
	at soot.PackManager$3.run(PackManager.java:1222)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.RuntimeException: oops,  base type must be PrimType or RefType but not &#39;null_type&#39;
	at soot.ArrayType.&#60;init&#62;(ArrayType.java:60)
	at soot.ArrayType.v(ArrayType.java:86)
	at soot.Type.makeArrayType(Type.java:76)
	at soot.jimple.toolkits.typing.fast.UseChecker.caseAssignStmt(UseChecker.java:232)
	at soot.jimple.internal.JAssignStmt.apply(JAssignStmt.java:238)
	at soot.jimple.toolkits.typing.fast.UseChecker.check(UseChecker.java:122)
	at soot.jimple.toolkits.typing.fast.TypeResolver.insertCasts(TypeResolver.java:411)
	at soot.jimple.toolkits.typing.fast.TypeResolver.minCasts(TypeResolver.java:422)
	at soot.jimple.toolkits.typing.fast.TypeResolver.inferTypes(TypeResolver.java:158)
	at soot.jimple.toolkits.typing.TypeAssigner.internalTransform(TypeAssigner.java:131)
	at soot.BodyTransformer.transform(BodyTransformer.java:51)
	at soot.Transform.apply(Transform.java:105)
	at soot.JimpleBodyPack.applyPhaseOptions(JimpleBodyPack.java:72)
	at soot.JimpleBodyPack.internalApply(JimpleBodyPack.java:95)
	at soot.Pack.apply(Pack.java:125)
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:1802)
	... 6 more
</pre>

**Comment by summerDG** [comment]
Has this problem been resolved? I count the same question.
