### ISSUE TITLE
ASM conversion error

### ISSUE THREAD

**Issue by Waldo1637** [Sable/soot#533]
A `java.lang.AssertionError: Multiple un-equal stacks!` is thrown when Soot tries to convert the following bytecode to Jimple:

```
iconst_1
dup
swap
iconst_2
if_icmplt 7
ireturn
iconst_3
imul
goto 2
```

Here is the full stack trace:

```
java.lang.RuntimeException: Failed to convert <TestUnequalStacks: int hashCode()>
    at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:1836)
    at soot.shimple.ShimpleMethodSource.getBody(ShimpleMethodSource.java:35)
    at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
    at soot.SootMethod.retrieveActiveBody(SootMethod.java:322)
    at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processNewMethod(OnFlyCallGraphBuilder.java:529)
    at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processReachables(OnFlyCallGraphBuilder.java:420)
    at soot.jimple.toolkits.callgraph.CallGraphBuilder.build(CallGraphBuilder.java:84)
    at soot.jimple.toolkits.callgraph.CHATransformer.internalTransform(CHATransformer.java:45)
    at soot.SceneTransformer.transform(SceneTransformer.java:39)
    at soot.Transform.apply(Transform.java:90)
    at soot.RadioScenePack.internalApply(RadioScenePack.java:57)
    at soot.jimple.toolkits.callgraph.CallGraphPack.internalApply(CallGraphPack.java:49)
    at soot.Pack.apply(Pack.java:121)
    at soot.PackManager.runWholeProgramPacks(PackManager.java:561)
    at soot.PackManager.runPacksNormally(PackManager.java:457)
    at soot.PackManager.runPacks(PackManager.java:392)
    at soot.Main.run(Main.java:271)
Caused by: java.lang.AssertionError: Multiple un-equal stacks!
    at soot.asm.AsmMethodSource.addEdges(AsmMethodSource.java:1563)
    at soot.asm.AsmMethodSource.convert(AsmMethodSource.java:1633)
    at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:1834)
    ...
```

Writing the same program a slightly different way, avoids the error:

```
iconst_1
dup
swap
iconst_2
if_icmpge 9
iconst_3
imul
goto 2
ireturn
```

The difference between the two code samples is that ASM converts/evaluates the two branches in the opposite order. If the edge to the `ireturn` statement is processed first (as happens with the second code sample), then the ASM conversion succeeds. However, when the edge to `iconst_3` is processed first (as happens with the first code sample), then the error occurs.

**Comment by Waldo1637** [comment]
A class file with the erring byte code is available on [Dropbox](https://www.dropbox.com/sh/03605ihm23as2zr/AAAEDt2SUUo3ZwQrK85OBGH2a?dl=0).

**Comment by anddann** [comment]
works with the current soot release 4.0
