### ISSUE TITLE
soot.SootResolver$SootClassNotFoundException when ...

### ISSUE THREAD

**Issue by jyotigajrani** [Sable/soot#539]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: <pre>trunk</pre>

Command line:
<pre>-android-jars /home/jyoti/Android/adt-bundle-linux-x86_64-20140702/sdk/platforms -cp . -pp AndroidInstrument -process-dir Onlytelephony.apk</pre>

Max Memory:
<pre>1746MB</pre>

Stack trace:
<pre>soot.SootResolver$SootClassNotFoundException: couldn&#39;t find class: soot.Local (is your soot-class-path set properly?)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:228)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:173)
	at soot.SootResolver.resolveClass(SootResolver.java:131)
	at soot.Scene.loadClass(Scene.java:725)
	at soot.Scene.loadClassAndSupport(Scene.java:710)
	at soot.Scene.loadNecessaryClass(Scene.java:1425)
	at soot.Scene.loadNecessaryClasses(Scene.java:1436)
	at soot.Main.run(Main.java:243)
	at soot.Main.main(Main.java:147)
</pre>

**Comment by Alexandre-Bartel** [comment]
Could you describe how you solved your problem? It may be useful to others.
