### ISSUE TITLE
java.lang.RuntimeException when ...

### ISSUE THREAD

**Issue by jchauhan** [Sable/soot#542]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: <pre>trunk</pre>

Command line:

<pre>-allow-phantom-refs -android-jars /Users/jc/Softwares/Development/android-sdk-macosx/platforms/ -src-prec apk -process-dir demo/InsecureBankv2.apk -output-format d</pre>

Max Memory:

<pre>1333MB</pre>

Stack trace:

<pre>java.lang.RuntimeException: Could not wait for pack threads to finish: null
    at soot.PackManager.runBodyPacks(PackManager.java:637)
    at soot.PackManager.runBodyPacks(PackManager.java:512)
    at soot.PackManager.runPacksNormally(PackManager.java:489)
    at soot.PackManager.runPacks(PackManager.java:396)
    at soot.Main.run(Main.java:271)
    at soot.Main.main(Main.java:147)
Caused by: java.lang.InterruptedException
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:996)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1303)
    at heros.solver.CountLatch.awaitZero(CountLatch.java:75)
    at heros.solver.CountingThreadPoolExecutor.awaitCompletion(CountingThreadPoolExecutor.java:79)
    at soot.PackManager.runBodyPacks(PackManager.java:633)
    ... 5 more
</pre>

<pre>
Decompiling android.support.v7.internal.widget.TintContextWrapper$TintResources... 
[Thread-12] ERROR heros.solver.IDESolver - Worker thread execution failed: DECOMPILATION INCOMPLETEThe type:null_type is neither a reftype or a primtype
soot.dava.DecompilationException: DECOMPILATION INCOMPLETEThe type:null_type is neither a reftype or a primtype
Decompiling com.google.android.gms.games.multiplayer.realtime.RoomBuffer... 
    at soot.dava.toolkits.base.AST.transformations.SuperFirstStmtHandler.createStmtAccordingToType(SuperFirstStmtHandler.java:1374)
    at soot.dava.toolkits.base.AST.transformations.SuperFirstStmtHandler.createDavaStoreStmts(SuperFirstStmtHandler.java:1212)
    at soot.dava.toolkits.base.AST.transformations.SuperFirstStmtHandler.finalizePreInitMethod(SuperFirstStmtHandler.java:724)
    at soot.dava.toolkits.base.AST.transformations.SuperFirstStmtHandler.inASTStatementSequenceNode(SuperFirstStmtHandler.java:272)
    at soot.dava.toolkits.base.AST.analysis.DepthFirstAdapter.caseASTStatementSequenceNode(DepthFirstAdapter.java:503)
    at soot.dava.internal.AST.ASTStatementSequenceNode.apply(ASTStatementSequenceNode.java:88)
    at soot.dava.toolkits.base.AST.analysis.DepthFirstAdapter.normalRetrieving(DepthFirstAdapter.java:487)
    at soot.dava.toolkits.base.AST.analysis.DepthFirstAdapter.caseASTMethodNode(DepthFirstAdapter.java:68)
    at soot.dava.internal.AST.ASTMethodNode.apply(ASTMethodNode.java:477)
    at soot.dava.DavaBody.<init>(DavaBody.java:381)
    at soot.dava.Dava.newBody(Dava.java:84)
    at soot.PackManager.runBodyPacks(PackManager.java:1010)
    at soot.PackManager.access$000(PackManager.java:137)
    at soot.PackManager$1.run(PackManager.java:625)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-12" soot.dava.DecompilationException: DECOMPILATION INCOMPLETEThe type:null_type is neither a reftype or a primtype
    at soot.dava.toolkits.base.AST.transformations.SuperFirstStmtHandler.createStmtAccordingToType(SuperFirstStmtHandler.java:1374)
    at soot.dava.toolkits.base.AST.transformations.SuperFirstStmtHandler.createDavaStoreStmts(SuperFirstStmtHandler.java:1212)
    at soot.dava.toolkits.base.AST.transformations.SuperFirstStmtHandler.finalizePreInitMethod(SuperFirstStmtHandler.java:724)
    at soot.dava.toolkits.base.AST.transformations.SuperFirstStmtHandler.inASTStatementSequenceNode(SuperFirstStmtHandler.java:272)
    at soot.dava.toolkits.base.AST.analysis.DepthFirstAdapter.caseASTStatementSequenceNode(DepthFirstAdapter.java:503)
    at soot.dava.internal.AST.ASTStatementSequenceNode.apply(ASTStatementSequenceNode.java:88)
    at soot.dava.toolkits.base.AST.analysis.DepthFirstAdapter.normalRetrieving(DepthFirstAdapter.java:487)
    at soot.dava.toolkits.base.AST.analysis.DepthFirstAdapter.caseASTMethodNode(DepthFirstAdapter.java:68)
    at soot.dava.internal.AST.ASTMethodNode.apply(ASTMethodNode.java:477)
    at soot.dava.DavaBody.<init>(DavaBody.java:381)
    at soot.dava.Dava.newBody(Dava.java:84)
    at soot.PackManager.runBodyPacks(PackManager.java:1010)
    at soot.PackManager.access$000(PackManager.java:137)
    at soot.PackManager$1.run(PackManager.java:625)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: Could not wait for pack threads to finish: null
    at soot.PackManager.runBodyPacks(PackManager.java:637)
    at soot.PackManager.runBodyPacks(PackManager.java:512)
    at soot.PackManager.runPacksNormally(PackManager.java:489)
    at soot.PackManager.runPacks(PackManager.java:396)
    at soot.Main.run(Main.java:271)
    at soot.Main.main(Main.java:147)
Caused by: java.lang.InterruptedException
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:996)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1303)
    at heros.solver.CountLatch.awaitZero(CountLatch.java:75)
    at heros.solver.CountingThreadPoolExecutor.awaitCompletion(CountingThreadPoolExecutor.java:79)
    at soot.PackManager.runBodyPacks(PackManager.java:633)
    ... 5 more
</pre>

**Comment by mxphu** [comment]
Try with argument "-cp" or "-pp"
