### ISSUE TITLE
no superclass for java.lang.CharSequence

### ISSUE THREAD

**Issue by manasthakur** [Sable/soot#543]
When I use soot (with coffi) with jdk7 on an ubuntu machine, it runs fine. However, with the same command-line options, I get the following error while running on Mac OS X:

```
java.lang.RuntimeException: no superclass for java.lang.CharSequence
    at soot.SootClass.getSuperclass(SootClass.java:745)
    at soot.jimple.toolkits.typing.fast.BytecodeHierarchy.buildAncestryTree(BytecodeHierarchy.java:82)
    at soot.jimple.toolkits.typing.fast.BytecodeHierarchy.lcas_(BytecodeHierarchy.java:182)
    at soot.jimple.toolkits.typing.fast.BytecodeHierarchy.lcas_(BytecodeHierarchy.java:136)
    at soot.jimple.toolkits.typing.fast.BytecodeHierarchy.lcas(BytecodeHierarchy.java:106)
    at soot.jimple.toolkits.typing.fast.TypeResolver.applyAssignmentConstraints(TypeResolver.java:513)
    at soot.jimple.toolkits.typing.fast.TypeResolver.inferTypes(TypeResolver.java:153)
    at soot.jimple.toolkits.typing.TypeAssigner.internalTransform(TypeAssigner.java:105)
    at soot.BodyTransformer.transform(BodyTransformer.java:51)
        .........
```

I am keeping `jce.jar` and `rt.jar` in soot's classpath on both the machines.

**Comment by anddann** [comment]
@mbenz89 fixed the error for mac
