### ISSUE TITLE
java.lang.NullPointerException when ...

### ISSUE THREAD

**Issue by jyotigajrani** [Sable/soot#547]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: <pre>trunk</pre>

Command line:

<pre>-d /home/jyoti/instrumentation/sootoutput/ -allow-phantom-refs -android-jars /home/jyoti/Android/adt-bundle-linux-x86_64-20140702/sdk/platforms/ -src-prec jimple -ire -f dex -process-dir jimple_onlytelephony_ref/</pre>

Max Memory:

<pre>5461MB</pre>

Stack trace:

<pre>java.lang.NullPointerException
    at soot.toolkits.graph.UnitGraph.&#60;init&#62;(UnitGraph.java:76)
    at soot.toolkits.graph.ExceptionalUnitGraph.&#60;init&#62;(ExceptionalUnitGraph.java:158)
    at soot.jimple.toolkits.scalar.UnreachableCodeEliminator.internalTransform(UnreachableCodeEliminator.java:79)
    at soot.BodyTransformer.transform(BodyTransformer.java:51)
    at soot.Transform.apply(Transform.java:105)
    at soot.JimpleBodyPack.applyPhaseOptions(JimpleBodyPack.java:61)
    at soot.JimpleBodyPack.internalApply(JimpleBodyPack.java:95)
    at soot.Pack.apply(Pack.java:125)
    at soot.jimple.JimpleMethodSource.getBody(JimpleMethodSource.java:49)
    at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
    at soot.SootMethod.retrieveActiveBody(SootMethod.java:322)
    at soot.PackManager$3.run(PackManager.java:1223)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
</pre>

**Comment by ZhengqiaoLi** [comment]
I also met the question.Did you solve this problem?
