### ISSUE TITLE
java.util.concurrent.RejectedExecutionException when ...

### ISSUE THREAD

**Issue by jyotigajrani** [Sable/soot#548]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: <pre>trunk</pre>

Command line:

<pre>-pp soot.Main -w -allow-phantom-refs -android-jars /home/jyoti/Android/adt-bundle-linux-x86_64-20140702/sdk/platforms/ -src-prec jimple -output-format dex -process-dir sootOutput/</pre>

Max Memory:

<pre>1820MB</pre>

Stack trace:

<pre>java.util.concurrent.RejectedExecutionException: Task soot.PackManager$3@71f8a7f8 rejected from heros.solver.CountingThreadPoolExecutor@7bdbc53c[Shutting down, pool size = 3, active threads = 2, queued tasks = 0, completed tasks = 2]
    at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2048)
    at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:821)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1372)
    at heros.solver.CountingThreadPoolExecutor.execute(CountingThreadPoolExecutor.java:51)
    at soot.PackManager.retrieveAllBodies(PackManager.java:1219)
    at soot.PackManager.runPacksNormally(PackManager.java:463)
    at soot.PackManager.runPacks(PackManager.java:396)
    at soot.Main.run(Main.java:271)
    at soot.Main.main(Main.java:147)
</pre>

**Comment by jyotigajrani** [comment]
Please tell how jimple can be converted to apk back.

**Comment by SOF3** [comment]
I also reproduced this issue when trying to invoke `soot.Main.v().run()` from junit. It appears that this happens when soot.Main is invoked multiple times on different classes.
