### ISSUE TITLE
Semantic Error:no visible type named soot.PackManager when I want to process java files

### ISSUE THREAD

**Issue by WangWenshuo** [Sable/soot#556]
Excuse me.
I used the below command to process java file but error occured.
java -cp soot-trunk.jar soot.Main  -src-prec java -cp .:/usr/lib/jvm/java-1.7.0-openjdk-amd64/jre/lib/rt.jar  Test1
Soot started on Wed Mar 16 01:20:55 CST 2016
/home/wws/IFDS/soot/test/Test1.java:3,8:
  Semantic Error: no visible type named soot.PackManager
soot.CompilationDeathException: there were errors during parsing and/or type checking (JastAdd frontend)
    at soot.JastAddInitialResolver.formAst(JastAddInitialResolver.java:63)
    at soot.JavaClassSource.resolve(JavaClassSource.java:54)
    at soot.SootResolver.bringToHierarchy(SootResolver.java:239)
    at soot.SootResolver.bringToSignatures(SootResolver.java:266)
    at soot.SootResolver.processResolveWorklist(SootResolver.java:170)
    at soot.SootResolver.resolveClass(SootResolver.java:131)
    at soot.Scene.loadClass(Scene.java:725)
    at soot.Scene.loadClassAndSupport(Scene.java:710)
    at soot.Scene.loadNecessaryClass(Scene.java:1425)
    at soot.Scene.loadNecessaryClasses(Scene.java:1436)
    at soot.Main.run(Main.java:243)
    at soot.Main.main(Main.java:147)

Ouuups... something went wrong! Sorry about that.

Would you please tell me how can I do to solve the problem?Thank you very much.

Sincerely.

**Comment by anddann** [comment]
JastAdd is deprecated please use the ASM frontend
