### ISSUE TITLE
Writing out Jimple class "to" and reading back in does not work

### ISSUE THREAD

**Issue by MarcMil** [Sable/soot#599]
Writing out Jimple class "to" and reading back in does not work

The problem lies in the SkeletonExtractorWalker:

            if(!className.equals(Scene.v().quotedNameOf(mSootClass.getName())))
                throw new RuntimeException("expected:  " + className + ", but got: " + mSootClass.getName());

Problem is that quotedNameOf("to") is "'to'", which does not match "to". IMHO this should not be quotedNameOf, but rather the unquoted name.

**Comment by roylin1994** [comment]
@MarcMil @StevenArzt 
This Bug seems that haven't fixed.
When I convert jimple files to DEX files,it reported error:

> F:\Master\AndroidSecurity\APK>java -Xmx6g -jar soot-trunk.jar soot.Main -w -allow-phantom-refs -android-jars D:\AndroidSDK\platforms\ -src-prec jimple -f dex -process-dir sootOutput\
Soot started on Sat Jul 09 09:15:07 CST 2016
Warning: java.lang.invoke.LambdaMetafactory is a phantom class!
java.lang.RuntimeException: expected:  android.'annotation'.SuppressLint, but got: android.annotation.SuppressLint
        at soot.jimple.parser.SkeletonExtractorWalker.caseAFile(SkeletonExtractorWalker.java:80)
        at soot.jimple.parser.node.AFile.apply(AFile.java:61)
        at soot.jimple.parser.analysis.DepthFirstAdapter.caseStart(DepthFirstAdapter.java:34)
        at soot.jimple.parser.node.Start.apply(Start.java:37)
        at soot.jimple.parser.JimpleAST.getSkeleton(JimpleAST.java:78)
        at soot.JimpleClassSource.resolve(JimpleClassSource.java:44)
        at soot.SootResolver.bringToHierarchy(SootResolver.java:243)
        at soot.SootResolver.bringToSignatures(SootResolver.java:275)
        at soot.SootResolver.bringToBodies(SootResolver.java:313)
        at soot.SootResolver.processResolveWorklist(SootResolver.java:166)
        at soot.SootResolver.resolveClass(SootResolver.java:134)
        at soot.Scene.loadClass(Scene.java:805)
        at soot.Scene.loadClassAndSupport(Scene.java:790)
        at soot.Scene.loadNecessaryClasses(Scene.java:1528)
        at soot.Main.run(Main.java:243)
        at soot.Main.main(Main.java:147)

APK is the same with [https://github.com/Sable/soot/issues/610](url)
I have mailed to MarcMil.
Soot edition is the newest.
