### ISSUE TITLE
Hello,I have a question! 

### ISSUE THREAD

**Issue by wcfTom** [Sable/soot#604]
Exception in thread "main" java.lang.RuntimeException: couldn't find class: D (is your soot-class-path set properly?)
    at soot.SootResolver.bringToHierarchy(SootResolver.java:184)
    at soot.SootResolver.bringToSignatures(SootResolver.java:219)
    at soot.SootResolver.processResolveWorklist(SootResolver.java:139)
    at soot.SootResolver.resolveClass(SootResolver.java:124)
    at soot.Scene.loadClass(Scene.java:425)
    at soot.Scene.loadClassAndSupport(Scene.java:410)
    at soot.Scene.loadNecessaryClass(Scene.java:1010)
    at soot.Scene.loadNecessaryClasses(Scene.java:1024)
    at soot.Main.run(Main.java:167)
    at soot.Main.main(Main.java:141)
    at soot.tools.CFGViewer.main(CFGViewer.java:101)
    at Example.main(Example.java:30)

**Comment by suvamM** [comment]
You probably need to set the soot class path appropriately using the -cp option. It would be more helpful if you could provide the full command you are trying to run.
