### ISSUE TITLE
how set soot-class-path on window7

### ISSUE THREAD

**Issue by snowcool** [Sable/soot#609]
The problem is below, I don't know why it can not find rt.jar, because the path is right, can someone give me a help? thank you very much. 
D:\SOOT\code>java -cp soot-trunk.jar soot.Main -cp . D:\ProgramFiles\Java\jdk1.7.0_79\jre\lib\rt.jar A B
Soot started on Wed Jun 22 16:28:12 CST 2016
soot.SootResolver$SootClassNotFoundException: couldn't find class: D:\ProgramFiles\Java\jdk1.7.0_79\jre\lib\rt.jar (is your soot-class-path set properly?)
        at soot.SootResolver.bringToHierarchy(SootResolver.java:232)
        at soot.SootResolver.bringToSignatures(SootResolver.java:275)
        at soot.SootResolver.processResolveWorklist(SootResolver.java:173)
        at soot.SootResolver.resolveClass(SootResolver.java:134)
        at soot.Scene.loadClass(Scene.java:786)
        at soot.Scene.loadClassAndSupport(Scene.java:771)
        at soot.Scene.loadNecessaryClass(Scene.java:1486)
        at soot.Scene.loadNecessaryClasses(Scene.java:1497)
        at soot.Main.run(Main.java:243)
        at soot.Main.main(Main.java:147)

**Comment by njupt-moon** [comment]
@StevenArzt 
Hi!
Currently, Soot still cannot handle such argument "-cp C:/A.jar:C:/B.jar" well on windows.

**Comment by snowcool** [comment]
Thank you very much.

**Comment by StevenArzt** [comment]
Well, the original command line is wrong. If you want to have the current directory and the rt.jar file on the classpath, you must separate the two using a colon, not a blank.
