### ISSUE TITLE
Convert Jimple to dex and repack dex to apk,apk can't run on the device.

### ISSUE THREAD

**Issue by roylin1994** [Sable/soot#610]
@MarcMil @StevenArzt 
[https://groups.google.com/forum/?hl=zh-Cn#!topic/soot-list/gkPV_7a_Iu0](url)
Background is shown in link.
I have faced the same problem with Dave.I'll show my steps below.The newest soot edition has Bug.It seems this Bug haven't be fixed clean. 
[https://github.com/Sable/soot/issues/599](url)
So I used the older edtion-2016\5\18(11533KB)
The command below is refer to [http://stackoverflow.com/questions/35824931/exception-in-converting-jimple-to-dex-using-soot#](url)

1. Convert APK to Jimple files:
`java -Xmx6g -jar soot-trunk.jar soot.Main -w -allow-phantom-refs -android-jars D:\AndroidSDK\platforms\ -src-prec apk -f jimple -process-dir ActivityLifeCycleTest.apk`
This command will output jimple files into sootOutput directory.

1. Convert Jimple files back to dex files:
`java -Xmx6g -jar soot-trunk.jar soot.Main -w -allow-phantom-refs -android-jars D:\AndroidSDK\platforms\ -src-prec jimple -f dex -process-dir sootOutput\`
DEX file will output to sootOutput directory.
For this step,one point should be noticed.
[https://github.com/Sable/soot/issues/565#issuecomment-230958531](url)
Soot now doesn't support dex spilt.Hope Soot can support dex splitter some days,otherwise Soot cann't support well to the big real-world apks.

1. Repack the new DEX file with the original.

1. Sign the new APK.I didn't zipalign it,which wouldn't influence the result.
After I use the new APK to run on the device,the error is below:
> java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.example.activitylifecycletest/com.example.activitylifecycletest.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.example.activitylifecycletest.MainActivity" on path: DexPathList[[zip file "/data/app/com.example.activitylifecycletest-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.activitylifecycletest-1/lib/arm, /vendor/lib, /system/lib]]
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2334)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483)
	at android.app.ActivityThread.access$900(ActivityThread.java:153)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5438)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.activitylifecycletest.MainActivity" on path: DexPathList[[zip file "/data/app/com.example.activitylifecycletest-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.activitylifecycletest-1/lib/arm, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1068)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2324)
	... 9 more
	Suppressed: java.io.IOException: Failed to open dex files from /data/app/com.example.activitylifecycletest-1/base.apk
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:80)
		at dalvik.system.DexFile.<init>(DexFile.java:59)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:279)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:65)
		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:57)
		at android.app.LoadedApk.getClassLoader(LoadedApk.java:376)
		at android.app.LoadedApk.makeApplication(LoadedApk.java:570)
		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4699)
		at android.app.ActivityThread.access$1600(ActivityThread.java:153)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412)
		... 6 more
	Suppressed: java.lang.ClassNotFoundException: com.example.activitylifecycletest.MainActivity
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 12 more
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

It seems my error report dind't all the same with Dave,And also didn't appear this error。But I think it may be also a Bug.

> Failure to verify dex file '/data/app/com.example.webb.test4-1/base.apk': Invalid type descriptor: 'Ljava/lang/'annotation'/Annotation;'
the "'" around annotation is because "annotation" is also a keyword, which needs to be escaped in the Jimple files, but should not be escaped in the dex file. Apparently soot does not unescape this.

@MarcMil 
The soot edition and APK I'll send you email.

**Comment by roylin1994** [comment]
In this issue,I also want to discuss with you about Soot apk's instrumentation.
Soot has two methods to do the instrumentation.

1. Convert APK to jimple files,then modify jimple files and convert jimple files back to DEX file.And repack DEX file to APK to run on the device.
This method has some problems:

- Soot doesn't support dex file splitter now.So When facing the big real-world apks,Soot can't convert jimple files to multiple dex files.And we can't repack to APK. I think this is a serious problem.

- When Soot can convert jimple files to dex file successfully.But APK after repacked can't run on the device,which is report in this issue.

- But it is also a large proporton When Soot can't convert jimple files to DEX file successfully.This error has many kinds,one of which is [https://github.com/Sable/soot/issues/599](url).And I have also meet other errors.

So first method has many problems.But I think Soot should solve problems above for that: Soot suggests developers to manually instrumentation first to verify whether is the instrumenation is right.And to do the instrumentation automately by Soot's API.But if this method has too many questions,we can't do this verify step.

1. And the other method:
With the help of Soot Eclipse-pulgin,we can instrument an apk in Eclipse IDE.And set the output format: 
`Options.v().set_output_format(Options.output_format_dex);`
This method also have problem.When I haven't done any instrumentation to APK,but I let apk transformed by Soot.It also has two problem:

- Soot cann't transform apk(big real-world apk) to new apk successfully,which will report some kinds of errors.If you need,I can post it later.

- The other situation is that Soot can transfom apk successfully.But after signed,new apk can't run on the device.It also have bug report.if you need,I can also post it later.

This two method have its own problem.And these problems make Soot can't perform well when instrumentation the real-world apk.

**Comment by roylin1994** [comment]
@StevenArzt Hope you can reply and give some advices.

**Comment by MarcMil** [comment]
Sorry for the late reply, had some work to do.
Well, the bug is quite simple to find.
A fix has been filed as pull request.
https://github.com/Sable/soot/pull/613

@StevenArzt We should consider creating a test case out of it. It is really that simple: Having any app with android.support.v4.annotation.X as a class name, writing out as Jimple and reading it back in.

**Comment by roylin1994** [comment]
@MarcMil 
Thanks for reply and solve.
For you commit,can it solve this issue?
#599 
After Steven merge this commit,I'll try and give feedback.

**Comment by MarcMil** [comment]
https://github.com/Sable/soot/issues/599 should be fixed with the same patch; these problems are related.
