### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException when ...

### ISSUE THREAD

**Issue by zhhailon** [Sable/soot#612]
Steps to reproduce:

Files used to reproduce: [link](https://drive.google.com/file/d/0BwijI6W2dHTxM19FQjZOd0dKVkU/view?usp=sharing)

Soot version: <pre>trunk</pre>

Command line:

<pre>-w -p cg.gui enabled:true -f n -keep-line-number -allow-phantom-refs -process-dir $HOME/org.isoron.uhabits_19forEclipseProject/bin/classes -cp $HOME/Android/Sdk/platforms/android-23/android.jar</pre>

where `cg.gui` is a customized phase.

Max Memory:

<pre>3547MB</pre>

Stack trace:

<pre>java.lang.ArrayIndexOutOfBoundsException: 6
    at org.objectweb.asm.ClassReader.readShort(ClassReader.java:2336)
    at org.objectweb.asm.ClassReader.&#60;init&#62;(ClassReader.java:169)
    at org.objectweb.asm.ClassReader.&#60;init&#62;(ClassReader.java:153)
    at org.objectweb.asm.ClassReader.&#60;init&#62;(ClassReader.java:424)
    at soot.asm.AsmClassSource.read(AsmClassSource.java:55)
    at soot.asm.AsmClassSource.resolve(AsmClassSource.java:65)
    at soot.SootResolver.bringToHierarchy(SootResolver.java:243)
    at soot.SootResolver.bringToSignatures(SootResolver.java:275)
    at soot.SootResolver.bringToBodies(SootResolver.java:313)
    at soot.SootResolver.processResolveWorklist(SootResolver.java:166)
    at soot.SootResolver.resolveClass(SootResolver.java:134)
    at soot.Scene.tryLoadClass(Scene.java:774)
    at soot.Scene.loadBasicClasses(Scene.java:1434)
    at soot.Scene.loadNecessaryClasses(Scene.java:1513)
    at soot.Main.run(Main.java:243)
    at soot.Main.main(Main.java:147)
    at presto.android.Main.setupAndInvokeSootHelper(Main.java:264)
    at presto.android.Main.setupAndInvokeSoot(Main.java:227)
    at presto.android.Main.main(Main.java:34)
    at TestSootAndroid.main(TestSootAndroid.java:30)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
</pre>

**Comment by anddann** [comment]
works on soot release 4.0
