### ISSUE TITLE
java.lang.NullPointerException when creating soot.toolkits.graph.pdg.EnhancedUnitGraph

### ISSUE THREAD

**Issue by smover** [Sable/soot#618]
Description of the bug:
I get a NullPointerException when creating the EnhancedUnitGraph from a method body.

The program just try to create an EnhancedUnitGraph in a method transformer:

`````` java

[bugnpe.zip](https://github.com/Sable/soot/files/398412/bugnpe.zip)
 public static void main(String[] args) {
    // Inject the analysis tagger into Soot
    PackManager.v().getPack("jtp").add(new Transform("jtp.myTransforma", new BodyTransformer() {
        protected void internalTransform(Body body, String phase, java.util.Map<String,String> options)
        {
          new EnhancedUnitGraph(body);
        }
      }));

    Options.v().set_verbose(true);
    // PhaseOptions.v().setPhaseOption("jtp", "on");
    // Invoke soot.Main with arguments given
    soot.Main.main(args);

    return;
  }```

Steps to reproduce:
- unzip bugnpe.zip
- add soot-trunk.jar to the lib folder
- build the program: `gradle build`
- run the program: java -classpath  .:./lib/soot-trunk.jar:./build/classes/main edu.colorado.plv.Main -cp <path-to-rt.jar>:./test simple.TestException

Files used to reproduce: The program and the test case are in the attached bugnpe.zip

Soot version: <pre>trunk</pre>
I used the nightly build of the 02-Aug-2016, 03:44

Command line:
<pre>-cp /usr/lib/jvm/jdk1.7.0/jre/lib/rt.jar:./test simple.TestException</pre>

Max Memory:
<pre>1708MB</pre>

Stack trace:
<pre>java.lang.NullPointerException
    at soot.toolkits.graph.pdg.EnhancedUnitGraph.addAuxiliaryExceptionalEdges(EnhancedUnitGraph.java:386)
    at soot.toolkits.graph.pdg.EnhancedUnitGraph.&#60;init&#62;(EnhancedUnitGraph.java:80)
    at edu.colorado.plv.Main$1.internalTransform(Main.java:42)
    at soot.BodyTransformer.transform(BodyTransformer.java:54)
    at soot.Transform.apply(Transform.java:105)
    at soot.BodyPack.internalApply(BodyPack.java:49)
    at soot.Pack.apply(Pack.java:125)
    at soot.PackManager.runBodyPacks(PackManager.java:986)
    at soot.PackManager.access$000(PackManager.java:138)
    at soot.PackManager$1.run(PackManager.java:633)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
</pre>
``````

**Comment by mbenz89** [comment]
Solved by https://github.com/Sable/soot/pull/1250
