### ISSUE TITLE
Exceptions while running 'jython' on DaCapo 9.12

### ISSUE THREAD

**Issue by gsridhar53** [Sable/soot#652]
Hi,

I am trying to analyze the 'jython' program from the dacapo-9.12-bach benchmark using Tamiflex 2.0.3, soot-trunk and java-8.

While executing using the play-out agent, I get the following exception:
`
 Exception in thread "Thread-0" java.lang.IllegalStateException: ClassReader.accept() should be called with EXPAND_FRAMES flag at org.objectweb.asm.commons.LocalVariablesSorter.visitFrame(Unknown Source) at org.objectweb.asm.commons.RemappingMethodAdapter.visitFrame(Unknown Source) at org.objectweb.asm.MethodAdapter.visitFrame(Unknown Source) at org.objectweb.asm.ClassReader.accept(Unknown Source) at org.objectweb.asm.ClassReader.accept(Unknown Source) at de.bodden.tamiflex.normalizer.Hasher.generateHashNumber(Hasher.java:99) at de.bodden.tamiflex.playout.ClassDumper.writeClassesToDisk(ClassDumper.java:84) at de.bodden.tamiflex.playout.Agent$1.run(Agent.java:123)
`

When I set `dontNormalize` flag in the poa.properties file, the play-out agent finishes successfully. But when I run Soot, it goes to an infinite loop while applying the SparkTransformer.

Can you please let me know how to handle this?

**Comment by pavanupb** [comment]
@sridhargopinath Is this still relevant?

**Comment by nvvishnu** [comment]
Hey! I am facing the same issue with the exact setup described. Any advice on how to resolve this?
