### ISSUE TITLE
ConcurrentModificationException in ExceptionFinder

### ISSUE THREAD

**Issue by davidmoten** [Sable/soot#668]
`ExceptionFinder` has this fragment:

```java
IterableSet<AugmentedStmt> try_body = en.get_TryBody();

for (AugmentedStmt tras : try_body) {
	for (AugmentedStmt pas : tras.cpreds) {
		Stmt ps = pas.get_Stmt();

		if ((try_body.contains(pas) == false)
				&& (ps instanceof GotoStmt)) {
			boolean add_it = true;

			for (AugmentedStmt pred : pas.cpreds)
				if ((add_it = try_body.contains(pred)) == false)
					break;

			if (add_it)
				en.add_TryStmt(pas);
		}
	}
}
```

if `add_it` is true then `try_body` can be modified by the call to `en.add_TryStmt(pas)` and thus the `ConcurrentModificationException` occurs on the next loop (calling `hasNext`). Given the intent I assume a different data structure would be appropriate that doesn't suffer from this limitation (like  a `Queue` that gets polled in a loop). Do you agree?

```
java.util.ConcurrentModificationException
	at soot.util.HashChain$LinkIterator.hasNext(HashChain.java:674)
	at soot.dava.toolkits.base.finders.ExceptionFinder.preprocess(ExceptionFinder.java:90)
	at soot.dava.DavaBody.<init>(DavaBody.java:321)
	at soot.dava.Dava.newBody(Dava.java:84)
	at soot.PackManager.runBodyPacks(PackManager.java:1018)
	at soot.PackManager.access$0(PackManager.java:883)
	at soot.PackManager$1.run(PackManager.java:633)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by priand** [comment]
I just got the same exception. There is a similar one in ExceptionNode #190. I easily fixed them locally, but then I'm got other exceptions going forward (ex: Could not verify approximated Synchronized body!, NullPointerException...)

Is Dava a "supported" part of Soot of is it considered as a nice attempt but will not get more attention? It is a great piece of software, but it seems to be unstable and stale. Should we bother reporting any issue and eventually pull requests?

**Comment by davidmoten** [comment]
Does the code still exist? It's an obvious bug isn't it? I'm not using the product at the moment but if you are interested in maintaining the product seems like an easy one to fix.
