### ISSUE TITLE
Can't run mvn install successfully

### ISSUE THREAD

**Issue by khatchad** [Sable/soot#687]
I've checked out revision 8ef2307f45b957894577582738499a2e79fa9e70, which is the last stable version according to Jenkins. I tried to build soot locally via `mvn install`, however, I am having trouble running the tests:

```
$ mvn clean install
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for ca.mcgill.sable:soot:jar:2016-07-27
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:build-helper-maven-plugin is missing. @ line 25, column 15
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Soot 2016-07-27
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ soot ---
[INFO] Deleting /home/rk1424/Documents/soot/target
[INFO] 
[INFO] --- build-helper-maven-plugin:1.12:add-source (default) @ soot ---
[INFO] Source directory: /home/rk1424/Documents/soot/generated/singletons added.
[INFO] Source directory: /home/rk1424/Documents/soot/generated/sablecc added.
[INFO] Source directory: /home/rk1424/Documents/soot/generated/options added.
[INFO] Source directory: /home/rk1424/Documents/soot/generated/jastadd added.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ soot ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/rk1424/Documents/soot/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ soot ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2751 source files to /home/rk1424/Documents/soot/target/classes
[INFO] /home/rk1424/Documents/soot/src/soot/SootMethod.java: Some input files use or override a deprecated API.
[INFO] /home/rk1424/Documents/soot/src/soot/SootMethod.java: Recompile with -Xlint:deprecation for details.
[INFO] /home/rk1424/Documents/soot/src/soot/Scene.java: Some input files use unchecked or unsafe operations.
[INFO] /home/rk1424/Documents/soot/src/soot/Scene.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ soot ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/rk1424/Documents/soot/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ soot ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 87 source files to /home/rk1424/Documents/soot/target/test-classes
[WARNING] /home/rk1424/Documents/soot/tests/soot/asm/backend/ConstantPoolTest.java:[19,50] com.sun.org.apache.bcel.internal.classfile.ClassFormatException is internal proprietary API and may be removed in a future release
[WARNING] /home/rk1424/Documents/soot/tests/soot/asm/backend/ConstantPoolTest.java:[223,26] com.sun.org.apache.bcel.internal.classfile.ClassFormatException is internal proprietary API and may be removed in a future release
[INFO] /home/rk1424/Documents/soot/tests/soot/toolkits/exceptions/UnitThrowAnalysisTest.java: Some input files use unchecked or unsafe operations.
[INFO] /home/rk1424/Documents/soot/tests/soot/toolkits/exceptions/UnitThrowAnalysisTest.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ soot ---
[INFO] Surefire report directory: /home/rk1424/Documents/soot/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
Configuring TestNG with: TestNG652Configurator
Configuring TestNG with: TestNG652Configurator
Soot started on Fri Dec 23 15:11:13 EST 2016
java.lang.RuntimeException: /home/rk1424/Documents/soot/testclasses does not exists
	at soot.SourceLocator.getClassSourceType(SourceLocator.java:185)
	at soot.SourceLocator.lookupInClassPath(SourceLocator.java:549)
	at soot.asm.AsmClassProvider.find(AsmClassProvider.java:35)
	at soot.SourceLocator.getClassSource(SourceLocator.java:75)
	at soot.Scene.tryLoadClass(Scene.java:762)
	at soot.Scene.loadBasicClasses(Scene.java:1434)
	at soot.Scene.loadNecessaryClasses(Scene.java:1513)
	at soot.Main.run(Main.java:250)
	at soot.Main.main(Main.java:147)
	at soot.asm.backend.AbstractASMBackendTest.runSoot(AbstractASMBackendTest.java:63)
	at soot.asm.backend.AbstractASMBackendTest.setupTest(AbstractASMBackendTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at org.testng.junit.JUnit4TestRunner.start(JUnit4TestRunner.java:81)
	at org.testng.junit.JUnit4TestRunner.run(JUnit4TestRunner.java:69)
	at org.testng.TestRunner$1.run(TestRunner.java:682)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1008)
	at org.testng.TestRunner.privateRunJUnit(TestRunner.java:713)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:211)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)


Ouuups... something went wrong! Sorry about that.
Follow these steps to fix the problem:
1.) Are you sure you used the right command line?
    Click here to double-check:
    https://ssebuild.cased.de/nightly/soot/doc/soot_options.htm

2.) Not sure whether it's a bug? Feel free to discuss
    the issue on the Soot mailing list:
    https://github.com/Sable/soot/wiki/Getting-help

3.) Sure it's a bug? Click this link to report it.
    https://github.com/Sable/soot/issues/new?title=java.lang.RuntimeException+when+...&body=Steps+to+reproduce%3A%0A1.%29+...%0A%0AFiles+used+to+reproduce%3A+%0A...%0A%0ASoot+version%3A+%3Cpre%3Etrunk%3C%2Fpre%3E%0A%0ACommand+line%3A%0A%3Cpre%3E-cp+.%2Ftestclasses%3A%2Fusr%2Flib%2Fjvm%2Fjava-8-openjdk-amd64%2Fjre%2Flib%2Frt.jar+-src-prec+only-class+-output-format+asm+-allow-phantom-refs+-java-version+default+soot.asm.backend.targets.Monitor%3C%2Fpre%3E%0A%0AMax+Memory%3A%0A%3Cpre%3E3481MB%3C%2Fpre%3E%0A%0AStack+trace%3A%0A%3Cpre%3Ejava.lang.RuntimeException%3A+%2Fhome%2Frk1424%2FDocuments%2Fsoot%2Ftestclasses+does+not+exists%0A%09at+soot.SourceLocator.getClassSourceType%28SourceLocator.java%3A185%29%0A%09at+soot.SourceLocator.lookupInClassPath%28SourceLocator.java%3A549%29%0A%09at+soot.asm.AsmClassProvider.find%28AsmClassProvider.java%3A35%29%0A%09at+soot.SourceLocator.getClassSource%28SourceLocator.java%3A75%29%0A%09at+soot.Scene.tryLoadClass%28Scene.java%3A762%29%0A%09at+soot.Scene.loadBasicClasses%28Scene.java%3A1434%29%0A%09at+soot.Scene.loadNecessaryClasses%28Scene.java%3A1513%29%0A%09at+soot.Main.run%28Main.java%3A250%29%0A%09at+soot.Main.main%28Main.java%3A147%29%0A%09at+soot.asm.backend.AbstractASMBackendTest.runSoot%28AbstractASMBackendTest.java%3A63%29%0A%09at+soot.asm.backend.AbstractASMBackendTest.setupTest%28AbstractASMBackendTest.java%3A50%29%0A%09at+sun.reflect.NativeMethodAccessorImpl.invoke0%28Native+Method%29%0A%09at+sun.reflect.NativeMethodAccessorImpl.invoke%28NativeMethodAccessorImpl.java%3A62%29%0A%09at+sun.reflect.DelegatingMethodAccessorImpl.invoke%28DelegatingMethodAccessorImpl.java%3A43%29%0A%09at+java.lang.reflect.Method.invoke%28Method.java%3A498%29%0A%09at+org.junit.runners.model.FrameworkMethod%241.runReflectiveCall%28FrameworkMethod.java%3A47%29%0A%09at+org.junit.internal.runners.model.ReflectiveCallable.run%28ReflectiveCallable.java%3A12%29%0A%09at+org.junit.runners.model.FrameworkMethod.invokeExplosively%28FrameworkMethod.java%3A44%29%0A%09at+org.junit.internal.runners.statements.RunBefores.evaluate%28RunBefores.java%3A24%29%0A%09at+org.junit.runners.ParentRunner.runLeaf%28ParentRunner.java%3A271%29%0A%09at+org.junit.runners.BlockJUnit4ClassRunner.runChild%28BlockJUnit4ClassRunner.java%3A70%29%0A%09at+org.junit.runners.BlockJUnit4ClassRunner.runChild%28BlockJUnit4ClassRunner.java%3A50%29%0A%09at+org.junit.runners.ParentRunner%243.run%28ParentRunner.java%3A238%29%0A%09at+org.junit.runners.ParentRunner%241.schedule%28ParentRunner.java%3A63%29%0A%09at+org.junit.runners.ParentRunner.runChildren%28ParentRunner.java%3A236%29%0A%09at+org.junit.runners.ParentRunner.access%24000%28ParentRunner.java%3A53%29%0A%09at+org.junit.runners.ParentRunner%242.evaluate%28ParentRunner.java%3A229%29%0A%09at+org.junit.runners.ParentRunner.run%28ParentRunner.java%3A309%29%0A%09at+org.junit.runner.JUnitCore.run%28JUnitCore.java%3A160%29%0A%09at+org.junit.runner.JUnitCore.run%28JUnitCore.java%3A138%29%0A%09at+org.testng.junit.JUnit4TestRunner.start%28JUnit4TestRunner.java%3A81%29%0A%09at+org.testng.junit.JUnit4TestRunner.run%28JUnit4TestRunner.java%3A69%29%0A%09at+org.testng.TestRunner%241.run%28TestRunner.java%3A682%29%0A%09at+org.testng.TestRunner.runWorkers%28TestRunner.java%3A1008%29%0A%09at+org.testng.TestRunner.privateRunJUnit%28TestRunner.java%3A713%29%0A%09at+org.testng.TestRunner.run%28TestRunner.java%3A614%29%0A%09at+org.testng.SuiteRunner.runTest%28SuiteRunner.java%3A348%29%0A%09at+org.testng.SuiteRunner.runSequentially%28SuiteRunner.java%3A343%29%0A%09at+org.testng.SuiteRunner.privateRun%28SuiteRunner.java%3A305%29%0A%09at+org.testng.SuiteRunner.run%28SuiteRunner.java%3A254%29%0A%09at+org.testng.SuiteRunnerWorker.runSuite%28SuiteRunnerWorker.java%3A52%29%0A%09at+org.testng.SuiteRunnerWorker.run%28SuiteRunnerWorker.java%3A86%29%0A%09at+org.testng.TestNG.runSuitesSequentially%28TestNG.java%3A1224%29%0A%09at+org.testng.TestNG.runSuitesLocally%28TestNG.java%3A1149%29%0A%09at+org.testng.TestNG.run%28TestNG.java%3A1057%29%0A%09at+org.apache.maven.surefire.testng.TestNGExecutor.run%28TestNGExecutor.java%3A115%29%0A%09at+org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti%28TestNGDirectoryTestSuite.java%3A211%29%0A%09at+org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute%28TestNGDirectoryTestSuite.java%3A107%29%0A%09at+org.apache.maven.surefire.testng.TestNGProvider.invoke%28TestNGProvider.java%3A112%29%0A%09at+org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader%28ForkedBooter.java%3A200%29%0A%09at+org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess%28ForkedBooter.java%3A153%29%0A%09at+org.apache.maven.surefire.booter.ForkedBooter.main%28ForkedBooter.java%3A103%29%0A%3C%2Fpre%3E
    Please be as precise as possible when giving us
    information on how to reproduce the problem. Thanks!

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.016 s
[INFO] Finished at: 2016-12-23T15:11:13-05:00
[INFO] Final Memory: 32M/907M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project soot: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/rk1424/Documents/soot && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -jar /home/rk1424/Documents/soot/target/surefire/surefirebooter2034222162293027651.jar /home/rk1424/Documents/soot/target/surefire/surefire3544838759992452993tmp /home/rk1424/Documents/soot/target/surefire/surefire_06521888973021421014tmp
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Comment by anddann** [comment]
Hi @khatchad ,
unfortunately, you tried to build soot during the time @mbenz89 migrated the ant build system to maven.
In 8ef2307, the maven-antrun-plugin was not configured in the pom.xml. This plugin generates the test classes, which are required to run all tests.
Now, @mbenz89 migrated everything to maven successfully.
Does the error still persist?

**Comment by anddann** [comment]
Since there has not been an answer for 2 years I close the issue.
