### ISSUE TITLE
[CFGViewer] couldn't find class: java.lang.Object

### ISSUE THREAD

**Issue by astefano** [Sable/soot#699]
Hi, 

I try to experiment with CFGViewer but i have this error:

`~/tools/soot_experiments$ java -cp soot-trunk.jar soot.tools.CFGViewer -cp .:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar ExceptionalGraphDemo
Soot started on Mon Feb 20 13:42:18 CET 2017
soot.SootResolver$SootClassNotFoundException: couldn't find class: java.lang.Object (is your soot-class-path set properly?) Try adding rt.jar to Soot's classpath, e.g.:
java -cp sootclasses.jar soot.Main -cp .:/path/to/jdk/jre/lib/rt.jar <other options>
	at soot.SootResolver.bringToHierarchy(SootResolver.java:232)
	at soot.SootResolver.bringToSignatures(SootResolver.java:275)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:173)
	at soot.SootResolver.resolveClass(SootResolver.java:134)
	at soot.Scene.loadClass(Scene.java:873)
	at soot.Scene.loadClassAndSupport(Scene.java:858)
	at soot.Scene.loadNecessaryClass(Scene.java:1575)
	at soot.Scene.loadNecessaryClasses(Scene.java:1586)
	at soot.Main.run(Main.java:250)
	at soot.Main.main(Main.java:147)
	at soot.tools.CFGViewer.main(CFGViewer.java:101)
` 

Running soot.Main seems to work fine:

`~/tools/soot_experiments$ java -cp soot-trunk.jar soot.Main -cp .:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar ExceptionalGraphDemo
Warning: Phase jb.dtr is not a standard Soot phase listed in XML files.
Soot started on Mon Feb 20 13:41:59 CET 2017
Transforming ExceptionalGraphDemo... 
Writing to sootOutput/ExceptionalGraphDemo.class
Soot finished on Mon Feb 20 13:42:01 CET 2017
Soot has run for 0 min. 1 sec.
`
Any clue what i'm missing?

Cheers,
Lacramioara

**Comment by astefano** [comment]
solved it with -pp: 

`:~/tools/soot_experiments$ java -cp soot-trunk.jar soot.tools.CFGViewer -cp . -pp ExceptionalGraphDemo`

`Soot started on Mon Feb 20 13:48:33 CET 2017
Transforming ExceptionalGraphDemo... 
Generate dot file in sootOutput/ExceptionalGraphDemo void <init>().dot
Generate dot file in sootOutput/ExceptionalGraphDemo void method0(int[],int,int).dot
Generate dot file in sootOutput/ExceptionalGraphDemo void method1(int[],int,int).dot
Generate dot file in sootOutput/ExceptionalGraphDemo void method2(int[],int,int,int).dot
Writing to sootOutput/ExceptionalGraphDemo.class
Soot finished on Mon Feb 20 13:48:35 CET 2017
Soot has run for 0 min. 1 sec.`
