### ISSUE TITLE
NoSuchMethodError happen when updated soot-trunk.jar

### ISSUE THREAD

**Issue by bertram-zbc** [Sable/soot#714]
```
import java.util.Collections;

import soot.PackManager;
import soot.Scene;
import soot.Transform;
import soot.options.Options;

public class Main {

	private static boolean SOOT_INITIALIZED=false;
	private final static String androidJAR=...;
	private final static String appApk=...;
	public static void initialiseSoot()
	{
		if(SOOT_INITIALIZED)
			return;
		Options.v().set_allow_phantom_refs(true);
		Options.v().set_prepend_classpath(true);
		Options.v().set_validate(true);
		Options.v().set_whole_program(true);
		
		Options.v().set_output_format(Options.output_format_dex);
		Options.v().set_process_dir(Collections.singletonList(appApk));
		Options.v().set_force_android_jar(androidJAR);
		Options.v().set_src_prec(Options.src_prec_apk);
		Options.v().set_soot_classpath(androidJAR);
		Scene.v().loadNecessaryClasses();
		SOOT_INITIALIZED=true;
		
	}
	public static void main(String[] args)
	{
		initialiseSoot();
		
		PackManager.v().getPack("jtp").add(new Transform("jtp.AndroidCFG", new AndroidWidgetRecord()));
		PackManager.v().runPacks();
		
```

When I used the former version of soot-trunk,jar, it can run successfully, but when I updated soot-trunk, some mistakes happen:
```
Exception in thread "main" java.lang.NoSuchMethodError: java.util.Map.putIfAbsent(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
	at soot.util.StringNumberer.findOrAdd(StringNumberer.java:38)
	at soot.SootMethod.<init>(SootMethod.java:179)
	at soot.dexpler.DexMethod.makeSootMethod(DexMethod.java:111)
	at soot.dexpler.DexClassLoader.loadMethod(DexClassLoader.java:36)
	at soot.dexpler.DexClassLoader.makeSootClass(DexClassLoader.java:105)
	at soot.dexpler.DexlibWrapper.makeSootClass(DexlibWrapper.java:183)
	at soot.dexpler.DexResolver.resolveFromFile(DexResolver.java:60)
	at soot.DexClassSource.resolve(DexClassSource.java:52)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:243)
	at soot.SootResolver.bringToSignatures(SootResolver.java:275)
	at soot.SootResolver.bringToBodies(SootResolver.java:313)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:166)
	at soot.SootResolver.resolveClass(SootResolver.java:134)
	at soot.dexpler.DexlibWrapper.initialize(DexlibWrapper.java:165)
	at soot.dexpler.DexResolver.resolveFromFile(DexResolver.java:57)
	at soot.DexClassSource.resolve(DexClassSource.java:52)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:243)
	at soot.SootResolver.bringToSignatures(SootResolver.java:275)
	at soot.SootResolver.bringToBodies(SootResolver.java:313)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:166)
	at soot.SootResolver.resolveClass(SootResolver.java:134)
	at soot.Scene.loadClass(Scene.java:873)
	at soot.Scene.loadClassAndSupport(Scene.java:858)
	at soot.Scene.loadNecessaryClasses(Scene.java:1598)
```

How would this happen?

**Comment by mbenz89** [comment]
I am not able to reproduce the problem with my configuration.
Seems like a Java related issue to me. Which Java version are you using? Have you tried the newest version?

Can you provide the "AndroidWidgetRecord" class?

**Comment by Xyrio** [comment]
same problem here but not for android code

java.util.Map.putIfAbsent was introduced with java 1.8 and soot is using it!!!

soot targets 1.7 but from what i have read, when it is built using 1.8 javac will not complain that you are using methods that do not exist in 1.7.

the manifest of the soot-3.0.0-SNAPSHOT.jar shows: Build-Jdk: 1.8.0_112

build the sources with jdk7 in the future

i tried to build the source with jdk7 and as expected it does not work:

```
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] .../soot/src/soot/util/StringNumberer.java:[38,46] cannot find symbol
  symbol:   method putIfAbsent(java.lang.String,soot.util.NumberedString)
  location: variable stringToNumbered of type java.util.Map<java.lang.String,soot.util.NumberedString>
[INFO] 1 error




fix:

 src/soot/util/StringNumberer.java | 7 ++++++-
 1 file changed, 6 insertions(+), 1 deletion(-)

diff --git a/src/soot/util/StringNumberer.java b/src/soot/util/StringNumberer.java
index a5f05f3..cb1925d 100644
--- a/src/soot/util/StringNumberer.java
+++ b/src/soot/util/StringNumberer.java
@@ -35,7 +35,12 @@ public class StringNumberer extends ArrayNumberer<NumberedString> {
     
     public synchronized NumberedString findOrAdd( String s ) {
     	NumberedString numStr = new NumberedString(s);
-        NumberedString ret = stringToNumbered.putIfAbsent(s, numStr);
+        NumberedString ret = null;
+        if (stringToNumbered.get(numStr) == null) {
+            stringToNumbered.put(s, numStr);
+        } else {
+            ret = stringToNumbered.get(numStr);
+        }
         if( ret == null ) {
             add(numStr);
             return numStr;
```

**Comment by mbenz89** [comment]
Fixed. Thanks for the report!
