### ISSUE TITLE
Convert Jimple files to dex (The file "parser.dat" is either missing or corrupted)

### ISSUE THREAD

**Issue by m3ftah** [Sable/soot#726]
Steps to reproduce:
1. convert snake.apk to jimple files
2. convert the jimple files to dex

Files used to reproduce: [Tutorial](http://www.abartel.net/dexpler)
<pre>snake.apk : the apk used in the tutorial [out.zip](https://github.com/Sable/soot/files/934300/out.zip)</pre>
The jimple files I am trying to convert : [out.zip](https://github.com/Sable/soot/files/934300/out.zip)

Soot version: <pre>trunk</pre>

Command line:
<pre>java -Xmx6g -jar soot.jar soot.Main -w -allow-phantom-refs \
-android-jars "/home/lakhdar/Android/Sdk/platforms/" \
-src-prec jimple -f dex -process-dir out</pre>

Max Memory:
<pre>1748MB</pre>

Android platform:
<pre>15</pre>

Stack trace:

<pre>Warning: soot.Main is a phantom class!
Exception in thread "main" java.lang.ExceptionInInitializerError
	at soot.jimple.parser.JimpleAST.<init>(JimpleAST.java:53)
	at soot.JimpleClassSource.resolve(JimpleClassSource.java:51)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:243)
	at soot.SootResolver.bringToSignatures(SootResolver.java:275)
	at soot.SootResolver.bringToBodies(SootResolver.java:313)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:166)
	at soot.SootResolver.resolveClass(SootResolver.java:134)
	at soot.Scene.loadClass(Scene.java:873)
	at soot.Scene.loadClassAndSupport(Scene.java:858)
	at soot.Scene.loadNecessaryClasses(Scene.java:1598)
	at soot.Main.run(Main.java:250)
	at soot.Main.main(Main.java:147)
Caused by: java.lang.RuntimeException: The file "parser.dat" is either missing or corrupted.
	at soot.jimple.parser.parser.Parser.<clinit>(Parser.java:7588)
	... 12 more
</pre>

**Comment by m3ftah** [comment]
Same exception when I use the API : 
`Options.v().set_src_prec(Options.src_prec_jimple);`
<pre>Exception in thread "main" java.lang.ExceptionInInitializerError
	at soot.jimple.parser.JimpleAST.<init>(JimpleAST.java:53)
	at soot.JimpleClassSource.resolve(JimpleClassSource.java:51)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:243)
	at soot.SootResolver.bringToSignatures(SootResolver.java:275)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:173)
	at soot.SootResolver.resolveClass(SootResolver.java:134)
	at soot.Scene.loadClass(Scene.java:873)
	at soot.Scene.loadClassAndSupport(Scene.java:858)
	at soot.Scene.loadNecessaryClasses(Scene.java:1598)
	at soot.Main.run(Main.java:250)
	at soot.Main.main(Main.java:147)
	at Main.main(Main.java:76)
Caused by: java.lang.RuntimeException: The file "parser.dat" is either missing or corrupted.
	at soot.jimple.parser.parser.Parser.<clinit>(Parser.java:7588)
	... 12 more</pre>

**Comment by amato-gianluca** [comment]
I have the same problem. Old nightly of soot used to have a file "soot/jimple/parser/parser/parser.dat" which has disappear in more recent builds.

**Comment by m3ftah** [comment]
@amato-gianluca do you have an old build that contain the parser.dat, that may solve my problem.

**Comment by amato-gianluca** [comment]
@m3ftah yes, I have an old build. Do you want me to send you a copy by email?

**Comment by m3ftah** [comment]
@amato-gianluca yes I would like to, thanks in advance.

**Comment by mbenz89** [comment]
Thanks for the report.
Indeed the problem originated from a misconfiguration of the new build process.
You can obtain a fixed version from our nightly build server: http://soot-build.cs.uni-paderborn.de/nightly/soot/

**Comment by m3ftah** [comment]
Thank you, indeed I tried the new build and it worked :+1:

**Comment by Jacoppy** [comment]
@mbenz89  Hi, I'm trying to parse a jimple file and I have the same issue, I'm using the latest version of FlowDroid.
I tried also to reach that link but I get 404, can someone share with me the fix please?

**Comment by mbenz89** [comment]
Are you using FlowDroid from [this](https://github.com/secure-software-engineering/FlowDroid) repository?
It uses the most recent version of Soot via Maven by default. I am not aware of the persistence of this error. Please check if you use the correct version and if the error remains, post a stack trace.

**Comment by Jacoppy** [comment]
Ok you are right, I downloaded FlowDroid 20 days ago, while the last update was 15 . 
My bad sorry

**Comment by Jacoppy** [comment]
Anyway I'm trying this  : 
` try {
                is = new FileInputStream(path);
                Parser p = new Parser(
                        new Lexer(new PushbackReader(new EscapedReader(new BufferedReader(new InputStreamReader(is))), 1024)));
                Start tree = null;

                tree = p.parse();
                Walker w = new Walker(null);
                System.out.println(tree.toString());
                tree.apply(w);
                w.getSootClass();


                is.close();
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            } catch (ParserException e) {
                e.printStackTrace();
            } catch (LexerException e) {
                e.printStackTrace();
            }



    }`

but I get this exception : 
`Exception in thread "main" java.lang.NullPointerException
	at soot.jimple.parser.Walker.outAMethodSignature(Walker.java:1489)
	at soot.jimple.parser.analysis.DepthFirstAdapter.caseAMethodSignature(DepthFirstAdapter.java:2985)
	at soot.jimple.parser.node.AMethodSignature.apply(AMethodSignature.java:75)
	at soot.jimple.parser.analysis.DepthFirstAdapter.caseANonstaticInvokeExpr(DepthFirstAdapter.java:2666)
	at soot.jimple.parser.node.ANonstaticInvokeExpr.apply(ANonstaticInvokeExpr.java:65)
	at soot.jimple.parser.analysis.DepthFirstAdapter.caseAInvokeStatement(DepthFirstAdapter.java:2044)
	at soot.jimple.parser.node.AInvokeStatement.apply(AInvokeStatement.java:40)
	at soot.jimple.parser.analysis.DepthFirstAdapter.caseAFullMethodBody(DepthFirstAdapter.java:1392)
	at soot.jimple.parser.node.AFullMethodBody.apply(AFullMethodBody.java:56)
	at soot.jimple.parser.analysis.DepthFirstAdapter.caseAMethodMember(DepthFirstAdapter.java:663)
	at soot.jimple.parser.node.AMethodMember.apply(AMethodMember.java:71)
	at soot.jimple.parser.analysis.DepthFirstAdapter.caseAFileBody(DepthFirstAdapter.java:470)
	at soot.jimple.parser.node.AFileBody.apply(AFileBody.java:46)
	at soot.jimple.parser.Walker.caseAFile(Walker.java:309)
	at soot.jimple.parser.node.AFile.apply(AFile.java:61)
	at soot.jimple.parser.analysis.DepthFirstAdapter.caseStart(DepthFirstAdapter.java:34)
	at soot.jimple.parser.node.Start.apply(Start.java:37)
	at Jimple_parser.parse(Jimple_parser.java:35)
	at Instrumenter.main(Instrumenter.java:42)`

with the attached jimple file  (I had to rename it txt or git doesn't like it )
[cxim.qngg.TEhr.sFiQa (copy).txt](https://github.com/Sable/soot/files/2397989/cxim.qngg.TEhr.sFiQa.copy.txt)

**Comment by mbenz89** [comment]
Writeout usually happens in `PackManager.writeOuput`. Can't you use this method?

**Comment by Jacoppy** [comment]
Well probably I'm doing things wrong.. I'm trying to load back a SootClass for a jimple file that I have made in a previous execution.
The file that is pointed by the inputStream is a jimple file.
I'm trying to use the same logic as here : https://github.com/Sable/soot/blob/develop/src/main/java/soot/jimple/parser/Parse.java

**Comment by Jacoppy** [comment]
That is awesome thank you bud!!!!
