### ISSUE TITLE
Running soot with Java1.8 

### ISSUE THREAD

**Issue by caiusb** [Sable/soot#760]
I'm trying to run soot using JDK8. However, I get this exception:

```
java -jar soot.jar -cp .:${HOME}/jdk8/jre/lib/rt.jar A

Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/cache/CacheLoader
	at soot.Scene.tryLoadClass(Scene.java:814)
	at soot.Scene.loadBasicClasses(Scene.java:1497)
	at soot.Scene.loadNecessaryClasses(Scene.java:1580)
	at soot.Main.run(Main.java:250)
	at soot.Main.main(Main.java:147)
Caused by: java.lang.ClassNotFoundException: com.google.common.cache.CacheLoader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

A.java is a basic file that doesn't use any libraries outside the standard JDK.

**Comment by caiusb** [comment]
I was using a bad jar. It now runs on the "toy" code. But when I try to run it on a real project throws this error:

```
Exception in thread "main" java.lang.Error: Error: Failed to load java.io.ObjectInputStream.
	at soot.JastAddJ.PathPart.getCompilationUnit(PathPart.java:109)
	at soot.JastAddJ.Program.getCompilationUnit(Program.java:844)
	at soot.JastAddJ.Program.getLibCompilationUnit_compute(Program.java:1517)
	at soot.JastAddJ.Program.getLibCompilationUnit(Program.java:1500)
	at soot.JastAddJ.Program.lookupLibType_compute(Program.java:1465)
	at soot.JastAddJ.Program.lookupLibType(Program.java:1433)
	at soot.JastAddJ.Program.lookupType_compute(Program.java:1412)
	at soot.JastAddJ.Program.lookupType(Program.java:1393)
	at soot.JastAddJ.Program.Define_TypeDecl_lookupType(Program.java:1981)
```

I am using the `soot-trunk.jar` as of August 2nd. I have the `rt.jar` on the classpath, and it has the required class path.

**Comment by mbenz89** [comment]
Soot's Java frontend is heavily outdated. I suggest you try to analyze the compiled bytecode of your target application.
