### ISSUE TITLE
Soot plugin and command line - windows - jdk1.7

### ISSUE THREAD

**Issue by valeriocos** [Sable/soot#761]
Hi,

I've created a simple plugin following the instructions found at:  https://github.com/Sable/soot/wiki/Creating-Soot-Plugins and http://blog.security-comprehension.org/?page_id=154. However, when I launch Soot from command line I get an error (I get a similar error also when using the full path of the jars)
```
C:\..\folder>java -cp soot-2.5.0.jar;plugin.jar soot.Main --plugin plugin.xml -p jap.foo opt:true java.lang.Object
```
```
Invalid option -plugin
Exception in thread "main" soot.CompilationDeathException: Option parse error
        at soot.Main.processCmdLine(Main.java:85)
        at soot.Main.run(Main.java:161)
        at soot.Main.main(Main.java:141)
```

What I'm missing?

**Comment by valeriocos** [comment]
The problem is solved by using the nightly build (https://soot-build.cs.uni-paderborn.de/nightly/soot/)
