### ISSUE TITLE
getting exception soot.SootResolver$SootClassNotFoundException when ...

### ISSUE THREAD

**Issue by ankitku** [Sable/soot#774]
Steps to reproduce:
1.) setup soot
2.) run AndroidInstrument.java

Files used to reproduce: 
AndroidInstrument.java

Soot version: <pre>trunk</pre>

Command line:
<pre>-android-jars /Users/ankitku/Library/Android/sdk/platforms -process-dir /Users/ankitku/Desktop/sample.apk</pre>

Max Memory:
<pre>1820MB</pre>

Stack trace:
<pre>soot.SootResolver$SootClassNotFoundException: couldn&#39;t find class: com.android.tools.fd.runtime.AppInfo (is your soot-class-path set properly?)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:229)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:209)
	at soot.SootResolver.bringToSignatures(SootResolver.java:267)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:171)
	at soot.SootResolver.resolveClass(SootResolver.java:134)
	at soot.dexpler.DexlibWrapper.initialize(DexlibWrapper.java:166)
	at soot.dexpler.DexResolver.resolveFromFile(DexResolver.java:57)
	at soot.DexClassSource.resolve(DexClassSource.java:52)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:236)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:209)
	at soot.SootResolver.bringToSignatures(SootResolver.java:267)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:171)
	at soot.SootResolver.resolveClass(SootResolver.java:134)
	at soot.Scene.loadClass(Scene.java:855)
	at soot.Scene.loadClassAndSupport(Scene.java:841)
	at soot.Scene.loadNecessaryClasses(Scene.java:1595)
	at soot.Main.run(Main.java:250)
	at soot.Main.main(Main.java:147)
	at soot.AndroidInstrument.main(AndroidInstrument.java:83)
</pre>

**Comment by mbenz89** [comment]
Can you provide AndroidInstrument.java?
How are you using Soot (CLI or inside your code)?

**Comment by ankitku** [comment]
I was using jar. But now, running in eclipse, with Soot as a dependency project works all right.
