### ISSUE TITLE
Soot jars for JDK 8

### ISSUE THREAD

**Issue by devikasondhi** [Sable/soot#830]
Hi,
Where could I obtain the Soot jars compatible with JDK 8? Using jars from release 2.5.0 gives the following exception:
Exception in thread "main" java.lang.RuntimeException: Could not load classfile: java.io.ObjectInputStream
	at soot.coffi.Util.resolveFromClassFile(Util.java:75)
	at soot.CoffiClassSource.resolve(CoffiClassSource.java:39)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:215)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:155)
	at soot.SootResolver.resolveClass(SootResolver.java:124)
	at soot.Scene.tryLoadClass(Scene.java:417)
	at soot.Scene.loadBasicClasses(Scene.java:990)
	at soot.Scene.loadNecessaryClasses(Scene.java:1061)
	at soot.Main.run(Main.java:167)
	at soot.Main.main(Main.java:141)

Unable to obtain the nightly build either as the link over this page https://www.sable.mcgill.ca/soot/soot_download.html  seems to be broken.

Thanks.

**Comment by gnom7** [comment]
Same problem.
I use nightly build, in maven:
```
    <repository>
        <id>soot-snapshot</id>
        <url>https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-snapshot/</url>
    </repository>

    <dependencies>
        <dependency>
            <groupId>ca.mcgill.sable</groupId>
            <artifactId>soot</artifactId>
            <version>3.0.0-SNAPSHOT</version>
        </dependency>
    </dependencies>
```
Or just use link from `repository` tag to get jar.

**Comment by mbenz89** [comment]
As gnom7 stated, you can either use Maven, or you download the nightly jars directly from [here](https://soot-build.cs.uni-paderborn.de/public/origin/develop/soot/soot-develop/build/).

**Comment by devikasondhi** [comment]
Thanks. Imported sootclasses-trunk-jar-with-dependencies.jar from the provided link into the Eclipse java project with JDK1.8.0_144. However, I get the following exception thrown when trying to run an analysis over the source program(named Tester inside a trans package)
soot.SootResolver$SootClassNotFoundException: couldn't find class: trans.Tester (is your soot-class-path set properly?)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:228)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:208)
	at soot.SootResolver.bringToSignatures(SootResolver.java:267)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:170)
	at soot.SootResolver.resolveClass(SootResolver.java:133)
	at soot.Scene.loadClass(Scene.java:853)
	at soot.Scene.loadClassAndSupport(Scene.java:839)
	at soot.Scene.loadNecessaryClass(Scene.java:1569)
	at soot.Scene.loadNecessaryClasses(Scene.java:1582)
	at soot.Main.run(Main.java:250)
	at soot.Main.main(Main.java:147)
	at trans.MethodAnalysis.main(MethodAnalysis.java:50)

Please note that the program works fine with soot-2.5.0.jar with Java 1.7

**Comment by mbenz89** [comment]
Without your code initializing Soot I cannot say much here. Generally, you would pass the root folder of that contains your class structure to Soot, e.g., for ".../classes/my/package/hierarchy/clazz.class", you would pass the 'classes' directory to `Options.v().set_process_dir(".../classes");`

**Comment by devikasondhi** [comment]
Explicitly set the classpath, but still the exception is getting thrown. Here's the code using Soot to run a basic analysis(as implemented in MyAnalysis class) to get method summary- extracting method parameters, return type etc. 
```
public static void main(String[] args) {
		
		String p=Scene.v().getSootClassPath()+";"+"/C:/Users/xyz/workspace/SootSamples/bin/trans/";
		Scene.v().setSootClassPath(p);
		ArrayList<String> slist=new ArrayList<String>();
		slist.add("/C:/Users/xyz/workspace/SootSamples/bin/trans");
		Options.v().set_process_dir(slist);
		System.out.println(Scene.v().getSootClassPath());
		PackManager.v().runPacks();
		PackManager.v().getPack("jtp").add(new Transform("jtp.instrumenter", new MyAnalysis() ));
		Options.v().set_output_format(Options.output_format_jimple);

		soot.Main.main(args);
	}
```
I'm passing trans.Tester as the argument. The Tester.class is present in the path specified in the method

**Comment by devikasondhi** [comment]
Managed to resolve this. It was the classpath issue, as you pointed out. Thanks for the help.
