### ISSUE TITLE
Failed to apply jb to method with try multi catch

### ISSUE THREAD

**Issue by gemivnet** [Sable/soot#864]
Using SOOT 3.0.0 the following error message is given:

`Exception in thread "main" java.lang.RuntimeException: Failed to apply jb to <cli.GathererCommand: cli.ICommand createCommand(java.lang.String[])>
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:1911)
	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:126)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:385)
	at soot.jimple.toolkits.annotation.LineNumberAdder.internalTransform(LineNumberAdder.java:44)
	at soot.PackManager.runPacksNormally(PackManager.java:451)
	at soot.PackManager.runPacks(PackManager.java:384)
	at gatherer.SceneBuilder.build(SceneBuilder.java:326)
	at gatherer.SootClassGatherer.getUML(SootClassGatherer.java:44)
	at main.Generator.<init>(Generator.java:29)
	at main.UMLGenerator.main(UMLGenerator.java:11)`

The GathererCommand method which is failing is:

`@Override
	public ICommand createCommand(String[] options) {
		String generator = options[0];
		
		IGatherer temp;
		
		try {
			temp = (IGatherer) Class.forName(generator).newInstance();
		} catch (InstantiationException | IllegalAccessException | ClassNotFoundException e) {
			throw new RuntimeException(e);
		}
		
		return new GathererCommand(temp);
		
	}`

When the try multi catch is removed from the method, SOOT is able to work with the class.

**Comment by pnest** [comment]
@gemivnet Was not able to reproduce on snapshot version. Could you provide exact options that were used to run soot?
