### ISSUE TITLE
Problems with soot 

### ISSUE THREAD

**Issue by 3lR0m4c** [Sable/soot#883]
Hi together,

I got an issue while using soot. I implemented a little test project and tried to analyze it with soot, using it like this:

`public class TestClass {

    public static void main(String[] args) {

        String outputDir = "/home/m4rc0/Code/Java_workspace/PTAProject/src/main/resources/output";
        String projectPath = "~/Code/Java_workspace/TestPTAProject/out/production/TestPTAProject";

        soot.Main.main(getArgsString(projectPath, outputDir, javaPath));

        Chain<SootClass> sootClasses = Scene.v().getApplicationClasses();

        System.out.println("\n\n\n\n\n\n______________START SDG ANALYSIS______________\n");

        int i = 1;
        for (SootClass sootClass : sootClasses) {
            System.out.println("\n" + i + ". " + sootClass.getName() + ":\n");
            int j = 1;
            for (SootMethod sootMethod : sootClass.getMethods()) {
                System.out.println(i + "." + j + ". Method " + sootMethod.getName() + ":\n");

                try {
                    Body body = sootMethod.retrieveActiveBody();
                    ExceptionalUnitGraph exceptionalUnitGraph = new ExceptionalUnitGraph(body);
                    SystemDependenceGraph systemDependenceGraph = new SystemDependenceGraph(exceptionalUnitGraph, sootClass.getName());
                    System.out.println(systemDependenceGraph.getCFG().getBody().toString());
                } catch (RuntimeException e) {
                    e.printStackTrace();
                }

                System.out.println("\n\n");
                j++;
            }

            i++;
        }

    }

    public static String[] getArgsString(String projectPath, String outputDir, String javaPath) {

        String args = "";

//        args += "-w ";
        args += "-p ";
        args += "cg verbose:true ";
        args += "-process-path ";
        args += projectPath + " ";
        args += "-d ";
        args += outputDir + " ";
        args += "-f ";
        args += "J ";
        args += "-allow-phantom-refs ";
        args += "-no-bodies-for-excluded ";

        return args.split(" ");
    }
}
`

The program will not load bodies. When I want to analyze them with 
`                    Body body = sootMethod.retrieveActiveBody();
`
I always got an output, similar to the following:

Soot started on Fri Feb 02 13:26:21 CET 2018
Transforming ClassC... 
Transforming ClassB... 
Transforming ClassA... 
Transforming ClassD... 
Writing to /home/m4rc0/Code/Java_workspace/PTAProject/src/main/resources/output/ClassC.jimple
Writing to /home/m4rc0/Code/Java_workspace/PTAProject/src/main/resources/output/ClassB.jimple
Writing to /home/m4rc0/Code/Java_workspace/PTAProject/src/main/resources/output/ClassA.jimple
Writing to /home/m4rc0/Code/Java_workspace/PTAProject/src/main/resources/output/ClassD.jimple
Soot finished on Fri Feb 02 13:26:22 CET 2018
Soot has run for 0 min. 0 sec.

______________START SDG ANALYSIS______________

1. ClassC:

1.1. Method <init>:

1.2. Method faa:

2. ClassB:

2.1. Method <init>:

2.2. Method fee:

3. ClassA:

3.1. Method <init>:

3.2. Method main:

3.3. Method foo:

3.4. Method bar:

4. ClassD:

4.1. Method <init>:

4.2. Method fuu:

java.lang.RuntimeException: No method source set for method <ClassC: void <init>()>
	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:123)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:385)
	at de.tud.ptaproject.TestClass.main(TestClass.java:83)
java.lang.RuntimeException: No method source set for method <ClassC: void faa(int)>
	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:123)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:385)
	at de.tud.ptaproject.TestClass.main(TestClass.java:83)
java.lang.RuntimeException: No method source set for method <ClassB: void <init>()>
	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:123)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:385)
	at de.tud.ptaproject.TestClass.main(TestClass.java:83)
java.lang.RuntimeException: No method source set for method <ClassB: void fee(int)>
	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:123)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:385)
	at de.tud.ptaproject.TestClass.main(TestClass.java:83)
java.lang.RuntimeException: No method source set for method <ClassA: void <init>()>
	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:123)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:385)
	at de.tud.ptaproject.TestClass.main(TestClass.java:83)
java.lang.RuntimeException: No method source set for method <ClassA: void main(java.lang.String[])>
	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:123)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:385)
	at de.tud.ptaproject.TestClass.main(TestClass.java:83)
java.lang.RuntimeException: No method source set for method <ClassA: void foo(int)>
	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:123)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:385)
	at de.tud.ptaproject.TestClass.main(TestClass.java:83)
java.lang.RuntimeException: No method source set for method <ClassA: int bar(int)>
	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:123)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:385)
	at de.tud.ptaproject.TestClass.main(TestClass.java:83)
java.lang.RuntimeException: No method source set for method <ClassD: void <init>()>
	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:123)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:385)
	at de.tud.ptaproject.TestClass.main(TestClass.java:83)
java.lang.RuntimeException: No method source set for method <ClassD: void fuu(java.lang.String)>
	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:123)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:385)
	at de.tud.ptaproject.TestClass.main(TestClass.java:83)

Process finished with exit code 0

Can anyone help please.

**Comment by anddann** [comment]
Soot releases the bodies after writing out jimple code, either
- run soot without the output options `-d -f`
- or try the option `-no-writeout-body-releasing` (I did not try this option myself)

**Comment by 3lR0m4c** [comment]
Thank you very much. `-no-writeout-body-releasing` was the key.
