### ISSUE TITLE
Problem with Java-9 Project

### ISSUE THREAD

**Issue by jgarci40** [Sable/soot#925]
I am trying to run a Java-9 project through Soot, but I get an error as shown below:
```
$ /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/bin/java -cp ~/IdeaProjects/Java9-Module-Inconsistencies/java-reflection-analysis/libs/sootclasses-trunk-jar-with-dependencies.jar soot.Main -process-dir target/number_api-1.0.jar 
Soot started on Thu Apr 12 04:50:27 PDT 2018
java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:185)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:168)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:439)
	at soot.asm.AsmClassSource.resolve(AsmClassSource.java:60)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:236)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:208)
	at soot.SootResolver.bringToSignatures(SootResolver.java:269)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:170)
	at soot.SootResolver.resolveClass(SootResolver.java:133)
	at soot.Scene.loadClass(Scene.java:860)
	at soot.Scene.loadClassAndSupport(Scene.java:846)
	at soot.Scene.loadNecessaryClasses(Scene.java:1601)
	at soot.Main.run(Main.java:250)
	at soot.Main.main(Main.java:147)


Ouuups... something went wrong! Sorry about that.
Follow these steps to fix the problem:
1.) Are you sure you used the right command line?
    Click here to double-check:
    https://soot-build.cs.uni-paderborn.de/doc/sootoptions/

2.) Not sure whether it's a bug? Feel free to discuss
    the issue on the Soot mailing list:
    https://github.com/Sable/soot/wiki/Getting-help

3.) Sure it's a bug? Click this link to report it.
    https://github.com/Sable/soot/issues/new?title=java.lang.IllegalArgumentException+when+...&body=Steps+to+reproduce%3A%0A1.%29+...%0A%0AFiles+used+to+reproduce%3A+%0A...%0A%0ASoot+version%3A+%3Cpre%3Etrunk%3C%2Fpre%3E%0A%0ACommand+line%3A%0A%3Cpre%3E-process-dir+target%2Fnumber_api-1.0.jar%3C%2Fpre%3E%0A%0AMax+Memory%3A%0A%3Cpre%3E3641MB%3C%2Fpre%3E%0A%0AStack+trace%3A%0A%3Cpre%3Ejava.lang.IllegalArgumentException%0A%09at+org.objectweb.asm.ClassReader.%26%2360%3Binit%26%2362%3B%28ClassReader.java%3A185%29%0A%09at+org.objectweb.asm.ClassReader.%26%2360%3Binit%26%2362%3B%28ClassReader.java%3A168%29%0A%09at+org.objectweb.asm.ClassReader.%26%2360%3Binit%26%2362%3B%28ClassReader.java%3A439%29%0A%09at+soot.asm.AsmClassSource.resolve%28AsmClassSource.java%3A60%29%0A%09at+soot.SootResolver.bringToHierarchyUnchecked%28SootResolver.java%3A236%29%0A%09at+soot.SootResolver.bringToHierarchy%28SootResolver.java%3A208%29%0A%09at+soot.SootResolver.bringToSignatures%28SootResolver.java%3A269%29%0A%09at+soot.SootResolver.processResolveWorklist%28SootResolver.java%3A170%29%0A%09at+soot.SootResolver.resolveClass%28SootResolver.java%3A133%29%0A%09at+soot.Scene.loadClass%28Scene.java%3A860%29%0A%09at+soot.Scene.loadClassAndSupport%28Scene.java%3A846%29%0A%09at+soot.Scene.loadNecessaryClasses%28Scene.java%3A1601%29%0A%09at+soot.Main.run%28Main.java%3A250%29%0A%09at+soot.Main.main%28Main.java%3A147%29%0A%3C%2Fpre%3E
    Please be as precise as possible when giving us
    information on how to reproduce the problem. Thanks!
```

The jar for the Java-9 project that I am trying to run through Soot can be obtained here: https://www.dropbox.com/s/jof113c5119g1tx/number_api-1.0.jar?dl=0

Could someone please help me address the error above?

**Comment by mbenz89** [comment]
Are you using Soot's java 9 version?
If not, have a look at the [java9 branch](https://github.com/Sable/soot/tree/java9).

**Comment by jgarci40** [comment]
Not for the error above; however, that branch also gives me a different set of errors.

**Comment by anddann** [comment]
What errors do you get?

**Comment by jgarci40** [comment]
I seem to be using `VIRTUAL_FS_FOR_JDK9` incorrectly, but I can't determine the right way to do it from the README.md file in the java9 branch.

```
joshua@Joshuas-MacBook-Pro:~/tmp/soot-java9
$ java -version
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
joshua@Joshuas-MacBook-Pro:~/tmp/soot-java9
$ java -cp target/sootclasses_j9-trunk-jar-with-dependencies.jar soot.Main -cp VIRTUAL_FS_FOR_JDK9:/Users/joshua/IdeaProjects/Java9-Module-Inconsistencies/test_projects/number-to-text_jdk9/number_api/target/number_api-1.0.jar --process-dir /Users/joshua/IdeaProjects/Java9-Module-Inconsistencies/test_projects/number-to-text_jdk9/number_api/target/number_api-1.0.jar
Soot started on Wed Apr 18 13:23:41 PDT 2018
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.Exception: Error: The path '/Users/joshua/tmp/soot-java9/VIRTUAL_FS_FOR_JDK9' does not exist.
	at soot.SourceLocator.getClassSourceType(SourceLocator.java:289)
	at soot.SourceLocator.lookupInClassPath(SourceLocator.java:565)
	at soot.asm.AsmClassProvider.find(AsmClassProvider.java:36)
	at soot.SourceLocator.getClassSource(SourceLocator.java:174)
	at soot.Scene.tryLoadClass(Scene.java:823)
	at soot.Scene.loadBasicClasses(Scene.java:1509)
	at soot.Scene.loadNecessaryClasses(Scene.java:1596)
	at soot.Main.run(Main.java:250)
	at soot.Main.main(Main.java:147)
Caused by: java.util.concurrent.ExecutionException: java.lang.Exception: Error: The path '/Users/joshua/tmp/soot-java9/VIRTUAL_FS_FOR_JDK9' does not exist.
	at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:137)
	at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2348)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2320)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at soot.SourceLocator.getClassSourceType(SourceLocator.java:287)
	... 8 more
Caused by: java.lang.Exception: Error: The path '/Users/joshua/tmp/soot-java9/VIRTUAL_FS_FOR_JDK9' does not exist.
	at soot.SourceLocator$1.load(SourceLocator.java:66)
	at soot.SourceLocator$1.load(SourceLocator.java:61)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	... 14 more
```

**Comment by anddann** [comment]
This is a patch aka "dirty quick fix" I introduced recently.
Have you downloaded the newest version https://soot-build.cs.upb.de/public/origin/java9/soot/soot-j9/build/ ?

**Comment by jgarci40** [comment]
Thanks for the patch. It worked.

**Comment by harshita19244** [comment]
@anddann I was using the java 9 patch, I am facing errors in passing arguments to soot. Could you guide me? This is how I am passing arguments.
 
![image](https://user-images.githubusercontent.com/60603854/133052498-ab4f2810-cf25-46e3-9031-adaa7e200410.png)

This is the error
![image](https://user-images.githubusercontent.com/60603854/133052790-abecb4d9-a40f-45c6-9e40-e91a267a2a27.png)

My code works with java 6 but not here.

**Comment by anddann** [comment]
Thanks for raising this question. After the argument `-soot-class-path`you have to give the location to the folder that contains your classes, e.g., `.` if its in the same folder.

The error shows that soot looked in the folder `-main-class`for class files.
