### ISSUE TITLE
Using phantom refs with Java source code

### ISSUE THREAD

**Issue by casperboone** [Sable/soot#932]
When I provide soot with the following file `A.java`:
```java
public class A {
        public void methodA() {
                B b = new B();
                b.hello();
        }
}
```
without giving B and including the option `-allow-phantom-refs`, I get the following exception:

```
soot.CompilationDeathException: there were errors during parsing and/or type checking (JastAdd frontend)
	at soot.JastAddInitialResolver.formAst(JastAddInitialResolver.java:66)
	at soot.JavaClassSource.resolve(JavaClassSource.java:57)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:240)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:212)
	at soot.SootResolver.bringToSignatures(SootResolver.java:273)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:174)
	at soot.SootResolver.resolveClass(SootResolver.java:137)
	at soot.Scene.loadClass(Scene.java:861)
	at soot.Scene.loadClassAndSupport(Scene.java:847)
	at soot.Scene.loadNecessaryClasses(Scene.java:1602)
	at soot.Main.run(Main.java:248)
	at soot.Main.main(Main.java:144)
```

I'm running soot using the following command:
```
java -cp ../sootclasses-trunk-jar-with-dependencies.jar soot.Main -cp . -pp -process-dir . -allow-phantom-refs -d ../out
```

I have tried to do the same on compiled bytecode for which I included a class `B` during compilation, and removed `B.class` afterwards. Then I run Soot on the bytecode of A.class with the `-allow-phantom-refs` option, this worked fine.

I was wondering if it is supposed to be possible to use phantom refs while operating on source code, or whether the frontend cannot deal with this.

**Comment by mbenz89** [comment]
Since we do not compile the source code but rather parse and translate it to Jimple, there should be no need to have a complete, compilable codebase. Therefore, phantoms are quite likely to be supported for source code as well. The reason I do not know this for sure is that the source code frontend is so heavily outdated that we do not use it ourselves. I would thus strongly discourage from using the source code frontend at all.
