### ISSUE TITLE
Branch Java9 can't Resolve List<String> infos=new ArrayList<>()

### ISSUE THREAD

**Issue by zhenyuqiaotencent** [Sable/soot#939]
I had asked a  same question before and the reply declare the branch java9 can  solve this issue! 

I switch to branch Java9 and  the code can't be  resolved 
the example code 

   public static void main(String[] args) {
        String data = "Hello World!";
        List<String> infos=new ArrayList<>();
    }

the method stack
Exception in thread "main" soot.CompilationDeathException: there were errors during parsing and/or type checking (JastAdd frontend)
	at soot.JastAddInitialResolver.formAst(JastAddInitialResolver.java:66)
	at soot.JavaClassSource.resolve(JavaClassSource.java:57)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:264)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:231)
	at soot.SootResolver.bringToSignatures(SootResolver.java:297)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:193)
	at soot.SootResolver.resolveClass(SootResolver.java:154)
	at soot.Scene.loadClass(Scene.java:863)
	at soot.Scene.loadClassAndSupport(Scene.java:849)
	at soot.Main.main(Main.java:191)

the  error message 
can not assign variable infos of type java.util.List<java.lang.String> a value of type java.util.ArrayList<@primitive.Unknown>

![_15249025859252](https://user-images.githubusercontent.com/20988649/39393927-a965cce2-4afd-11e8-9b79-31ed8b53098d.png)
![1](https://user-images.githubusercontent.com/20988649/39393938-d43f965a-4afd-11e8-8153-bb6f7ba4b99d.png)
![2](https://user-images.githubusercontent.com/20988649/39393939-d46f4846-4afd-11e8-80ec-e3d912230a8b.png)

**Comment by anddann** [comment]
Okay, what cmd line arguments do you use?
It seems use the Jast(Java Frontend), which is outdated. 
I recommend using the asm frontend and using only `*.class` as input but not Java source code

**Comment by zhenyuqiaotencent** [comment]
I didn't use any cmd line arguments, just make the soot load the special source code to verify the jast grammar.

Is there any other way to  support the Jast? 

 it's difficult for me to get the asm or *.class as input, the code project is so big and I want to use the Soot as an IDE plugin to provide special service!

**Comment by zhenyuqiaotencent** [comment]
I solve this issue by using the .class as input!
