### ISSUE TITLE
FATAL ERROR while using Play In Agent Tamiflex

### ISSUE THREAD

**Issue by VedaNiks** [Sable/soot#940]
Hi all,

I am trying to use Tamiflex.
I am using jdk version 1.8.0_131.
 
I can use Play out Agent without any error.

```
java -javaagent:poa-2.0.3.jar -jar dacapo-9.12-bach.jar avrora -s small
============================================================
TamiFlex Play-Out Agent Version 2.0.3
Loaded properties ~/.tamiflex/poa.properties
============================================================
===== DaCapo 9.12 avrora starting =====
===== DaCapo 9.12 avrora PASSED in 1778 msec =====

============================================================
TamiFlex Play-Out Agent Version 2.0.3
Found 34 new log entries.
Dumped 1207 new classes.
Log file written to: path_to/out/refl.log
============================================================
```

then I run my transform on it.
change the pia.properties to make it point to correct folder.

but when I run Play In agent I get the following error

```
 java -javaagent:pia-2.0.3.jar -jar dacapo-9.12-bach.jar avrora -s small
=======================================================
TamiFlex Play-In Agent Version 2.0.3
Loaded properties from ~/.tamiflex/pia.properties
=======================================================
Exception in thread "main" java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
    at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.InternalError
    at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
    at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
    at de.bodden.tamiflex.playin.Agent.premain(Agent.java:60)
    ... 6 more
FATAL ERROR in native method: processing of -javaagent failed
Aborted (core dumped)
```

This happen even if I put _InDir_ of _pia.properties_ as the out directory of Play-out agent.
Can someone help me resolve this error?

Thanks,
Nikhil

**Comment by VedaNiks** [comment]
Hi @ericbodden,  Thanks for replying.

No, the error remains even if I disable some instruments in the configuration file.

The poa.properties I am using is

```
dontDumpClasses = false
dontNormalize = false
count = false
useDeclaredTypes = false
verbose = false
#outDir = /tmp/out

#NOTE: out of the following instruments, the "Booster" only supports the first four! 
transformations =\
			de.bodden.tamiflex.playout.transformation.clazz.ClassForNameTransformation \
			de.bodden.tamiflex.playout.transformation.clazz.ClassNewInstanceTransformation \
			de.bodden.tamiflex.playout.transformation.constructor.ConstructorNewInstanceTransformation \
			de.bodden.tamiflex.playout.transformation.method.MethodInvokeTransformation \
			de.bodden.tamiflex.playout.transformation.field.FieldGetTransformation \
			de.bodden.tamiflex.playout.transformation.field.FieldSetTransformation 

```

Even If I remove all transformations the error is there.

If I run the pia-2.0.3.jar on the untransformed code(out directory created by poa-2.0.3 jar as inDir of pia.properties as ), I get the same error.

As of now I am just stuck with this error.
```
=======================================================
TamiFlex Play-In Agent Version 2.0.3
Loaded properties from /home/nikkhil/.tamiflex/pia.properties
=======================================================
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.InternalError
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
	at de.bodden.tamiflex.playin.Agent.premain(Agent.java:60)
	... 6 more
FATAL ERROR in native method: processing of -javaagent failed
Aborted (core dumped)
```
Can Java version be the problem?

Thanks,
Nikhil

**Comment by ericbodden** [comment]
Hello.

I just tried this on my MacBook, but _without_ any sort of code transformation, i.e., just reading in the classes that the POA dumped. That worked without any problem.

Could you try this as well? Maybe your transformation is buggy…

Best wishes
Eric

**Comment by VedaNiks** [comment]
Hi @ericbodden,

Finally, I was able to run it without performing any transformation. I didn't get the source of error but I think java was corrupted. After I reinstalled java it worked fine.

```
nikkhil@nikhil:~/Downloads/Dacapo$ java -javaagent:poa-2.0.3.jar -jar dacapo-9.12-MR1-bach.jar avrora -s small
============================================================
TamiFlex Play-Out Agent Version 2.0.3
Loaded properties from /home/nikkhil/.tamiflex/poa.properties
============================================================
===== DaCapo 9.12-MR1 avrora starting =====
===== DaCapo 9.12-MR1 avrora PASSED in 1869 msec =====

============================================================
TamiFlex Play-Out Agent Version 2.0.3
Found 66 new log entries.
Dumped 1126 new classes.
Log file written to: /home/nikkhil/Downloads/Dacapo/out/refl.log
============================================================
nikkhil@nikhil:~/Downloads/Dacapo$ java -javaagent:pia-2.0.3.jar -jar dacapo-9.12-MR1-bach.jar avrora -s small
=======================================================
TamiFlex Play-In Agent Version ${tf.version}
Loaded properties from /home/nikkhil/.tamiflex/pia.properties
/home/nikkhil/Downloads/Dacapo/out
=======================================================
===== DaCapo 9.12-MR1 avrora starting =====
===== DaCapo 9.12-MR1 avrora PASSED in 1904 msec =====

=======================================================
TamiFlex Play-In Agent Version ${tf.version}
Replaced 1126 out of 1136 classes.
=======================================================

```

Thank you for looking into this.

Nikhil

**Comment by VedaNiks** [comment]
Edit:

I found the source of this error.
I was copying soot-trunk.jar into  ```/jre/lib/ext``` of java.
When I removed soot-trunk.jar, and gave it directly in java's classpath, it worked.

Thanks
-Nikhil
