### ISSUE TITLE
RuntimeException: Class names not equal!

### ISSUE THREAD

**Issue by Bearshanjun** [Sable/soot#955]
Conversion from .class to .jimple  have An error occurred, why

java -cp sootclasses-trunk-jar-with-dependencies.jar soot.Main -cp . -pp $name -allow-phantom-refs -f J -src-prec class -process-dir .

java.lang.RuntimeException: Class names not equal! org.apache.log4j.helpers.AbsoluteTimeDateFormat != AbsoluteTimeDateFormat
	at soot.asm.SootClassBuilder.visit(SootClassBuilder.java:99)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:637)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:521)
	at soot.asm.AsmClassSource.resolve(AsmClassSource.java:62)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:240)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:212)
	at soot.SootResolver.bringToSignatures(SootResolver.java:273)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:174)
	at soot.SootResolver.resolveClass(SootResolver.java:137)
	at soot.Scene.loadClass(Scene.java:861)
	at soot.Scene.loadClassAndSupport(Scene.java:847)
	at soot.Scene.loadNecessaryClass(Scene.java:1577)
	at soot.Scene.loadNecessaryClasses(Scene.java:1590)
	at soot.Main.run(Main.java:248)
	at soot.Main.main(Main.java:144)

**Comment by ericbodden** [comment]
Hello.

I am pretty sure that your command line is incorrect. If you use “-process-dir” then “.” must be a directory containing org/apache/log4j/helpers/AbsoluteTimeDateFormat.class

Best wishes
Eric

**Comment by Bearshanjun** [comment]
Hi ericbodden. Thanks for your help, I have another question. The configuration environment is jdk1.7,Conversion from .java to .jimple

java -cp soot-2.5.0.jar soot.Main -cp . -pp  $name -allow-phantom-refs -f J

Exception in thread "main" soot.CompilationDeathException: there were errors during parsing and/or type checking (JastAdd frontend)
	at soot.JastAddInitialResolver.formAst(JastAddInitialResolver.java:63)
	at soot.JavaClassSource.resolve(JavaClassSource.java:54)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:215)
	at soot.SootResolver.bringToSignatures(SootResolver.java:239)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:154)
	at soot.SootResolver.resolveClass(SootResolver.java:124)
	at soot.Scene.loadClass(Scene.java:448)
	at soot.Scene.loadClassAndSupport(Scene.java:433)
	at soot.Scene.loadNecessaryClass(Scene.java:1053)
	at soot.Scene.loadNecessaryClasses(Scene.java:1067)
	at soot.Main.run(Main.java:167)
	at soot.Main.main(Main.java:141)

What should I do?

**Comment by mbenz89** [comment]
You are using a very old version of Soot. Please retry with the [current version](https://soot-build.cs.uni-paderborn.de/public/origin/master/soot/soot-master/3.1.0/build/sootclasses-trunk-jar-with-dependencies.jar).

**Comment by Bearshanjun** [comment]
when i use jdk1.8 and sootclasses-trunk-jar-with-dependencies.jar,Also will go wrong (Conversion from .java to .jimple)

java -cp sootclasses-trunk-jar-with-dependencies.jar soot.Main -cp.:/usr/lib/jvm1.8/jdk1.8.0_171/jre/lib/rt.jar -pp CommonConfig -f J

java.lang.RuntimeException: Class names not equal! com.ctc.wstx.api.CommonConfig != CommonConfig
	at soot.asm.SootClassBuilder.visit(SootClassBuilder.java:99)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:637)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:521)
	at soot.asm.AsmClassSource.resolve(AsmClassSource.java:62)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:240)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:212)
	at soot.SootResolver.bringToSignatures(SootResolver.java:273)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:174)
	at soot.SootResolver.resolveClass(SootResolver.java:137)
	at soot.Scene.loadClass(Scene.java:861)
	at soot.Scene.loadClassAndSupport(Scene.java:847)
	at soot.Scene.loadNecessaryClass(Scene.java:1577)
	at soot.Scene.loadNecessaryClasses(Scene.java:1590)
	at soot.Main.run(Main.java:248)

Thanks again

**Comment by mbenz89** [comment]
I wasn't aware you are trying to analyze Java files directly. The source code frontend is heavily outdated. I suggest compiling and using the bytecode frontend instead.
