### ISSUE TITLE
ClassFormatError caused by default method in interface

### ISSUE THREAD

**Issue by ReedOei** [Sable/soot#956]
Here is a simple example that demonstrates this behavior. If I make the method `f` into a non-default method and implement it like normal, there are no errors. Therefore, I am fairly confident there is some issue with the default methods in interfaces.

Using the code below I run these commands:
```bash
$ javac Test/*.java
$ java -cp Test/: Main # Without soot, it works find.
4
$ java -cp sootclasses-trunk-jar-with-dependencies.jar: soot.Main -process-path Test
$ java -cp sootOutput/: Main # With, it fails.
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.ClassFormatError: Method f in class InterfaceTest has illegal modifiers: 0x1
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
```

InterfaceTest.java:
```java
public interface InterfaceTest {
    default int f() {
        return 4;
    }   
}
```

Main.java:
```java
public class Main {
    public static void main(String[] args) {
        InterfaceTest i = new Impl();

        System.out.println(i.f());
    }

    public static class Impl implements InterfaceTest {}
}
```

I am using Java 8:
```
$ java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
```

My `sootclasses-trunk-jar-with-dependencies.jar` I downloaded via `wget https://soot-build.cs.uni-paderborn.de/public/origin/develop/soot/soot-develop/build/sootclasses-trunk-jar-with-dependencies.jar` today, so it is the version from 07-Jun-2018 17:29. I have tried using Jasmine and the asm-backend flag and get the same error with both.

**Comment by ericbodden** [comment]
Hmm, I wonder if we are failing to propagate some tag from the original to the generated bytecode. @ReedOei do you have any concrete info about how such methods are flagged in the bytecode? Do they have a special modifier?

**Comment by ReedOei** [comment]
@ericbodden Actually, it looks like the error is just caused by having the wrong major/minor version set in the class files Soot writes. Soot writes version 45.3, but if I manually change it to 52.0 it works just fine.

**Comment by mbenz89** [comment]
@ReedOei Can you give me a hint on where you changed the version?

**Comment by ReedOei** [comment]
@mbenz89 I opened the InterfaceTest.class file generated by Soot, then right after `CA FE BA BE` at the beginning of the file I see `00 03 00 2D` which I changed to `00 00 00 34`. Then I ran the program using `java -cp sootOutput/: Main` and the program ran as expected.

**Comment by ericbodden** [comment]
I see. Looks like we would have to adjust this number in ASM when we write out the bytecode, or more easily maybe preserve it from the original number that was also ready by ASM during jimplification.

**Comment by mbenz89** [comment]
Moved to #968
