### ISSUE TITLE
Exception in thread "main" soot.SootMethodRefImpl$ClassResolutionFailedException when running data flow analysis

### ISSUE THREAD

**Issue by Katie2018** [Sable/soot#977]
Hello,

When I was running Test.java in soot.jimple.infoflow.android.TestApps in eclipse, I got the following error:

Running data flow analysis...
Exception in thread "main" soot.SootMethodRefImpl$ClassResolutionFailedException: Class android.content.ServiceConnection doesn't have method onServiceConnected([android.content.ComponentName]) : void; failed to resolve in superclasses and interfacesLooking in android.content.ServiceConnection which has methods [<android.content.ServiceConnection: void onServiceConnected(android.content.ComponentName,android.os.IBinder)>, <android.content.ServiceConnection: void onServiceDisconnected(android.content.ComponentName)>, <android.content.ServiceConnection: void onBindingDied(android.content.ComponentName)>, <android.content.ServiceConnection: void onNullBinding(android.content.ComponentName)>]
Looking in java.lang.Object which has methods [<java.lang.Object: void <init>()>, <java.lang.Object: java.lang.Class getClass()>, <java.lang.Object: int hashCode()>, <java.lang.Object: boolean equals(java.lang.Object)>, <java.lang.Object: java.lang.Object clone()>, <java.lang.Object: java.lang.String toString()>, <java.lang.Object: void notify()>, <java.lang.Object: void notifyAll()>, <java.lang.Object: void wait(long)>, <java.lang.Object: void wait(long,int)>, <java.lang.Object: void wait()>, <java.lang.Object: void finalize()>]

	at soot.SootMethodRefImpl.resolve(SootMethodRefImpl.java:237)
	at soot.SootMethodRefImpl.resolve(SootMethodRefImpl.java:152)
	at soot.jimple.internal.AbstractInvokeExpr.getMethod(AbstractInvokeExpr.java:56)
	at soot.jimple.validation.InvokeArgumentValidator.validate(InvokeArgumentValidator.java:54)
	at soot.jimple.JimpleBody.validate(JimpleBody.java:118)
	at soot.jimple.JimpleBody.validate(JimpleBody.java:98)
	at soot.jimple.infoflow.cfg.LibraryClassPatcher.patchServiceConnection(LibraryClassPatcher.java:563)
	at soot.jimple.infoflow.cfg.LibraryClassPatcher.patchLibraries(LibraryClassPatcher.java:55)
	at soot.jimple.infoflow.android.SetupApplication.initializeSoot(SetupApplication.java:1021)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1187)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1160)
	at soot.jimple.infoflow.android.TestApps.Test.runAnalysis(Test.java:798)
	at soot.jimple.infoflow.android.TestApps.Test.main(Test.java:249)

Could you please help with this? 
Thank you!

**Comment by StevenArzt** [comment]
Hi Katie,

This bug has been fixed. Apparently, you are using an outdated version of FlowDroid (also judging from the class names on your stack trace). Please try again with the current development version. Also note that the FlowDroid repository has been moved to https://github.com/secure-software-engineering/FlowDroid. Building the new version from source should be easy using Maven.

Best regards,
  Steven

**Comment by Katie2018** [comment]
Thank you so much!

But I got another error when I ran soot.jimple.infoflow.android.test.droidBench.AliasingTests, I do have the class in bin/:
Class not found soot.jimple.infoflow.android.test.droidBench.AliasingTests

java.lang.ClassNotFoundException: soot.jimple.infoflow.android.test.droidBench.AliasingTests

at java.net.URLClassLoader.findClass(URLClassLoader.java:381)

at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)

at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.loadClass(RemoteTestRunner.java:770)

at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.loadClasses(RemoteTestRunner.java:499)

at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:522)

at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)

at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)

at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)

Best regards,
Katie

**Comment by StevenArzt** [comment]
That can happen with Eclipse. Try compiling hte project with Maven and then try again in Eclipse. I haven't found out yet why Eclipse doesn't properly locate the files otherwise.

**Comment by mbenz89** [comment]
Hi Steven. Just an idea: I've seen you compile your classes to "./build" while "./target" would be the native maven output directory. It might be that eclipse does not handle the custom output dir when compiling and, thus, your tests won't find the target classes.

**Comment by lingnancfy** [comment]
@Katie2018 I am also have second problem.

**Comment by mbenz89** [comment]
Could you please open a new issue on FlowDroid's issue tracker. This is not really related to Soot.
