### ISSUE TITLE
soot.SootResolver$SootClassNotFoundException when ...

### ISSUE THREAD

**Issue by aksinghdce** [Sable/soot#984]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: <pre>trunk</pre>

Command line:
<pre>-p jb use-original-names:true -p jap.unreadanalysis on ca.ubc.ece.eece514.a2.Countdown</pre>

Max Memory:
<pre>1796MB</pre>

Stack trace:
<pre>soot.SootResolver$SootClassNotFoundException: couldn&#39;t find class: ca.ubc.ece.eece514.a2.Countdown (is your soot-class-path set properly?)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:232)
	at soot.SootResolver.bringToSignatures(SootResolver.java:275)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:173)
	at soot.SootResolver.resolveClass(SootResolver.java:134)
	at soot.Scene.loadClass(Scene.java:873)
	at soot.Scene.loadClassAndSupport(Scene.java:858)
	at soot.Scene.loadNecessaryClass(Scene.java:1575)
	at soot.Scene.loadNecessaryClasses(Scene.java:1586)
	at soot.Main.run(Main.java:250)
	at soot.Main.main(Main.java:147)
	at ca.ubc.ece.eece514.a2.Utils.runSoot(Utils.java:70)
	at ca.ubc.ece.eece514.a2.UnreadAnalysisMain.main(UnreadAnalysisMain.java:30)
</pre>

**Comment by mbenz89** [comment]
This means that Soot cannot find the stated class on your classpath.
I cannot see any classpath or process-dir setting in your command line? Please make sure to pass a Jar or a directory with your to-be-analyzed bytecode to Soot

**Comment by aksinghdce** [comment]
Got it! Thanks
