### ISSUE TITLE
java.lang.RuntimeException when ...

### ISSUE THREAD

**Issue by bigempire** [Sable/soot#988]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: <pre>trunk</pre>

Command line:
<pre>-f J ./bin/core/NewConstraint.class</pre>

Max Memory:
<pre>3641MB</pre>

Stack trace:
<pre>java.lang.RuntimeException: Attempt to create RefType containing a / --&#62; ./bin/core/NewConstraint.class
	at soot.RefType.&#60;init&#62;(RefType.java:64)
	at soot.RefType.v(RefType.java:82)
	at soot.SootClass.&#60;init&#62;(SootClass.java:97)
	at soot.SootClass.&#60;init&#62;(SootClass.java:111)
	at soot.SootResolver.makeClassRef(SootResolver.java:114)
	at soot.SootResolver.resolveClass(SootResolver.java:129)
	at soot.Scene.loadClass(Scene.java:706)
	at soot.Scene.loadClassAndSupport(Scene.java:691)
	at soot.Scene.loadNecessaryClass(Scene.java:1343)
	at soot.Scene.loadNecessaryClasses(Scene.java:1354)
	at soot.Main.run(Main.java:243)
	at soot.Main.main(Main.java:147)
</pre>

**Comment by anddann** [comment]
Do you want to provide further details?
Otherwise, we will close the issue.
