### ISSUE TITLE
soot.SootResolver$SootClassNotFoundException when ...

### ISSUE THREAD

**Issue by harsh7809** [Sable/soot#994]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: <pre>trunk</pre>

Command line:
<pre>checkcfg.java</pre>

Max Memory:
<pre>1790MB</pre>

Stack trace:
<pre>soot.SootResolver$SootClassNotFoundException: couldn&#39;t find class: checkcfg.java (is your soot-class-path set properly?)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:226)
	at soot.SootResolver.bringToSignatures(SootResolver.java:264)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:168)
	at soot.SootResolver.resolveClass(SootResolver.java:129)
	at soot.Scene.loadClass(Scene.java:702)
	at soot.Scene.loadClassAndSupport(Scene.java:687)
	at soot.Scene.loadNecessaryClass(Scene.java:1339)
	at soot.Scene.loadNecessaryClasses(Scene.java:1350)
	at soot.Main.run(Main.java:243)
	at soot.Main.main(Main.java:147)
</pre>

**Comment by pavanupb** [comment]
The problem is you are giving a single file and soot is not able to find all the classes referenced in it. Try using -process-dir by giving the directory that contains all the files.
