### ISSUE TITLE
soot.SootResolver$SootClassNotFoundException when ...

### ISSUE THREAD

**Issue by harsh7809** [Sable/soot#995]
Steps to reproduce:
1.) ...

Files used to reproduce: 
...

Soot version: <pre>trunk</pre>

Command line:
<pre>-f J -cp C:\Users\harsh bansal\Desktop\Soot -pp CallGraphExample</pre>

Max Memory:
<pre>1790MB</pre>

Stack trace:
<pre>soot.SootResolver$SootClassNotFoundException: couldn&#39;t find class: soot.jimple.toolkits.callgraph.CallGraph (is your soot-class-path set properly?)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:226)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:171)
	at soot.SootResolver.resolveClass(SootResolver.java:129)
	at soot.Scene.loadClass(Scene.java:702)
	at soot.Scene.loadClassAndSupport(Scene.java:687)
	at soot.Scene.loadNecessaryClass(Scene.java:1339)
	at soot.Scene.loadNecessaryClasses(Scene.java:1350)
	at soot.Main.run(Main.java:243)
	at soot.Main.main(Main.java:147)
</pre>

**Comment by anddann** [comment]
Do you want to provide further details?
Otherwise, we will close the issue...
